### ISSUE TITLE
client: Whitelist logout redirect URL per client

### ISSUE THREAD

**Issue by k-lepa** [ory/hydra#1004]
Hello,

Our team has many apps that use OAuth2. Each app requires own logout redirect url. In #984 OAUTH_LOGOUT_REDIRECT_URL was added but for all. May we have the ability to set it for one client only?

Thanks

**Comment by aeneasr** [comment]
Tracked as enhancement but currently not on our priority list for 1.0.0 stable.

**Comment by singlewind** [comment]
@k-lepa You actually can implement your own logic. 
1. Your app's logout redirect to OP with return_url as query params, eg  /signout where you record the return_url from query into session
2. /signout redirect the user the /oauth2/sessions/login/revoke 
3. Then OP will redirect to OAUTH_LOGOUT_REDIRECT_URL which can be, eg /signout-redirect fetch the return_url from the session. And redirect the user back where they come from.
