### ISSUE TITLE
Duplicate entry error for second consent request

### ISSUE THREAD

**Issue by condemil** [ory/hydra#1007]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Client is on consent page. Client press allow button and while the client waits for response client decide to press deny button. Two requests is sent to hydra: `/oauth2/auth/requests/consent/[challenge]/accept` and `/oauth2/auth/requests/consent/[challenge]/reject`

For the reject call hydra sends back the following json response with 500: Internal Server Error http code:

```javascript
{
    "error": "error",
    "error_description": "The error is unrecognizable.",
    "status_code": 500,
    "error_debug": "Error 1062: Duplicate entry '3412b770ef1a49ef91260a3be06ca1c5' for key 'PRIMARY'"
}
```

**What is the expected behavior?**

Handle second request for the same challenge correctly and give descriptive error about what happened.

From developer point of view second request from user is something that may happen and developer should be able to handle that correctly (ignore?) in consent provider application.

**Which version of the software is affected?**

1.0.0 beta 8

**Comment by aeneasr** [comment]
> From developer point of view second request from user is something that may happen and developer should be able to handle that correctly (ignore?) in consent provider application.

Yup, the error should be ignored or shown to the user.

**Comment by aeneasr** [comment]
Is this MySQL?

**Comment by condemil** [comment]
Yes MySQL.

**Comment by aeneasr** [comment]
Ah, yeah, dupe key detection is broken there, fixing...
