### ISSUE TITLE
Client creation gives incorrect error message

### ISSUE THREAD

**Issue by vHanda** [ory/hydra#1016]
```
export HYDRA_URL=http://127.0.0.1:4445
./hyda clients create
```
Results in -
`To execute this command, the endpoint URL must point to the URL where ORY Hydra is located. To set the endpoint URL, use flag --endpoint or environment variable HYDRA_URL.`

The error message should reflect that the `HYDRA_ADMIN_URL` must be set and not the `HYDRA_URL`.

**Comment by aeneasr** [comment]
Thanks, PRs welcome!
