### ISSUE TITLE
Allow for insecure redirect URI for development

### ISSUE THREAD

**Issue by apognu** [ory/hydra#1021]
Hi,

This is a feature request.

Currently, even when **dangerous-force-http** is enabled, there is a hard requirement that all redirect URIs be HTTPS, except for .localhost suffixes (and possibly raw IP adresses). I have to admit this is a pain for development, when using a domain that maps to a private network (Docker, VM, etc.).

The hardcoded .localhost suffix is also problematic, as on some Linux distros (with nss-myhostname), it automatically resolves to 127.0.0.1, bypassing DNS totally (and therefore not hitting my Hydra box), unless the NSS module is totally disabled.

My company also has a policy to use a public TLD for development domains even if the IP is non-routable, and as far as I know, Hydra is not usable like that without a proper DNS certificate.

I totally understand that forcing HTTPS is a feature for production, but I think it would be interesting to either:
 * have a flag that marks the instance as non-production (that would remove all HTTPS failsafes);
 * or allow for setting which domain are to be whitelisted by the redirect URI failsafe.

Thanks for your input.

**Comment by apognu** [comment]
I just saw that this is actually handled in [fosite](https://github.com/ory/fosite), do you want me to open the issue there instead? Any configuration would be done on hydra, but handling would happen in fosite.

**Comment by apognu** [comment]
I understand that letting a way to do insecure thing is globally a bad thing, because people tend to choose the easy way over the secure one. If that's your stance, I totally understand it and will not argue this further.

For my particular situation, we do not mirror the public production domain. We have subdomain, unresolvable from the Internet, routable only from private networks and VPNs, that is used for development machines.

_.localhost_ is a bit annoying because it does resolve to the current machine (as I said, through [nss-myhostname](https://www.freedesktop.org/software/systemd/man/nss-myhostname.html), enabled on systemd hosts), and does not even allow a Hydra instance in a Docker container.

If the way of not allowing whitelisting domains is kept, I'll continue using a patched fork that adds my internal domain to fosite for my development host, that is not a big deal. :)

**Comment by aeneasr** [comment]
> If that's your stance, I totally understand it and will not argue this further.

Yes, the "mantra" of this ecosystem is to make bad things hard. Another option is of course to add an SSL termination proxy in front of your API gateway or whatever you use, with a certificate that is either issued by an internal-trusted CA or self-issued (and trusted obviously)

**Comment by aeneasr** [comment]
It makes sense to fix that and lower developer frustration. It makes sense to have `--dangerous-force-http` to enable `http` redirect urls as well.

**Comment by aeneasr** [comment]
We will probably not address this as part of rc.1 but it's on the roadmap for 1.0 stable!

**Comment by aeneasr** [comment]
Revisiting this, I think it makes sense to have a list of domains whitelisted for development. This would only work when `--dangerous-force-http` is enabled and probably be a flag like `--dangerous-allow-insecure-redirect-urls=http://mydomain.com/callback,http://mydomain2.com/callback`. That way we would allow those redirect URLs to be combined with HTTP.

**Comment by balibebas** [comment]
[Related issue](https://github.com/txn2/kubefwd/issues/156#issuecomment-751156614) cropping up when running with `dangerous-force-http` as an argument passed in using a container context. May not be your issue but I want to link these together for anyone who's digging later: https://github.com/slingshotlabs/reaction-oss-helm-chart/blob/develop/templates/hydra/hydra-deployment.yaml#L38
