### ISSUE TITLE
oryd/hydra:v1.0.0-beta.9 clients api return 404

### ISSUE THREAD

**Issue by liguobao** [ory/hydra#1036]
Do you want to request a feature or report a bug?
bug

What is the current behavior?

GET https://localhost:9000/clients return 404 not found

Click here to show Hydra Traceback
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

run docker image : v1.0.0-beta.9

docker run -d \
  --name ory-hydra-example--hydra \
  --network hydraguide \
  -p 9000:4444 \
  -e SYSTEM_SECRET=$SYSTEM_SECRET \
  -e DATABASE_URL=$DATABASE_URL \
  -e OAUTH2_ISSUER_URL=https://localhost:9000/ \
  -e OAUTH2_CONSENT_URL=http://localhost:5000/Account/Consent \
  -e OAUTH2_LOGIN_URL=http://localhost:5000/Account \
  oryd/hydra:v1.0.0-beta.9 serve

on beta.7 ,hydra log like that:
```
time="2018-09-15T16:36:40Z" level=info msg="started handling request" method=GET remote=114.91.68.137 request=/clients request_id=90a119bd266a8af73e9b1cc352b0752c
time="2018-09-15T16:36:40Z" level=info msg="completed handling request" measure#https://mydomain.com
 latency=2505374 method=GET remote=114.91.68.137 request=/clients request_id=90a119bd266a8af73e9b1cc352b0752c status=200 text_status=OK took=2.505374ms

```
on beta.9 ,hydra log like that:
```

time="2018-09-15T16:33:54Z" level=info msg="started handling request" method=GET remote=114.91.68.137 request=/clients request_id=953081257a40206153e800d04a53da94
time="2018-09-15T16:33:54Z" level=info msg="completed handling request" measure#https://mydomain.com .latency=102896 method=GET remote=114.91.68.137 request=/clients request_id=953081257a40206153e800d04a53da94 status=404 text_status="Not Found" took="102.896µs"
```

Which version of the software is affected?

1.0 beta 9

**Comment by aeneasr** [comment]
Please read the upgrade guide (UPGRADE.md in root directory). Hydra has now two ports, you’re probably accessing the public one.
