### ISSUE TITLE
missing end_session_endpoint from .well-known doc

### ISSUE THREAD

**Issue by Earth-43** [ory/hydra#1040]
I am using [ angular OIDC](https://github.com/manfredsteyer/angular-oauth2-oidc) with hydra as my oauth2 server , angular oidc client accepting `end_session_endpoint` as a logout URL which will be acting as `postLogoutRedirectUri `  so while loading well-known configuration `end_session_endpoint  ` is missing.
so post logout redirection is not working. Below is sample response for well-known document 

```
{
	"issuer": "http://localhost:4444/",
	"authorization_endpoint": "http://localhost:4444/oauth2/auth",
	"registration_endpoint": "http://localhost:4444/clients",
	"token_endpoint": "http://localhost:4444/oauth2/token",
	"jwks_uri": "http://localhost:4444/.well-known/jwks.json",
	"subject_types_supported": ["public"],
	"response_types_supported": ["code",
	"code id_token",
	"id_token",
	"token id_token",
	"token",
	"token id_token code"],
	"claims_supported": ["sub"],
	"grant_types_supported": ["authorization_code",
	"implicit",
	"client_credentials",
	"refresh_token"],
	"response_modes_supported": ["query",
	"fragment"],
	"userinfo_endpoint": "http://localhost:4444/userinfo",
	"scopes_supported": ["offline",
	"openid"],
	"token_endpoint_auth_methods_supported": ["client_secret_post",
	"client_secret_basic",
	"private_key_jwt",
	"none"],
	"userinfo_signing_alg_values_supported": ["none",
	"RS256"],
	"id_token_signing_alg_values_supported": ["RS256"],
	"request_parameter_supported": true,
	"request_uri_parameter_supported": true,
	"require_request_uri_registration": true,
	"claims_parameter_supported": false
}
```

**Comment by aeneasr** [comment]
Thanks, would you mind addressing this in a PR?

**Comment by aeneasr** [comment]
Ok, so I just checked with the spec and `end_session_endpoint` is a value from `OpenID Connect Session Management 1.0` which is currently a *draft* and is thus not stable. We discussed implementing this spec a few times here but the general consensus was to wait until it's final, and also big question marks regarding some of the flows which use hidden iframes and other ugliness. As such, this feature will currently not be added as we don't want to implement something from a spec that's actually not supported.

Please raise an issue with the lib you're using for making this configurable or working towards a solution which enables you to consume this functionality without relying on the value. Thanks!
