### ISSUE TITLE
API doc: GET /userinfo works but not documented

### ISSUE THREAD

**Issue by fredbi** [ory/hydra#1049]
**Do you want to request a *feature* or report a *bug*?**
bug (documentation)

**What is the current behavior?**
Only POST method documented. GET is mandatory according to spec and btw, is served ok.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Swagger doc should reflect the GET /userinfo endpoint 

**Which version of the software is affected?**
doc corresponding to "latest stable" (which I assume is beta9)

**Comment by aeneasr** [comment]
Do you know how I can define multiple HTTP Methods in the swagger spec for go-swagger?

**Comment by fredbi** [comment]
you can't: for swagger, it is a different endpoint.

**Comment by aeneasr** [comment]
Yeah that makes sense!
