### ISSUE TITLE
Add API versioning for administrative APIs

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1050]
Here's some libraries and articles that could help with approaching this:

* https://medium.com/@sjk/maintaining-api-versions-in-go-24bb4409a8a6
* https://github.com/sjkaliski/pinned
* https://github.com/beme/abide
* https://github.com/yageek/apiversion

**Comment by aaslamin** [comment]
Hey @aeneasr if you are thinking of API versioning for the admin endpoints, does that mean you intend on keeping older versions of an endpoint (_marked as deprecated or something_) for a few releases before completely removing them?

**Comment by aeneasr** [comment]
Yes that's the intention. This is part of the efforts for version 1.0 and has long been anticipated. The issue is of course that we're introducing it without having it tested extensively prior to that. Then again, as long as we adhere to the contract set by ourselves (I heavily tend towards `Accept: v1.0.1`) the implementation is just a detail. The big decision that has to be made is if we want semantic versioning here too (makes the most sense to me as it would be 1:1 with the software version) or stripe-like date-based versioning. What I don't like is `v0`, `v1` as part of the URL. It makes it really hard to introduce even minor changes without having like `v100` at one point. This may lead to pushing back fixes that could land today because of "oh yeah let's release that all together".

**Comment by aeneasr** [comment]
Moving this to post v1 as this is quite a huge task and there are currently no resources to get it done in time.

**Comment by kminehart** [comment]
This might be some good related reading material:

https://www.cockroachlabs.com/blog/calendar-versioning/

**Comment by aeneasr** [comment]
Marked as stale in error.

**Comment by aeneasr** [comment]
We never got anywhere with this, I don't think it's the right approach either at the moment. I'm closing this until the need actually arises.
