### ISSUE TITLE
Feature: admin endpoint for deleting expired tokens

### ISSUE THREAD

**Issue by aaslamin** [ory/hydra#1058]
I know this is possible via the [CLI](https://github.com/ory/hydra/blob/master/cmd/cli/handler_token.go#L101), but it would be nice if we could also trigger this action via an (admin) API.

Use case is to automate the flushing of expired tokens on a periodic basis via internal tooling. The process that is responsible for scheduling this API call could then report success/failure/stats (i.e. how many tokens were removed, etc.) to the development team (i.e. email, slack notification, etc.)

**Comment by aeneasr** [comment]
The CLI uses `/oauth2/flush` for this.
