### ISSUE TITLE
OpenID configuration endpoint returns wrong registration endpoint

### ISSUE THREAD

**Issue by retendo** [ory/hydra#1072]
Type: Bug

Description:
When http://localhost:4444/ is the issuer, http://localhost:4444/.well-known/openid-configuration returns
```
{ ...
"registration_endpoint": "http://localhost:4444/clients"
... }
```
which is actually not correct, this is found on the administrative api on port 4445

Steps to reproduce:
- Check out example app at https://github.com/ory/hydra-login-consent-node
- Start Hydra server
- Navigate to http://localhost:4444/.well-known/openid-configuration
- Observe "registration_endpoint": "http://localhost:4444/clients" in JSON
- http://localhost:4444/clients returns 404
- http://localhost:4445/clients returns expected data (empty array)

Expected behaviour:
http://localhost:4444/.well-known/openid-configuration should return the right registration endpoint.

Version: v1.0.0-beta.9

Edit:
Or maybe expected behaviour would be to remove registration_endpoint, because it is not part of the public API?

**Comment by aeneasr** [comment]
I think the best way to solve is is what @fredbi set on discord: Introduce "admin" and "public" tags to the swagger conf and thus separating the interfaces.
