### ISSUE TITLE
oauth2: Support mTLS client authentication

### ISSUE THREAD

**Issue by dudedad** [ory/hydra#1084]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Unable to use  x.509 certificates for OAuth Client Authentication.

**What is the expected behavior?**
Allow for the IETF draft standard: Auth 2.0 Mutual TLS Client Authentication and Certificate Bound Access Tokens ([draft-ietf-oauth-mtls-11](https://tools.ietf.org/html/draft-ietf-oauth-mtls-11))

Also, would need to deal with[ SPIFFE](https://spiffe.io/) name spacing.

Initial target would be for Client Credential Grant Flow.
Secondary Target would be for Authorization Code Grant Flow.

**Which version of the software is affected?**
Current

**Comment by aeneasr** [comment]
We have [this](https://www.ory.sh/docs/guides/master/hydra/6-how-to/3-advanced#oauth-20-client-authentication-with-rsa-privatepublic-keypairs) which uses RSA private/public keypairs. I don't think x.509 client certificates are something that can be added in reasonable time.

**Comment by aeneasr** [comment]
Forgot to add: If you have ideas or plans to implement it a PR would be interesting. Please address what you're planning on doing first though.

**Comment by aeneasr** [comment]
As discussed in SF, https://tools.ietf.org/html/draft-ietf-oauth-mtls-11 is a pretty good draft but needs some polishing. While Evan and I work on this, I'll put this on hold.

**Comment by tomberek** [comment]
Where is this? What support or assistance is needed?

**Comment by aeneasr** [comment]
This is currently on hold due to lack of clarity and lack of resources. But happy to talk options if you have any.

**Comment by evan2645** [comment]
Hello! Not sure if you saw, but draft-ietf-oauth-mtls now supports [SPIFFE IDs via SAN URI](https://tools.ietf.org/html/draft-ietf-oauth-mtls-14#section-2.1.2)

**Comment by aeneasr** [comment]
Evan, that’s great news! We should catch up and figure out how to integrate with SPIFFE!

**Comment by Julien-Eyraud** [comment]
Hello,
This draft is now [RCF8705](https://tools.ietf.org/html/rfc8705). Is there any plan for implementation now ?

Thanks.

**Comment by aeneasr** [comment]
Contributions welcomed!

**Comment by Julien-Eyraud** [comment]
Wish I could help but never work with go.

**Comment by narg95** [comment]
Hi @aeneasr,

we would like to use Hydra with *mTLS* for Client Authentication.
I am wondering if this feature is still wanted and if you or some hydra team member would like to discuss its implementation and give us some guidance to contribute.

Thanks!

**Comment by isodude** [comment]
I've done a couple of implementation of this now and it's fairly simple, what I've added to projects is the possibility to whitelist SANs and fingerprints. From what I can tell it's not possible to specify:
* client certificates
* CA certificates
* Allowed SAN/Fingerprints

What more is hindering mTLS? It would be super since you can power it with certbot/step-ca in the backend, generating all the certificates.

**Comment by erichwoo-scale** [comment]
Hi all + @aeneasr,

I’d like to revive this issue. I have a complete + tested implementation of [RFC 8705 Section 2](https://www.rfc-editor.org/rfc/rfc8705.html#section-2) on a fork (happy to share if useful). Before opening a PR, wanted to confirm that the contribution is still welcome. 

It follows earlier maintainer direction:
* RFC 8705 contributions were [welcomed above](https://github.com/ory/hydra/issues/1084#issuecomment-942425557)
* Fosite discussion supported both [RFC client-authentication methods](https://github.com/ory/fosite/issues/661#issuecomment-1099655785) and a [provider-specific certificate-source interface](https://github.com/ory/fosite/issues/661#issuecomment-1100916796)
* Preference for [terminating mTLS at Envoy or another ingress proxy](https://github.com/ory/hydra/issues/3411#issuecomment-1402005490), while the earlier discussion identified [forged forwarding headers](https://github.com/ory/hydra/discussions/2273#discussioncomment-262491) as the main security concern.

The implementation:
* Supports `tls_client_auth` and `self_signed_tls_client_auth`
* Requires certificate-bearing evidence and derives all identities from the certificate itself
* Adds an optional Fosite certificate-source interface and explicit Hydra proxy-source configuration, with local or delegated chain validation
* Supports [RFC 9440](https://www.rfc-editor.org/info/rfc9440/) and common proxy formats (HAProxy, NGINX, Apache, Traffic, Envoy) with strict fail-closed header handling
* **Does not** implement other sections of RFC 8705, including certificate-bound access tokens, `cnf.x5t#S256`, `mtls_endpoint_aliases`, or listener-level client-CA management

Validation I’ve already done:
- repository test and vet suites
- all four database backends
- targeted race tests
- real-proxy E2E tests
- a Kubernetes/Istio sidecar matrix

FYI per the [CONTRIBUTING.md](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#ai-assisted-contributions), Codex + Claude Code assisted with research, implementation, testing, and review.
