### ISSUE TITLE
govet cmd/tooken_user.go: the cancel function returned by context.WithTimeout should be called

### ISSUE THREAD

**Issue by fredbi** [ory/hydra#1090]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
cd cmd
go vet
...
token_user.go:121:9: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
			ctx, _ := context.WithTimeout(context.Background(), time.Second*5)
			     ^
``` 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
go vet passes

**Which version of the software is affected?**
beta-9

**Comment by aeneasr** [comment]
feel free to PR
