### ISSUE TITLE
Reduce debt: adopt modern linter

### ISSUE THREAD

**Issue by fredbi** [ory/hydra#1092]
I suggest to adopt golangci (https://golangci.com) to help cleaning up code and 
potential smelly structures.

**Comment by aeneasr** [comment]
go lint isn't reporting undocumented but exported functions right?

**Comment by fredbi** [comment]
Yes undocumented exports cause go lint to crok. But this is not just about go lint: there is a whole lotta static analysis tools.

Try it out: github.com/golangci/golangci-lînt

**Comment by aeneasr** [comment]
Resolved!
