### ISSUE TITLE
Improve follow-up on numerous ORY repos

### ISSUE THREAD

**Issue by fredbi** [ory/hydra#1093]
I suggest setting up webhooks in the discord chat to better follow-up what's going on the multiple github ORY repos.

The idea is to notify chat members of Q/A on github issues as well as submitted PRs and further discussions on PRs.

As a discord member, this allows me to directly jump to my github and check or participate when the issue or PR is of some interest to me, rather than using github notifications (which I usually discard, given the number of them I receive every day from many subscribed/forked repos).

Something like that is described here:

https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Comment by aeneasr** [comment]
go lint isn't reporting undocumented but exported functions right?

**Comment by aeneasr** [comment]
I would feel more comfortable with this if there was a bot ready to use. I think webhooks are being deprecated at GitHub as well (not entirely sure, maybe I misread)

**Comment by fredbi** [comment]
Here is a bot. It relies on webhooks as well.

https://github.com/Falconerd/discord-bot-github/blob/develop-es6/README.md

**Comment by fredbi** [comment]
Github services are deprecated not webhooks

https://developer.github.com/v3/guides/replacing-github-services/

**Comment by aeneasr** [comment]
added
