### ISSUE TITLE
CHALLENGE_TOKEN_LIFESPAN unused

### ISSUE THREAD

**Issue by fredbi** [ory/hydra#1097]
**Describe the bug**
Environment variable `CHALLENGE_TOKEN_LIFESPAN` is defined, parsed and documented in cmd/serve.go, but seems otherwise unused in hydra. The intent remains unclear to me.

This is confusing.

**To Reproduce**
1. `find . -name \*.go|xargs grep -iE (CHALLENGE.?TOKEN)`

**Expected behavior**
Either this variable is put to use (what was the intent?) or it is suppressed from source as it is confusing an already complex configuration.

**Desktop (please complete the following information):**
 - OS: n/a
 - Version master, v1-beta9

**Comment by aeneasr** [comment]
Thank you, see #1057
