### ISSUE TITLE
PHP SDK is not PSR-4 compliant

### ISSUE THREAD

**Issue by chrodriguez** [ory/hydra#1099]
**Describe the bug**
PHP SDK violates [PSR4](https://www.php-fig.org/psr/psr-4/). This is a problem when using frameworks such as Symfony >=3.4 where this standards are checked

**To Reproduce**
1. Download & install [PHP Coding Standard fixer](https://cs.sensiolabs.org/) && ory/hydra sdk using composer
2. Run php-cs-fixer
```
mkdir -p psr4-error && cd psr4-error
composer require "ory/hydra-sdk:>=1.0@beta" "friendsofphp/php-cs-fixer"
./vendor/bin/php-cs-fixer fix --rules=psr4 --allow-risky yes --dry-run --diff ./vendor/ory/hydra-sdk/
```
The above command will output:
```
Loaded config default.
Using cache file ".php_cs.cache".
   1) vendor/ory/hydra-sdk/sdk/php/swagger/lib/Model/JSONWebKeySet.php
   2) vendor/ory/hydra-sdk/sdk/php/swagger/lib/Model/JSONWebKey.php

Checked all files in 0.121 seconds, 12.000 MB memory used
```
> The error are class names not being in the same case as filename:
>  `-class JsonWebKeySet implements ArrayAccess`
> `+class JSONWebKeySet implements ArrayAccess`
> And
> `-class JsonWebKey implements ArrayAccess`
> `+class JSONWebKey implements ArrayAccess`

**Expected behavior**
Named classes to be writen as expected

**Comment by aeneasr** [comment]
This is a tricky one as it relates to issues with the Java SDK, see #1037, #1045. My recommendation is to use just simple the language-native get/post requests to the API as it's pretty straight forward.

**Comment by aeneasr** [comment]
I don't think there's a reasonable way (in terms of resources) for us right now to supply SDKs outside of what's generated by swagger right now. Closing as a *wontfix*.
