### ISSUE TITLE
consent: ignores extra claims for id and access token

### ISSUE THREAD

**Issue by zyclonite** [ory/hydra#1106]
**Describe the bug**
set additional claims in the consent step are not included in the resulting id or access token

**To Reproduce**
* uncomment the two session attributes https://github.com/ory/hydra-login-consent-node/blob/a21588aa78f8ad996581f84ec2a2db3d3b2e56f3/routes/consent.js#L35-L38
* follow the steps from the docker section of the readme
* none of the scopes in any combination (openid, offline...) include the claims in the issued token(s) 

**Expected behavior**
included claims in the access token and/or id token

**Version:**
 - Environment: Docker
 - Version v1.0.0-beta.9

**Comment by aeneasr** [comment]
That's rather unlikely because this whole pipeline is tested to death and has been added since the first 1.0 beta without anyone else noticing. Can you show the commands (e.g. `hydra token user`, `hydra token validate`) you're running to reproduce this? I'd also like to know if you're confident that your changes were actually deployed.

**Comment by aeneasr** [comment]
I tried to reconstruct this with the context given but as noted before was unable to reproduce this issue. However, you linked a line in the code which sets the session data **for already accepted consent requests**. If you're starting anew, the proper lines are probably a [bit further down](https://github.com/ory/hydra-login-consent-node/blob/a21588aa78f8ad996581f84ec2a2db3d3b2e56f3/routes/consent.js#L96-L103).

I really encourage you to read [the documentation](https://www.ory.sh/docs/guides/master/hydra/3-overview/1-oauth2#authenticating-users-and-requesting-consent), it's there for a reason and all of this stuff is explained there as well. This could have saved both you and me time to figure out what's going on ;)

If that's not the cause, most likely sources of something like this happening is:

1. Forgetting to restart the consent/login server after changes made
2. Making changes in consent/login server at the wrong place or misspelling something
3. Forgetting to rebuild and re-tag the docker image (if running in docker)
4. Mixing up deployments (e.g. 2 or 3 instances running in docker, different ports, ..
5. Mixing up the flows (e.g. mistaking authorize code flow with client credentials)

As the provided context is extremely sparse (no information on how to reliably reproduce what you did) I can not help you any further.

**Comment by zyclonite** [comment]
you are right, i did only mark the lines for the getConsent

i redid the test from scratch (uncomment the claims for getConsent and acceptConsent), correct container version (no own build, your hub version)
interesting is: if i use scope openid i get the id token with the set claim but the access token does not get the claim (like in any other scope configuration)

this proves at least that i did change the consent code in the right place
but it still does not explain why the access token is always empty

**Comment by aeneasr** [comment]
To set additional claims of the access tokens set `session.access_token`, to set additional claims of the id token (only available if scope openid is granted) set `session.id_token`. It works, I tested it, it's tested with e2e, unit, integration tests. That's all I can help. If you still have trouble, someone in the chat can help you for sure.

**Comment by zyclonite** [comment]
@aeneasr i did set session.access_token and it does *NOT* work, i can record you a screencast if that proves it ;)

**Comment by aeneasr** [comment]
Well, I disagree, it does work as again, I tested it, and there are several unit, e2e, integration tests that also check this behavior. A screencast would indeed be incredibly helpful because with the information given I can not help you any further.

**Comment by aeneasr** [comment]
Are you by any chance using JWT for access tokens? It appears that the extra claim is not set in the JWT Access Token, only in the introspection response.

**Comment by zyclonite** [comment]
this was the missing piece! when i set the strategy to jwt it works, thank you

**Comment by aeneasr** [comment]
Just to be clear, when `OAUTH2_ACCESS_TOKEN_STRATEGY=jwt` is set, there is a bug. If it is not set, there is no bug. I'm creating a PR to fix the bug where the claim is missing from the JWT Access Token but not the introspection response.

**Comment by zyclonite** [comment]
let me verify both scenarios...

**Comment by aeneasr** [comment]
And on another sidenote, using `OAUTH2_ACCESS_TOKEN_STRATEGY=jwt` is *bad* and should be avoided, unless you really need it and know what you're doing and why and all the downsides of using it, see also: https://www.ory.sh/docs/guides/master/hydra/6-how-to/3-advanced#json-web-tokens

**Comment by zyclonite** [comment]
both work now, so nothing to fix on your side

the only hurdle i had, the introspect endpoint is on the admin port which i did not map to the public on my reverse proxy...

**Comment by aeneasr** [comment]
> the only hurdle i had, the introspect endpoint is on the admin port which i did not map to the public on my reverse proxy...

That's a pretty bad practice, the introspect endpoint is not hidden for fun, but because it may expose confidential data to people that are not you or in your company. Do this only if you really know what you're doing.

**Comment by aeneasr** [comment]
> but how should a third party app be able to get the subject of that token it requested?

`/userinfo` or OpenID Connect

**Comment by zyclonite** [comment]
would it make sense to support basic auth for that endpoint? client_id and client_secret are used by most public providers as it seems
https://tools.ietf.org/html/rfc7662#section-2.1

**Comment by aeneasr** [comment]
there has been extensive discussion (#904) about this, the short answer is no and for good reason.

**Comment by zyclonite** [comment]
ok, makes sense

thank you for the clarification!
