### ISSUE TITLE
oauth2: Allow and enforce global scope/audience

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1134]
Instead of allowing scope/audience per client, it should be possible to enforce these settings with a global configuration variable.

**Comment by bbulczynski** [comment]
1. What problem does it solve?
2. Will there be possibility to enforce wider aud for certain clients?
3. In case od scopes you refer to default scopes described in https://tools.ietf.org/html/rfc6749#section-3.3 last paragraph?

**Comment by aeneasr** [comment]
> What problem does it solve?

If you have a focused authorization server where all clients are created equal (with equal audience, scope) it will be easier to manage it than to e.g. update 100 clients when you're adding a new scope to the mix.

> Will there be possibility to enforce wider aud for certain clients?

Can you elaborate?

> In case od scopes you refer to default scopes described in https://tools.ietf.org/html/rfc6749#section-3.3 last paragraph?

Yes, the OAuth 2.0 Scope, as it exists today in ORY Hydra

**Comment by bbulczynski** [comment]
Thanks,

> Can you elaborate?
I meant, will clients have possibility to overwrite default either by hydra client definition or authorization request.
> Yes, the OAuth 2.0 Scope, as it exists today in ORY Hydra
I meant, according to source, there can be possibility of serving request with no scopes with default one. Currently hydra is not supporting that, right?

**Comment by aeneasr** [comment]
Closing due to lack of public interest.
