### ISSUE TITLE
Setting up a fresh hydra installation results in panic

### ISSUE THREAD

**Issue by someone1** [ory/hydra#1137]
**Describe the bug**
Trying to test something in hydra _(does the script test-e2e-jwt.sh work when NOT using the memory databse? May need to open separate issue)_ and get an error when trying to setup the tables:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ory/hydra/cmd/cli.getDBUrl(0x160a560, 0x167bf28, 0x0, 0x0, 0x0, 0xc4200f4d00, 0xc420223c78)
	/home/workspace/src/github.com/ory/hydra/cmd/cli/handler_migrate.go:100 +0x39a
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL(0xc42000e720, 0x160a560, 0x167bf28, 0x0, 0x0)
	/home/workspace/src/github.com/ory/hydra/cmd/cli/handler_migrate.go:149 +0x62
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL-fm(0x160a560, 0x167bf28, 0x0, 0x0)
	/home/workspace/src/github.com/ory/hydra/cmd/migrate_sql.go:43 +0x52
...
```

**To Reproduce**
1. mkdir -p $HOME/workspace/hydra
2. export GOPATH=$HOME/workspace/hydra
3. go get -u -d github.com/ory/hydra
4. cd $GOPATH/src/github.com/ory/hydra
5. export GO111MODULE=on
6. go install .
7. docker run --name postgres -e POSTGRES_USER=hydra -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=hydra -d -p 5432:5432 postgres:9.6
8. DATABASEURL="postgres://hydra:secret@localhost:5432/hydra?sslmode=disable" $GOPATH/bin/hydra migrate sql

**Expected behavior**
No panics - tables created

**Version:**
 - Environment: [e.g. Docker, Kubernetes, ...]: Ubuntu 18.04.1/ go version go1.11.1 linux/amd64
 - Version [e.g. v1.0.0]: Commit 48b2a2278cc371d800891dd4a3ffeea9322a6140

**Comment by aeneasr** [comment]
You forgot `-e` in `DATABASEURL="postgres://hydra:secret@localhost:5432/hydra?sslmode=disable" $GOPATH/bin/hydra migrate sql`, it should be `DATABASEURL="postgres://hydra:secret@localhost:5432/hydra?sslmode=disable" $GOPATH/bin/hydra migrate sql -e` but obviously not panic.

**Comment by someone1** [comment]
I've done this so many times and yet I didn't realize ...Mondays, amirite? 

Also should have been `DATABASE_URL`
