### ISSUE TITLE
consent: Allow removing tokens without revoking consent

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1142]

**Comment by jtescher** [comment]
This would be very useful from an admin API, currently it is difficult to manage token invalidation. 

Also ideally this would work per session so users could log out and have their tokens not remain active.

**Comment by aeneasr** [comment]
> This would be very useful from an admin API, currently it is difficult to manage token invalidation.

Could you explain why?

> Also ideally this would work per session so users could log out and have their tokens not remain active.

Not really, Access Tokens are not a proof of authentication and they are not SSO tokens. If you log out, you would never remove a token. If you use Circle CI with GitHub and you log out of GitHub, you would never log out of Circle CI too - that's not how OAuth2 works. Just imagine the amount of sh*t Google would get if they would revoke OAuth2 Access Tokens everytime you log out of your Google account - it would be utter madness!

**Comment by jtescher** [comment]
One use case for an admin API is to revoke all tokens for a device that a user has lost access to. For an administrative interface like https://myaccount.google.com/device-activity, it would be preferable that protected resources are no longer accessible via tokens that were generated via that authentication session. Also standard OIDC endpoints like /userinfo would ideally be inaccessible after the session was removed.

For any resource that is protected by oathkeeper, it is also necessary to be able to invalidate tokens or the resource will still be accessible after the user ends their session with hydra.

Something like `Delete /oauth2/auth/sessions/login/{user}/{authSession}` would be along the lines of what I was thinking. Presuming there was some way of listing auth sessions.

**Comment by aeneasr** [comment]
> One use case for an admin API is to revoke all tokens for a device that a user has lost access to. For an administrative interface like https://myaccount.google.com/device-activity, it would be preferable that protected resources are no longer accessible via tokens that were generated via that authentication session.

There is a serious misconception about OAuth2 - Google's Account Activity revokes a login session (SSO), it does not revoke any OAuth2 tokens. An OAuth2 token is something inherently different, *it does not represent a user session in the context of SSO*. I'm coming back to my previous comment:

>  If you use Circle CI with GitHub and you log out of GitHub, you would never log out of Circle CI too - that's not how OAuth2 works.

Messing with that concept in a way that is not aligned with OAuth2 terminology and intent will cause trouble. We do however plan on implementing [OIDC session management](https://openid.net/specs/openid-connect-session-1_0.html) which might solve (in part) your use case. Given that you don't actually revoke the OAuth2 token but instead a session based on the ID Token.
