### ISSUE TITLE
Implementation of user idel time sout 

### ISSUE THREAD

**Issue by Earth-43** [ory/hydra#1146]
Hi All,
I need to implement user idel session time out, as after completing successful login, I have access_token which I am verifying on every request come to serve using  `/oauth2/introspect`  so if access_token is active user can access the resource . so now i want to refresh expire time of access_token on every request and compare with idel session time configured .
for example if session time out is configured 15 min and server is not receiving request till 14 min if on next second request comes I need to refresh expire time of token to 15 min.
Thanks .

**Comment by aeneasr** [comment]
As noted in the issue templates, ask questions like these in [the chat](https://www.ory.sh/chat) or in [the forums](https://community.ory.sh).
