### ISSUE TITLE
How to authenticate with POST /clients endpoint

### ISSUE THREAD

**Issue by tanujs-tech** [ory/hydra#1148]
I am trying to authenticate with the `POST /clients endpoint` to dynamically create apps. I am not able to find any documentation related to authorization & Authentication. Where can I find the resource URN for the consumers to only be able to create apps?

**Comment by aeneasr** [comment]
Security model is documented here: https://www.ory.sh/docs/guides/master/hydra/2-environment/1-securing-ory-hydra.html

The issue templates and contribution guidelines are there for a reason. Questions belong in the [forum](https://community.ory.sh) or the [chat](https://www.ory.sh/chat).
