### ISSUE TITLE
consent: Remember logic confuses developers

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1165]
Right now, the `remember` payload has to be `false` or `false || !request.skip` for both login and consent requests. This is confusing and not very clear, and does not serve a real purpose. Let's think about why it is there and if it's non-sensical to keep this check, remove it.

**Comment by aeneasr** [comment]
I think the idea here was to educate people about the consent flow and user interaction model, but that doesn't really happen - all it does is make this flow more confusing.

**Comment by kminehart** [comment]
I think reading https://www.ory.sh/docs/hydra/oauth2 makes the `remember` process makes sense.

What alternative would you suggest to imply that a login UI should not be presented?

Maybe to resolve confusion it would worth renaming "skip" to "remembered". Just a guess, but most people might expect the data in a response to be descriptive of the data rather than the action the client should take.

**Comment by aeneasr** [comment]
So `skip` would still indicate that the UI should not be presented. I think having `remember` forcibly true/false is just a bit too much? Since `skip: true` indicates that the process has been remembered already, we can probably just discard `remember`? Does that make sense?

**Comment by aeneasr** [comment]
So what I want to say is, `skip` will only be `true`, if that specific session has had `remember` set to `true`. Since `true` > `false` in terms of authorization (remembering consent/login usually requires extra consent like clicking a checkbox), there will be no negative implication (read privilege escalation) if `remember` is set to `true` if `skip` is `true` because `remember` had to be `true` before anyways. If `remember` is set to `false` it won't have an impact (imo) because, well, the session was remembered before and the user is actually not presented the user interface so the value `remember` can be ignored. Not sure that makes sense how I wrote it, but it does make sense in my head :D

**Comment by kminehart** [comment]
Would removing `remember` from responses cause problems with existing clients? Or would it be easier to just set it to `false` everywhere?

**Comment by aeneasr** [comment]
Setting it to false / ignoring it will be the safest route IMO. Since it didn't have an effect before, it won't change that now either.

**Comment by kminehart** [comment]
A PR for this will hopefully be ready tonight. :)
