### ISSUE TITLE
dbal: Memory adapter has weak consistency

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1179]
**Describe the bug**

The memory adapters lack certain features wrt to consistency. If a client is deleted, for example, the associated access tokens are still valid.

**To Reproduce**

1. Run `OAUTH2_ACCESS_TOKEN_STRATEGY=jwt DATABASE_URL=memory ./scripts/test-e2e.sh` and watch it fail

**Expected behavior**

It shouldn't fail

**Version:**
 - Version v1.0.0-beta.9/rc.10

**Additional context**

This issue causes several tests to be disabled in the CI. This makes sense as the memory adapter is more for testing/playing around than anything serious. Therefore, this issue is also low in priority.

**Comment by aeneasr** [comment]
@someone1 this will impact you. Make sure to remove tokens that belong to clients when deleting clients.

**Comment by someone1** [comment]
@aeneasr Thanks for the heads up - is this in any of the exported tests? If so it shouldn't be a problem!

**Comment by aeneasr** [comment]
The e2e tests are doing *some* consistency checks, but very simple ones.

**Comment by someone1** [comment]
If this is a security concern then there should be a test for it (IMHO) - don't want to forget about it one day! Adding it to one of the `test_helpers.go` files would make it reachable for anybody developing plugins.

**Comment by aeneasr** [comment]
It has tests, but the complexity of setting it up is...not light. That's why it ended up in binary e2e tests because the set up is much faster and easier there.

**Comment by aeneasr** [comment]
This was replaced with SQLite.
