### ISSUE TITLE
tracing: sql args are added as tags when they should be omitted

### ISSUE THREAD

**Issue by aaslamin** [ory/hydra#1181]
This is a bug. See https://github.com/ory/x/issues/15 for context

## Solution:

• Do steps outlined in the issue linked above
• Bump version of github.com/ory/x
• Verify that sql arguments are not added as tags in spans by following https://www.ory.sh/docs/hydra/hydra-debugging#alright-how-can-i-set-this-up-locally

**Comment by aeneasr** [comment]
Sounds good, let's get this landed for rc.1!

**Comment by aeneasr** [comment]
Closed by #1182
