### ISSUE TITLE
Key rotation CLI message is unclear how to use ROTATED_SYSTEM_SECRET

### ISSUE THREAD

**Issue by paxswill** [ory/hydra#1187]
The docs say that ROTATED_SYSTEM_SECRET should be set to the old system secret, but the output of `hydra migrate secret` says to set it to the new secret. Is [/cmd/cli/handler_migrate.go#L144](https://github.com/ory/hydra/blob/8ca315c90b42c4dcb4a28e7451821564e0702313/cmd/cli/handler_migrate.go#L144) supposed to be `newSecret` and the documentation updated, or is the documentation correct and it's supposed to be `oldSecret`?

**Comment by aeneasr** [comment]
Nice catch, taht should be `oldSecret` and `set to old secret` in handler_migrate.go

**Comment by paxswill** [comment]
Closing, resolved by #1195
