### ISSUE TITLE
Keep tests exportable

### ISSUE THREAD

**Issue by someone1** [ory/hydra#1204]
I'm back at developing my plugin as hydra approaches its 1.0 release, however, I've noticed that the `oauth2` tests (and possibly others) are no longer exported (sad)!

https://github.com/ory/hydra/commit/3a10df9bff259dee9b0d635b6522e098fbdd8cc3#diff-88

Was there a reason behind this? I see more and more tests are being added but since I can't access them I can't ensure feature parity with the internal database implementations.

**Comment by aeneasr** [comment]
Just me being stupid, sorry - I forgot about you. Feel free to revert and add a note to remind me not to mess it up again :)

**Comment by someone1** [comment]
Not a problem! 

I wonder if there's a way for tests to load the plugin (if present) into the database managers  list when running tests, maybe that way I don't have to worry about tests being exportable and can even gain entry to any tests I've overlooked. I'll be sure to look into as I catch up with hydra over the next couple weeks!

**Comment by aeneasr** [comment]
Sounds good, and sorry again :)

**Comment by aeneasr** [comment]
Resolved by #1212
