### ISSUE TITLE
Accept consent flow cause bug with id_token have field in utf8 value for MySQL 5.7+

### ISSUE THREAD

**Issue by tangkhaiphuong** [ory/hydra#1205]
**Describe the bug**
Accept consent flow cause a bug with id_token have filed in utf8 value for MySQL 5.7+. I test with Postgres is fine but a bug with MySQL.

**To Reproduce**
1. I ran migrate SQL with command
`docker run -it --rm --network hydra-network oryd/hydra:v1.0.0-rc.2_oryOS.9-alpine migrate sql mysql://root:root@tcp\(172.16.26.10:3306\)/oauth?parseTime=true`
2. I ran Ory Hydra, create the client. Run consent app then perform login, consent
3. At accept consent flow phase its cause bug:
```
{
        "error": "error",
        "error_description": "The error is unrecognizable.",
        "status_code": 500,
        "error_debug": "Error 1366: Incorrect string value: '\\xC4\\x83ng K...' for column 'session_id_token' at row 1",
        "request_id": ""
    }
```
The value for id_token to accept consent 
```
 "id_token": {
      "passwordType": "secret",
      "languageCode": "fr",
      "customerId": 602,
      "userId": 174,
      "userName": "Tăng Khải Phương",
      "siteId": -1,
      "groupId": 1
    }
  },

```
**Expected behavior**
It should be ok and invoke callback for get access/refresh token

**Screenshots**

**Version:**
 - Environment: hydra:v1.0.0-rc.2_oryOS.9-alpine
 - Version :v1.0.0-rc.2_oryOS.9-alpine

**Additional context**
The only bug with MySQL, Postgres is fine

**Comment by aeneasr** [comment]
Make sure that the collation of your database is `utf8`: https://dev.mysql.com/doc/refman/8.0/en/charset-database.html

**Comment by aeneasr** [comment]
Closing because I think this is resolved. Let me know if you have further questions.
