### ISSUE TITLE
hydra migrate sql requires superuser privileges

### ISSUE THREAD

**Issue by RazerM** [ory/hydra#1209]
**Describe the bug**
`hydra migrate sql` requires superuser privileges, which is not ideal and not documented.

The documentation states (emphasis mine)

> One-off admin processes should be run in an identical environment as the regular long-running processes of the app. They run against a release, using the **same codebase and config** as any process run against that release.

Given this statement, it would seem Hydra requires superuser permissions for its database user.

So far I had Hydra with a non-superuser role, and it owns everything in its database. I would rather not have to temporarily make the hydra user a superuser before migrations.

I'm not sure exactly why `session_replication_role` is used, is it just for performance reasons during the migration or is it truly required?

**To Reproduce**
1. Run `hydra migrate sql` with a non-superuser PostgreSQL role.
2. See error `pq: permission denied to set parameter "session_replication_role"`

**Expected behavior**
The migrations complete successfully.

**Version:**
 - Environment: In-house server.
 - Version v1.0.0-rc.3

**Comment by aeneasr** [comment]
Use a different user for migrations?

**Comment by aeneasr** [comment]
That's by the way one of the reasons why migrations are a separate command, so we can modify schemas with different privileges than the normal process needs.

**Comment by RazerM** [comment]
Sure, then it should be documented, which contradicts the part I already quoted:

> One-off admin processes should be run in an identical environment as the regular long-running processes of the app. They run against a release, using the same codebase and config

If it was documented I would have the hydra database and tables owned by a superuser and granted permissions to the Hydra user from the start.

**Comment by aeneasr** [comment]
> One-off admin processes should be run in an identical environment as the regular long-running processes of the app. They run against a release, using the same codebase and config.

Refers to commands such as "hydra clients create", migrations are a separate things that need a different set of privileges. Would you mind updating the docs there?

**Comment by aeneasr** [comment]
The environment section would be good for that (in hydra)

**Comment by RazerM** [comment]
What about using `ALTER TABLE ... DISABLE/ENABLE TRIGGER ALL` instead?

**Comment by aeneasr** [comment]
Sorry, I missed part of the post:

> I'm not sure exactly why session_replication_role is used, is it just for performance reasons during the migration or is it truly required?

Yes, performance reasons.

> What about using ALTER TABLE ... DISABLE/ENABLE TRIGGER ALL instead?

I fear that modifying migrations retroactively is not possible/a bad idea unless the outcome is 1:1 100% of the time for all versions of the software and database under all circumstances.

**Comment by RazerM** [comment]
Never mind, that requires superuser privileges too:

> This requires superuser privilege if any of the triggers are internally generated constraint triggers such as those that are used to implement foreign key constraints or deferrable uniqueness and exclusion constraints.

**Comment by aeneasr** [comment]
> I would tend to think that the performance of verifying the foreign keys doesn't matter too much for a one-time migration. But of course you'll have more information than me about that 😄

That would be nice, but unfortunately it can lock your database for several hours depending on the size.

**Comment by chrissachs** [comment]
I ran into the same issue. My hydra database is a postgresql database at google cloud, and the user can't be granted the SUPERUSER privilege: https://cloud.google.com/sql/docs/postgres/users

**Comment by aeneasr** [comment]
Ok damn, I didn't know that. I'll try to come up with a fix.

**Comment by aeneasr** [comment]
Ok, so the reason is really only `session_repliaction_role`, right? I think it should be possible to disable that retroactively in the SQL migrations. If you confirm that, I'll merge a patch for this today.

**Comment by aeneasr** [comment]
And by the way, sorry for the inconvenience and my initial stubbornness on this issue!

**Comment by JamesnaW** [comment]
Im not sure if [https://github.com/ory/hydra/issues/1225](url) related to this issue

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/pull/1226
