### ISSUE TITLE
Service account

### ISSUE THREAD

**Issue by pluservice** [ory/hydra#1220]
Allow to set custom claims and subject on an access token obtained with the Client Credentials Grant.

ie:
https://developers.google.com/identity/protocols/OAuth2ServiceAccount
https://www.keycloak.org/docs/latest/server_admin/index.html#_service_accounts

**Comment by aeneasr** [comment]
The client credentials grant is fully supported and you can request any scopes you want, as long as they're whitelisted.

**Comment by pluservice** [comment]
From what I read in the documentation client creation rest api does not allow to specify custom claims or subject ..

**Comment by pluservice** [comment]
Ok sorry here is the new feature request
https://github.com/ory/hydra/issues/1221
