### ISSUE TITLE
Migration from beta.9 fails on google cloudsql

### ISSUE THREAD

**Issue by tback** [ory/hydra#1224]
**Describe the bug**
Migration from beta.9 to 1.0.0.rc3-oryos9 fails on cloudsql: 
```
Applying `jwk` SQL migrations...
Applied 0 `jwk` SQL migrations.
Applying `client` SQL migrations...
Applied 0 `client` SQL migrations.
Applying `consent` SQL migrations...
An error occurred while running the migrations: could not apply consent SQL migrations: Could not migrate sql schema, applied 0 migrations: pq: permission denied to set parameter "session_replication_role" handling 7
```

This is the same issue as the one reported as #1185. Unfortunately the solution doesn't work on cloudsql because the user does not have access to the superuser or replication privilege (https://cloud.google.com/sql/docs/postgres/users#postgresql_roles_and_users)

**To Reproduce**
Run beta9 with google cloudsql database. Update to rc3.

**Expected behavior**
I expect the migrations to apply without error.

**Version:**
 - Environment: Kubernetes (v1.10.7-gke.11)
 - Version v1.0.0-rc.3_oryOS.9

**Comment by aeneasr** [comment]
Dupe: #1221

**Comment by aeneasr** [comment]
Sorry, yes!
