### ISSUE TITLE
Why is the Ory Hydra Docker image nearly 1GB in size?

### ISSUE THREAD

**Issue by popey456963** [ory/hydra#1237]
This seems exceptionally large compared with the minimal size of the Go binary.

**Comment by aeneasr** [comment]
I don’t know what you’re talking about, all recent tags are literally 5MB, please check the docker hub info properly.

**Comment by popey456963** [comment]
Apologies, it appears I was using the 'latest' tag, which was last updated 13 months ago.  You are indeed correct that the latest images are much smaller.
