### ISSUE TITLE
Error: "Command failed because error occurred: invalid character 'p' after top-level value" on running hydra client create

### ISSUE THREAD

**Issue by sum2000** [ory/hydra#1244]
**Describe the bug**
When running 
`hydra clients create` 
i get an error 
`Command failed because error occurred: invalid character 'p' after top-level value`

**To Reproduce**
1. Download hydra [binary](https://github.com/ory/hydra/releases) for darwin-amd64 and version:1.0.0-rc.5+oryOS.10 
2. Set environment variable 'HYDRA_ADMIN_URL' to http://localhost:4444/
2. Run `hydra client create`  after making the binary executable
3. See error described above

**Expected behavior**
 Should receive information about necessary flags required to run the command instead of the error.

**Screenshots**
<img width="872" alt="screen shot 2018-12-19 at 6 29 02 pm" src="https://user-images.githubusercontent.com/1329618/50254471-1c987800-03bc-11e9-92a6-9bd3cd45f6fe.png">

**Version:**
 - Environment: macOS High Sierra
 - Version: 10.13.6

**Additional context**
Surprisingly, `hydra clients delete` and `hydra clients get` work as expected.

**Comment by aeneasr** [comment]
Admin URL should be 4445

**Comment by sum2000** [comment]
Yes, I figured that part. But when we provide public URL, this error is due to JSON parsing. I guess the method looks for JSON in the response body but hits 404.

**Comment by aeneasr** [comment]
The router now returns a JSON response when `application/json` was requested!
