### ISSUE TITLE
Refresh token not works properly

### ISSUE THREAD

**Issue by cisco90** [ory/hydra#1246]
**Describe the bug**
Sometimes, when you try to use refresh token, hydra response with error, see logs below:

    time="2018-12-20T16:08:55Z" level=info msg="started handling request" method=POST remote=10.255.0.2 request=/oauth2/token,
    time="2018-12-20T16:08:55Z" level=error msg="An error occurred" debug="read tcp 10.0.155.158:41540->10.0.155.7:5432: read: connection reset by peer" description="Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)" error=invalid_client,
    time="2018-12-20T16:08:55Z" level=debug msg="Stack trace: 
    \ngithub.com/ory/fosite.(*Fosite).AuthenticateClient\n\t/go/pkg/mod/github.com/ory/fosite@v0.28.0/client_authentication.go:185
    \ngithub.com/ory/fosite.(*Fosite).NewAccessRequest\n\t/go/pkg/mod/github.com/ory/fosite@v0.28.0/access_request_handler.go:81
    \ngithub.com/ory/hydra/oauth2.(*Handler).TokenHandler\n\t/go/src/github.com/ory/hydra/oauth2/handler.go:535
    \ngithub.com/ory/hydra/oauth2.(*Handler).TokenHandler-fm\n\t/go/src/github.com/ory/hydra/oauth2/handler.go:172
    \nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964
    \ngithub.com/julienschmidt/httprouter.(*Router).Handler.func1\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v0.0.0-20180715161854-348b672cd90d/params_go17.go:26
    \ngithub.com/julienschmidt/httprouter.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/julienschmidt/httprouter@v0.0.0-20180715161854-348b672cd90d/router.go:334
    \ngithub.com/urfave/negroni.Wrap.func1\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
    \ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
    \ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/urfave/negroni.middleware.ServeHTTP-fm\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964
    \ngithub.com/ory/hydra/cmd/server.(*Handler).RejectInsecureRequests\n\t/go/src/github.com/ory/hydra/cmd/server/handler.go:292
    \ngithub.com/ory/hydra/cmd/server.(*Handler).RejectInsecureRequests-fm\n\t/go/src/github.com/ory/hydra/cmd/server/handler.go:62
    \ngithub.com/urfave/negroni.HandlerFunc.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
    \ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/urfave/negroni.middleware.ServeHTTP-fm\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/ory/hydra/metrics/prometheus.(*MetricsManager).ServeHTTP\n\t/go/src/github.com/ory/hydra/metrics/prometheus/middleware.go:26
    \ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/urfave/negroni.middleware.ServeHTTP-fm\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP\n\t/go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136
    \ngithub.com/urfave/negroni.middleware.ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
    \ngithub.com/urfave/negroni.(*Negroni).ServeHTTP\n\t/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
    \ngithub.com/gorilla/context.ClearHandler.func1\n\t/go/pkg/mod/github.com/gorilla/context@v1.1.1/context.go:141
    \nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964
    \nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741
    \nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847
    \nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333",

**To Reproduce**
This issue is not reproducible because sometimes works properly, other not.

**Expected behavior**
Refresh token generates new token

**Version:**
 - Environment: Docker image, using oryd/hydra:v1.0.0-rc.5_oryOS.10-alpine 
 - Version: v1.0.0-rc.5_oryOS.10

**Additional context**
It seems that client_id is missing but, if I try to search for client_id with

`hydra --endpoint http://hydra:4445 clients get mycleintid`

it works properly.
If I retry with the same refresh token immediately, it works properly.

**Comment by aeneasr** [comment]
`read tcp 10.0.155.158:41540->10.0.155.7:5432: read: connection reset by peer` indicates a database connectivity issue, should/is not related to hydra internals.

**Comment by cisco90** [comment]
ok perfect, I just update hydra from version 0.11.12 to v1.0.0-rc.5_oryOS.10, previously I didn't notice this error, as you know, something change on postgres connection?

**Comment by cisco90** [comment]
Yes, I guess the problem may be the connection between containers went in idle status and needs to be recreated. I will working on it.

Thanks

**Comment by aeneasr** [comment]
Yeah sounds like an issue related to that. Try tweaking the parameters, it should eventually work. Other than that I can't be of much more help but feel free to come back to this issue if you can't figure it out - closing
