### ISSUE TITLE
Support fosite delegated transactions in SQL storage

### ISSUE THREAD

**Issue by aaslamin** [ory/hydra#1247]
**Is your feature request related to a problem? Please describe.**

Certain oauth flows require transactional semantics (_see issue linked below_). Thanks to Fosite v0.29.0, Fosite will now attempt to initiate a transaction if the underlying storage provider has implemented the [`Transactional` interface](https://github.com/ory/fosite/blob/master/storage/transactional.go#L17).

**Describe the solution you'd like**

- Bump fosite to at least `v0.29.0`
- Extend `FositeSQLStore` so that it implements `Transactional`
- Modify all sql storage methods to first lookup for a transaction in the context (_if one does not exist, its business as usual_).
- Test coverage of new behaviour

**Additional context**

https://github.com/ory/fosite/issues/309
https://github.com/ory/fosite/pull/343

**Comment by aeneasr** [comment]
👍

**Comment by aaslamin** [comment]
My colleague, @michaelwagler, has decided to take this issue on for his first contribution to Hydra 🏆

**Comment by michaelwagler** [comment]
Yup 👍
