### ISSUE TITLE
docs: Are refresh tokens introspectable or not?

### ISSUE THREAD

**Issue by jshearer** [ory/hydra#1250]
**Describe the bug**
The API docs for introspecting a token are contradictory. The description paragraph says 
> The introspection endpoint allows to check if a token (both refresh and access) is active or not.

But the description for the `token` body parameter says,
> This endpoint DOES NOT accept refresh tokens for validation.

I believe refresh tokens _are_ introspectable, so as long as that's true, the description for token should be updated to reflect that.

**Comment by aeneasr** [comment]
Yup, they are indeed introspectable and you'll get a type back which says if it's a refresh or access token! Feel free to create a PR to fix this :)
