### ISSUE TITLE
OpenID Connect Discovery endpoint is missing revocation_endpoint

### ISSUE THREAD

**Issue by jcxplorer** [ory/hydra#1268]
**Describe the bug**
The `GET /.well-known/openid-configuration` endpoint doesn't include the revocation endpoint.

**To Reproduce**
1. Request `GET /.well-known/openid-configuration`
2. Try to find the `revocation_endpoint` field.

**Expected behavior**
Response should include a `revocation_endpoint` field.

**Version:**
 - All released versions.

**Additional context**
I've checked the name of the field from other OpenID Connect implementations such as Google's, and also the [AppAuth](https://appauth.io/) libraries look for a field named `revocation_endpoint`.

**Comment by aeneasr** [comment]
`revocation_endpoint` is not defined [per spec](https://openid.net/specs/openid-connect-discovery-1_0.html) which is why it isn't included. Are you, by any chance, confusing this with [this draft](https://tools.ietf.org/html/draft-ietf-oauth-discovery-06) for which we have [an issue already](https://github.com/ory/hydra/issues/1127)?

**Comment by jcxplorer** [comment]
You're right, it's not in the spec. Unfortunately it seems like some other providers have started adding it to their `GET /.well-known/openid-configuration` endpoints:

- https://developer.okta.com/docs/api/resources/oidc#well-knownopenid-configuration
- https://accounts.google.com/.well-known/openid-configuration

I guess this is why AppAuth has also decided to start looking for it.

However, you're correct that it's not in the spec, so it makes sense to not implement it. It's easy enough to workaround from our apps.

Feel free to close if you believe Hydra shouldn't implement it, and thanks for the awesome work and incredibly fast replies! 🙌

**Comment by bretep** [comment]
This would be nice to have since the oidc-client-js I use also discovers `revocation_endpoint`. Will hardcode for now.

**Comment by aeneasr** [comment]
Ok, let's include it. How's up for a PR?

**Comment by bretep** [comment]
I’ll work on it today.

**Comment by aeneasr** [comment]
This is now resolved!
