### ISSUE TITLE
CI: cannot install gometalinter at CircleCI

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#1272]
**Describe the bug**

No longer gometalinter installer doesn't work.
It seems default installation directory was changed to "$GOPATH" from "./bin"

https://github.com/alecthomas/gometalinter/commit/83891259ab664a6d96066685f7f07431375ca8e5#diff-80423f13d45b53af35790ffc6009be4d

CircleCI log

```
$ #!/bin/bash -eo pipefail
curl -L https://git.io/vp6lP | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  9857  100  9857    0     0  89002      0 --:--:-- --:--:-- --:--:-- 89002
alecthomas/gometalinter info checking GitHub for latest tag
alecthomas/gometalinter info found version: 2.0.12 for v2.0.12/linux/amd64
install: cannot change permissions of ‘/go/bin’: Operation not permitted
Exited with code 1
```

**To Reproduce**
1. exec `curl -L https://git.io/vp6lP | sh`  at CircleCI

**Version:**
 - Environment: CircleCI
 - Version master

**Comment by aeneasr** [comment]
Resolved by #1273 - thank you!
