### ISSUE TITLE
Not Generating other token

### ISSUE THREAD

**Issue by dushyantgohil** [ory/hydra#1275]
Please use issues only to file potential bugs or request features. For everything else please go to
the [ORY Community](https://community.ory.sh/) or join the [ORY Chat](https://www.ory.sh/chat).

Hello,

I am new to oAuth and I have configured that as mentioned in below url : 
https://www.ory.sh/run-oauth2-server-open-source-api-security

I am facing issue while creating a second token and also not able to redirect to user login page.

all the necessary ports are opened as mentioned in the installation guide. 

when I try to access the url http://localhost:9000/

its giving me page ok screen.

Thanks.

**Comment by aeneasr** [comment]
Please read the issue template and ask your question in the forum or the chat. Please note that Hydra won't teach you oauth2 and that it is assumed that you have knowledge about oauth2. You can find resources on oauth2 in the docs or by asking in the chat. Thank you.

**Comment by dushyantgohil** [comment]
can you please provide a chat link?
