### ISSUE TITLE
Log readiness and liveness routes in debug log level

### ISSUE THREAD

**Issue by anon6789** [ory/hydra#1278]
Readiness (`/health/ready`) and liveness route (`health/alive`) requests are logged into `info` log level.
This causes a lot of logs when hydra is deployed in loadbalanced cloud setups.

Readiness and liveness routes should log into debug log level to not flood the info log level.

It would be possible to filter out all liveness/readiness logs with the `LOG_LEVEL` environment variable, but this will also suppress all other info logs.

**Comment by aeneasr** [comment]
It should be possible to filter this out in your log system, as you would do with any inspection into a specific trace. The router is emitting to info for all routes and it's actually not easily possible to have different routes with different log levels. It's also not very clear where this would be documented and could be quite frustrating to debug e.g. loadbalancers.

**Comment by hypnoglow** [comment]
@aeneasr

IMHO health logs sometimes considered noisy and not very useful. It would be convenient if the application could support an option to disable such logs, and not rely to external filtering log system.

> t's actually not easily possible to have different routes with different log levels

We could just disable health logs completely. Probably adding an option like DISABLE_HEALTH_ACCESS_LOGS.

The logger supports `ExcludeURL` method, so implementing it is as easy as `middleware.ExcludeURL("/health/alive")`
