### ISSUE TITLE
Is the hydra security console open source?

### ISSUE THREAD

**Issue by raymondsze** [ory/hydra#1281]
**Is your feature request related to a problem? Please describe.**
Could I deploy the security console myself like running a docker container instance? I didn't find any source on github.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aeneasr** [comment]
It’s not open source but you can buy a license allowing you to run it locally.

**Comment by boeboe** [comment]
@aeneasr ... were and how can I get such a license. It's seems so well hidden I can't even find any info on it on your home page. 

Best regards,
Bart

**Comment by aeneasr** [comment]
We have deprecated the original console itself but we do have plans to offer something like that in the near future. If you're interested reach out to jared@ory.sh :)

**Comment by vinckr** [comment]
You can now find the console for Ory Cloud at https://console.ory.sh. 
Feel free to reach out to office@ory.sh if you have more questions.
