### ISSUE TITLE
Support multi proxies between TLS termination proxy and hydra

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#1282]
**Is your feature request related to a problem? Please describe.**

Hydra seems to support only following architecture.

```
Client -> TLS termination proxy -> hydra
```

Then, set TLS termination proxy's CIRDER address as `HTTPS_ALLOW_TERMINATION_FROM`.

But how about following case?

```
Client -> TLS termination proxy -> proxy -> hydra
```
Set TLS termination proxy's CIRDER address then it doesn't work.
Set proxy's CIRDER address then it works but is it best way?

**Describe the solution you'd like**

I think it's the best setting TLS termination proxy's CIDER address as `HTTPS_ALLOW_TERMINATION_FROM`  even if there proxies between TLS termination proxy and hydra.

**Comment by aeneasr** [comment]
Why wouldn't you just set `HTTPS_ALLOW_TERMINATION_FROM` to the IP of `proxy`?

**Comment by sawadashota** [comment]
Yes, it works but I think this is not better in the sense of `HTTPS_ALLOW_TERMINATION_FROM` option.
This option seems to mean "set TLS termination proxy's IP then trust it and check X-Forwarded-Proto header".
Therefore, I think it better to ensure TLS termination proxy's IP.

https://github.com/ory/hydra/blob/aa6ab26908ea5fc856c67c2650c2124d3331e184/cmd/serve.go#L186-L190

In addition my case, using AWS, TLS termination proxy and proxy are different subnet.
When I set `HTTPS_ALLOW_TERMINATION_FROM` to the IP of nginx, it works but I want to change to ALB IP.

```
Client -> ALB (TLS termination) -> nginx on ECS -> hydra on ECS
```
