### ISSUE TITLE
Consent /reject without error data will always return an invalid_request error

### ISSUE THREAD

**Issue by LaylConway** [ory/hydra#1285]
**Describe the bug**
When rejecting a consent request, but not including "error", "error_description" or "error_hint", the values that aren't given will default to a generic invalid_request error. This is completely inaccurate to what happened and very confusing while developing.

**To Reproduce**
1. Go through the OAuth2 authorization code flow until consent
2. Reject consent, but do not set any value for "error", "error_description" or "error_hint"
3. Read the resulting error in the callback

**Expected behavior**
The right behavior should probably be either passing an error that indicates the consent request was rejected, or a generic error. The invalid_request error sends the developer to the wrong place for debugging.

**Version:**
 - Environment: Docker
 - Version oryd/hydra:v1.0.0-rc.6_oryOS.10

**Comment by aeneasr** [comment]
Thank you! Feel free to PR :)
