### ISSUE TITLE
flush endpoint throw error

### ISSUE THREAD

**Issue by singlewind** [ory/hydra#1288]
**Describe the bug**
/oauth2/flush endpoint return 500 error.

**To Reproduce**
1. In postman, post flush endpoint
2. Return error message below
{
    "error": "error",
    "error_description": "The error is unrecognizable.",
    "status_code": 500,
    "error_debug": "EOF",
    "request_id": ""
}

**Expected behavior**
Return status code 200

**Version:**
 - Environment: [Docker]
 - Version [oryd/hydra:v1.0.0-rc.6_oryOS.10]

**Additional context**
See error log below
```
hydra_1          | time="2019-02-21T07:00:50Z" level=error msg="An error occurred while handling a request" code=500 details="map[]" error=EOF reason= request-id= status= trace="Stack trace could not be recovered from error type *errors.errorString" writer=JSON
hydra_1          | time="2019-02-21T07:00:50Z" level=info msg="completed handling request" measure#https://gandalf.cloudscene.dev.latency=513900 method=POST remote="172.22.0.8:53788" request=/oauth2/flush status=500 text_status="Internal Server Error" took="513.9µs"
```

**Comment by aeneasr** [comment]
You need to send a POST request with a body, see the docs: https://www.ory.sh/docs/hydra/sdk/api#flush-expired-oauth2-access-tokens

**Comment by singlewind** [comment]
thanks @aeneasr that was the issue. In the documentation, it says body is not required. So I thought it was optional.
