### ISSUE TITLE
Ambiguous Dockerfile versions

### ISSUE THREAD

**Issue by yanishoss** [ory/hydra#1289]
## Issue
There is an issue with the documentation and the Dockerfile. The latest version of the image on Docker Hub doesn’t expose the « hydra serve all » command, this is an outdated version in regards of the documentation. 

# Solution
Please update the image on Docker Hub with the latest stable(ish) version of Hydra on the Hub

**Comment by aeneasr** [comment]
I tried to delete the :latest tag before but it's just not possible in docker. Might have to re-add :latest to the CI release pipeline to fix this.
