### ISSUE TITLE
Website displays 0 github stars

### ISSUE THREAD

**Issue by MariusMeiners** [ory/hydra#1292]
**Describe the bug**
your website displays that you have 0 github stars. You guys are underselling yourselves...

**To Reproduce**
visit https://www.ory.sh/?utm_source=github&utm_medium=banner&utm_campaign=hydra

**Expected behavior**
see actual github stars

**Comment by aeneasr** [comment]
:) This may happen when you hit the GitHub API request limits (i.e. reloading the front page a couple of times). We might have to add some caching in there...

**Comment by aeneasr** [comment]
This should be fixed with the next website update!
