### ISSUE TITLE
Add TLS certificate validation for DB connection

### ISSUE THREAD

**Issue by condemil** [ory/hydra#1294]
**Is your feature request related to a problem? Please describe.**

As discussed in the chat it is not possible to verify certificate for TLS database connection at that moment. It would be nice to add it.

**Describe the solution you'd like**
Add a way (probably though config yaml / environment variable) to specify path to PEM certificate file to validate TLS database connection.

**Describe alternatives you've considered**
For not the only possible to connect though TLS to database without certificate validation, it is workable, but not that secure.

**Additional context**
How it can be achieved with mysql driver is mentioned here: https://github.com/go-sql-driver/mysql/issues/908

**Comment by aeneasr** [comment]
Ok so the idea would be to add [this](https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig) somewhere around [herre](https://github.com/ory/x/blob/master/sqlcon/connector.go#L127-L130). One difficulty is that the mysql driver doesn't handle this automatically so we would have to add a hardcoded check here against mysql to make this work which kinda sucks (the postgresdriver supports setting the CA via a flag). Any ideas how to solve this in a better way?

**Comment by condemil** [comment]
The better way is to add another DNS argument (to be consistent with postgres), get it from query as you get other options [in here](https://github.com/ory/x/blob/469085ae3cf9fbe46e2ab525665c81cd5b554576/sqlcon/connector.go#L164-L171) and add it to `SQLConnection` struct. Later when we do mysql connection we can check that path to tls certificate is specified in `SQLConnection`.

**Comment by aeneasr** [comment]
Ah my description wasn't very clear, that's definitely the idea here, have something like `?tlsCAPath` or whatever (we can mimic what postgres is doing).

**Comment by condemil** [comment]
`?tlsCAPath` or some other parameter on DSN sound better than my initial idea with config / environment.

**Comment by condemil** [comment]
The only other idea I have how to make it better without hardcoded check here against mysql is to file another feature request on mysql driver to support it tough DNS the way postgres driver does it.

**Comment by aeneasr** [comment]
> The only other idea I have how to make it better without hardcoded check here against mysql is to file another feature request on mysql driver to support it tough DNS the way postgres driver does it.

I think that would be the most reasonable path as this should really be part of the driver spec IMO and it would benefit the community using the upstream dependency (mysql driver) the most.

**Comment by condemil** [comment]
Created issue https://github.com/go-sql-driver/mysql/issues/926

**Comment by aeneasr** [comment]
Awesome!

**Comment by aeneasr** [comment]
I will close this issue as it really is something which needs to be done upstream. Looks like there is some progress on the issue, but it's not yet merged. Once it's merged, it will be in the next update for ORY Hydra!
