### ISSUE TITLE
Terraform Provider

### ISSUE THREAD

**Issue by svett** [ory/hydra#1304]
I am not sure how to communicate this. But I managed to create a terraform provider that manages clients for Hydra. Check it out here https://github.com/phogolabs/terraform-provider/tree/master/cmd/terraform-provider-hydra

Note that there is a know issue regards the `client_secret`. Because the `GET` request does not return the `client_secret`, the provider thinks that the secret has been changes. Therefore, each time when you do `terraform apply` will make update.

**Comment by aeneasr** [comment]
This is awesome!! We might even end up forking this here officially :)

**Comment by svett** [comment]
It's very early version. I don't even have tests. Let me add good tests coverage prior to forking it.

**Comment by IGassmann** [comment]
@aeneasr Is there any plan to have Terraform supported officially? Otherwise, what's the current recommended infrastructure-as-code solution for Hydra OAuth 2.0 clients?

**Comment by aeneasr** [comment]
No plans yet. For IAC just create a JSON file and use a curl command or the Hydra CLI :)

**Comment by zdelanofw** [comment]
Just leaving a comment here to say that this would be very helpful in my case. I've never made a Terraform provider before, but I'd maybe be willing to partner up with someone at ORY to make this possible. It all depends on the needs surrounding OAuth in my organization.

**Comment by aeneasr** [comment]
Sure! I also don't have any experience with terraform providers. But given that we have SDKs for Hydra in Go it should be pretty straight forward! As a workaround you could also use the ORY Hydra CLI with the [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html) provider.

**Comment by hypnoglow** [comment]
Hey @zdelanofw @aeneasr 

I've made a terraform provider and published it to the registry: https://registry.terraform.io/providers/hypnoglow/oryhydra/latest

It is by no means official, I started it mostly for our company internal use case. And currently only OAuth2 Client is available. If you want to see other resources or features, feel free to submit an issue to the GitHub repo: https://github.com/hypnoglow/terraform-provider-oryhydra

**Comment by aeneasr** [comment]
@hypnoglow very cool! We could probably add that to the documentation, what do you think?

**Comment by IGassmann** [comment]
@hypnoglow how can you apply the configuration when the admin URL is a private URL only available inside a private cloud network? What strategy do you need if you're using something like Terraform Cloud to apply terraform configurations?

**Comment by hypnoglow** [comment]
> very cool! We could probably add that to the documentation, what do you think?

@aeneasr IDK maybe docs could include a dedicated page something like "community" which aggregates projects from third-parties. Anyway feel free to add it wherever you think it fits. 

> how can you apply the configuration when the admin URL is a private URL only available inside a private cloud network? What strategy do you need if you're using something like Terraform Cloud to apply terraform configurations?

@IGassmann Terraform itself does not manage access and networking in case of private clouds, as it tightly depends on your infrastructure. For example, we use terraform in GitLab CI and we have our GitLab runners connected to the same VPC where Hydra runs, and firewall allows to accept requests from these runners.

I have no experience with Terraform Cloud, and cannot suggest the way to solve network/access problem, sorry.

**Comment by zdelanofw** [comment]
> @hypnoglow how can you apply the configuration when the admin URL is a private URL only available inside a private cloud network? What strategy do you need if you're using something like Terraform Cloud to apply terraform configurations?

There are ways to get around this. You could use Terraform to set up a client VPN, associate the VPN with a subnet, run your Terraform plans, then disassociate it from the subnet when you're done running Terraform to avoid incurring costs. Another alternative is to temporarily whitelist your IP.

Also, @hypnoglow that's awesome that the provider is up! I'll likely use it in the future.

**Comment by aeneasr** [comment]
Added to README: https://github.com/ory/hydra/commit/7ed887032431886c5fdc14462467ed3b5c0937de
