### ISSUE TITLE
consent: Login and consent request challenge should be sent as query parameter

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1307]
Currently, the consent request is consumed as a path parameter. This can cause issues when the parameter is not properly parsed at the login or consent app: `https://consent/consent?challenge=../foo` will cause the consent app to make the request to the wrong endpoint if `challenge` is not properly escaped.

**Comment by toddams** [comment]
Seems like api doc is not up to date. It still shows it as path parameter
