### ISSUE TITLE
cmd: Clients list command

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#1310]
**Is your feature request related to a problem? Please describe.**

Want `hydra clients list` command.
Client list API exists but command does not.

**Describe alternatives you've considered**

About column, I think  `client_id`, `name`, `response type`, `scope` are appropriate.
Finally it's the best to add column and filter items but this is enought at the time.

**Comment by aeneasr** [comment]
Feel free to PR this!

**Comment by sawadashota** [comment]
OK! I will try it :)
