### ISSUE TITLE
Token user container exit after getting the access token for a single login.

### ISSUE THREAD

**Issue by KishanRavindran** [ory/hydra#1320]
Hi All,
       I am following the login consent node example and I am able to get the access token and refresh token for the login. But once I get the token the hydra token user container exit. So if I need to do login in Production there based on the login consent example how can I make the container from exiting after I get access token for a user and proceed to next. Can someone guide me on how it can be done?

**Comment by aeneasr** [comment]
`hydra token user` is an **example** that is supposed to help you check if the OAuth2 flow is working correctly. It does not replace your OAuth2 client and is supposed to exit on success.
