### ISSUE TITLE
Rest API `Logs user out by deleting the session cookie is not working`

### ISSUE THREAD

**Issue by nishantd01** [ory/hydra#1329]
**Describe the bug**
I am trying to hit administrative rest end point `Logs user out by deleting the session cookie` ,
which in turn is returning me `405: Method not allowed` as a response

**To Reproduce**
1. Run `GET /oauth2/auth/sessions/login/revoke`
2. Error : `405: Method not allowed`

**Expected behavior**
This endpoint should delete  the user's login session cookie and redirect the browser to the url listed in LOGOUT_REDIRECT_URL environment variable.

**Version:**
 - Environment: Docker
 - Version: oryd/hydra:v1.0.0-rc.6_oryOS.10

**Comment by aeneasr** [comment]
Thank you for creating an issue in this repository. Unfortunately, your issue does not comply with community guidelines by not using one of the provided issue templates. Those templates help us better understand your issue and reduce latency as well as communication overhead. Please update your issue in accordance with the [issue template](../tree/master/.github/ISSUE_TEMPLATE) that fits best or this issue will be auto-closed in a 3 days.

**Comment by nishantd01** [comment]
**Describe the bug**
I am trying to hit administrative rest end point `Logs user out by deleting the session cookie` ,
which in turn is returning me `405: Method not allowed` as a response

**To Reproduce**
Steps to reproduce the behavior:
1. Run `GET /oauth2/auth/sessions/login/revoke`
2. Error : `405: Method not allowed`

**Expected behavior**
This endpoint should delete  the user's login session cookie and redirect the browser to the url listed in LOGOUT_REDIRECT_URL environment variable.


**Version:**
 - Environment: Docker
 - Version: oryd/hydra:v1.0.0-rc.6_oryOS.10

**Comment by aeneasr** [comment]
Ah yeah, that's a documentation error. That endpoint is exposed at the public port!
