### ISSUE TITLE
Reenable Config Option

### ISSUE THREAD

**Issue by gregdhill** [ory/hydra#1344]
**Describe the bug**
[This commit](https://github.com/ory/hydra/commit/5292f6c379e9fcbb0dbaa6bd188a03fa1b29feda) removes the root config option which means we can no longer provide the [YAML configuration](https://www.ory.sh/docs/next/hydra/configuration).

**To Reproduce**
1. Run `hydra -c <anything>`
2. See error

**Expected behavior**
I'm packaging the new [Helm chart for Hydra](https://github.com/helm/charts/pull/12845); it would be much nicer to provide a yaml config from the command line when running `hydra serve all`.

**Comment by ysaakpr** [comment]
When does this fix goes live,
