### ISSUE TITLE
Unable to test silent refresh in local development

### ISSUE THREAD

**Issue by DASPRiD** [ory/hydra#1364]
This might be related to #1068, getting the same error as those users. I did some digging around, and if I understand @aeneasr post on [this issue here](https://github.com/openid-certification/oidctest/issues/97) correctly, this is basically caused by the silent renew requiring additional user consent, unless the callback URL has an HTTPS scheme.

This is clearly fine for normal deployment, but it breaks in local development. Would it be possible to whitelist "localhost" return URLs for that case, possibly as a server config variable? Browsers actually follow the same pattern, e.g. with service workers, which normally require https, except when the host is "localhost".

**Comment by aeneasr** [comment]
> This is clearly fine for normal deployment, but it breaks in local development. Would it be possible to whitelist "localhost" return URLs for that case, possibly as a server config variable? Browsers actually follow the same pattern, e.g. with service workers, which normally require https, except when the host is "localhost".

"localhost" and "*.localhost" are both whitelisted for HTTP callback URLs.

**Comment by DASPRiD** [comment]
Was that always the case or just in a recent release? Our server is running on RC.6 and returning that error, although the same scopes are requested as originally, and the "remember" flag was set on the consent as well.

**Comment by aeneasr** [comment]
Yes, always the case. Maybe the client id changed, the scope was only partially granted, the timeout reached (rememberFor) for either login or consent, or the browser auth session is invalid.

**Comment by DASPRiD** [comment]
I can guarantee that it's none of those. `grant_scope` is set to `requested_scopes` in the consent app, the timeout for login and consent is set to a day, and the hydra auth session is still there (the login app is called with skip=true). Any other idea what might cause the failure or how to debug this?

**Comment by aeneasr** [comment]
Required for debugging: logfiles, request URLs, request payloads, cookies, config.

**Comment by DASPRiD** [comment]
Hm, are you sure that localhost is whitelisted? I don't see that in the code here:

https://github.com/ory/hydra/blob/20aaa46eaeeddf6a1c05cf2eb3df14bcd6638ff1/consent/strategy_default.go#L417-L426

**Comment by aeneasr** [comment]
Nice catch, so the problem is that the client is public (using implicit flow) with silent refresh which fails because the redirect URL here requires https?

**Comment by DASPRiD** [comment]
Well, I'm using authorization code flow with PKCE, since that is now recommended over implicit flow, but yeah, this makes the client public. So then as written above this fails for development on localhost which doesn't run HTTPS.

**Comment by aeneasr** [comment]
Ok that makes sense, we could probably use `github.com/ory/hydra/x.IsRedirectURISecure` here instead.

**Comment by aeneasr** [comment]
Oh not really, because that would allow custom schemes like `wta://` too. But we could use parts of that logic here to check for localhost/whitelisted.

**Comment by DASPRiD** [comment]
That sounds like a good solution :+1:

**Comment by aeneasr** [comment]
Would you be up for a PR?

**Comment by DASPRiD** [comment]
I have never worked in go before. If I find the place where the check for localhost is already done I could probably hack a PR together.
