### ISSUE TITLE
how to get userinfo

### ISSUE THREAD

**Issue by FireLustre** [ory/hydra#1367]
the api of getting userinfo is `:4444/userinfo` , but I only got this info
```
{
 "acr": "oauth2",
 "sub": "xxx@xxx.com"
}
```
and how can I get other info, like username, sex, e.g.

**Comment by aeneasr** [comment]
Endpoint `/userinfo` receives all claims you set for the ID Token (when accepting consent it's the payload of `sessions.id_token`). If you want, you can modify the userinfo location to another endpoint using [https://github.com/ory/hydra/blob/master/docs/config.yaml#L265](this configuration key).

**Comment by FireLustre** [comment]
Thanks, I solved.
