### ISSUE TITLE
Access Tokens JWT signed with ID Token key when AcessTokenStrategy is JWT

### ISSUE THREAD

**Issue by jlujan-omg** [ory/hydra#1371]
**Describe the bug**
The ID Token key is used to sign all JWTs even when Access Token strategy is JWT. The Access Token JWT should be signed using the access token signing key.

**To Reproduce**
1. Run hydra with strategies.access_token set to jwt
2. Go through authentication flow to receive signed JWT access token
3. `kid` in access token JWT is the OpenID JWT signing key

**Expected behavior**
Access Token JWT should be signed using the access token signing key.

**Version:**
 - Environment: All
 - Version master

**Additional context**

https://github.com/ory/hydra/blob/cb2ad555ce12f44af90f61ef73e7e2904af70a2c/driver/registry_base.go#L277

**Comment by aeneasr** [comment]
Please try out rc.9, which should have fixed the issue. The problem was [this line](https://github.com/ory/hydra/commit/6a16b1ee0575be4fa59e85a132c9e390f20a6889#diff-caf7a097bb542082a5ed26d24656b285R329).
