### ISSUE TITLE
SDK documentation dissapeared 

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#1377]
SDK documentation disappeared ( there used to be a README file in swagger directory, but now it's gone)

**Comment by aeneasr** [comment]
This one? https://www.ory.sh/docs/hydra/sdk/go

Also see: https://github.com/ory/hydra/blob/master/UPGRADE.md#go-sdk

**Comment by janekolszak** [comment]
This one doesn't show how to accept/reject login requests. There's a link at the bottom where I think it used to be described, but now it's 404.

UPGRADE.md is an awesome idea, very helpful when doing a big upgrade (from rc-6).

**Comment by janekolszak** [comment]
I guess doc is just not up to date. I'll wait
