### ISSUE TITLE
Outdated hydra PHP composer package

### ISSUE THREAD

**Issue by DASPRiD** [ory/hydra#1382]
Currently the latest version of the Hydra SKK in packagist `v1.0.0-rc.6+oryOS.10`, while the current Hydra release is at `rc.9`. Since meanwhile at least one API endpoint changed, the old SDK is not working with `rc.9` and should be updated.

By the way, how about splitting the SDKs into individual repositories, so when installing the PHP, JS or any other SDK it doesn't have to pull all the stuff it doesn't care about?

**Comment by lpotherat** [comment]
Hydra API libraries should be in separate repositories, it is weird to install the whole hydra sources to only get the rest api sdk.

**Comment by aeneasr** [comment]
The SDKs are packaged and the packaging removes unnecessary files - if not that's a bug (please file a separate issue). So I don't see the upside of pushing that to separate repositories which adds additional complexity for releases.

**Comment by aeneasr** [comment]
I'm assuming that composer doesn't work well with optional build tags (`+oryOS.10`). Since composer is fetching basically the git tag, and we git tag things properly, this really seems to be an issue with the version naming. What about trying to just get `v1.0.0-rc.6` (without the `oryOS` part)?

**Comment by DASPRiD** [comment]
No dice there. Packagist actually requires a trigger on your github repository to be informed about new tags. Maybe the trigger got disabled?

**Comment by aeneasr** [comment]
Yeah looks like the webhooks didn't work / weren't enabled. All tags should now be available again!
