### ISSUE TITLE
sdk/php: `composer require` installs entire hydra repository

### ISSUE THREAD

**Issue by DASPRiD** [ory/hydra#1386]
As per https://github.com/ory/hydra/issues/1382#issuecomment-486602809:

Installing the latest version in packagist via `composer require ory/hydra-sdk v1.0.0-rc.6+oryOS.10` in a fresh directory will install the entire ory/hydra repository. This means the vendor package will take up 34 MB instead of just the required ~800 KB.

Since composer loads either (via source) the entire git repository or via (via dist) the archive published and managed through .gitattributes, I don't see a proper solution to publish the PHP SDK without moving it to its own repository.

I see a similar behaviour in the JS SDK through npm by the way, although not as bad. There it seems to exclude most things, but still includes a few things which don't belong in there, like the hydra executable, which comes in at 27 MB. Also the consent and the sdk/java directory don't seem to belong there.

**Comment by aeneasr** [comment]
What about [this option](https://getcomposer.org/doc/04-schema.md#archive)?

**Comment by DASPRiD** [comment]
Hm, never seen that one before. Might work, although no idea how that integrates into the build/github/packagist process.

**Comment by aeneasr** [comment]
Would you be open to take a look? It's been a while for me since I've done anything with PHP, and seeing you being in ZF/ZF Commons you probably have more context :)

**Comment by DASPRiD** [comment]
Sure, as soon as I got that other PR working with the whitelist, that one is more pressing… Unless you can take that one over and save me from getting the go installation running here ;)

**Comment by aeneasr** [comment]
Sure happy to take over.

Regarding Go: if you're on macOS just run `brew install go`, if you're on Windows just install the MSI. If you're on linux, use [`gvm`](https://github.com/moovweb/gvm)

**Comment by aeneasr** [comment]
did you have any luck with figuring out if excluding dirs is possible with composer?

**Comment by DASPRiD** [comment]
Circling back to this: the archive->exclude option is not a solution here, as packagist relies on either the ZIP file generated by GitHub or directly clones the source, no exclusion happening there. The Exclude flag is for when someone calls `composer archive`. 

A solution to keep the everything in this repository would be to subtree split the PHP sdk together with the composer.json into a read-only repository on release. This could either be done with `git subtree split` or with a helper tool like <https://github.com/splitsh/lite>.

**Comment by aeneasr** [comment]
https://github.com/ory/hydra-client-php
