### ISSUE TITLE
CORS for public is disabled?

### ISSUE THREAD

**Issue by toddams** [ory/hydra#1387]
**Describe the bug**
Seems like setting environment variable "SERVE_PUBLIC_CORS_ENABLED" makes no effect. I can not find any message in log that CORS is enabled, even though for Admin part it works with "SERVE_ADMIN_CORS_ENABLED".
Also, I see this line: https://github.com/ory/hydra/blob/067e4983792e5527a9f024bda5255913fb2e4713/cmd/server/handler.go#L120 - seems like configuration setting is not taken into account at all (````false```` is passed)

**To Reproduce**
Run hydra with following environment variables
````yaml
environment:
      - SERVE_PUBLIC_CORS_ENABLED=true
      - LOG_LEVEL=debug
      - SERVE_PUBLIC_CORS_DEBUG=true
      - SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*
      - SERVE_ADMIN_CORS_ENABLED=true
      - SERVE_ADMIN_CORS_DEBUG=true
      - SERVE_ADMIN_CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - DSN=postgres://$POSTGR_USER:$POSTGR_PASSWORD@database:5432/$POSTGR_DB?sslmode=disable
      - URLS_LOGIN=http://localhost:5000/openid/login
      - URLS_CONSENT=http://localhost:5000/openid/consent
````

**Expected behavior**
CORS is enabled

**Version:**
 - Environment: docker
 - Version: v1.0.0-rc.9_oryOS.10

**Comment by aeneasr** [comment]
What endpoint are you trying to access?

**Comment by toddams** [comment]
It's /userinfo

**Comment by aeneasr** [comment]
What does the log show?

**Comment by aeneasr** [comment]
CORS is enabled differently at those endpoints as OAuth 2.0 Clients can advertise their own origin. It's most likely something missing, I would include `CORS_ALLOWED_HEADERS` (with Authorization because you're sending the access token), potentially `CORS_ALLOW_CREDENTIALS` as well as the methods (POST, GET).

**Comment by aeneasr** [comment]
You can check if `./well-known/jwks.json` responds with CORS headers, if it does it's probably due to you sending an Authorization Header.

**Comment by cobraz** [comment]
👋
I'm having issues with this as well. I'm still testing, but I've tested against `./well-known/jwks.json`. CORS did not work there either.

**Comment by aeneasr** [comment]
I just tried it and CORS is working fine, pretty sure it's the header setting.

```
$ hydra serve all --dangerous-force-http
```

![image](https://user-images.githubusercontent.com/3372410/56766704-52a29a00-67aa-11e9-962c-d2d037de3265.png)

**Comment by cobraz** [comment]
I've tested more – and got it working. You just have to make sure to add `Authorization` to CORS_ALLOWED_HEADERS.

**Comment by aeneasr** [comment]
Perfect, I'll document that in the docs.

**Comment by aeneasr** [comment]
I've added this to the docs

**Comment by aeneasr** [comment]
We'll actually set the defaults to something sane, as per #1400 .

This will hopefully avoid unnecessary work in the future.
