### ISSUE TITLE
go sdk is broken in rc9

### ISSUE THREAD

**Issue by pereslava** [ory/hydra#1388]
**Describe the bug**
The sdk for golang broken or documentation does not reflect the latest changes

**To Reproduce**
1. Run command from documentation `go get -u -d github.com/ory/hydra/sdk/go/hydra`
**Result**
- GOPATH mode: 

> package github.com/ory/hydra/sdk/go/hydra: no Go files in $GOPATH/src/github.com/ory/hydra/sdk/go/hydra

 - GOMOD mode:

> go get github.com/ory/hydra/sdk/go/hydra: no matching versions for query "latest"

2. Inside go module run `go get -u -d github.com/ory/hydra`
  The tag v0.11.14 fetched
**Expected behavior**
The version tagged v1.0.0-rc.9+oryOS.10 should be fetched

3. Inside go module run go get -u -d github.com/ory/hydra@v1.0.0-rc9+oryOS.10

> go get github.com/ory/hydra@v1.0.0-rc9+oryOS.10: unknown revision v1.0.0-rc9

And same for v1.0.0-rc9 and v1.0.0

4 Inside of go module try to fetch by latest release tag commit hash:
`go get github.com/ory/hydra@9c6e4c120c12b37b349bb7dd2695cd52ed2fc0ea`
The build failed with 

> cannot load github.com/ory/hydra/sdk/go/hydra: cannot find module providing package github.com/ory/hydra/sdk/go/hydra

5 I didn't found the hydra.NewSDK func (the documentation refers to it) in $GOPATH/src/github.com/ory/hydra/sdk/go

**Version:**
 - Version [v1.0.0-rc.9+oryOS.10]

**Comment by pereslava** [comment]
Actually there are two problems, which I think easy to solve.
1. The SDK initialization code was gone.
2. Go does not recognize the repository tag. I think tagging the repository without "+oryOS.10" should solve the problem with go get inside the go modules. Because getting by hash is working.

**Comment by aeneasr** [comment]
Yeah, the URL changed. It also seems that go modules isn't particularly good at resolving:

* submodules of a go module
* semver with metadata (`+...`)

As a workaround:

```
go get -u -d github.com/ory/hydra@master
```

**Comment by aeneasr** [comment]
The SDK docs in general need to be updated

**Comment by aeneasr** [comment]
https://github.com/ory/docs/pull/119/files?short_path=9814f96#diff-9814f9683440dfba95a7899639b723a5
