### ISSUE TITLE
Accept login request 404s

### ISSUE THREAD

**Issue by leovingi** [ory/hydra#1406]
**Describe the bug**
I'm currently testing out the latest binary locally and am running into an issue where the login acceptance URL returns a 404
```{"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}```

**To Reproduce**
1. I successfully created an OAuth2 client
2. I started the auth process through https://localhost:4444/oauth2/auth?client_id=12345&response_type=code&state=aaaaaaaa
3. I got redirected to the login URL with a login_challenge query parameter
4. I verify that the login challenge is in my Postgres DB
5. `[PUT] https://localhost:4444/oauth2/auth/requests/login/{challenge}/accept` returns a 404

**Expected behavior**
I would expect it to throw an error only if the challenge code is wrong, but not when I actually want to accept the request after a successful login attempt.

**Version:**
 - Environment: binary, Linux, Elementary OS
 - Version v1.0.0-rc.10

**Comment by MDrollette** [comment]
The routes changed to pass the challenge as a query string https://github.com/ory/hydra/blob/master/UPGRADE.md#accepting-login-and-consent-requests

Also the login/consent requests https://github.com/ory/hydra/blob/master/UPGRADE.md#login-and-consent-management

**Comment by leovingi** [comment]
Thank you. I was going through these docs, but I guess they're not updated yet?
https://www.ory.sh/docs/hydra/sdk/api#accept-an-login-request

I'll test this out and will close the issue if all good.

**Comment by aeneasr** [comment]
Yeah, it's actually shown correctly in the params section but not the path

**Comment by leovingi** [comment]
Yes, the new route worked.

Thanks a bunch for the help!
