### ISSUE TITLE
Documentation is incorrect for some admin URLs

### ISSUE THREAD

**Issue by yukw777** [ory/hydra#1410]
**Describe the bug**
The REST API documentation states that the urls to {accept, reject} login or consent requests are in the form of `/oauth2/auth/requests/{login,consent}/{challenge}/{accept,reject}`. However, this is incorrect and it actually needs to be `/oauth2/auth/requests/{login,consent}/{accept,reject}?{login,consent}_challenge={challenge}`.
**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Version:**
v1.0.0

**Additional context**
N/A

**Comment by aeneasr** [comment]
The API docs didn't get build properly, this should be resolved now in the docs!.
