### ISSUE TITLE
.well-known/openid-configuration endpoint swapped values

### ISSUE THREAD

**Issue by jtescher** [ory/hydra#1420]
**Describe the bug**

`.well-known/openid-configuration` swapped values for `claims_supported` and `scopes_supported`

**To Reproduce**

Use curl to view openid configuration payload and note that the above mentioned keys are swapped.

Additionally the test case here shows them swapped https://github.com/ory/hydra/blob/master/oauth2/handler_test.go#L401-L402

**Comment by aeneasr** [comment]
Thank you! Would you be open to create a PR for this?

**Comment by aeneasr** [comment]
This is resolved
