### ISSUE TITLE
Invalid namespace on composer.json

### ISSUE THREAD

**Issue by MASNathan** [ory/hydra#1429]
**Describe the bug**
The new version of generated Hydra Client assumes the namespace of `Hydra\SDK` as you can see [here](https://github.com/ory/hydra/blob/master/sdk/php/swagger/lib/ApiClient.php#L30), the issue is that the [composer.json](https://github.com/ory/hydra/blob/master/composer.json#L20) was not updated to match this new namespace, it still used `HydraSDK`

**To Reproduce**
1. Install via composer  with version `v1.0.0-rc.11`
2. Try instantiate the client via composer's autoload
3. See error `Class Hydra\SDK\Api\AdminApi does not exist`

**Expected behavior**
Instantiate the Api client

**Version:**
 - Composer version 1.8.5 2019-04-09 17:46:47
 - Version v1.0.0-rc.11

**Additional context**
This is the exact opposite of the issue #1199

**Comment by aeneasr** [comment]
Would you be open to create a PR to fix this? :)

**Comment by MASNathan** [comment]
Done 😄
