### ISSUE TITLE
Unix socket ignores first part of the uri

### ISSUE THREAD

**Issue by jopicornell** [ory/hydra#1433]
**Describe the bug**

When using unix as host for the administrative REST API, it seems that the first part of the uri is being ignored. You can put whatever you want at the first part of the path (usually oauth2) and it will get ignored, receiving a 404.

**Reproducing the bug**

1. Run `hydra serve all`
2. Make API Request to with `curl --unix-socket /opt/hydra/admin.sock "http:/oauth2/auth/requests/login?login_challenge=0bc25c8363e14156b2d637009bdc3f12"`
3. Request fails with response: `{"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}`
4. Make API Request to with `curl --unix-socket /opt/hydra/admin.sock "http:/11111/oauth2/auth/requests/login?login_challenge=0bc25c8363e14156b2d637009bdc3f12"`
5. Request success with response: `{"challenge":"0bc25c8363e14156b2d637009bdc3f12","requested_scope":["openid"],...`

*Server logs*

```
May 15 20:51:47 joan-arch hydra[31638]: time="2019-05-15T20:51:47+02:00" level=info msg="completed handling request" measure#hydra/admin: https://auth.mercator.test/.latency=128428 method=GET remote=@ request="/auth/requests/login?login_challenge=0bc25c8363e14156b2d637009bdc3f12" status=404 text_status="Not Found" took="128.428µs"
May 15 20:51:58 joan-arch hydra[31638]: time="2019-05-15T20:51:58+02:00" level=info msg="started handling request" method=GET remote=@ request="/oauth2/auth/requests/login?login_challenge=0bc25c8363e14156b2d637009bdc3f12"
```

*Server configuration*

**Expected behavior**

It should allow to make a request with cURL like `curl --unix-socket /opt/hydra/admin.sock "http:/clients"`

**Environment**

* Version:    v1.0.0-rc.11
Git Hash:   33acfa8d18cb8b3f7896de813d4e8f61f19dde0c
Build Time: 2019-05-02T14:03:15Z

* Environment: ArchLinux x86_64, Kernel 5.0.7

**Comment by aeneasr** [comment]
ping @someone1 

However it feels like this should be `http:///clients`.

**Comment by jopicornell** [comment]
@aaslamin Not an expert on unix domain sockets. I didn't found official documentation about this, but many people connecting to docker http socket like the way I do ([Like this](https://gist.github.com/patrickmslatteryvt/1d9e5212fe96e19f111cb7a0f8d498fb), [this](https://kelcecil.com/curl/2015/12/07/query-unix-socket-with-curl.html), and [here, on the "HTTP" example tab](https://docs.docker.com/develop/sdk/))

Maybe a curl problem?

**Comment by jopicornell** [comment]
@aaslamin @someone1 Further investigation lead me to curl and I tried to find something related inside curl. It seems that [this discussion](https://github.com/curl/curl/issues/936) is what is giving me the problem and hydra is handling the request correctly.

Sorry for opening the bug. It seemed premature opened but yesterday I was crazy finding the right solution and I thought hydra was the problem. Thank you guys!
