### ISSUE TITLE
Incorrect namespace for PHP SDK

### ISSUE THREAD

**Issue by hoangnd25** [ory/hydra#1443]
**Describe the bug**

Since this commit: https://github.com/ory/hydra/commit/b5cb1534cc243202e90da10015aa8895fbbd9b66

PHP SDK is using HydraSDK namespace

However, namespace is set to Hydra\Sdk in composer.json

**Reproducing the bug**

1. Run composer install
2. Requires the package

**Expected behavior**

composer.json should be updated according to the latest sdk

**Comment by DASPRiD** [comment]
Interestingly, #1431 changed the composer.json only 10 days ago, when the PHP namespace was apparently `Hydra\Sdk`, which changed again.

**Comment by aeneasr** [comment]
Oh, that's most likely because of [swagger-codegen](https://github.com/ory/hydra/blob/master/Makefile#L105-L106) - would you be up for checking what's going on there?

**Comment by DASPRiD** [comment]
I'll be out on vacation for the next 7 days, I suppose I could look at it after that when it's not resolved until then. Which namespace is the actual preferred one, `Hydra\Sdk` oder `HydraSDK`?

**Comment by hoangnd25** [comment]
@aeneasr PHP namespace seems to be `HydraSDK` now, but the namespace in composer.json file is still `Hydra\Sdk`
