### ISSUE TITLE
Support Jaeger Tracing with Istio and Kubernetes

### ISSUE THREAD

**Issue by ptescher** [ory/hydra#1447]
**Is your feature request related to a problem? Please describe.**

The Opentracing integration is nice but it does not support a few features needed to integrate with Istio (at least not with the standard Istio setup). Istio uses Zipkin b3 headers which are supported by jaeger-client-go but not by default. A standard Istio/Kubernetes setup will also run jaeger-agent as a daemon set and in order to get the IP address you usually do `fieldPath: status.hostIP` but that only sets the host, not the port.

**Describe the solution you'd like**

- [x] Support for separate JAEGER_AGENT_HOST env var (https://github.com/jaegertracing/jaeger-kubernetes/blob/master/README.md#jaeger-components).
- [ ] Support Zipkin B3 headers (https://github.com/jaegertracing/jaeger-client-go/blob/master/zipkin/README.md#NewZipkinB3HTTPHeaderPropagator) potentially via the `JAEGER_PROPAGATION` env var.

**Describe alternatives you've considered**

Using a custom bash script to initialize hydra.

**Additional context**

The Jaeger Go client already supports a bunch of env vars, it would be nice to support all of them: https://www.jaegertracing.io/docs/1.12/client-features/

**Comment by aeneasr** [comment]
Related #1442

**Comment by aeneasr** [comment]
Did the related issue resolve the Zipkin B3 issue too? If not, would you be open for a PR?

**Comment by ptescher** [comment]
@aeneasr it did not, the go framework doesn't want to expose the B3 via an env var because it would require that the configuration module be linked to other modules. Should be an easy PR though.

**Comment by aeneasr** [comment]
Would you be up for a PR?

**Comment by ptescher** [comment]
Yeah I can take a shot at it.
