### ISSUE TITLE
Slow MySQL query 

### ISSUE THREAD

**Issue by leonfancy** [ory/hydra#1454]
**Describe the bug**

MySQL slow query log files gives many slow queries when I do performance test against hydra.

I found the all slow queries are in three categories shown below.

```
# Time: 2019-05-24T09:56:29.681400Z
# User@Host: hydra[hydra] @  [10.71.20.146]  Id:    53
# Query_time: 0.233999  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 62344
SET timestamp=1558691789;
SELECT h.* FROM
	hydra_oauth2_consent_request_handled as h
JOIN
	hydra_oauth2_consent_request as r ON (h.challenge = r.challenge)
WHERE
		r.subject='620b091f-d47a-3b67-9d99-faeb174498ec' AND r.client_id='nmaid:SAMPLE_***_ID' AND r.skip=FALSE
	AND
		(h.error='{}' AND h.remember=TRUE)
ORDER BY h.requested_at DESC
LIMIT 1;
```

I use MySQL `EXPLAIN` to analyze this query, 
![image](https://user-images.githubusercontent.com/4530475/58322739-6e09cf00-7e54-11e9-9dfb-6cb1d1ba560e.png)
The query on `hydra_oauth2_consent_request_handled` doesn't use any index, and scan the whole table. That's why it's slow.

```
# Time: 2019-05-24T09:56:29.447401Z
# User@Host: hydra[hydra] @  [10.71.20.151]  Id:    54
# Query_time: 0.202798  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1558691789;
INSERT INTO hydra_oauth2_code (signature, request_id, requested_at, client_id, scope, granted_scope, form_data, session_data, subject, active, requested_audience, granted_audience, challenge_id) VALUES ('lWhL8WTx4ZOlvplXxGEA8ckVy1oQc3hi4XAyhRR6Tm0', 'cf22b93655c241f8b08e087e33004cac', '2019-05-24 09:57:05.074431', 'nmaid:SAMPLE_***_ID', 'ncs', 'ncs', 'redirect_uri=http%3A%2F%2F127.0.0.1%3A8090%2Fcallback', '{\"idToken\":{\"Claims\":{\"JTI\":\"\",\"Issuer\":\"https://demo.***.net/\",\"Subject\":\"620b091f-d47a-3b67-9d99-faeb174498ec\",\"Audience\":null,\"Nonce\":\"\",\"ExpiresAt\":\"0001-01-01T00:00:00Z\",\"IssuedAt\":\"2019-05-24T09:57:05.086211212Z\",\"RequestedAt\":\"2019-05-24T09:57:02Z\",\"AuthTime\":\"2019-05-24T09:56:56Z\",\"AccessTokenHash\":\"\",\"AuthenticationContextClassReference\":\"\",\"CodeHash\":\"\",\"Extra\":{}},\"Headers\":{\"Extra\":{\"kid\":\"public:aac91d82-b050-4ad0-841c-120883d8f5c4\"}},\"ExpiresAt\":{\"authorize_code\":\"2019-05-24T10:07:05.0862354Z\"},\"Username\":\"\",\"Subject\":\"620b091f-d47a-3b67-9d99-faeb174498ec\"},\"extra\":{},\"KID\":\"public:e2574f8c-486a-4ee4-9eec-53c7a72e2ccc\",\"ClientID\":\"nmaid:SAMPLE_***_ID\",\"ConsentChallenge\":\"cf22b93655c241f8b08e087e33004cac\"}', '620b091f-d47a-3b67-9d99-faeb174498ec', 1, '', '', 'cf22b93655c241f8b08e087e33004cac');
```

```
# Time: 2019-05-24T06:02:41.240906Z
# User@Host: hydra[hydra] @  [10.71.20.158]  Id:    22
# Query_time: 3.026381  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 0
SET timestamp=1558677758;
INSERT INTO hydra_oauth2_access (signature, request_id, requested_at, client_id, scope, granted_scope, form_data, session_data, subject, active, requested_audience, granted_audience, challenge_id) VALUES ('075265ef8659d0ebb2c6a26c31c4d9c456e78acc596c58a30afe523a8dbb3b108e6468905fafcd21a15f64baec491b5d', '02efe722167a438abff706711fa66b40', '2019-05-24 06:03:12.443321', 'nmaid:SAMPLE_***_ID', 'ncs', 'ncs', '', '{\"idToken\":{\"Claims\":{\"JTI\":\"\",\"Issuer\":\"https://demo.***.net/\",\"Subject\":\"620b091f-d47a-3b67-9d99-faeb174498ec\",\"Audience\":null,\"Nonce\":\"\",\"ExpiresAt\":\"0001-01-01T00:00:00Z\",\"IssuedAt\":\"2019-05-24T06:03:12.406409502Z\",\"RequestedAt\":\"2019-05-24T06:03:12Z\",\"AuthTime\":\"2019-05-24T06:02:53Z\",\"AccessTokenHash\":\"\",\"AuthenticationContextClassReference\":\"\",\"CodeHash\":\"\",\"Extra\":{}},\"Headers\":{\"Extra\":{\"kid\":\"public:aac91d82-b050-4ad0-841c-120883d8f5c4\"}},\"ExpiresAt\":{\"access_token\":\"2019-05-24T12:03:13Z\",\"authorize_code\":\"2019-05-24T06:13:12.406429942Z\",\"refresh_token\":\"2019-06-23T06:03:13Z\"},\"Username\":\"\",\"Subject\":\"620b091f-d47a-3b67-9d99-faeb174498ec\"},\"extra\":{},\"KID\":\"public:e2574f8c-486a-4ee4-9eec-53c7a72e2ccc\",\"ClientID\":\"nmaid:SAMPLE_***_ID\",\"ConsentChallenge\":\"02efe722167a438abff706711fa66b40\"}', '620b091f-d47a-3b67-9d99-faeb174498ec', 1, '', '', '02efe722167a438abff706711fa66b40');
```
I'm not sure why these two `INSERT` queries are slow. I guess it's because the primary key `signature` is a string, when inserting new row, it's hard to sort the string index. 

**Reproducing the bug**

Performance test againt hydra with 50 concurrency thread. 

*Server configuration*

docker run -d --name hydra --rm -p 4444:4444 -p 4445:4445 \
    --network hydraguide \
    -e SECRETS_SYSTEM=**** \
    -e LOG_LEVEL=debug \
    -e OAUTH2_EXPOSE_INTERNAL_ERRORS=true \
    -e STRATEGIES_ACCESS_TOKEN=jwt \
    -e TTL_ACCESS_TOKEN=6h \
    -e URLS_CONSENT=http://127.0.0.1:8080/consent \
    -e URLS_LOGIN=http://127.0.0.1:8080/login \
    -e URLS_SELF_ISSUER=http://127.0.0.1:4444 \
    -e DSN=$DSN \
    -e WEBFINGER_JWKS_BROADCAST_KEYS=hydra.jwt.access-token \
   oryd/hydra:v1.0.0-rc.9 serve all --dangerous-force-http

**Expected behavior**

**Environment**

* Version: oryd/hydra:v1.0.0-rc.9
* Environment: K8s

**Comment by aeneasr** [comment]
Nice, the first one can probably be solved fairly easy (by adding an index).

It's possible that the second slow query is caused by the long string. There's definitely a 10x performance difference between code (which uses HMAC strategy) and access token (which uses the JWT strategy), most likely caused by the string length difference - not sure.

Could you re-execute your benchmark against mysql without the JWT strategy?

**Comment by leonfancy** [comment]
I found this slow query is because every requests has same `subject` so that the index can't be used. 

```
# Time: 2019-05-24T09:56:29.681400Z
# User@Host: hydra[hydra] @  [10.71.20.146]  Id:    53
# Query_time: 0.233999  Lock_time: 0.000000 Rows_sent: 0  Rows_examined: 62344
SET timestamp=1558691789;
SELECT h.* FROM
	hydra_oauth2_consent_request_handled as h
JOIN
	hydra_oauth2_consent_request as r ON (h.challenge = r.challenge)
WHERE
		r.subject='620b091f-d47a-3b67-9d99-faeb174498ec' AND r.client_id='nmaid:SAMPLE_***_ID' AND r.skip=FALSE
	AND
		(h.error='{}' AND h.remember=TRUE)
ORDER BY h.requested_at DESC
LIMIT 1;
```

Please ignore this issue, since `subject` won't be all the same in practise.

**Comment by inigohu** [comment]
I'm experiencing the same issue with the first query.

I have some `sql-conn-query` spans that have large latencies when running this query:
`SELECT h.* FROM hydra_oauth2_consent_request_handled as h JOIN hydra_oauth2_consent_request as r ON (h.challenge = r.challenge) WHERE r.subject=$1 AND r.client_id=$2 AND r.skip=FALSE AND (h.error='{}' AND h.remember=TRUE) ORDER BY h.requested_at DES`

Some of them takes up to 46798.673 ms, 7196.002 ms, or 4821.986 ms for example

**Comment by aeneasr** [comment]
Please open a new issue and include vital information such as your hydra version.
