### ISSUE TITLE
The hydra can't handle the DB username with "@" character

### ISSUE THREAD

**Issue by yxzhm** [ory/hydra#1460]
**Describe the bug**
If I set the user name of DB with "@" char, the hydra can't connect to the DB.
When we create the mysql db in Azure, the user name always contains "@" character.
The DSN example is as following:
DSN=mysql://sa@test.mysql.database.azure.com:MyPassword@(127.0.0.1:3306)/hydra

According to my investigation, the issue caused by below function in sqlcon lib.
This QueryEscape will replace "@" to "%40".
```
func connectionString(clean *url.URL) string {
	if clean.Scheme == "mysql" {
		q := clean.Query()
		q.Set("parseTime", "true")
		clean.RawQuery = q.Encode()
	}

	username := clean.User.Username()
	userinfo := username
	password, hasPassword := clean.User.Password()
	if hasPassword {
		userinfo = url.QueryEscape(userinfo) + ":" + url.QueryEscape(password)
	}
	clean.User = nil
	u := clean.String()
	clean.User = url.UserPassword(username, password)

	if strings.HasPrefix(u, clean.Scheme+"://") {
		u = strings.Replace(u, clean.Scheme+"://", clean.Scheme+"://"+userinfo+"@", 1)
	}
	if clean.Scheme == "mysql" {
		u = strings.Replace(u, "mysql://", "", -1)
	}
	return u
}
```

**Comment by aeneasr** [comment]
Does `mysql://sa%40test.mysql.database.azure.com:MyPassword@(127.0.0.1:3306)/hydra` work?

**Comment by yxzhm** [comment]
> Does `mysql://sa%40test.mysql.database.azure.com:MyPassword@(127.0.0.1:3306)/hydra` work?

Nope

**Comment by aeneasr** [comment]
Can you confirm that connecting to `mysql://sa@test.mysql.database.azure.com:MyPassword@(127.0.0.1:3306)/hydra` works when:

```
- userinfo = url.QueryEscape(userinfo) + ":" + url.QueryEscape(password)
+ userinfo = userinfo + ":" + password
```

?

**Comment by aeneasr** [comment]
It seems like [ParseDSN](https://github.com/go-sql-driver/mysql/blob/master/dsn.go#L375) doesn't care about URL formatting (username and info should be url encoded...) but simply uses the "last" `@` or the last `/`. I have to check if that's the case for the postgres driver too (I think they actually care about proper URL formatting).

**Comment by yxzhm** [comment]
The below update works fine.
Do you have a plan to fix this issue recently? This issue blocks the deployment in Azure cloud.

BTW: The https://github.com/ory/sqlcon is archived. 

`- userinfo = url.QueryEscape(userinfo) + ":" + url.QueryEscape(password)
+ userinfo = userinfo + ":" + password
`

**Comment by aeneasr** [comment]
> BTW: The https://github.com/ory/sqlcon is archived.

It moved to: https://github.com/ory/x/tree/master/sqlcon

> Do you have a plan to fix this issue recently? This issue blocks the deployment in Azure cloud.

Next couple of days are busy but I have time to review and merge PRs if you create one!

**Comment by yxzhm** [comment]
Sure, I will try to create a PR ASAP. Thank you in advance.

**Comment by yxzhm** [comment]
I have created the PR. Could you please help to review it?
Thank you

https://github.com/ory/x/pull/57

**Comment by leonfancy** [comment]
When will this feature be released? We are going to use it in our product.
