### ISSUE TITLE
What's the deal with LICENSE.txt in the 64-bit linux tarball? is this open source or not?

### ISSUE THREAD

**Issue by Max-E** [ory/hydra#1462]
Although the LICENSE file in the git source tree is a copy of the Apache 2.0 license, when I download the precompiled Linux tarball (https://github.com/ory/hydra/releases/download/v1.0.0-rc.15/hydra_1.0.0-rc.15_Linux_64-bit.tar.gz) the included license doesn't look open source at all.

I get that there may be a dual-licensing situation going on here, but if Hydra is truly open source, the license text in this download should be corrected or clarified to explicitly include both licenses.

**Comment by aeneasr** [comment]
We've been experimenting (not executing) with a license model where the source code is and stays Apache 2.0 licensed, but all builds are licensed with a more restrictive license (such as EULA). This follows practices set by RedHat.

However, this is just an experiment so far. We have not talked about this publicly or made a decision towards full open source (everything, including builds, Apache 2.0) or a split model (the one above). If we do decide for the second, we will state it transparent and clear in the appropriate channels.
