### ISSUE TITLE
hydra fails to connect mysql server

### ISSUE THREAD

**Issue by RaspiRepo** [ory/hydra#1463]
**Describe the bug**

"oryd/hydra:v1.0.0-rc.12" fails to connect mysql database server
but "oryd/hydra:v1.0.0-rc.6_oryOS.10"  works fine with same mysql server

**Reproducing the bug**
Kubernate cluster
1. deploy mysql server (pod) in kubernte cluster
2. deploy hydra service using  "image: "oryd/hydra:v1.0.0-rc.12"

*Server logs*

```
`time="2019-06-07T07:26:48Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:48Z" level=info msg="Retrying in 0.100000 seconds..."
time="2019-06-07T07:26:49Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:49Z" level=info msg="Retrying in 0.200000 seconds..."
time="2019-06-07T07:26:49Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:49Z" level=info msg="Retrying in 0.400000 seconds..."
time="2019-06-07T07:26:49Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:49Z" level=info msg="Retrying in 0.800000 seconds..."
time="2019-06-07T07:26:50Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:50Z" level=info msg="Retrying in 1.600000 seconds..."
time="2019-06-07T07:26:52Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:52Z" level=info msg="Retrying in 3.200000 seconds..."
time="2019-06-07T07:26:55Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:26:55Z" level=info msg="Retrying in 5.000000 seconds..."
time="2019-06-07T07:27:00Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:27:00Z" level=info msg="Retrying in 5.000000 seconds..."`
```
*Server configuration*
Kubernate cluster
1. deploy mysql server (pod) in kubernte cluster
image: "mysql"
imageTag: "5.7.14"
2. deploy hydra 
  "image: "oryd/hydra:v1.0.0-rc.12"

**Expected behavior**
`>> Subscribe now: http://eepurl.com/di390P <<
time="2019-06-07T07:21:30Z" level=info msg="Setting up tracing middleware"
time="2019-06-07T07:21:30Z" level=info msg="Jaeger tracer configured!"
time="2019-06-07T07:21:30Z" level=info msg="Connecting with mysql://*:*@tcp(mysql:3306)/dt10?"
time="2019-06-07T07:21:30Z" level=info msg="Connected to SQL!"
time="2019-06-07T07:21:30Z" level=warning msg="Could not parse login and consent request lifespan value (). Defaulting to 15m"
time="2019-06-07T07:21:30Z" level=info msg="Setting up Prometheus middleware"
time="2019-06-07T07:21:30Z" level=info msg="Setting up http server on :4445"
time="2019-06-07T07:21:30Z" level=info msg="TLS termination enabled, disabling https."
time="2019-06-07T07:21:30Z" level=info msg="Setting up http server on :4444"
time="2019-06-07T07:21:30Z" level=info msg="TLS termination enabled, disabling https."`

**Environment**

* Version: v1.2.3, git sha hash
https://github.com/ory/hydra/releases/tag/v1.0.0-rc.12
* Environment: aws kubernate, ...

**Additional context**
version image oryd/hydra:v1.0.0-rc.6_oryOS.10"  works   mysql server version  "5.7.14"
but "v1.0.0-rc.12" does not work.

**Comment by aeneasr** [comment]
Probably dupe #1457 or #1460

**Comment by RaspiRepo** [comment]
its not dupe #1457 or #1460
mysql username/psw don't have char @, but & *

**Comment by aeneasr** [comment]
It is a dupe, as it uses a non-url-standard char.
