### ISSUE TITLE
`id_token_hint` should be optional on `end_session_endpoint`

### ISSUE THREAD

**Issue by bodewig** [ory/hydra#1472]
As it is currently implemented the `end_session_endpoint` wil reject requests without any `id_token_hint` parameter. This contradicts https://openid.net/specs/openid-connect-session-1_0.html#RPLogout which says the parameter is RECOMMENDED but not required.

I'm not sure what the proper behavior of Hydra in the absence of an `id_token_hint` would be. I'd likely want Hydra to terminate all session currently associated with the request and revoke any Cookies it has set.

Navigate to the end_session_endpoint without any `Id_token_hint` parameter.

**Expected behavior**

Sessions get terminated, the user is redirected to a post_redirect_uri if the parameter is present.

**Comment by aeneasr** [comment]
`id_token_hint` is not enforced, but required for certain parameter combinations. You're probably hitting one of those: https://github.com/ory/hydra/blob/master/consent/strategy_default.go#L727-L738

**Comment by bodewig** [comment]
Yes, I'm using `post_logout_redirect_uri`.

Why does Hydra require the `id_token_hint` in that case? I can guess it needs it to determine the `client_id` in order to verify the redirect_uri is valid.

**Comment by aeneasr** [comment]
No, it's not possible to guess the client_id in that scenario.

**Comment by bodewig** [comment]
Sorry, I used a crude way to pose the question. It should have been

I guess Hydra requires the `id_token_hint` so it can know the `client_id`, right?

And you've already answered that :-)

Understood. Many thanks.
