### ISSUE TITLE
Support different read/write database URLs

### ISSUE THREAD

**Issue by ianmobbs** [ory/hydra#1475]
**Is your feature request related to a problem? Please describe.**

I'd like to use Hydra in a multi-datacenter, multi-node environment. I'd like to utilize AWS Aurora as the data store for it's global read capabilities. However, this means I can only have one write node for the database and several read nodes. 

**Describe the solution you'd like**

I'd like a set of two additional, optional config parameters introduced - `dsnw` and `dsnr`. If given a `dsn`, Hydra performs all operations on the same database. If given `dsnw` and `dsnr`, Hydra performs write operations ([inserts, updates, deletes, and DDL changes](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.Endpoints.html#Aurora.Endpoints.Cluster)) on the `dsnw` (in this case, the AWS Aurora write node) and read operations on the `dsnr` (in this case, the globally replicated read nodes).

**Describe alternatives you've considered**

- Hosting all clients in the same (writeable) datacenter and redirecting users to other (read-only) datacenters after authentication.
- Adding a reader and writer host to one JDBC URL, as mentioned in the Postgres documentation [here](https://jdbc.postgresql.org/documentation/94/connect.html).
>  For example an application can create two connection pools. One data source is for writes, another for reads. The write pool limits connections only to master node:
> `jdbc:postgresql://node1,node2,node3/accounting?targetServerType=master.`
> And read pool balances connections between slaves nodes, but allows connections also to master if no slaves are available:
> `jdbc:postgresql://node1,node2,node3/accounting?targetServerType=preferSlave&loadBalanceHosts=true`
> If a slave fails, all slaves in the list will be tried first. If the case that there are no available slaves the master will be tried. If all of the servers are marked as "can't connect" in the cache then an attempt will be made to connect to all of the hosts in the URL in order.

However, this requires some implementation of connection pooling on Hydra's part.

**Additional context**

n/a

--

Thank you!

**Comment by aaslamin** [comment]
Can't you setup something like https://proxysql.com/ then configure custom query routing? So you would basically have a LB fronting your database(s).

**Comment by aeneasr** [comment]
Yeah, this is out of Hydra's domain and there are plenty SQL LoadBalancers out there, proxysql being on of the most popular.

**Comment by ianmobbs** [comment]
Thanks @aeneasr!
