### ISSUE TITLE
oauth2/token issue

### ISSUE THREAD

**Issue by jarvisparacha** [ory/hydra#1484]
---
name: oauth2/token refresh token issue
about: oauth2/token is returning an error during refresh token

---

**Describe the bug**

oauth2/token refresh token issue

oauth2/token to generate a bearer token responds correctly: with bearer token / refresh token
However, calling oauth2/token to refresh a token is giving us an error

**Reproducing the bug**

1. Run the curl:
curl -X POST http://localhost:32769/oauth2/token -d "grant_type=refresh_token&refresh_token=AAAAAzzzzzzzzzzzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxAAA&redirect_uri=https://ZZZZZZ" -H "x-api-key : ZZZZZZ" -H 'content-type: application/x-www-form-urlencoded' -H 'Authorization: Basic XXXXXXXX' -vv

*Server logs*

[ec2-user@ip-12-8-9-6 ~]$ curl -X POST http://localhost:32769/oauth2/token -d "grant_type=refresh_token&refresh_token=AAAAAzzzzzzzzzzzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxAAA&redirect_uri=https://ZZZZZZ" -H "x-api-key : ZZZZZZ" -H 'content-type: application/x-www-form-urlencoded' -H 'Authorization: Basic XXXXXXXX' -vv
Note: Unnecessary use of -X or --request, POST is already inferred.

Trying 127.0.0.1...
TCP_NODELAY set
Connected to localhost (127.0.0.1) port 32769 (#0)
POST /oauth2/token HTTP/1.1
Host: localhost:32769
User-Agent: curl/7.53.1
Accept: /
x-api-key : ZZZZZZ
content-type: application/x-www-form-urlencoded
Authorization: Basic XXXXXXXX
Content-Length: 166

upload completely sent off: 166 out of 166 bytes
Empty reply from server
Connection #0 to host localhost left intact
curl: (52) Empty reply from server

**Environment**
* hydra v 1.0.0-beta.7-alpine

**Additional context**

Since we released last year, we are not having any problem.
3 to 4 weeks ago, a client reported this issue and it still persists until now

**Comment by aeneasr** [comment]
Thank you for creating an issue in this repository. Unfortunately, your issue does not comply with community guidelines by not using one of the provided issue templates. Those templates help us better understand your issue and reduce latency as well as communication overhead. Please update your issue in accordance with the [issue template](../tree/master/.github/ISSUE_TEMPLATE) that fits best or this issue will be auto-closed in a 3 days.

**Comment by aeneasr** [comment]
Please format the issue ([how to format code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)) and include hydra server logs. Also, you're on a very old version of Hydra and I recommend upgrading to the latest one.

**Comment by jarvisparacha** [comment]
Thank you and I will provide what is asked
How to enable hydra server logs?

**Comment by aeneasr** [comment]
Hydra always emits logs, you don't need to enable that.

**Comment by aeneasr** [comment]
I'm closing this issue because:

- Issue is stale
- No logs were provided
- Hydra is running as an old/unsupported version

Feel free to post any findings here regardless, if you find them.
