### ISSUE TITLE
Configuration docs link is incorrect in `hydra serve --help`

### ISSUE THREAD

**Issue by goknsh** [ory/hydra#1486]
**Describe the bug**

Link to configuration documentation when running `hydra serve --help` shows a link to: <https://github.com/ory/hydra/blob/v1.0.0+oryOS.12/docs/config.yaml>, which leads to a 404 page.

**Reproducing the bug**

1. Install Hydra with:
```bash
$ curl https://raw.githubusercontent.com/ory/hydra/master/install.sh | bash -s -- -b .
```
2. Run command to view help info:
```bash
$ ./hydra serve --help
```

**Expected behavior**
See [serve.go](https://github.com/ory/hydra/tree/master/cmd/serve.go):  
Looks like the URL for config documentation is being generate using the installed `Version`.

It should instead use the commit for the installed `Version`.  
So if the error is corrected, the correct URL would be:  
`https://github.com/ory/hydra/blob/<commit>/docs/config.yaml`

**Comment by aeneasr** [comment]
Nice catch! Would you be up for a PR?

**Comment by goknsh** [comment]
Sorry I can't do a PR since I do not know Go at all and was able to identify what was wrong using my general knowledge in code.

**Comment by goknsh** [comment]
I think changing `Version` to `Commit` should work, but I am unsure and could not setup the Hydra development environment to test it.
