### ISSUE TITLE
cmd: Register logout params with the OP as part of client registration 

### ISSUE THREAD

**Issue by safurabahrami** [ory/hydra#1487]
`backchannel-logout-session-required` and `backchannel-logout-uri` is not being handled in cmd as part of client registration.

Right now we are using this command to register client but can not pass those params.
```
      clients create
        --id rp-client
        --secret secret
        --grant-types authorization_code,refresh_token
        --response-types code,id_token,token
        --scope openid,offline
        --callbacks http://rp.ca/callback
        --token-endpoint-auth-method client_secret_post
```

**Comment by aaslamin** [comment]
Hi @safurabahrami,

Thanks for creating the issue, for future correspondence could you please follow the issue template by providing the rest of the deets requested.

I took a quick peek, these attribute are indeed currently not possible to configure with the CLI. It should be a straightforward contribution if you are up for the challenge:

- Add new flag
- Consume flag in the handler
- Unit test

**Comment by vinckr** [comment]
@tacurran 
Is this issue still relevant?

**Comment by aeneasr** [comment]
Yes

**Comment by mbonnell-wish** [comment]
Just discovered this issue on our side :) will be working on this today.
