### ISSUE TITLE
cmd: Difficult to understand Swagger Errors

### ISSUE THREAD

**Issue by lakshman1977** [ory/hydra#1492]
Hi I am using steps mentioned in https://www.ory.sh/docs/hydra/5min-tutorial
when i run below command
docker-compose -f quickstart.yml exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445/ \
    --id my-client \
    --secret secret \
    -g client_credentials

I am getting error as below
Config file not found because "Config File ".hydra" Not Found in "[/]""

kindly help to create client.

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
This is a cross-post from here: https://community.ory.sh/t/creates-a-new-oauth-2-0-client-ubunthu/1231

You are seeing a 409 error (conflict) which means that the client exists already:

```
Unable to execute request: [POST /clients][409] createOAuth2ClientConflict &{Code:0 Debug: Hint: Name:0xc000574010}
```

We should probably improve the error messages here.

**Comment by lakshman1977** [comment]
Hi ,
  I am getting error something like lakshman@laksh:~/hydra$ docker-compose -f quickstart.yml exec hydra     hydra clients create     --endpoint http://127.0.0.1:4445/     --id my-client     --secret secret     -g client_credentials
Config file not found because "Config File ".hydra" Not Found in "[/]""
**You should not provide secrets using command line flags, the secret might leak to bash history and similar systems**
OAuth 2.0 Client ID: my-client
I dont see "OAuth2 client secret: secret" in the output

when i open 127.0.0.0 :4445
**"{"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}"**
kindly advise.

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
Please follow the guide at https://www.ory.sh/docs/hydra/5min-tutorial step-by-step. You can reset using `docker rm -f $(docker ps -aq)`. For more information please read the docs: https://www.ory.sh/docs/

You can not simply access `http://127.0.0.1:4445` in your browser, you will only find REST APIs there.

**Comment by lakshman1977** [comment]
Hi Aeneasr,
  Its very disappointing, still not getting the answer for the question asked. Yes, I went through 
"Please follow the guide at https://www.ory.sh/docs/hydra/5min-tutorial step-by-step. You can reset using docker rm -f $(docker ps -aq). For more information please read the docs: https://www.ory.sh/docs/"
its of no use, because when you use the docker to run its throwing an error 
"Config file not found because "Config File ".hydra" Not Found in "[/]""
**You should not provide secrets using command line flags, the secret might leak to bash history and similar systems**
OAuth 2.0 Client ID: my-client
I dont see "OAuth2 client secret: secret" in the output"

Yes i agree its a cross post , do you see anyone reply to the post ??? no one..
i am just keep trying for past 3 days still no one really trying to help.

I believe you are more interested in closing the ticket rather than solving the problem..
very disappointing.

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
> "Config file not found because "Config File ".hydra" Not Found in "[/]""

You can ignore this line.

> I dont see "OAuth2 client secret: secret" in the output"

The documentation is not up to date there, our CLI no longer echoes the OAuth2 Secret when you explicitly provide it with `--secret`.

I'm not sure what else I can help you with here.

**Comment by lakshman1977** [comment]
Hi Aeneasr, 
  Thank you for replying.Yes the document is not upto date. I ignored all the warnings. Its working fine.
In our company we are planning to use ory hydra.Thank you so much.

warm regards
Lakshman

**Comment by acodercat** [comment]
me too
