### ISSUE TITLE
Can't connect Azure Postgres as username contains '@' character

### ISSUE THREAD

**Issue by leonfancy** [ory/hydra#1494]
**Describe the bug**

When create Postgres in Azure, you provide the instance name and a username, in my case, the username is `leon` and instance name is `perfpost`. However, when I want connect to the DB, I must set the connect username as `leon@perfpost`. Hydra doesn't handle well with special character in username, so Hydra can't connect to it.

![image](https://user-images.githubusercontent.com/4530475/61506989-90fccd80-aa16-11e9-87dd-0f07536dc4da.png)

![image](https://user-images.githubusercontent.com/4530475/61507155-34e67900-aa17-11e9-9ca3-240330d52dbd.png)

**Environment**

* Version: v1.0.0

**Comment by aeneasr** [comment]
Could you try urlencoding the username?

**Comment by leonfancy** [comment]
It's not working.

**Comment by aeneasr** [comment]
Ok so you tried `DSN=postgres://leon%40perfpost:yourpassword@host:port/db` right?

**Comment by leonfancy** [comment]
Yes, it doesn't help.

**Comment by aeneasr** [comment]
Ok, will investigate. We had the same issue with Azure MySQL. I really don't understand why they are using '@' in the username for DSN connection strings...

**Comment by aeneasr** [comment]
I believe this should be fixed now?
