### ISSUE TITLE
Desired documentation points to not found page

### ISSUE THREAD

**Issue by avkonst** [ory/hydra#1498]
**Describe the bug**

It is documentation bug report.

I have asked a question here: https://community.ory.sh/t/what-api-to-use-to-exchange-the-code-and-get-the-access-refresh-and-id-tokens/1235 which has not received any answer. Later I learnt that the answer should be hidden in the documentation for /oauth/token api. The documentation has got a link to this API here: https://www.ory.sh/docs/hydra/sdk/api#authentication but when I click it, the page could not be found. It would be great to receive the answer to my question and to get the API documented.

**Comment by aeneasr** [comment]
These endpoints are not properly documented here as we usually [expect people](https://www.ory.sh/docs/hydra/sdk/api#the-oauth-20-authorize-endpoint) to use [one of the many OAuth2 Libraries](https://oauth.net/code/) out there instead of trying to implement this on their own.

**Comment by avkonst** [comment]
I disagree that it is closed.

First of all, we need to know what is really going on with or without
library. Our security department needs all of this for review. Next, in
case the lib gets unsupported or when we need to replace it. We can not
risk to use some dependency, if we do not know what it does.

Secondly, there are 3 libs stated for JavaScript. All three execute
implicit core flow for spa. Not the thing we want to use, because our spa
has got API server which can exchange the code using client secret. What
library should I use for this scenario?

And finally, I am evaluating various implementation alternatives. One
alternative is using hydra and other related tools. You rejecting to answer
makes me now concerned if we should continue this path with hydra. Now
looks risky that we may not get the basic answer when we need in the future.

**Comment by aeneasr** [comment]
If you want to learn more about OAuth2, head over to the docs: https://www.ory.sh/docs/hydra/#introduction-to-oauth-20-and-openid-connect

There are also plenty of documents, blog posts, and others around the internet that explain the protocols very thoroughly. We only handle according to spec so whatever you find there will work here.

> And finally, I am evaluating various implementation alternatives. One
alternative is using hydra and other related tools. You rejecting to answer
makes me now concerned if we should continue this path with hydra. Now
looks risky that we may not get the basic answer when we need in the future.

As you've probably noticed, this is an open source project. Open source maintainership is done with limited resources during spare time. **You are not entitled to free support**, and in all honesty - you're asking the community to explain to you how OAuth2 works. That's not the task of the community nor the maintainers but your own, as you are using a self-service, open source, tool. If you want someone to explain every detail without your own research, hire a consultant.

You are free to choose whatever tool you want. If you're unhappy with the contribution guidelines or the way this is handled here there are no hard feelings if you do not use this tech stack. But rest assured, free consulting - especially if all of this documented even with videos, is not something we consider to be part of our open source work.

**Comment by avkonst** [comment]
That is all fine. No worries. It looks like you comfortable with having
broken link in the documentation website. Sure I can not change that, it is
open source.
