### ISSUE TITLE
Invalid request error following the tutorial

### ISSUE THREAD

**Issue by fyang1024** [ory/hydra#1515]
**Describe the bug**

When I follow either https://www.ory.sh/docs/hydra/5min-tutorial or https://www.ory.sh/docs/hydra/configure-deploy, I cannot see the access token described at the end of the tutorials, instead I see `invalid request` error, with ```Hint: "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.```

**Reproducing the bug**

Follow https://www.ory.sh/docs/hydra/5min-tutorial
or https://www.ory.sh/docs/hydra/configure-deploy step by step

**Expected behavior**

Access token should be shown as described in the tutorials

**Environment**

Ubuntu 18.04 / Docker 18.06.1-ce

**Comment by aeneasr** [comment]
I saw your question on the chat. Make sure to not mix up 127.0.0.1 and localhost.
