### ISSUE TITLE
ory hydra login and consent page demo(Golang)

### ISSUE THREAD

**Issue by lakshman1977** [ory/hydra#1516]
Hi,
 I see the demo is in node.js. do we have login and consent page demo in Golang ?
Really appreciate your support.

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
No, but it’s easily reproducible.

**Comment by lakshman1977** [comment]
Hi aeneasr,
  if you have something written in Golang. please share.

Thanks and Regards
Lakshman

**Comment by aeneasr** [comment]
I do not have something written in golang

**Comment by tacurran** [comment]
@lakshman1977 : "Create an example demo app in Go for Ory Hydra." Can I assign you this issue?

**Comment by lakshman1977** [comment]
Hi aeneasr,
 Thanks.
Hi tacurran,
 I am really not sure to use the SDK for . do you have anything similar to node.js example ?
example demo app in Go for Ory Hydra.?

**Comment by lakshman1977** [comment]
Hi aeneasr & tacurran,
 I tried using ory hydra.. but its unable to connect to server. please find the attached code.
I removed the vendor folder due to size.

Kindly help.

Thanks and Regards
Lakshman
[loginRegister (copy).tar.gz](https://github.com/ory/hydra/files/3475025/loginRegister.copy.tar.gz)

**Comment by lakshman1977** [comment]
Hi @aeneasr  and @tacurran ,
  please find the above code. kindly guide .
Snap shot of the code
if challenge != "" {
		if !helpers.IsEmpty(name) && !helpers.IsEmpty(pass) {
			// Database check for user data!
			// _userIsValid := repos.UserIsValid(name, pass)

			// if _userIsValid {
			// 	SetCookie(name, response)
			// 	redirectTarget = "/index"
			// } else {
			// 	redirectTarget = "/register"
			// }

			ll.Info("Init Hydra SDK")
			var err error
			hydraSDK, err := hydra.NewSDK(&hydra.Configuration{
				AdminURL: "http://localhost:4445",
			})
			if err != nil {
				ll.Fatal("Unable to connect to Hydra", l.Error(err))
			}

			loginRequest, resp, err := hydraSDK.GetLoginRequest(challenge)

			if err != nil {
				ll.Fatal("Unable to connect to Hydra Login", l.Error(err))
			}
			if err != nil {
				ll.Error("Could not connect to Hydra", l.Error(err))
			} else if !isSuccessStatus(resp.StatusCode) {
				ll.Error("Invalid request to Hydra")
			}

			if loginRequest.Skip {
				//redirectTo, err := hydraSDK. //HydraAcceptLogin(challenge, loginRequest.Subject)
				accept, resp, err := hydraSDK.AcceptLoginRequest(challenge, swagger.AcceptLoginRequest{
					Subject:  loginRequest.Subject,
					Remember: false,
				})

				if err != nil {
					ll.Error("Could not connect to Hydra", l.Error(err))
				} else if !isSuccessStatus(resp.StatusCode) {
					ll.Error("Invalid request to Hydra")
				}
				//return e.Redirect(http.StatusTemporaryRedirect, redirectTo)
				http.Redirect(response, request, accept.RedirectTo, http.StatusTemporaryRedirect)

			}

			// accept, response, err := hydra.SDK.GetLoginRequest(challenge)
			//loginRequest, response, err := hydra.SDK.GetLoginRequest(challenge)
			// hydra.SDK.AcceptLoginRequest(challenge, swagger.AcceptLoginRequest{
			// 	Subject:  subject,
			// 	Remember: false,
			// })

			// if err != nil {
			// 	ll.Error("Could not connect to Hydra", l.Error(err))
			// 	return "", err
			// } else if !isSuccessStatus(response.StatusCode) {
			// 	ll.Error("Invalid request to Hydra")
			// 	return "", err
			// }
		}
		//http.Redirect(response, request, redirectTarget, 302)
	}

The error is : unable to connect to Hydra Login

**Comment by lakshman1977** [comment]
Guys please support @aeneasr & @tacurran

**Comment by ArnoSen** [comment]
I created a demo login/consent page implementation in GO here: https://github.com/ArnoSen/hydraloginconsentprovider

It is very rough and does not (yet) support some features like logout and support for the `skip` flag.

**Comment by aeneasr** [comment]
Thank you @ArnoSen - feel free to PR the docs if you want to share it with the community :) I'm closing this now
