### ISSUE TITLE
token introspection docs mentions authentication

### ISSUE THREAD

**Issue by RazerM** [ory/hydra#1520]
Just a documentation bug I noticed.

https://www.ory.sh/docs/next/hydra/sdk/api#introspect-oauth2-tokens contains the following text:

"To perform this operation, you must be authenticated by means of one of the following methods: basic, oauth2"

This endpoint is available on the admin port and doesn't require any authentication.

**Comment by rwenz3l** [comment]
I created a PR on the ory/docs Repository: https://github.com/ory/docs/pull/208
