### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [ory/hydra#1530]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [fuzzitdev/example-go](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [google/syzkaller](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by aeneasr** [comment]
Where would you apply fuzzing in particular here?

**Comment by yevgenypats** [comment]
@aeneasr I'm not too familiar with the code-base yet. But I'll go to places where some mission-critical parsing/validation is done. 

maybe [validator.go](https://github.com/ory/hydra/blob/bbeee653de32aa8d6eb172b836257b7bfa4c5df3/client/validator.go), just on top of my head.

Would love to hear your feedback as well as you are more familiar with the codebase.

**Comment by aeneasr** [comment]
In that case I don't think this repo is a right fit for your product as we're not doing raw input parsing or any other type of parsing that would benefit from fuzzing.
