### ISSUE TITLE
Add development docker image

### ISSUE THREAD

**Issue by aaahrens** [ory/hydra#1558]
**Is your feature request related to a problem? Please describe.**

Right now the only image is multi staged into scratch, which means that it is unusable from a CI perspective, because both drone and gitlab use /bin/sh to run processes and grep outputs.

**Describe the solution you'd like**

Add a development docker image tag. ory/hydra-alpine:v1.0. Or something similar. /shrug

**Describe alternatives you've considered**

Right now we have to build our custom images that replicate on hydra's dockerhub. This just removed a step and guarentees that the images are mirrored right.

**Comment by aeneasr** [comment]
Ok, those are valid reasons and we'll add a `vX.Y.Z-alpine` image for these use cases to Docker Hub
