### ISSUE TITLE
Previous consent consistency

### ISSUE THREAD

**Issue by jtescher** [ory/hydra#1559]
**Describe the bug**

`FindGrantedAndRememberedConsentRequests` currently has a limit 1 clause, so consent helper's `matchScopes` loops through what ends up always being an array of only the latest remembered and granted consent. 

This means previously granted and remembered scopes will not always be correctly approved.

Additionally the query executed in `FindGrantedAndRememberedConsentRequests` cannot take advantage of an index, so performance becomes poor as the number of consent requests and handled consent requests grow.

**Reproducing the bug**

1. Accept and remember two scopes.
2. Accept and remember only one of the two scopes.
3. Now request the first two scopes again and even through you remembered the consent the first time, it will not be remembered.

**Expected behavior**

The third request should expect to see the consent from the first request.

**Comment by aeneasr** [comment]
The limit 1 clause is actually intended behavior. We want to see the "remember" only the most recent user interaction, not the previous ones. A user might reconsider and revoke certain permissions. Keeping them around would cause a security incident.

Fixing the index is definitely something that should be done. Could you go into a bit more detail what index is missing or even throw up a PR? :)

**Comment by jtescher** [comment]
The performance is more complex than I originally anticipated, I will do a PR once I have improvements.
