### ISSUE TITLE
Add support of openid-connect-federation?

### ISSUE THREAD

**Issue by rocketk** [ory/hydra#1560]
Would hydra support [openid-connect-federation](https://openid.net/specs/openid-connect-federation-1_0.html) protocol in the future? Is there such plan?

**Comment by aeneasr** [comment]
We are generally open towards this standard. However, we are currently in feature freeze mode for hydra as we're working on other projects so there is no plan to implement this in the short or midterm future. We do however accept contributions for this.

Please be aware that this can be a significant amount of work so please discuss your ideas for implementing it with us beforehand. Another option is to become a sponsor which allows us to allocate more resources towards requests like this.

**Comment by rocketk** [comment]
Thank you!
