### ISSUE TITLE
hope support password grant

### ISSUE THREAD

**Issue by acodercat** [ory/hydra#1561]
hope support password grant

**Comment by aeneasr** [comment]
https://www.ory.sh/docs/hydra/limitations#resource-owner-password-credentials-grant-type-rocp

**Comment by acodercat** [comment]
I am my own app, not a third-party app.

**Comment by bbsclient** [comment]
I too would like to use Hydra in my closed ecosystem with a client that must use native UI without support for a browser.  So I need an authentication system that supports the password grant.

**Comment by k90s** [comment]
Hey guys, I forked and twisted it a little bit to add password grant support, feel free to check it out.

https://github.com/gdpass/hydra
