### ISSUE TITLE
No way to handle 409 GetLoginRequestConflict.

### ISSUE THREAD

**Issue by hypnoglow** [ory/hydra#1569]
**Describe the bug**

Sometimes we experience `409 GetLoginRequestConflict` errors when calling Admin API **GetLoginRequest**. Logically, there is no error, as *used* login request cannot be used anymore. But the problem is that there is no way to handle it from the Identity Provider point of view:

1) Identity Provider gets request e.g. `/login?login_challenge=abc123` from the user.
2) Identity Provider gets response with 409 error with no helpful details from Hydra Admin API.
3) Identity Provider does not know anything about OAuth Client, he can get this info only doing `GetLoginRequest` to Admin API.
4) Identity Provider cannot redirect the user back to the beginning of the login process (OAuth Client), so the user can either re-authenticate or continue using the Resource Provider is authenticated.
5) Identity Provider can only fail the user request, showing typical "Something went wrong, go back where you started" or something.

Note that while we should not get this error in "normal" flow, our users still getting them occasionally, maybe due to "double-click" phenomena or other client-side issues, which we cannot always control.

**Reproducing the bug**

This can be trivially reproduced by doing typical login/consent flow, and then trying to call **GetLoginRequest** again with the same login challenge.

*Server logs*

```
"error":"[GET /oauth2/auth/requests/login][409] getLoginRequestConflict &{Code:0 Debug:Login request has been used already Hint: Name:0xc00066e9f0}"
```

**Expected behavior**

One solution can be returning 200 response from Hydra even if the login challenge is used. The response can contain `WasUsed` field to indicate that this login challenge is not available for accepting, but at least we can extract client info and redirect the user back to restart the login process.

*Note: I think that returning 200 response instead of 409 will be a breaking change.*

Or, somehow include client info in the error response.

Or, maybe, the `redirect` field should be included into all 4xx responses so Identity Provider can at least redirect the user back to restart the login process on any similar errors.

**Additional context**

Code reference: https://github.com/ory/hydra/blob/master/consent/handler.go#L266

Am I missing something? If so, please point me how to handle this problem.

Or, if this should be fixed, please let me know if any help wanted, so I can provide a PR.

**Comment by hypnoglow** [comment]
Also I thought about another solution: maybe we can provide additional query parameters when redirecting to the Identity Provider [here](https://github.com/ory/hydra/blob/master/consent/strategy_default.go#L280), e.g. OAuth Client "callback" redirect URL. This way Identity Provider can use this URL to redirect the user if any error occurs. What do you think?

**Comment by aeneasr** [comment]
Yeah, we definitely should have a way to mitigate this error. Either returning a 409 with the initial called URL or a 200 seem like a suitable solution both! I would prefer 409 with more context, because this is definitely an error state that should not further be propagated

**Comment by aeneasr** [comment]
Would oyu be up for a PR?

**Comment by moeryomenko** [comment]
We have same problems into our project.

**Comment by 7fELF** [comment]
I have a similar problem when I call AcceptLoginRequest twice I get a 409. I would expect the [same behavior as AcceptConsentRequest](https://github.com/ory/hydra/issues/1256) so my client can call a second time if there is a network error.

**Comment by hypnoglow** [comment]
Let's agree on how this issue should be solved, and I will try to provide a PR for this.

> I would prefer 409 with more context, because this is definitely an error state that should not further be propagated

@aeneasr I thought on this, but I'm not sure that putting "actionable data" like URLs into errors (409 in this case) is a good idea. I would prefer a "cleaner" way to handle this, like passing additional details beforehand as I suggested in https://github.com/ory/hydra/issues/1569#issuecomment-533473641 But I'm not profound in this project, maybe there are even better ways.

> I would expect the same behavior as AcceptConsentRequest so my client can call my endpoint

It would be much better if this can be handled transparently like AcceptConsentRequest. I'm not sure this approach is suitable for GetLoginRequest though. @aeneasr can you give a comment on this?

**Comment by aeneasr** [comment]
> It would be much better if this can be handled transparently like AcceptConsentRequest. I'm not sure this approach is suitable for GetLoginRequest though. @aeneasr can you give a comment on this?

I agree that acceptConsent and acceptLogin should be consistent in behavior!

**Comment by hypnoglow** [comment]
> I agree that acceptConsent and acceptLogin should be consistent in behavior!

But this issue is about GetLogin, and it is currently consistent with GetConsent which also throws 409 for "used" consents. So basically in both methods we can't do anything meaningful for the user that somehow triggers this behavior.

**Comment by aeneasr** [comment]
Oh my bad - and I'm really sorry for the super slow replies on this issues but the workload these days is very intense.

I think we could probably return a 409 error with the login/consent payload as part of the error response?

**Comment by hypnoglow** [comment]
@aeneasr How would you suggest adding structured payload to the error response? Currently, I see no easy way to add custom structured data to the error, i.e. for this code: https://github.com/ory/hydra/blob/master/consent/handler.go#L266

**Comment by mariovazquezio** [comment]
Hey there, I'm currently facing the same problem just for one user stuck at WasHandled flag with 409 error (out of a few thousand). I can see this is still on the to-do list. Anyways, I was wondering if any of you guys know of a --hopefully easy workaround on this.
@aeneasr @hypnoglow

**Comment by aeneasr** [comment]
Yes, you can redirect the user to the `request_url` which you find in the login request :)

**Comment by jonkjenn** [comment]
@aeneasr This wouldn't directly give us the URI we need to complete though right?

**Comment by dselyuzhitskiy** [comment]
We have sometimes same problem but i have np idea how to reproduce such situation

**Comment by aeneasr** [comment]
I don't understand what you are asking @jonkjenn - it gives you the full initial request url. Check the payload ;)

**Comment by jonkjenn** [comment]
@aeneasr 
`PUT oauth2/auth/requests/login/accept?login_challenge=12387zb3281` returns ` "redirect_to": TARGET_URI` and 
 `TARGET_URI` contains `login_verifier`.
All attempts to retry this `PUT` gives `409` so when the request fails, and we don't receive `TARGET_URI`, it seems impossible to get the `login_verifier` which is required to continue the login. Am I missing something?

**Comment by aeneasr** [comment]
You can't complete something that is expired. I already said what you need to do: https://github.com/ory/hydra/issues/1569#issuecomment-739573442 - it reinitializes the flow without a timeout.

**Comment by hypnoglow** [comment]
> Yes, you can redirect the user to the `request_url` which you find in the login request :)

We are doing kind of similar thing to workaround the issue currently. In particular:

1. After user gets redirected to our Identity Provider with login challenge, we cache some details of the login request including `redirect_uri`. We need to cache it because login process can consist of multiple steps.
2. If there is a conflict when we try to accept login request, we retrieve these details from cache and redirect user to `redirect_uri` of this login challenge.
3. User gets back to the client which checks if the login flow was successful or we need to execute it once again.

This looks tedious and involves a decent amount of additional code and a cache. I wonder if something can be done to ease handling of this issue.

As an option that would eliminate the need of cache and other stuff, I still think that Hydra API method `Get Login Request` should not return 409 error when the login request was already accepted/rejected. Instead, it should return 200 with full login request information and additional details, like fields indicating that the request was already accepted. This way we can fetch login request details in all cases and get that `redirect_uri` when we need it. And API method `Accept Login Request` can keep returning 409.

**Comment by snikch** [comment]
Just adding my voice here as another user who is affected. The use case we are seeing is

* User lands on login page 
* User submits the form twice in quick succession
* First request accepts the login
* Second request attempts to accept the login, receives an error.

In the context of this second request, we ideally would like to know where to send the user to continue on with the flow.

One thing we *can* do at this point is redirect back to the initial request URL which will generate a new login flow, however this isn't a great experience for the user as they would then be back on the page they started with.

Note: I realise this can be solved via the browser, i.e. debouncing the login form so it doesn't send twice, but other use cases exist which are outside of control, such as a failed network request etc. that leads the user to reload the page.

**Comment by lpedrosa** [comment]
Just to confirm, is this fix in `v1.10.2`? It's still marked as 1.11 in the milestone.

**Comment by aeneasr** [comment]
It's referenced and closed so yes :)

**Comment by mig5** [comment]
This works for Login requests that have already been used, but Consent requests that have already been used still throw a 409 and there is no redirect_uri in the error's `getResponseBody()`.

Simple way to test is to proceed through the auth screen til you get to the Consent page. Then open that same Consent page in another tab (it has same challenge).

Submit the first Consent page, which works, then try submitting it in the other tab. I get a 409 Conflict, not a 410 Gone like I do with Login challenge in the same scenario, and there's no redirect_to so I can't gracefully help the user out of it.
