### ISSUE TITLE
No existing login session was found

### ISSUE THREAD

**Issue by RemiKalbe** [ory/hydra#1573]
Hydra returns to the client ( a browser ) `The+Authorization+Server+requires+End-User+authentication`, when the user is in fact authenticated.

I have a web app that is a public client, it uses the code + pkce flow.
When the user open the page, the app try to get an access token using an iframe, with the https://github.com/IdentityModel/oidc-client-js library.
But the iframe gets back  `The+Authorization+Server+requires+End-User+authentication`.
When an error like that occurs my app redirects the user to the login provider to authenticate, the authentification works when looking at the logs and the user is redirected back to the app, but as I said, my app tries to get an access token using an iframe but it get back the error stated earlier, and the cycle continues indefinitely.

**This error only occurs on the Brave browser in incognito mode.**

*Server logs*

```
hydra_1          | time="2019-09-21T16:48:07Z" level=error msg="An error occurred" debug="Prompt \"none\" was requested, but no existing login session was found" description="The Authorization Server requires End-User authentication" error=login_required
```
**Environment**

* Version: v1.0.0 (2019-06-24)
* Environment: Docker compose

**Comment by aeneasr** [comment]
> This error only occurs on the Brave browser in incognito mode.

Brave behaves very weird when it comes to cookies, iframes, and especially cross domain. Nothing we can do on our side to fix that!

**Comment by aeneasr** [comment]
Also make sure to set "remember" to true with a remember_for value sufficiently high for both login and consent.

**Comment by RemiKalbe** [comment]
I'm gonna open an issue on brave then.

**Comment by RemiKalbe** [comment]
> > This error only occurs on the Brave browser in incognito mode.
> 
> Brave behaves very weird when it comes to cookies, iframes, and especially cross domain. Nothing we can do on our side to fix that!

Yeah, It was working yesterday, I haven't changed anything and now it's broken

**Comment by RemiKalbe** [comment]
> Also make sure to set "remember" to true with a remember_for value sufficiently high for both login and consent.

It is set to true with a value of 604800
