### ISSUE TITLE
login_challenge parameter not always put at the end of the login url

### ISSUE THREAD

**Issue by rspenkelink** [ory/hydra#1583]
We have setup hydra, all is working. Here is a fragment of our script: 

docker run -d \
  --name ory-hydra \
  --network hydra-network \
  -p $HYDRA_PORT:$HYDRA_DOCKER_PORT \
  -p $HYDRA_ADMIN_PORT:$HYDRA_DOCKER_ADMIN_PORT \
  -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
  -e DSN=$DSN \
  -e URLS_SELF_ISSUER=https://localhost:$HYDRA_PORT/ \
  -e URLS_CONSENT=http://localhost:$CONSENT_LOGIN_PORT/consent \
  ****-e URLS_LOGIN=http://localhost:8001/dist/#/login \****
  oryd/hydra:v1.0 serve all

The issue we have is the thing that is bolded, namely the login url. Our login page is an angularjs app that does not use HTML 5 mode, but as you see in the url uses hashtags ('#').

After sending a code request to our demo client hydra redirects us to:
- http://localhost:8001/dist/?login_challenge={id}#/login

As you see it puts login_challenge in front of the '#'. To be able to work in our system, we need it to be put behind /login:
- http://localhost:8001/dist/#/login?login_challenge={id}

Is there an option we can set to make this work?

**Comment by aeneasr** [comment]
I'm not sure how your app works, but the login and consent app is expected to be something that runs on a secured / hardened server (at least the part sending the REST requests). Hydra's Admin APIs are not to be exposed to the public. If it's just a UI layer that sends the login challenge and username + password to some API running on a server, that would be ok.

I don't think that there's currently a way to forward to hashbang URLs for these endpoints as we're parsing the URL as is and adding the challenge to the query, which requires an additional parsing of the hashbang.
