### ISSUE TITLE
Add ext properties on OAuth clients

### ISSUE THREAD

**Issue by pike1212** [ory/hydra#1594]
**Is your feature request related to a problem? Please describe.**

We are migrating from another OAuth implementation and there are not suitable fields for some of the values in hydra. For example, extra metadata about the client that is specific to our environment.

**Describe the solution you'd like**

An ext property added to OAuth client similar to the token endpoint
```
"ext": {
    "property1": {},
    "property2": {}
  }
```
I am willing to work on a PR for this feature

**Describe alternatives you've considered**

Overriding the use of another field

**Comment by aeneasr** [comment]
As long as it's clear that this field is not searchable/indexable I'm totally fine with having that. For naming we have:

* `ext`
* `extra`
* `meta`
* `metadata`
* `custom`

(open for alternate suggestions)

**Comment by pike1212** [comment]
I don't see any need to search/index by the fields. I'm going to use `metadata`. Working on the PR, I get an error when I run `make sdk` even against master. Looks like it is making updates to the swagger docs as well

```
$(go env GOPATH)/bin/swagger generate spec -m -o ./docs/api.swagger.json -x sdk
$(go env GOPATH)/bin/swagger validate ./docs/api.swagger.json
panic: Invalid schema provided to SchemaValidator: object has no key "default"

goroutine 1 [running]:
github.com/go-openapi/validate.NewSchemaValidator(0xab2de60, 0x87bdb40, 0xab2de60, 0x0, 0x0, 0x894ce20, 0xac9e3a0, 0x0, 0x0, 0x0, ...)
	/home/clp207/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/schema.go:72 +0xd5e
github.com/go-openapi/validate.(*SpecValidator).Validate(0xa9ec9c0, 0x879a7c0, 0xacd5320, 0xaf0f2c0, 0xaf0f320)
	/home/clp207/go/pkg/mod/github.com/go-openapi/validate@v0.19.2/spec.go:92 +0x1d8
github.com/go-swagger/go-swagger/cmd/swagger/commands.(*ValidateSpec).Execute(0xa81c614, 0xacdc4f0, 0x1, 0x2, 0xa81c614, 0x1)
	/home/clp207/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.0/cmd/swagger/commands/validate.go:60 +0xf8
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xacf8360, 0xa818148, 0x2, 0x3, 0x0, 0x8806edd, 0x2a, 0x86caec0, 0xa980fa0)
	/home/clp207/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x740
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/home/clp207/go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
	/home/clp207/go/pkg/mod/github.com/go-swagger/go-swagger@v0.20.0/cmd/swagger/swagger.go:145 +0xa5c
Makefile:90: recipe for target 'sdk' failed
make: *** [sdk] Error 2
```

**Comment by aeneasr** [comment]
Hm, hard to tell what's going on there. Maybe submit the PR without swagger and I'll look into it :)

**Comment by pike1212** [comment]
I'll dig a little more and submit without swagger if nothing comes up, what version of go-swagger should I be using?

**Comment by timkelley-ingage** [comment]
@aeneasr : I have attempted to do some testing on this feature in Hydra.  I am calling the REST API on POST /clients.  The feature doesn't seem to be implemented there.  Looking through this PR, it appears that it was only implemented for the Hydra SDK.  Shouldn't this be included from every method for creating a client?

**Comment by pike1212** [comment]
Maybe I'm misunderstanding what you are doing, but I've been using postman to successfully test creating clients with metadata.

**Comment by aeneasr** [comment]
That's because this hasn't been released yet, so unless you're building hydra on your own this feature is not shipped yet: https://github.com/ory/hydra/compare/v1.0.8...master

**Comment by timkelley-ingage** [comment]
I see, my apologies.  I was able to build locally and set the metadata. Thanks!
