### ISSUE TITLE
sqlData struct PK field should be an int64

### ISSUE THREAD

**Issue by pike1212** [ory/hydra#1595]
**Describe the bug**

The sqlData struct PK field is declared as an int, but is actually an int64 in Cockroach DB

**Reproducing the bug**

Run `make test` with a 32 bit version of Go

*Server logs*

```
sql: Scan error on column index 23, name "pk": converting driver.Value type int64 ("492838020877385729") to a int: value out of range
```

**Comment by aeneasr** [comment]
Oh yeah this should be a 64bit integere. Would you be up for a PR?
