### ISSUE TITLE
Consider creating .netrc or removing User [1000] from alpine image

### ISSUE THREAD

**Issue by aaahrens** [ory/hydra#1596]
**Is your feature request related to a problem? Please describe.**

Right now the alpine image wont work on CI providers who use .netrc for git credentials/environment variables, due to the base of the images users permissions level. 

**Describe the solution you'd like**

Either provide a development tag which runs as the root user and adds a big fat echo "DISCLAIMER" like in --serve-insecure, or just remove it altogether. 

I don't know the security implications of doing so however, but I would like to have a production container with /bin/sh for debugging. 

**Describe alternatives you've considered**

Run a custom public image.

**Additional context**

I run a bunch of on premise clusters and typically I don't pull from a custom registry,  only push to it. So typically I just make a public image, which just adds moving parts for upgrading and e2e testing.

edit: I just want to clarify, the image works for CI for most general tasks (what 95% of people use). This is only an edge case which might get to be an issue later on for other side effects that I don't know about.

**Comment by aeneasr** [comment]
Removing root from an image considered for production is not a good idea.

Regarding .netrc on CI, could you please elaborate?

**Comment by aaahrens** [comment]
So .netrc is used for self hosted and/or self signed git repositories. Sometime at very large companies there exist more than one git repository for either security or legacy reasons. This leads to multiple git authentication per deployment (not dockerized, old school scripting stuff)

this is how git ties into .netrc:
https://confluence.atlassian.com/fisheye/permanent-authentication-for-git-repositories-over-http-s-960155789.html

this is how drone does it:
https://discourse.drone.io/t/how-does-cloning-private-https-repos-work/2110

for example pulling private go modules in gitlab:
https://gitlab.com/gitlab-org/gitlab-foss/issues/45055 

(This is what I envision might be a future issue imo, with people pulling custom stuff and linking it to hydra in one container)

I hit this issue specifically pulling old C repositories out of a git repo for hardware deployments.

**Comment by aeneasr** [comment]
Just to understand, are you trying to pull these repos into the hydra container, or why do you need support for .netrc in it?
