### ISSUE TITLE
Need return login_challenge with body instead of in Location header and redirect.

### ISSUE THREAD

**Issue by human453453467** [ory/hydra#1604]
I have rest api login page. And i want login from my client mobile app without ui. So could my client mobile get login_challenge from Hydra server when http://hydra/oauth2/auth?client_id=...&... without redirect, in body for example? Because for mobile client redirect doesn't make sense. Or get login_challenge from Location header id only one possible solution?

**Comment by aeneasr** [comment]
You ware trying to solve an OAuth2 authorize flow without actually using an OAuth2 flow (opening a browser with the proper authorization URL) which defeats the purpose of OAuth2 all together. Therefore, this use case is not supported by Hydra. However, all generic http clients (e.g. in switft, php, go) are capable of returning the 302 Location header as well as e.g. Cookie Jars.

Please read:

- https://www.ory.sh/oauth2-for-mobile-app-spa-browser/
- https://www.oauth.com/oauth2-servers/mobile-and-native-apps/authorization/

**Comment by human453453467** [comment]
@aeneasr Understood, thanks for the clarifying!
