### ISSUE TITLE
Need to add "username" key inside access_token

### ISSUE THREAD

**Issue by mymtw** [ory/hydra#1610]
**Is your feature request related to a problem? Please describe.**
I'm using library django-oauth-toolkit it gets username from response of authorization server(hydra)
django-oauth-toolkit making request for introspecting access_token of resource owner, then it expecting "username" key and value in response. 

https://github.com/jazzband/django-oauth-toolkit/blob/master/oauth2_provider/oauth2_validators.py#L314

Hydra not responding with "username":
https://www.ory.sh/docs/hydra/sdk/api#introspect-oauth2-tokens

**Describe the solution you'd like**
I think here could be optional(not required) param `username`:
https://github.com/ory/hydra/blob/bbeee653de32aa8d6eb172b836257b7bfa4c5df3/consent/handler.go#L322

**A clear and concise description of what you want to happen.**
I want to get "username" when I do request like:
```
curl -X POST \
-H 'Accept: application/json' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'token=e4g4TpL826gZy8OPl8kjqplz1vJHsju-HInA2Hz4ktA.C6XoY_PLKJApMI7DZHR1FafsTgpgtuPitn7kMwxlHAM' \
http://localhost:4445/oauth2/introspect
```

**Comment by hisamura333** [comment]
I want to challenge this issue.
so I'm trying it.

**Comment by hisamura333** [comment]
@aeneasr 

I tried this issue.

So I have a question.

I have added `userdata` code. I referred your comment.
https://github.com/ory/hydra/issues/1610#issuecomment-548389671

But, failed to get username. In this method.
https://github.com/ory/hydra/blob/ee61dfff139572227b597b0239e3f208bb45cf56/oauth2/handler.go#L613

I tried to get `username` like this.

```
session.ConsentRequest.Username
```




`GetConsentRequest` method is called during the process of acquiring the session.
https://github.com/ory/hydra/blob/ee61dfff139572227b597b0239e3f208bb45cf56/consent/manager_sql.go#L229


In this method, retrieving values ​​from `hydra_oauth2_consent_request_handled` table and `hydra_oauth2_consent_request` table.
```
	err := m.DB.GetContext(ctx, &d, m.DB.Rebind("SELECT r.*, COALESCE(hr.was_used, false) as was_handled FROM hydra_oauth2_consent_request r "+
		"LEFT JOIN hydra_oauth2_consent_request_handled hr ON r.challenge = hr.challenge WHERE r.challenge=?"), challenge)
```

But,I think this table(hydra_oauth2_consent_request_handled) does not have `userdata` column.

so , I think this table need `username` column.
Is my perception correct?

**Comment by aeneasr** [comment]
Yes! That is correct

**Comment by hisamura333** [comment]
Thank you!
I will try again.

**Comment by hisamura333** [comment]
@aeneasr
Let me ask you a question.

I tried to add column.
but I don't know how to change `consent/sql_migration_files.go` file.

I want you to tell me how to do it.

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
