### ISSUE TITLE
Examples of use with SPA

### ISSUE THREAD

**Issue by jayon34** [ory/hydra#1614]
**Is your feature request related to a problem? Please describe.**

I would like to request an example or material on using ORY Hydra with a SPA.

_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

I have been looking around for an idea of how to implement Hydra with a first party SPA. I have looked in the chat, forum and example repo with no luck.

As it's quite a popular solution to have a SPA for first party clients, e.g. Facebook have a SPA as an example.

**Describe the solution you'd like**

_A clear and concise description of what you want to happen._

Either an example provided, some information/material on the subject or a discussion around this topic.

**Describe alternatives you've considered**

_A clear and concise description of any alternative solutions or features you've considered._

I have been looking around for the last few days to find a solution on how a SPA can be used with Hydra specifically.

I understand that the Auth Code grant + PKCE should be used, however, I am unsure of the best practices surrounding this implementation.

Having looked at the node consent example, that makes complete sense how it would work. But, how would this translate over to a SPA that wanted the login form to be on that 'SPA'? Is that even possible?

**Additional context**

Some questions:

Should we have a separate login provider application like the node consent example, that the SPA redirects to?

Can we just make requests from the SPA? How would we handle redirects in this case?

Hydra is awesome. ORY is Awesome!

**Comment by aeneasr** [comment]
We do not have the resources to provide different examples for SPAs as implementation details vary between React, Angular 1/2/3/4/5 (or whatever version they are on now..), and so on. There are however many, many resources on building SPA integration with OAuth2 and/or OpenID Connect in the wild.

SPAs do not neccessarily require PKCE. Something like https://github.com/IdentityModel/oidc-client-js is a good start for client-side browser apps.

**Comment by jayon34** [comment]
Ok, to clarify, a SPA should not/can not have a login form. Instead, the login form should be part of a separate application, i.e. the login provider?

Also, to comment on this:

> We do not have the resources to provide different examples for SPAs as implementation details vary between React, Angular 1/2/3/4/5 (or whatever version they are on now..), and so on.

I think one example in react/angular/vue (a popular SPA) could go a long way! Looking at the node consent app, I could transfer that idea to a go app etc.

**Comment by aeneasr** [comment]
> Ok, to clarify, a SPA should not/can not have a login form. In

You need to interact with ORY Hydra's Admin API (especially login and consent) which must never be exposed to the public internet. So yes, the login and consent ui must have access to that and can thus not be served directly from the client.

What you can do is writing an API server capable of logging in via API and interacting with Hydra. Then your SPA would talk to that API.

> Looking at the node consent app, I could transfer that idea to a go app etc.

Absolutely, that would be great :)

**Comment by jayon34** [comment]
> What you can do is writing an API server capable of logging in via API and interacting with Hydra. Then your SPA would talk to that API.

Ok, so would a flow like this be suitable:

1. Click on login link (in SPA) - In the background, a login challenge is created and sent to the API so Hydra can remember it.
2. User enters details in a login form (on SPA) - these details + the login verifier are sent to the API. Here, the user is authenticated and Hydra is told about it.
3. Here we would also force consent because its a first party app.
4. Hydra deems that user is good and has given 'consent'
5. The API now gives the SPA back an access token, refresh token and openid token

Am I completely wrong and missing the point here?

**Comment by aeneasr** [comment]
Yeah, you're mixing up some concepts. Maybe read over the docs again. Keep login and consent and your actual OAuth2 App conceptually separate. You can merge them into one later if you've separated the concerns and boundaries in your architecture.

**Comment by Joshgallagher** [comment]
In terms of this @aeneasr, I can see that it's a little bit mixed up

> Ok, so would a flow like this be suitable:

Click on login link (in SPA) - In the background, a login challenge is created and sent to the API so Hydra can remember it.
User enters details in a login form (on SPA) - these details + the login verifier are sent to the API. Here, the user is authenticated and Hydra is told about it.
Here we would also force consent because its a first party app.
Hydra deems that user is good and has given 'consent'
The API now gives the SPA back an access token, refresh token and openid token
Am I completely wrong and missing the point here?

I am hoping to make this solution open source, so I'm just trying to nail it!

However, could you give us an idea of how a flow would work?

Given a SPA, how would you implement the API to allow a login form to exist on the SPA, rather than having a separate application for login?

**Comment by aeneasr** [comment]
> As I am just thinking this user flow for a first-party app is not very nice - in terms of redirects...

Why? The user doesn't notice. No regular user has devtools enabled with network inspection on.

**Comment by aeneasr** [comment]
> Given a SPA, how would you implement the API to allow a login form to exist on the SPA, rather than having a separate application for login?

I don't understand the question - just implement an API that has login/signup, implement the regular CSRF protection and you're done.

**Comment by Joshgallagher** [comment]
> Given a SPA, how would you implement the API to allow a login form to exist on the SPA, rather than having a separate application for login?

> I don't understand the question - just implement an API that has login/signup, implement the regular CSRF protection and you're done.

You said this above:

> You need to interact with ORY Hydra's Admin API (especially login and consent) which must never be exposed to the public internet. So yes, the login and consent ui must have access to that and can thus not be served directly from the client.

And this:

> What you can do is writing an API server capable of logging in via API and interacting with Hydra. Then your SPA would talk to that API.

It terms of the API you references, I understood this as being something that wrapped the whole process. For example, from the SPA you would create a `code verifier` and when making a login request, you would pass the credentials used to verify the user with the `code challenge`.

Your API would then handle the process of talking to Hydra, forcing consent (as it's first-party) and then return the tokens.

So, from what you have said above, that's what I thought you were getting at - wrapping the process in an endpoint that the SPA could request and tokens returned back to it.

However, from your reply, I am guessing I am completely wrong also.

To make this more clear, I understand how the flow works in the node example. However, I am unsure of how this would be translated to work with a SPA. The reason being that the node example handles everything securely on the server-side, e.g. talking to Hydra, redirecting and checking if the user is who they say they are.

I'm not sure if I am getting across where I am not understanding the difference in design with the node consent app vs a SPA implementation.

**Comment by jayon34** [comment]
@Joshgallagher this is where I am falling over. I'm clearly not understanding something or overcomplicating it.

**Comment by aeneasr** [comment]
> It terms of the API you references, I understood this as being something that wrapped the whole process. For example, from the SPA you would create a code verifier and when making a login request, you would pass the credentials used to verify the user with the code challenge.

You're still mixing up the OAuth2 Request and the actual Login and Consent part, please read over the documentation again. Those two things have **absolutely nothing to do with one another**.

> Your API would then handle the process of talking to Hydra, forcing consent (as it's first-party) and then return the tokens.

The API doesn't do any of that. Again, please re-read the docs, I think it will clarify things. You're mixing up first-party client with the login flow and so on. I'm sorry but this is currently the most I can help you with. I'm happy to help with pointed questions but I can not explain the whole flow here as that's the purpose of the docs. If those are unclear we can absolutely work on that but this knowledge should not be buried somewhere in a GitHub issue.

I would **very strongly** recommend starting with the node app first to understand how all of this works before jumping into your own implementation.

**Comment by Joshgallagher** [comment]
@aeneasr I'll have a further dig into the docs and test somethings out - I'm clearly getting something mixed up...

**Comment by aeneasr** [comment]
For clarification:

> The API doesn't do any of that.

Your login and consent server-side api would accept the username/password and consent input data and then talk to Hydra, which would return the URL to be redirected to (back to the OAuth2 Client that initiated the request).

"any of that" was certainly not correct, but it does not involve any PKCE code challenges or verifiers nor does it return tokens.

**Comment by Joshgallagher** [comment]
@aeneasr Thanks for the further clarification. I am going to go back through the docs and mess around with some SPA centric implementations. Then, I may have a clearer understanding so you're not trying to answer multiple, convoluted questions 🤦‍♂

**Comment by aeneasr** [comment]
No problem. My suggestion would be to use the available example login app, then create a simple SPA client using e.g. an oidc library and get that to work, and then start going down SPA for the login app.

**Comment by aeneasr** [comment]
Is it ok if I close this? I think we can also move this to community.ory.sh (better searchability/visibility) - I'll make sure to respond. In case I miss it (happens sometimes) ping me privately on discord

**Comment by Joshgallagher** [comment]
@aeneasr I'm good! I'll talk on the chatroom.

**Comment by jayon34** [comment]
ill use the chatroom for more questions. thanks @aeneasr
