### ISSUE TITLE
DELETE does not return 404 when a non-existing client id is used

### ISSUE THREAD

**Issue by alin-t** [ory/hydra#1625]
**Describe the bug**

According to the REST API documentation, the admin service should return 404 when trying to delete a non-existing client, but instead is returning 204.

https://www.ory.sh/docs/next/hydra/sdk/api#deletes-an-oauth-20-client

**Reproducing the bug**

1. clone the repo
`git clone https://github.com/ory/hydra.git`

2. run container
 ```
docker-compose -f quickstart.yml \
    -f quickstart-postgres.yml \
    up --build
```

3. delete a client
`curl -vvvv -X DELETE http://localhost:4445/clients/test`

**Expected behavior**

Should return:
```
{
  "debug": "The database adapter was unable to find the element",
  "error": "The requested resource could not be found",
  "error_description": "Object with ID test does not exist",
  "status_code": 404
}
```

**Environment**

* Version: ORY Hydra v1.0.8+oryOS.12
* Environment: Docker OSX

**Comment by alin-t** [comment]
curl -vvvv -X DELETE http://localhost:4445/clients/test
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4445 (#0)
> DELETE /clients/test HTTP/1.1
> Host: localhost:4445
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 204 No Content
< Date: Mon, 04 Nov 2019 12:37:04 GMT
<
* Connection #0 to host localhost left intact
* Closing connection 0

**Comment by alin-t** [comment]
Log entry:
hydra_1          | time="2019-11-04T12:37:04Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=773100 method=DELETE remote="172.18.0.1:59936" request=/clients/test status=204 text_status="No Content" took="773.1µs"

**Comment by aeneasr** [comment]
Are you using the in memory store or SQL?

**Comment by alin-t** [comment]
according to this flag: "-f quickstart-postgres.yml", it should use postgres, right?

**Comment by aeneasr** [comment]
Yeah, I missed that. Would the error message help you in any way in your application logic?

**Comment by alin-t** [comment]
Well, I noticed this when I tried to upgrade in our backend the hydra version. We have integration tests, and in previous versions 404 was returned. We can adapt our tests ofc, but I think it would be semantically  correct to have 404 for not found resources.

**Comment by aeneasr** [comment]
Makes sense - would you be up for a PR? I think you'd have to check for `RowsAffected == 0` to return a 404 somewhere around here:

https://github.com/ory/hydra/blob/master/client/manager_sql.go#L335

**Comment by alin-t** [comment]
Sure, I can look into this in the immediate future, as soon as I have some time for it.

**Comment by aeneasr** [comment]
Awesome!

**Comment by alin-t** [comment]
Sorry, things got kinda pilled up at work, so it may take a while still.

**Comment by aeneasr** [comment]
No problem! Happy to see you're keeping track of this :)

**Comment by aeneasr** [comment]
Another issue emerged - we're actually not supposed to send 404 errors when a client is not found, but instead 401 indicating that there's either a lack of authentication or that the client does not exist. This is to prevent enumeration attacks.

**Comment by alin-t** [comment]
I see. Hope I will find out some time soon, but ofc I won't mind if someone else could take care of it.

**Comment by aeneasr** [comment]
This is actually already implemented. Also, 204 on DELETE is quite common because your action succeeded (the client (no longer) exists) - regardless of whether it was there in the first place or not.
