### ISSUE TITLE
Add support for MongoDB 4.0 [NEW][NOT DUPLICATED]

### ISSUE THREAD

**Issue by juanjoseluisgarcia** [ory/hydra#1629]
MongoDB 4.0 now fully supports the ACID model yet being NoSQL. It supports transactions providing a snapshot to other users before the transaction and creating a new snapshot after the transaction has completed. 

Alongside with Go this database seems the right database in terms of performance. I would like the feature at least to be considered.

Many Thanks

**Comment by aeneasr** [comment]
ACID is not enough, we need a relational database with proper consistency across columns. Key/value and document stores are per definition not suited. On top, we do not have the resources to support and maintain a MongoDB adapter.
