### ISSUE TITLE
Handle 404 for GET /userinfo

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra#1630]
**Is your feature request related to a problem? Please describe.**

When the admin service returns a 404 from `GET /userinfo`, it's not handled by a `UserinfoNotFound` error

**Describe the solution you'd like**

Add a 404 handler to the spec

**Describe alternatives you've considered**

Just detecting a 404 on the open api runtime error instead

**Additional context**

I attempted to generate the sdk after altering the spec, but I am getting errors that I'll report in a separate issue

**Comment by aeneasr** [comment]
The admin server does not expose `/userinfo` - it's a routing error. Hence UserinfoNotFound is not a viable return option.
