### ISSUE TITLE
SDK Generation Fails

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra#1631]
**Describe the bug**

Generating the SDK fails

**Reproducing the bug**

Clone the repo, run `make init` and then `make sdk`

**Expected behavior**

Generation of the SDK with no errors

**Environment**

* Version: git master
* Environment: go 1.13, arch linux

**Additional context**

When generating it could not find the `swagger` binary, which I was able to install, though I am not sure it was the same version.

After that, I get an error finding `$GOBIN/listx` which I could not find anywhere. 

One solution to both of these issues is to version the tooling and installing a local copy to build with that are ignored by git, as I've done here for gRPC generation.

```makefile
PROTOC := protoc
PROTOC_GEN_GO := bin/protoc-gen-go

$(PROTOC_GEN_GO):
	GOBIN=$(PWD)/bin go install github.com/golang/protobuf/protoc-gen-go

compile: $(PROTOC_GEN_GO)
	PATH=$(PWD)/bin:$$PATH $(PROTOC) --go_out=plugins=grpc:$(PWD) -I $(PROTO_DIR) $(wildcard $(PROTO_DIR)/$*/*)        
```

You can also add an "empty" tools.go file to version tools that are not required by the source [as described here](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module)

This is related to #1630

**Comment by aeneasr** [comment]
Dependencies are fixed, we should probably add `go-swagger` and `listx` and any other dev deps to: https://github.com/ory/hydra/blob/master/Makefile#L138

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/blob/master/cmd/tools.go
