### ISSUE TITLE
Unable to request id_token 

### ISSUE THREAD

**Issue by barsaboowo** [ory/hydra#1633]
I am unable to use response type "token id_token" or just "id_token" when creating a client for user with openid. However, "token" is working fine.

Hydra version: 1.0.9 
Environment: docker using image tagged "latest"

Config:
- name: OIDC_SUBJECT_IDENTIFIERS_ENABLED
          value: public
        - name: OAUTH2_ACCESS_TOKEN_STRATEGY
          value: jwt
        - name: URLS_SELF_ISSUER
          value: https://xxxxx
        - name: URLS_CONSENT
          value: https://xxx/hydra/consent
        - name: URLS_LOGIN
          value: https://xxxx/hydra/login
        - name: DSN
          value: memory
        - name: SECRETS_SYSTEM
          value: xxxxx
        - name: OIDC_SUBJECT_TYPES_SUPPORTED
          value: public,pairwise
        - name: OIDC_SUBJECT_TYPE_PAIRWISE_SALT
          value: xxxxx

Client setup:
hydra.exe clients create --skip-tls-verify --endpoint https://xx.xx.xx.xx:ppppp --id "auth-endpoint" -r token,id_token -g implicit -a xxxx --callbacks https://www.getpostman.com/oauth2/callback -a openid,offline

Request:
https://xxxxx/oauth2/auth?client_id=auth-endpoint&redirect_uri=https://www.getpostman.com/oauth2/callback&response_type=token%20id_token&state=somethinglong1&scope=openid%20offline

Logs:
time="2019-11-11T06:41:08Z" level=info msg="completed handling request" measure#hydra/public: https://xxxxxx/.latency=51254220 method=GET remote="xxxxx" request="/oauth2/auth?client_id=auth-endpoint&consent_verifier=adcaa1b39454485fa2dda40d8d7f2ead&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=token&scope=openid+offline&state=somethinglong1" status=302 text_status=Found took=51.25422ms
time="2019-11-11T06:42:02Z" level=info msg="started handling request" method=GET remote="172.17.239.64:55187" request="/oauth2/auth?client_id=auth-endpoint&redirect_uri=https://www.getpostman.com/oauth2/callback&response_type=token%20id_token&state=somethinglong1&scope=openid%20offline"
time="2019-11-11T06:42:02Z" level=warning msg="Configuration key OAUTH2_ACCESS_TOKEN_STRATEGY is deprecated and will be removed in a future release. Use key strategies.access_token instead!"
time="2019-11-11T06:42:02Z" level=error msg="An error occurred" description="The authorization server does not support obtaining a token using this method" error=unsupported_response_type hint="The client is not allowed to request response_type \"token id_token\"."

**Comment by aeneasr** [comment]
https://www.ory.sh/docs/hydra/debugging#openid-connect-id-token-missing
