### ISSUE TITLE
Unexpected logout behavior

### ISSUE THREAD

**Issue by robotlovesyou** [ory/hydra#1634]
**Describe the bug**

The documentation on logout found here: https://www.ory.sh/docs/hydra/oauth2#logout suggests that the user agent will be redirected to the configured logout url **whether or not an id_token_hint is supplied as a parameter to /oauth2/sessions/logout.**

In fact, when no id_token_hint is suppled the user agent is redirected straight to the post logout url **AND** the oauth server cookies are not cleared, meaning the user is effectively not logged out.

**Reproducing the bug**

1. I have the following docker-compose configuration
```
hydra:
    image: oryd/hydra:v1.0.9
    links:
    - postgresd:postgresd
    depends_on:
    - hydra-migrate
    ports:
    - "4444:4444"
    - "4445:4445"
    command:
      serve all --dangerous-force-http
    environment:
    - URLS_SELF_ISSUER=http://127.0.0.1:4444
    - OAUTH2_CONSENT_URL=http://localhost:4000/consent
    - OAUTH2_LOGIN_URL=http://localhost:4000/login
    - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    - SECRETS_SYSTEM=youReallyNeedToChangeThis
    - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
    - URLS_LOGOUT=http://localhost:4000/logout
    - URLS_POST_LOGOUT_REDIRECT=http://localhost:4000/logout?post-logout=true
    restart: unless-stopped
```
2. Log in via the login provider (I cannot provide ours but it follows the provided guidelines)
3. In the same browser visit the url http://127.0.0.1:4444/oauth2/sessions/logout
4. The user agent is directed to the post-logout url

*Server configuration*
See above

**Expected behavior**

Either the user agent should still be sent to the logut page with a logout challenge, or if you are supporting the old behaviour, then the user agents cookies for the oauth server should be cleared. Neither of these things happen

**Environment**
Docker

* Version: v1.0.9
* Environment: Docker

**Comment by aeneasr** [comment]
Your was most likely already signed out when you did the request. If you check the logs, you will probably be able to confirm this. If no session is available, and no id_token_hint is provided, there is no need to do anything, hence you're being redirected to the post logout url.

**Comment by robotlovesyou** [comment]
No. That is not correct. The user *is* logged in when the request is made. I can take the same browser session and visit a protected resource and I am logged straight in because the oauth server returns skip=true

**Comment by aeneasr** [comment]
The code says (and it's tests) differently:

https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L731-L771


If you are certain that you are correct, please provide a reproducible test case.

**Comment by robotlovesyou** [comment]
We are experiencing this issue in development. We are running hydra live but not the current version. We are redeveloping our login provider to take account of changes in the newer versions of hydra. 

I have updated the docker compose configuration to remove the remaining warnings from the hydra logs. It is now
```
hydra:
    image: oryd/hydra:v1.0.9
    links:
    - postgresd:postgresd
    depends_on:
    - hydra-migrate
    ports:
    - "4444:4444"
    - "4445:4445"
    command:
      serve all --dangerous-force-http
    environment:
    - URLS_SELF_ISSUER=http://127.0.0.1:4444
    - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    - SECRETS_SYSTEM=youReallyNeedToChangeThis
    - OAUTH2_EXPOSE_INTERNAL_ERRORS=true
    - LOG_LEVEL=debug
    - URLS_CONSENT=http://localhost:4000/consent
    - URLS_LOGIN=http://localhost:4000/login
    - URLS_LOGOUT=http://localhost:4000/logout
    - URLS_POST_LOGOUT_REDIRECT=http://localhost:4000/logout?post-logout=true
    restart: unless-stopped
```

Whilst in development mode, our login provider has a protected resource path to simplify development. 

Additonally, I have modified the login provider to dump the response from the get login request to hydra out to the console, to show that it is returning skip=true

All the steps below are carried out in the same browser window. The browser window is a fresh private window.

1) I type http://localhost:4000/user/token into the navigation bar. As this is a protected resource this starts the access code grant flow and I am directed to our login page.
2) I log in.
3) I am shown the protected resource page at http://localhost:4000/user/token, because I am now logged in. 
4) I paste the url http://localhost:4444/oauth2/sessions/logout into the navigation bar. 
5) I am immediately directed to http://localhost:4000/logout?post-logout=true. This is not what I would expect given the documentation mentioned in my original post. The page I am taken to on our login provider clears its session. 
6) Once again I type http://localhost:4000/user/token. At this point I *expect* to be taken to the login page but I am not. Looking in the browser logs I can see that the browser _has_ gone through the access code grant again but it has not shown the login screen because hydra has told it to skip it.

The logs below are only those for step 6 above for the sake of brevity. I have included both the logs for our login provider AND the logs for hydra. 

As can be seen, the response from hydra includes the skip flag set to true. My understanding is that that would _only_ be returned if there were an existing session on the hydra server, but you stated above that the behaviour I am seeing with the logout url would only occur if the user has no session on the hydra server. 

Please let me know if you want to see more extensive server logs from either our login provider or hydra.

**LOGIN PROVIDER LOGS**
```
[info] GET /user/token
[debug] Processing with CanScoutWeb.ResourceController.token/2
  Parameters: %{}
  Pipelines: [:user]
[info] No token in session
[debug] got authorize url http://127.0.0.1:4444/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d
[info] Sent 302 in 320µs
[info] GET /login
[debug] Processing with CanScoutWeb.LoginController.new/2
  Parameters: %{"login_challenge" => "2d78f517f0b349aa81b143558f856e1b"}
  Pipelines: [:anonymous]
[debug] selecting locale from session
[debug] fall back to selecting locale from accept-language header
[debug] selected locale en
%{
  "challenge" => "2d78f517f0b349aa81b143558f856e1b",
  "client" => %{
    "allowed_cors_origins" => [],
    "audience" => [],
    "client_id" => "can_scout_client",
    "client_name" => "",
    "client_secret_expires_at" => 0,
    "client_uri" => "",
    "contacts" => [],
    "created_at" => "2019-11-11T20:29:29Z",
    "grant_types" => ["authorization_code", "refresh_token"],
    "logo_uri" => "",
    "metadata" => nil,
    "owner" => "",
    "policy_uri" => "",
    "redirect_uris" => ["http://localhost:4000/callback"],
    "response_types" => ["code", "id_token"],
    "scope" => "offline_access offline openid",
    "subject_type" => "public",
    "token_endpoint_auth_method" => "client_secret_basic",
    "tos_uri" => "",
    "updated_at" => "2019-11-11T20:29:29Z",
    "userinfo_signed_response_alg" => "none"
  },
  "oidc_context" => %{},
  "request_url" => "http://127.0.0.1:4444/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d",
  "requested_access_token_audience" => [],
  "requested_scope" => ["offline_access", "offline", "openid"],
  "session_id" => "c2788009-0e40-4f51-87f7-cd801ee0faf4",
  "skip" => true,
  "subject" => "andrew@pluspeter.com"
}
[info] skipping log in. user authenticated at oauth server
[info] Sent 302 in 18ms
[debug] CanScoutWeb.LoginController halted in :action/2
[info] GET /consent
[debug] Processing with CanScoutWeb.LoginController.consent/2
  Parameters: %{"consent_challenge" => "4eb4a4614ffb4d16bff5cd58496f0664"}
  Pipelines: [:anonymous]
[debug] selecting locale from session
[debug] fall back to selecting locale from accept-language header
[debug] selected locale en
[info] skipping consent
[info] Sent 302 in 13ms
[debug] CanScoutWeb.LoginController halted in :action/2
[info] GET /callback
[debug] Processing with CanScoutWeb.Auth.AuthController.callback/2
  Parameters: %{"code" => "pxfPzwF7jGwFKoCnS1dfztGmcncHE0ZX8NTiDFZ0Z-8.3hV5_TOcMFtvx11a5Aeh184NKES4f2J2MNfTXqhjP-M", "scope" => "offline_access offline openid", "state" => "0d606afc-11c2-47c7-afa8-b394b9b5f31d"}
  Pipelines: [:anonymous]
[debug] selecting locale from session
[debug] fall back to selecting locale from accept-language header
[debug] selected locale en
[info] Sent 302 in 143ms
[debug] CanScoutWeb.Auth.AuthController halted in :action/2
[info] GET /user/token
[debug] Processing with CanScoutWeb.ResourceController.token/2
  Parameters: %{}
  Pipelines: [:user]
[info] Found token in session
[info] Token is still valid
[debug] selecting locale from session
[debug] fall back to selecting locale from accept-language header
[debug] selected locale en
[info] Sent 200 in 634µs

```

**HYDRA LOGS**
```
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d"
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=11953200 method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d" status=302 text_status=Found took=11.9532ms
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="started handling request" method=GET remote="192.168.144.1:50420" request="/oauth2/auth/requests/login?login_challenge=2d78f517f0b349aa81b143558f856e1b"
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=3619000 method=GET remote="192.168.144.1:50420" request="/oauth2/auth/requests/login?login_challenge=2d78f517f0b349aa81b143558f856e1b" status=200 text_status=OK took=3.619ms
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="started handling request" method=PUT remote="192.168.144.1:50420" request="/oauth2/auth/requests/login/accept?login_challenge=2d78f517f0b349aa81b143558f856e1b"
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=8567200 method=PUT remote="192.168.144.1:50420" request="/oauth2/auth/requests/login/accept?login_challenge=2d78f517f0b349aa81b143558f856e1b" status=200 text_status=OK took=8.5672ms
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&login_verifier=64b0b3f5642047d49b723d9b6f17ad6d&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d"
hydra_1          | time="2019-11-11T21:01:09Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=13910700 method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&login_verifier=64b0b3f5642047d49b723d9b6f17ad6d&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d" status=302 text_status=Found took=13.9107ms
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="started handling request" method=GET remote="192.168.144.1:50420" request="/oauth2/auth/requests/consent?consent_challenge=4eb4a4614ffb4d16bff5cd58496f0664"
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=2925100 method=GET remote="192.168.144.1:50420" request="/oauth2/auth/requests/consent?consent_challenge=4eb4a4614ffb4d16bff5cd58496f0664" status=200 text_status=OK took=2.9251ms
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="started handling request" method=PUT remote="192.168.144.1:50420" request="/oauth2/auth/requests/consent/accept?consent_challenge=4eb4a4614ffb4d16bff5cd58496f0664"
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=6427500 method=PUT remote="192.168.144.1:50420" request="/oauth2/auth/requests/consent/accept?consent_challenge=4eb4a4614ffb4d16bff5cd58496f0664" status=200 text_status=OK took=6.4275ms
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&consent_verifier=f7ef96cf68aa4c3f9e9e37de15013cca&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d"
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=21742300 method=GET remote="192.168.144.1:38834" request="/oauth2/auth?client_id=can_scout_client&consent_verifier=f7ef96cf68aa4c3f9e9e37de15013cca&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=0d606afc-11c2-47c7-afa8-b394b9b5f31d" status=302 text_status=Found took=21.7423ms
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="started handling request" method=POST remote="192.168.144.1:38838" request=/oauth2/token
hydra_1          | time="2019-11-11T21:01:10Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=140282200 method=POST remote="192.168.144.1:38838" request=/oauth2/token status=200 text_status=OK took=140.2822ms

```

**Comment by aeneasr** [comment]
Did you set `remember: true` when accepting login?

**Comment by robotlovesyou** [comment]
Yes, remember is true and remember_for is 300 (for testing. It is a lot longer in live)

**Comment by aeneasr** [comment]
The server logs are missing calls to `/session/logout`, could you please include the full logs?

**Comment by robotlovesyou** [comment]
This includes the call to /sessions/logout followed by the logs resulting visiting the protected resource, as described above

```
hydra_1          | time="2019-11-11T21:31:44Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38854" request=/oauth2/sessions/logout
hydra_1          | time="2019-11-11T21:31:44Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=348200 method=GET remote="192.168.144.1:38854" request=/oauth2/sessions/logout status=302 text_status=Found took="348.2µs"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=16466800 method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5" status=302 text_status=Found took=16.4668ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=GET remote="192.168.144.1:50428" request="/oauth2/auth/requests/login?login_challenge=0104f3ae96bb48e5b1a036dad8975ab0"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=3394000 method=GET remote="192.168.144.1:50428" request="/oauth2/auth/requests/login?login_challenge=0104f3ae96bb48e5b1a036dad8975ab0" status=200 text_status=OK took=3.394ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=PUT remote="192.168.144.1:50428" request="/oauth2/auth/requests/login/accept?login_challenge=0104f3ae96bb48e5b1a036dad8975ab0"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=6186900 method=PUT remote="192.168.144.1:50428" request="/oauth2/auth/requests/login/accept?login_challenge=0104f3ae96bb48e5b1a036dad8975ab0" status=200 text_status=OK took=6.1869ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&login_verifier=d9d2fed3410f409bbff987aed8d14ff3&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=12316800 method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&login_verifier=d9d2fed3410f409bbff987aed8d14ff3&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5" status=302 text_status=Found took=12.3168ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=GET remote="192.168.144.1:50428" request="/oauth2/auth/requests/consent?consent_challenge=618b13ee77ec48e4b9c5ac8ad5ea4bcf"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=2681700 method=GET remote="192.168.144.1:50428" request="/oauth2/auth/requests/consent?consent_challenge=618b13ee77ec48e4b9c5ac8ad5ea4bcf" status=200 text_status=OK took=2.6817ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=PUT remote="192.168.144.1:50428" request="/oauth2/auth/requests/consent/accept?consent_challenge=618b13ee77ec48e4b9c5ac8ad5ea4bcf"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/admin: http://127.0.0.1:4444/.latency=7796200 method=PUT remote="192.168.144.1:50428" request="/oauth2/auth/requests/consent/accept?consent_challenge=618b13ee77ec48e4b9c5ac8ad5ea4bcf" status=200 text_status=OK took=7.7962ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&consent_verifier=7ff419466d6a40aa9f546ef79d2cb3c6&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5"
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=11710400 method=GET remote="192.168.144.1:38848" request="/oauth2/auth?client_id=can_scout_client&consent_verifier=7ff419466d6a40aa9f546ef79d2cb3c6&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fcallback&response_type=code&scope=offline_access+offline+openid&state=95b266af-a6d8-4b36-9fe9-c22189ba9fe5" status=302 text_status=Found took=11.7104ms
hydra_1          | time="2019-11-11T21:31:56Z" level=info msg="started handling request" method=POST remote="192.168.144.1:38846" request=/oauth2/token
hydra_1          | time="2019-11-11T21:31:57Z" level=info msg="completed handling request" measure#hydra/public: http://127.0.0.1:4444/.latency=134178700 method=POST remote="192.168.144.1:38846" request=/oauth2/token status=200 text_status=OK took=134.1787ms

```

**Comment by aeneasr** [comment]
It's really difficult to see what the error could be. Most of the times the issue is something like:

- Cookies not being set properly (maybe an adblocker, notrack or whatever. Especially brave is very problematic here)
- Multiple instances with non-uniform configs or some other type of reset of "system secret"
- The login app does not properly set remember
- The session ended through some other means
- The client code is buggy

The code call stack is very straight forward here.

1. https://github.com/ory/hydra/blob/master/oauth2/handler.go#L82
* https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/oauth2/handler.go#L120
* https://github.com/ory/hydra/blob/master/oauth2/handler.go#L121
* https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L942
* because verifier is empty: https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L945
* because hint is empty (op initiated logout): https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L731
* both are zero and thus skipped: https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L734-L742
* this causes the redirect to the post logout url: https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L745-L749

Unless [`authenticateSession`](https://github.com/ory/hydra/blob/a47dd97835684b04df2c26cf8f9e142f549bbcb1/consent/strategy_default.go#L744) is buggy, which supposedly is not because you get "skip" on consecutive requests, this should work.

Can you maybe share the network stack (screenshot with URLs and headers visible is enough) of the request route redoing the flow?

It would be of course easier for me to debug if I had access to a repro case, but this should do it for now (thank you for your patience) :)

**Comment by aeneasr** [comment]
For sanity check, you can also update `URLS_POST_LOGOUT_REDIRECT=http://localhost:4000/logout?post-logout=true` and see if the URL changes once the flow is completed. There have been some issues on (especially Windows) where ports are allocated twice and Docker taking the back seat (so you're actually hitting a Hydra instance of an old running process on your host).

**Comment by aeneasr** [comment]
Another possibility is that your browser has isolated containers when in incognito. So if you have one tab with your hydra flow and you paste the logout url into another tab, those tabs don't share cookies. This is especially the case when privacy-sensitive settings are used.

**Comment by robotlovesyou** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/883991/68623387-ab324e00-04d4-11ea-924a-cd2d41291bea.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/883991/68623456-dc128300-04d4-11ea-85d8-9e35ae3f63e0.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/883991/68623492-ef255300-04d4-11ea-8b25-b3f8461d81c5.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/883991/68623533-05cbaa00-04d5-11ea-8004-66257c77f274.png">

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/883991/68623568-1714b680-04d5-11ea-83a4-ce2201c969d2.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/883991/68623591-23990f00-04d5-11ea-8951-6db083286349.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/883991/68623619-2dbb0d80-04d5-11ea-8da2-6899717e3add.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/883991/68623634-37dd0c00-04d5-11ea-8c60-d0c0b5780478.png">


The websocket requeset I have skipped is just the live-reload for dev.

**Comment by aeneasr** [comment]
Thank you! This is missing the logout request though?

**Comment by aeneasr** [comment]
This image: https://user-images.githubusercontent.com/883991/68623533-05cbaa00-04d5-11ea-8004-66257c77f274.png

And this image: https://user-images.githubusercontent.com/883991/68623591-23990f00-04d5-11ea-8951-6db083286349.png

Are missing the session cookie (maybe it's omitted in the …)

You should have a cookie called `oauth2_authentication_session` for `localhost:4444`.

**Also make sure you're not mixing up "127.0.0.1" and "localhost".** While those two are identical in terms of where they resolve to, they are separate FQDNs and thus do not share cookies! If you mix up `localhost` and `127.0.0.1` somewhere in there this could cause that issue.

**Comment by robotlovesyou** [comment]
OK. I'm too tired to keep looking at this today but I'll pick it up again tomorrow.

**Comment by robotlovesyou** [comment]
OK yes. I see it now. I had the logout url misconfigured. Thanks for all your assistance. Sorry for the false alarm.

**Comment by aeneasr** [comment]
So was it a localhost/127.0.0.1 mixup? It would probably make sense to have that as a section in the docs and your resolution would be very helpful here!

**Comment by robotlovesyou** [comment]
Yes. I have http://127.0.0.1:xxxx configured _everywhere_ for hydra except where I had the login url. I am _very_ annoyed at myself for not spotting it, especially given how many times I've pointed out the exact same issue to other developers here when we first started working with hydra

**Comment by robotlovesyou** [comment]
Sorry there is a typo in my last response. There error was where I had the log **out** url configured.

**Comment by titus-zx** [comment]
> oauth2_authentication_session

Hello. I am facing same issue. regarding this cookie `oauth2_authentication_session` i dont have but have cookie called `oauth2_authentication_session_insecure`. This can could the issue?

**Comment by norasotanext** [comment]
> > oauth2_authentication_session
> 
> Hello. I am facing same issue. regarding this cookie `oauth2_authentication_session` i dont have but have cookie called `oauth2_authentication_session_insecure`. This can could the issue?

It is not the problem. Make sure your `post_logout_redirect_uri` is included in `post_logout_redirect_uris` in the `http://localhost:4445/clients/:clientId`
