### ISSUE TITLE
client_id case sensitivity is not properly enforced when using MySQL

### ISSUE THREAD

**Issue by chris-branch** [ory/hydra#1644]
**Describe the bug**

Calling authorize and/or token endpoints should throw an error if the client_id parameter does not match an existing client in the database using a case-sensitive comparison.  For example, if the database contains "test-client" and the authorize or token endpoint is called with "client_id=TEST-CLIENT", that should produce a "invalid_client" error.  Case sensitivity is enforced properly when running Postgres, but not when running MySQL.

**Reproducing the bug**

1. Follow the steps at [https://www.ory.sh/docs/hydra/5min-tutorial](https://www.ory.sh/docs/hydra/5min-tutorial) to install Hydra

2. Start Hydra using MySQL (command line below copy/pasted from tutorial):
```
docker-compose -f quickstart.yml \
    -f quickstart-mysql.yml \
    up --build
```

3. Create a client (command line below copy/pasted from tutorial):
```
docker-compose -f quickstart.yml exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445/ \
    --id my-client \
    --secret secret \
    -g client_credentials
```

4. Perform client credentials grant using the client ID that matches except for case (notice "T" instead of "t"):
```
docker-compose -f quickstart.yml exec hydra \
    hydra token client \
    --endpoint http://127.0.0.1:4444/ \
    --client-id my-clienT \
    --client-secret secret
```

**Expected behavior**

Actual response: valid access token is returned

Expected response:
```
Could not retrieve access token because: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)","status_code":401}
```

**Environment**

* Version: v1.0.9
* Environment: Docker (oryd/hydra:latest)

**Additional context**

Works as expected when using Postgres.  Hydra should not rely on the underlying database when performing validations that are required to enforce case sensitivity.

**Comment by aeneasr** [comment]
Nice find, this indeed should not work. I saw that MySQL generally treats varchar as case-insensitive and auto-trimming spaces. *More implicit RDBMS knowledge, yay!*

We should probably update all `varchar()`s in MySQL to: `VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL UNIQUE`, which appears to be the recommended way. Alternatively, `VARBIN`.

**Comment by chris-branch** [comment]
You might consider doing this validation in code (after the query returns) so that it's enforced consistently independent of whatever data store is running behind the scenes and how they've elected to handle case sensitivity.

Also, if I were an existing user with Hydra running in production, I would be concerned about a Hydra upgrade changing column types on my existing database.  For example, does switching to utf8 / binary impact performance characteristics of indexes or have other unintended side effects?  I'm not currently running Hydra in production, so this isn't really a concern for me personally, but something to consider for your other users.

**Comment by aeneasr** [comment]
> You might consider doing this validation in code (after the query returns) so that it's enforced consistently independent of whatever data store is running behind the scenes and how they've elected to handle case sensitivity.

Unfortunately not, this also affects joins and other modules. We're using UUID almost exclusively everywhere, so case-sensitivity is not an issue with most of these systems, but it's best to resolve this in the DB layer and write some integration tests to ensure compliance of the adapter.

> Also, if I were an existing user with Hydra running in production, I would be concerned about a Hydra upgrade changing column types on my existing database. For example, does switching to utf8 / binary impact performance characteristics of indexes or have other unintended side effects? I'm not currently running Hydra in production, so this isn't really a concern for me personally, but something to consider for your other users.

That is correct. We will issue a warning for anyone applying the changes to a MySQL deployment. Some downtimes are unfortunately unavoidable sometimes.

**Comment by aeneasr** [comment]
As we will no longer support user-set client_ids, this issue becomes obsolete in Ory Hydra v2.0 - thus closing!
