### ISSUE TITLE
Add support for Syslog logging

### ISSUE THREAD

**Issue by forrest-lookback** [ory/hydra#1645]
**Is your feature request related to a problem? Please describe.**

We'd like to ship logs somewhere other than stdout but cannot at this time, so this is a feature request to support Syslog shipping.

Currently logs can not be sent remotely, while it is possible to collect these logs and send them forward it would be nice if Hydra itself could ship logs to a Syslog server.

**Describe the solution you'd like**

Support for Syslog in the standard RFC 5424 syslog format as [described in RFC 5424](https://tools.ietf.org/html/rfc5424) with configuration options for the host, TLS (True/False), port, and [enterprise number](https://tools.ietf.org/html/rfc5424#section-7.2.2).

**Describe alternatives you've considered**

Secondary support for pluggable logging systems.

**Comment by aeneasr** [comment]
That's the job of your deployment environment and will is very unlikely to ever land here. This can also easily be achieved with basic bash:

```
$ /home/dirname/application_name -v 2>&1 | logger &
```

or with netcat (in case of remote). There are probably more options for remote piping.

**Comment by forrest-lookback** [comment]
Okay thanks for the quick response.
