### ISSUE TITLE
Encryption for claims data storage

### ISSUE THREAD

**Issue by chaopeng** [ory/hydra#1649]
## Issue

Currently, Hydra stores claims from consent application as json in database. In our case, we will have a field in /userinfo endpoint stores JWT. Similar to [Aggregated Claims](https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims).

This can be supported by adding claims to id token session in hydra consent application. But hydra will save claims in plain text. Attacker can use the JWT if they grant the database access.

## Solution

1. add a config flag `encryption_session_data` to hydra
2. if flag is true, encrypt data before writing in database and decrypt after reading from database.
encryption can use same encryption system today with the RSA key encryption in database. 
3. Optional, we can also support GCP KMS for long term. See  https://github.com/ory/hydra/issues/1328

**Comment by aeneasr** [comment]
Encrypting the claims storage is a good idea. If you'd be up for it we'd definitely accept a PR. We're using this methodology already for JSON Web Keys.

Please do not use RSA encryption, but AES-GCM instead. There is an implementation already available for that in ORY Hydra!

**Comment by chaopeng** [comment]
I start work on this on this week.

**Comment by aeneasr** [comment]
Let me know if you need help!
