### ISSUE TITLE
Revoke current session tokens after logout

### ISSUE THREAD

**Issue by tyaps** [ory/hydra#1651]
Hello.

I think it is a good idea to have an opportunity to revoke tokens that were created during hydra login session when we do logout.

Right now hydra logout operation only deletes authentication_session, but tokens for user remain active.

I have following situation: 

Each web site proceed authentication_code flow and stores tokens in its own session.
When web client make request for web site, it uses cookies for that site and the site obtains tokens from corresponding session.
IDP sets remember=true when accepting login request, therefore I enter credentials only once for the first site. And where I do authentication_code flow for the second site, I don't need to provide credentials.

Each site is a part of ecosystem. So when I do logout from the first site, I somehow must be logged out from the second site.

I believe that revoking all tokens for given login (subject) after logout is the safest and reliable way that guarantees that user (via RP) is unable to access resources.

Of course, maybe current hydra logout behavior was implemented such way especially (to follow some vision or concepts). In this case, please tell me the reasons why it doesn't remove tokens.

I'm aware of endpoints like DELETE /oauth2/auth/sessions/consent?subject=xx&client=xx
that removes all tokens for given subject/client

but it cannot fit my situation: because I can be logged as "user1" on different computers and when log out I must log out only on that computer, but stay logged in on another.

I and my team discussed options that can help us meet our needs. We are ready to contribute to make it possible to revoke all tokens for given hydra session. We can discuss this idea if you approve that it doesn't conceptually break anything. Or advise some better approach, please. ))

**Comment by aeneasr** [comment]
Please use OpenID Connect Front/Back-channel logout, there is a whole section for this: https://www.ory.sh/docs/hydra/implementing-consent#user-logout
