### ISSUE TITLE
How to redirect back to the previously unauthenticated page after successful login

### ISSUE THREAD

**Issue by YeLuoYiFanChen** [ory/hydra#1652]
When I request a URL, because the token detection fails, I will start the login process, but after the login succeeds, how can I jump back to the previous page？please help me

**Comment by aeneasr** [comment]
Store it in a cookie.

**Comment by YeLuoYiFanChen** [comment]
> Store it in a cookie.
> […](#)
> On 27. Nov 2019, at 09:31, YeLuoYiFanChen ***@***.***> wrote: ﻿ When I request a URL, because the token detection fails, I will start the login process, but after the login succeeds, how can I jump back to the previous page？please help me — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

very thanks
