### ISSUE TITLE
Support Postgres schemas

### ISSUE THREAD

**Issue by anthonator** [ory/hydra#1657]
**Is your feature request related to a problem? Please describe.**

We'd like to have the ability to support shemas other then the default `public` schema.

https://www.postgresql.org/docs/current/ddl-schemas.html

**Describe the solution you'd like**

A schema name should be configurable when using the Postgres adapter. This would allow the adapter to assemble queries that can talk to tables in other schemas.

**Describe alternatives you've considered**

We aren't aware of any alternatives.

**Comment by aeneasr** [comment]
Unless this is possible on the driver level, this is a nofix because it's a postgres only solution and would not be applicable to other databases. We are using https://github.com/lib/pq

**Comment by anthonator** [comment]
I did find this.

https://github.com/lib/pq/issues/471

Although I can't find any documentation that `search_path` is a thing for Postgres connection URI's.

https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by aeneasr** [comment]
If it says that it works that way it simply should. Have you tried it? In any case, I think this is lib/pq upstream and not something we can/will solve here.

**Comment by aeneasr** [comment]
I checked, first - lib/pq is not using the C libpq library, so the link is not relevant. `search_path` is documented lib/pq behavior and should work as advertised. closing.
