### ISSUE TITLE
Fix docker build command in comment and add doc

### ISSUE THREAD

**Issue by rickwang7712** [ory/hydra#1658]
**Describe the bug**

Using build command in Dockerfile's comment will get error log like "standard_init_linux.go:190: exec user process caused "no such file or directory"":
```
  1 # To compile this image manually run:
  2 #
  3 # $ GO111MODULE=on GOOS=linux GOARCH=amd64 go build && docker build -t oryd/hydra:v1.0.0-rc.7_oryOS.10 . && rm hydra
```

And the reason is environment like alpine and scratch cannot support golang dynamic linking due to missing libc libraries.
Ref: https://stackoverflow.com/questions/52640304/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

**Reproducing the bug**

1. Run the command in Dockerfile: GO111MODULE=on GOOS=linux GOARCH=amd64 go build && docker build -t oryd/hydra:v1.0.0-rc.7_oryOS.10 . && rm hydra
2. Run docker
3. And use docker logs <image_name> will see the error log: standard_init_linux.go:190: exec user process caused "no such file or directory"

*Server logs*
standard_init_linux.go:190: exec user process caused "no such file or directory"

*Server configuration*

**Expected behavior**

Should build and run smoothly without error.

**Environment**

* Version: v1.2.3, git sha hash
* Environment: Debian, Docker, ...

**Additional context**

If you agree the comment and the doc need a improvement, I would like to make contribution on this(adding CGO_ENABLED=0).
Because I had suffered from this last week...

**Comment by aeneasr** [comment]
Which Go version are you using? `CGO_ENABLED=0` is the default for Go 1.13+

**Comment by rickwang7712** [comment]
I see. Thanks!
I’m on 1.12, because my application still using hydra v1.0.0.

**Comment by aeneasr** [comment]
Ok, yes, with Go 1.12 you need to explicitly set `CGO_ENABLED=0` :) It would be great if you could update the docs there!
