### ISSUE TITLE
Question about Auth Request prompt=none behavior

### ISSUE THREAD

**Issue by rickwang7712** [ory/hydra#1659]
Hi @aeneasr,

I'm curious about the behavior while using prompt=none parameter on auth request.
I found that Hydra will still redirect user-agent to Login Provider & Consent Provider
even if both login and consent session cookies are still valid.

Is it necessary to keep redirecting useragent to login/consent providers? Why?
I thought the Hydra could redirect useragent to callback url directly with auth code, because those cookies stand for identity and authorization proof.

Thanks!

**Comment by aeneasr** [comment]
Yes, because you might want to block the request in your login or consent app, or do some other callback logic.
