### ISSUE TITLE
Multistaging Build for hydra

### ISSUE THREAD

**Issue by evalsocket** [ory/hydra#1662]
**Is your feature request related to a problem? Please describe.**

Currently dockerfile is needed local go build before `docker build` command. Idea is to create multi staging build for dockerfile 

**Describe the solution you'd like**

```
FROM golang:1.13.5-alpine3.10 AS build-env
WORKDIR /go/src/github.com/ory/hydra/
RUN apk --no-cache add build-base git bzr mercurial gcc
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build -o hydra .

#second stage
FROM alpine:3.10
RUN apk add -U --no-cache ca-certificates
WORKDIR /app
COPY --from=build-env /go/src/github.com/ory/hydra/hydra /usr/bin/hydra
USER 1000
ENTRYPOINT ["hydra"]
CMD ["serve"]
```

**Describe alternatives you've considered**

**Additional context**

**Comment by aeneasr** [comment]
This is on purpose because we use one and the same binary across all systems. This is part of the way how goreleaser works and is unlikely to be changed.
