### ISSUE TITLE
Improve documentation for hydra responses

### ISSUE THREAD

**Issue by retendo** [ory/hydra#1663]
**Is your feature request related to a problem? Please describe.**

When I'm consuming hydra APIs I would like to know which fields in the response json can be optional/null/absent, so that I can model my types properly on the consumer side.

For some responses there is a proper description of the fields in the documentation.
For example for [login request responses](https://www.ory.sh/docs/hydra/implementing-consent#user-login) there are already helpful comments

```javascript
{
    // Skip, if true, let's us know that ORY Hydra has successfully authenticated the user and we should not show any UI
    "skip": true|false,

    // The user-id of the already authenticated user - only set if skip is true
    "subject": "user-id",

    ...
}
```
____

This information lets me model this as
```python
type Subject = string

type HydraLoginContinuation =
| Skip of Subject
| Continue

type HydraLoginRequest = {
    Continuation: HydraLoginContinuation
    ...
}
```
otherwise it would look like this:
```python
type HydraLoginRequest = {
    Skip: bool option
    Subject: string option
    ...
}
```
____

That is all great, but I would like this information for all fields in all response objects.
After the sample json in the documentation it says

> For a full documentation on all available keys, please head over to the API documentation (make sure to select the right API version).

But the API documentation doesn't give me the information I need:
https://www.ory.sh/docs/hydra/sdk/api#loginrequest

**Describe various solutions you'd like**

This information belongs in the API documentation.
Possible solutions:
a. Right now there is "Required" column that always seems to be false. We could use that value to indicate that a field will always be present in the response and that it has a non-null value.
b. We could postfix Name or Type values with "(optional)"
c. We could prefix Description value with "(optional)"

**More opinions**

I think this should apply to at least all endpoints of all ory services that are not supposed to be consumed by a standard library (like oauth2/token etc)

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
