### ISSUE TITLE
Applying migrations causes downtime

### ISSUE THREAD

**Issue by jtescher** [ory/hydra#1664]
**Describe the bug**

Applying migrations that add columns break currently running hydra instances, causing downtime for at least the duration of the rollout to the new version of hydra.

**Reproducing the bug**

1. run hydra v1.0.8
2. apply migrations for hydra v1.0.9
3. run oauth flow or get client details from running v1.0.8 hydra instance

*Server logs*

```
level=error msg="An error occurred" debug="missing destination name metadata in *client.sqlData" description="Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)" error=invalid_client hint="The requested OAuth 2.0 Client does not exist."
```

**Expected behavior**

Running hydra instances should continue to work and ignore the additional fields.

**Possible solution**

Use known list of columns in sql queries.

---

e.g. in [client/manager_sql.go](https://github.com/ory/hydra/blob/master/client/manager_sql.go#L255) instead of using:

```go
m.DB.Rebind("SELECT * FROM hydra_client WHERE id=?"), id)
```

use the known set of columns from `sqlParams`:

```go
m.DB.Rebind(fmt.Sprintf(`SELECT %s FROM hydra_client WHERE id=?`, strings.Join(sqlParams, ", "))), id)
```

**Comment by aeneasr** [comment]
That’s unfortunately not in the realm of possibility. Please adhere to the given guidance. We do not provide backwards compatible SQL adapters and we do warn regarding potential sql migration locks/updates/backups as best as we can.

We do not provide zero downtime upgrades - this is the task of your ops teams if you use this software.

Running OSS yourself is not a free lunch and there is nothing we can do in the realm of OSS support here. Each RDBMS behaves differently and it is not our OSS contract to provide zero downtime upgrades for every system.

There is nothing we can solve here with reasonable amount of work -> closing
