### ISSUE TITLE
Include total count in pagination header

### ISSUE THREAD

**Issue by UkonnRa** [ory/hydra#1666]
**Is your feature request related to a problem? Please describe.**

When querying the Clients/Consent Sessions using pagination, ORY Hydra will only return results with some links, but not **the total count of the items**, which is useful to display in the frontend, you know, showing the total pages or something.

**Describe the solution you'd like**

Add the `total_count` parameter into Header.

Although I think that the most elegant pagination solution is following [JSON:API Spec](https://jsonapi.org/), but I know it's almost impossible to change the data structure totally. So I think adding a parameter into Header is also a nice solution.

**Comment by aeneasr** [comment]
I believe we're sending `rel=last` as part of the HTTP Link Header, similar as we do with next/prev?

**Comment by aeneasr** [comment]
Yes, that is indeed the case:

https://github.com/ory/hydra/blob/master/client/handler.go#L200-L206

Should probably document this somewhere :D

**Comment by UkonnRa** [comment]
@aeneasr I have seen the code also, but in fact, there is no `total_page` param in the `Link` header or so.

Say I have 100 clients, and calling `http://127.0.0.1:4445/clients?limit=10&offset=30`. I will get the following `Link` header:

```
</clients?limit=10&offset=0>; rel="first",</clients?limit=10&offset=40>; rel="next",</clients?limit=10&offset=20>; rel="prev",</clients?limit=10&offset=50>; rel="last"
```

**Comment by aeneasr** [comment]
`SERVE_ADMIN_CORS_EXPOSED_HEADERS ` is for CORS, it doesn't have any effect here.

What I meant is that you can calculate the approximate number of items by taking last (in that case it would be about 500 items or "50 pages a 10 items"):

```
</clients?limit=10&offset=50>; rel="last"
```

Does that help?

**Comment by UkonnRa** [comment]
If Hydra can ensure that every **list request** can return the **last rel**, I think it helps

**Comment by aeneasr** [comment]
I am confused, I thought you always receive the last rel in the header, that's what you said ehre ( https://github.com/ory/hydra/issues/1666#issuecomment-567853093 ), no? Is the header missing sometimes? And if so, when exactly?

**Comment by UkonnRa** [comment]
Like this, https://github.com/ory/hydra/issues/1667, **when the `limit` is larger than the total count**, the `Link` header will only return `first` and `prev`(And the `prev` is wrong). So what should I expect in such situation?

**Comment by nmlc** [comment]
We can see the current behavior of the Link header in [these](https://github.com/ory/x/blob/master/pagination/header_test.go) test cases. The case when there is only a single page (#1667) is not covered. If we could agree on the desired behavior (only rel=first or maybe no header at all) I'm willing to fix this.

**Comment by UkonnRa** [comment]
Yes, no matter what the behavior is, I hope the feature could be **freezed and documented** as fast as we can

**Comment by aeneasr** [comment]
As always, we happily accept any PRs that help with that - for implementing this within Ory it always depends on internal sprint and milestone planning.

**Comment by aeneasr** [comment]
@nmlc sorry I missed your comment - your contribution would be very much welcomed!
