### ISSUE TITLE
Negative offset

### ISSUE THREAD

**Issue by UkonnRa** [ory/hydra#1667]
**Describe the bug**

Say I have **only one** client in ORY Hydra server. And when I am using `GET /clients`, the `Link` header is:

```
Link: </clients?limit=100&offset=0>; rel="first",</clients?limit=100&offset=-100>; rel="prev"
```

**Expected behavior**

In this situation, the expected result is containing `first` link only

**Environment**

Using the latest docker image:

```
# docker.yml
  hydra:
    image: oryd/hydra:latest
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:4201/static/consent
      - URLS_LOGIN=http://127.0.0.1:4201/static/login
      - URLS_LOGOUT=http://127.0.0.1:4201/static/logout
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - LOG_LEVEL=debug

    restart: unless-stopped
```

**Comment by aeneasr** [comment]
Nice catch!

**Comment by aeneasr** [comment]
Would you be able to fix this? The code is located at: https://github.com/ory/x/blob/master/pagination/header.go

**Comment by UkonnRa** [comment]
Well, embarrassing, I have **no** idea how to write Go at all, this is a total black box for me...
