### ISSUE TITLE
Feature Request: Configurable sql table prefix

### ISSUE THREAD

**Issue by paulbdavis** [ory/hydra#1668]
**Is your feature request related to a problem? Please describe.**

I ran into an issue trying to run multiple instances of hydra with postgres. The purpose of the multiple hydras is to have admin and user oauth access (the login flow is very different, so I need a second set of auth and consent URLs... at least this is the solution I'm working on right now, if there is a better way of doing this, someone let me know)

**Describe the solution you'd like**

A config option (like `--table-prefix` or `-t`) to specify a table prefix when running the migrations and accessing the data when sql is used. A default of `hydra_` would result in the current behavior (and I would say that a `_` would be appended to the option value if it's not included by the user?).

**Describe alternatives you've considered**

Currently I just set up a second database for the data, one could also use the same database with a different user/schema combination.

**Additional context**

I am willing to work on the change, but since it would be a bigger, tedious job, I wanted to open an issue to see if it would be accepted in general. If there is a better way to accomplish my goal outlined above of having different login processes without running a second instance I'd be interested in that as well.

**Comment by aeneasr** [comment]
This might help: https://github.com/ory/hydra/issues/1657
