### ISSUE TITLE
hydra not finding passwords

### ISSUE THREAD

**Issue by dac2020** [ory/hydra#1670]
I looked around the net and in the issues before posting this. I'm not sure if this is a known problem or something I'm doing wrong.
I created a test password file with the password contained then run hydra and it doesn't find the password. The username and password are both admin, admin.

This is how I ran the command. 
hydra -l admin -P testwords 192.168.1.41 -t 4 -V ssh

*Server logs*

`[root@loc hydra]# hydra -l admin -P testwords 192.168.1.41 -t 4 -V ssh
Hydra v8.2-dev (c) 2016 by van Hauser/THC - Please do not use in military or secret service organizations, or for illegal purposes.

`Hydra (http://www.thc.org/thc-hydra) starting at 2019-12-20 08:58:18
[DATA] max 4 tasks per 1 server, overall 64 tasks, 27 login tries (l:1/p:27), ~0 tries per task
[DATA] attacking service ssh on port 22
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "kingshit" - 1 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "monkey" - 2 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "admin" - 3 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "abc123" - 4 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "nicole" - 5 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "daniel" - 6 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "babygirl" - 7 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "monkey" - 8 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "lovely" - 9 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "jessica" - 10 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "654321" - 11 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "michael" - 12 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "ashley" - 13 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "qwerty" - 14 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "111111" - 15 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "iloveu" - 16 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "000000" - 17 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "michelle" - 18 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "tigger" - 19 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "sunshine" - 20 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "chocolate" - 21 of 27 [child 1]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "password1" - 22 of 27 [child 0]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "soccer" - 23 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "anthony" - 24 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "friends" - 25 of 27 [child 2]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "administrator" - 26 of 27 [child 3]
[ATTEMPT] target 192.168.1.41 - login "admin" - pass "" - 27 of 27 [child 0]
1 of 1 target completed, 0 valid passwords found
Hydra (http://www.thc.org/thc-hydra) finished at 2019-12-20 08:58:50
`
Centos 7.6. New server, minimal build, not much on it yet.

**Comment by aeneasr** [comment]
wrong repository and project.

**Comment by dac2020** [comment]
I'm trying to help out. The least you could do is point me to the correct project then please.

**Comment by tleef** [comment]
You appear to be talking about a different hydra, not ory/hydra.

**Comment by aeneasr** [comment]
He's looking for the THC Hydra project for password cracking

**Comment by dac2020** [comment]
Thank you, yes, that's what I'm looking for. A manufacturer of a piece of hardware I have went under and never left me the password so trying to see if I can get into it to manage my setup.
