### ISSUE TITLE
Add authenticated_at to type HandledConsentRequest

### ISSUE THREAD

**Issue by marcohutzsch1234** [ory/hydra#1684]
**Is your feature request related to a problem? Please describe.**

When we ask hydra for all accepted consents for a subject we want to show the subject the date, when the latest consent was accepted. This value exists in the db but is not accessible via go-sdk.

**Describe the solution you'd like**

We had the idea of adding the value to the mentioned struct. Would you accept a PR for that?

**Describe alternatives you've considered**

No idea.

**Comment by aeneasr** [comment]
I think `authenticated_at` is currently not part of the consent itself but only of the authentication session. Do you need the time of the authentication itself, or the time where the consent request was granted?

**Comment by marcohutzsch1234** [comment]
Closing Issue because discussion moved to PR: https://github.com/ory/hydra/pull/1689
