### ISSUE TITLE
CORS disabled for 'public' API

### ISSUE THREAD

**Issue by jasper22** [ory/hydra#1688]
I'm trying to build Angular with authentication that token generated by Hydra. After reading a lot (!) of documentation of Hydra I compose an configuration file when Hydra somehow started without the errors. Here is the file: [Google-Project-01/configuration/hydra-config.yaml](https://github.com/jasper22/google-project-01/blob/master/configs/hydra-config.yaml)

The important parts is that:

    serve:
      public:
        port: 4444
        # host: localhost # leave this out or empty to listen on all devices which is the default

        cors:
          enabled: true
    ...
    ...

    admin:
        port: 4445
    
        # host: localhost # leave this out or empty to listen on all devices which is the default

        cors:
          enabled: true

I build an GET request in Angular such as:

    const httpOptions = {
      headers: new HttpHeaders({
        'Content-Type':  'application/json'
      })};

    this.httpClient.get(targetUrl, httpOptions)
                    .pipe(
                      catchError(err => this.handleError(err))
                    )
                    .subscribe(
                      x => console.log("All ok"),
                      error => {
                        this.redirectToOAuthError(error);
                    });

    // targetUrl = http://localhost:4444/oauth2/auth?client_id=aclient&scope=torrents_status%20upload_new&response_type=code&redirect_uri=http://localhost:4200&state=b14eefa1-5da7-4e51-a694-cd60dd0a534b

From Chrome browser point of view it always send OPTION http command to endpoint to detect if I could send this GET request (I guess because I use ` 'Content-Type':  'application/json',` and it always fails with error:

![image](https://user-images.githubusercontent.com/2697004/72256458-ef93b480-3611-11ea-8d62-51880cde18cf.png)

    Access to XMLHttpRequest at 'http://localhost:4444/oauth2/auth?client_id=aclient&scope=torrents_status%20upload_new&response_type=code&redirect_uri=http://localhost:4200&state=b14eefa1-5da7-4e51-a694-cd60dd0a534b' from origin 'http://localhost:4200' 
**has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

as I understand it's not Angular related. For example if I'm running Google Chrome as:

`chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security`

as described here: [StackOverflow](https://stackoverflow.com/a/19317888/1144952) --> it **does work** and my Angular GET request pass through.

BTW: Why does Hydra use 302 Found as an answer to 'login' request ? Somehow this response is handled by Chrome and not directly by Angular so redirection fails and must be handled specially inside Angular code. Because what Angular see it's 404 Not Found because redirection fails :( Why not use: 401 Unauthorized  ?

After a lot of searching and learning about CORS/Angular/Hydra/etc... I found that Hydra itself absolutely **disable** all CORS for 'public' API !

Here: [/cmd/server/handler.go::RunServePublic() ](https://github.com/ory/hydra/blob/fc16ab97646bb444d90925b920c651e450cf1f38/cmd/server/handler.go#L121)

and here: [/cmd/server/handler.go::RunServeAll() ](https://github.com/ory/hydra/blob/fc16ab97646bb444d90925b920c651e450cf1f38/cmd/server/handler.go#L145)

as you see in both cases the parameter passed is just `false` no question asked :(

This is very confusing (at least) behavior for Hydra.

* I configured it to use CORS
* I start it as /hydra.exe serve all --config .....

1. There's no logs whatsoever about CORS didn't start for 'public'. Here is example of log output:

{"level":"info","msg":"No tracer configured - skipping tracing setup","time":"2020-01-13T14:49:56+02:00"}
{"level":"warning","msg":"Using deprecated hierarchical scope strategy, consider upgrading to \"wildcard\"\" or \"exact\"\".","time":"2020-01-13T14:49:56+02:00"}
{"level":"warning","msg":"JSON Web Key Set \"hydra.openid.id-token\" does not exist yet, generating new key pair...","time":"2020-01-13T14:49:56+02:00"}
{"level":"warning","msg":"JSON Web Key Set \"hydra.jwt.access-token\" does not exist yet, generating new key pair...","time":"2020-01-13T14:49:59+02:00"}
Thank you for using ORY Hydra master!

Take security seriously and subscribe to the ORY Security Newsletter. Stay on top of new patches and security insights.                                                             

Subscribe now: http://eepurl.com/di390P <<
{"level":"info","msg":"Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa","time":"2020-01-13T14:50:02+02:00"}
{"level":"warning","msg":"JSON Web Key Set \"hydra.https-tls\" does not exist yet, generating new key pair...","time":"2020-01-13T14:50:02+02:00"}
{"level":"info","msg":"Setting up http server on :4444","time":"2020-01-13T14:50:03+02:00"}
{"level":"warning","msg":"HTTPS disabled. Never do this in production.","time":"2020-01-13T14:50:03+02:00"}
{"level":"info","msg":"Enabling CORS on interface: :4445","options":"{AllowedOrigins:[http://*] AllowOriginFunc:\u003cnil\u003e AllowOriginRequestFunc:\u003cnil\u003e AllowedMethods:[POST GET PUT PATCH DELETE] AllowedHeaders:[Authorization Content-Type] ExposedHeaders:[Content-Type] MaxAge:10 AllowCredentials:true OptionsPassthrough:false Debug:true}","time":"2020-01-13T14:50:03+02:00"}
{"level":"info","msg":"Setting up http server on :4445","time":"2020-01-13T14:50:03+02:00"}
{"level":"warning","msg":"HTTPS disabled. Never do this in production.","time":"2020-01-13T14:50:03+02:00"}

There's a message about `Enabling CORS on interface: :4445` but it silent about `:4444` url :(

2. Why CORS is just disabled for 'public' API even if I specifically enabled it in YAML/configuration file ? 
I did it on purpose to allow my GET request from Angular to pass through Google Chrome security check. Otherwise missing 'Access-Control-Allow-Origin' in header when server replay to OPTION verb just stop any other other request to Hydra server from Angular. I just start to receive errors in client.

**Expected behavior**

I expect from Hydra to implement CORS on 'public' and 'admin' URLs to allow Chrome Browser (or any other browser) to continue working correctly with Hydra server.

**Environment**

* Hydra version: latest from git (commit fc16ab97646bb444d90925b920c651e450cf1f38)
* Environment: Windows 10, VS Code, Angular 8

**Comment by aeneasr** [comment]
This has been reported in this repository before. You are trying to access `/oauth2/auth` using CORS. This is not an endpoint that you can CORS against. If you're doing that, you are using OAuth2 **completely wrong**. Please read our docs and introductions to OAuth2.

**Comment by jasper22** [comment]
completely wrong ??? It based on your examples....  Where I could read on 'How to use Hydra' ?? Could you provide a link ? Actual example could help

**Comment by aeneasr** [comment]
> completely wrong ??? It based on your examples....

Impossible, we never use AJAX to access `/oauth2/auth`, that is not how you consume this endpoint and it is also not documented as such anywhere in the docs. Please point me to the specific section where you think that we're using AJAX to call that endpoint.

As we're stating in our docs, we do not give a full overview of how OAuth2 works, but we do provide several links to articles and videos where you can learn about OAuth2, here: https://www.ory.sh/docs/hydra/oauth2

**Comment by jasper22** [comment]
Hmmm... I'm not sure - what about: https://www.ory.sh/docs/hydra/login-consent-flow  ?? The very first step in first paragraph suggest (?) that client (Angular) should make a request to `/oauth2/auth` and then Hydra will redirect it with strange HTTP status to /login page...   here is another example (?) https://www.ory.sh/docs/hydra/sdk/api#get-an-login-request

**Comment by aeneasr** [comment]
No, that is not correct and we're not saying that there. There is no mentioning of an AJAX request. Please read the OAuth2 docs first. Without understanding the most basic OAuth2 interactions, you will have a very hard and frustrating time using this software. That is all I can help for now.
