### ISSUE TITLE
jwt signature verification failed

### ISSUE THREAD

**Issue by anshudutta** [ory/hydra#1698]
**Describe the bug**

I am using kong as my ingress controller and nokia/kong-oidc plugin as my oauth2 proxy
https://github.com/nokia/kong-oidc
The loging and consent flow works fine, but fails when the proxy requests `/oauth2/token`.
Error:
```
jwt signature verification failed: Decode secret is not a valid cert/public key: ASN1 lib: public key decode error: RSA lib: nested asn1 error: bad object header: too long
```
I believe this is because hydra doesn't return the jwt bearer token by default.

So I have set the `strategies` to return a valid jwt. But it still returns an "opaque" token

*Server logs*

From proxy
```
127.0.0.1 - - [20/Jan/2020:00:36:51 +0000] "GET /admin/hydra/public/.well-known/openid-configuration HTTP/1.1" 200 1457 "-" "lua-resty-http/0.14 (Lua) ngx_lua/10015"
127.0.0.1 - - [20/Jan/2020:00:36:51 +0000] "POST /admin/hydra/public/oauth2/token HTTP/1.1" 200 1524 "-" "lua-resty-http/0.14 (Lua) ngx_lua/10015"
127.0.0.1 - - [20/Jan/2020:00:36:51 +0000] "GET /admin/hydra/public/.well-known/jwks.json HTTP/1.1" 200 803 "-" "lua-resty-http/0.14 (Lua) ngx_lua/10015"
2020/01/20 00:36:51 [error] 40#0: *133913 [lua] openidc.lua:858: openidc_load_and_validate_jwt_id_token(): id_token 'RS256' signature verification failed, client: 127.0.0.1, server: kong, request: "GET /admin/grafana/?code=lv7BeURDaYAVZn8giuGF-V_cDTspPy41zEtO71KVFi4.jtK57jwYLH4fu2hCnVIEOy0yIs0A7DRLfUMEovxduxg&scope=openid&state=2a03de92014282032073e10c1c022f9a HTTP/2.0", host: "experiment.alkmi.app", referrer: "https://experiment.alkmi.app/mcp/encapto/consent?consent_challenge=5e539b493643427b9e7f6b13dbc7f00a"
127.0.0.1 - - [20/Jan/2020:00:36:51 +0000] "GET /admin/grafana/?code=lv7BeURDaYAVZn8giuGF-V_cDTspPy41zEtO71KVFi4.jtK57jwYLH4fu2hCnVIEOy0yIs0A7DRLfUMEovxduxg&scope=openid&state=2a03de92014282032073e10c1c022f9a HTTP/2.0" 500 172 "https://experiment.alkmi.app/mcp/encapto/consent?consent_challenge=5e539b493643427b9e7f6b13dbc7f00a" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

```
Hydra
```
time="2020-01-20T00:36:51Z" level=info msg="completed handling request" measure#hydra/admin: https://experiment.alkmi.app/admin/hydra/public.latency=13836097 method=PUT remote="10.24.3.120:53894" request="/oauth2/auth/requests/consent/accept?consent_challenge=5e539b493643427b9e7f6b13dbc7f00a" request_id=ee6a5c99-bde0-4013-93cf-b049a6f74417 status=200 text_status=OK took=13.836097ms
time="2020-01-20T00:36:51Z" level=info msg="started handling request" method=GET remote=127.0.0.1 request="/oauth2/auth?client_id=grafana&consent_verifier=101c02d233cb449fbab507cdc40a22be&nonce=bf1da331fede03de27dfa9be346d742b&redirect_uri=https%3A%2F%2Fexperiment.alkmi.app%2Fadmin%2Fgrafana%2F&response_type=code&scope=openid&state=2a03de92014282032073e10c1c022f9a" request_id=68c0a212-0aeb-46ae-aedb-07c92a16b66d
time="2020-01-20T00:36:51Z" level=info msg="completed handling request" measure#hydra/public: https://experiment.alkmi.app/admin/hydra/public.latency=36332843 method=GET remote=127.0.0.1 request="/oauth2/auth?client_id=grafana&consent_verifier=101c02d233cb449fbab507cdc40a22be&nonce=bf1da331fede03de27dfa9be346d742b&redirect_uri=https%3A%2F%2Fexperiment.alkmi.app%2Fadmin%2Fgrafana%2F&response_type=code&scope=openid&state=2a03de92014282032073e10c1c022f9a" request_id=68c0a212-0aeb-46ae-aedb-07c92a16b66d status=302 text_status=Found took=36.332843ms
time="2020-01-20T00:36:51Z" level=info msg="started handling request" method=GET remote=127.0.0.1 request=/.well-known/openid-configuration request_id=a010262c-1413-428c-935f-779c1c372ee8
time="2020-01-20T00:36:51Z" level=info msg="completed handling request" measure#hydra/public: https://experiment.alkmi.app/admin/hydra/public.latency=515995 method=GET remote=127.0.0.1 request=/.well-known/openid-configuration request_id=a010262c-1413-428c-935f-779c1c372ee8 status=200 text_status=OK took="515.995µs"
time="2020-01-20T00:36:51Z" level=info msg="started handling request" method=POST remote=127.0.0.1 request=/oauth2/token request_id=e4c9fac1-b074-46b0-9ea9-31f082dcd9ea
time="2020-01-20T00:36:51Z" level=info msg="completed handling request" measure#hydra/public: https://experiment.alkmi.app/admin/hydra/public.latency=173955941 method=POST remote=127.0.0.1 request=/oauth2/token request_id=e4c9fac1-b074-46b0-9ea9-31f082dcd9ea status=200 text_status=OK took=173.955941ms
time="2020-01-20T00:36:51Z" level=info msg="started handling request" method=GET remote=127.0.0.1 request=/.well-known/jwks.json request_id=de7ab2a2-d3b1-40e9-a24c-6b39bb401a35
time="2020-01-20T00:36:51Z" level=info msg="completed handling request" measure#hydra/public: https://experiment.alkmi.app/admin/hydra/public.latency=9218501 method=GET remote=127.0.0.1 request=/.well-known/jwks.json request_id=de7ab2a2-d3b1-40e9-a24c-6b39bb401a35 status=200 text_status=OK took=9.218501ms

```
Note: From the above logs the code that is returned `lv7BeURDaYAVZn8giuGF-V_cDTspPy41zEtO71KVFi4.jtK57jwYLH4fu2hCnVIEOy0yIs0A7DRLfUMEovxdux`. Doesn't look like a valid jwt. Its missing the signature

*Server configuration*
```
config:
        oidc:
          subject_identifiers:
            enabled:
              - public
        urls:
          self:
            issuer: "https://${var.sub_domain}.${var.parent_domain}/admin/hydra/public"
            public: "https://${var.sub_domain}.${var.parent_domain}/admin/hydra/public"
          login: "https://${var.sub_domain}.${var.parent_domain}/mcp/encapto/sp-login"
          consent: "https://${var.sub_domain}.${var.parent_domain}/mcp/encapto/consent"
          error: "https://${var.sub_domain}.${var.parent_domain}/mcp/error/500"
        strategies:
          access_token: jwt
```

**Expected behavior**

Return jwt when `strategies.access_token` is set to `jwt`

**Environment**

* Version: v1.0.0

**Comment by anshudutta** [comment]
Also, I cannot introspect the code that is returned. I get `active: false`

**Comment by aeneasr** [comment]
Our JWT startegy only issues JWT tokens for access tokens (which is why the config key is `strategies.access_token`). This does not apply to authorize codes or refresh tokens as there is absolutely no need and use case to have those in JWT format. I believe that's the root cause of your issue.

**Comment by aeneasr** [comment]
> Also, I cannot introspect the code that is returned. I get active: false

You can not introspect authorization codes. They are not access tokens.

**Comment by anshudutta** [comment]
So you mean the proxy is trying to validate jwt signature by using authorisation vcode and not access token?

**Comment by aeneasr** [comment]
Yes, the proxy is trying to validate the authorization code which it should not do, because that's the business of the OAuth2 Server only.

**Comment by anshudutta** [comment]
How do I see the access token getting generated? I couldn't find it in logs or database.

**Comment by aeneasr** [comment]
The access token is being generated when you exchange the Authorization Code at `/oauth2/token` which apparently doesn't happen because the proxy is trying to validate it first. For more info on OAuth2, please read our docs: https://www.ory.sh/docs/hydra/oauth2

**Comment by anshudutta** [comment]
Interesting. If you see the logs that I have posted, the proxy does make a post request `/oaith2/token`.

**Comment by aeneasr** [comment]
Without additional info on why the proxy is failing (show the access token for example) it will be impossible to help. It does appear however that there is a request to `/oauth2/token`. The `jwks.json` request also seems to be correct.

**Comment by anshudutta** [comment]
How can I retrieve the access token from the auth code. Is there a cli command?

**Comment by anshudutta** [comment]
Also, I don't quite understand how the flag `strategies.access_token` is working? 
1. The proxy is making a request `/oauth2/token`
2. Hydra is returning the access token which is opaque
3. The proxy is then trying to validate the token assuming it is jwt and throwing validation error trying to validate the jet
So clearly setting the flag `strategies.access_token` should have returned hey instead of opaque token

**Comment by aeneasr** [comment]
Here's how to set up the OAuth2 access token strategy: https://www.ory.sh/docs/hydra/advanced#json-web-tokens

You can perform an OAuth2 flow using the CLI with `hydra token client` or `hydra troken user` as we do in the docs: 
https://www.ory.sh/docs/hydra/5min-tutorial

Keep in mind that you need to **restart** ORY Hydra when you apply config changes. We do not yet support hot reloading of config

**Comment by anshudutta** [comment]
Thanks
