### ISSUE TITLE
How to connect my own data to the hydra system

### ISSUE THREAD

**Issue by Txiaozhe** [ory/hydra#1711]
Please use issues only to file potential bugs or request features. For everything else please go to
the [ORY Community](https://community.ory.sh/) or join the [ORY Chat](https://www.ory.sh/chat).

**Comment by aeneasr** [comment]
Please use the issue template. Your issue description is just some standard text and does not describe what you want to resolve.

Please start by reading the documentation: https://ory.sh/docs
