### ISSUE TITLE
Multiple audience setting does'nt work by statndard golang library "clientcredentials"

### ISSUE THREAD

**Issue by SmotrovaLilit** [ory/hydra#1724]
**Describe the bug**

When i create token with few audiences by client credentials flow using statndard golang library "clientcredentials", hydra creates token with only first audience. 

**Reproducing the bug**

1. Run hydra 
```bash
git clone https://github.com/ory/hydra.git

cd hydra

docker-compose -f quickstart.yml \
    -f quickstart-postgres.yml \
    -f quickstart-tracing.yml \
    up --build
```
2. Create client with two audience ad1, ad2
```bash
docker-compose -f quickstart.yml exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445/ \
    --id my-client-new2 \
    --secret secret \
    --audience "ad1" \
    --audience "ad2" \
    -g client_credentials
```
3. Create token with two audiences 
 https://play.golang.org/p/3LM85U_xeyh

Or by curl:
```bash
curl -u "my-client-new2:secret" -X POST http://127.0.0.1:4444/oauth2/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'audience=ad1&audience=ad2&grant_type=client_credentials'
```
4. Introspect token
```bash
curl -X POST http://127.0.0.1:4445/oauth2/introspect \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'token=token from previous response'
```
5. Hydra returned response with only first audience 
```json
{"active":true,"scope":"openid offline","client_id":"my-client-new2","sub":"my-client-new2","exp":1581954213,"iat":1581950613,"**aud**":["ad1"],"iss":"http://127.0.0.1:4444/","token_type":"access_token"}
```

**Expected behavior**

Introspect returned one audience instead two: ["ad1", "ad2"]

**Environment**

* Version:  https://github.com/ory/hydra/commit/2f9f103bf867b1ba3f1ef978c6dc0f4a083f8107
* Environment: Docker

**Additional context**

Hydra expects that audiences will be send in one string splited by space. https://github.com/ory/fosite/blob/master/access_request_handler.go#L75 

Golang library sends audience in multiple field, not one string.  https://godoc.org/golang.org/x/oauth2/clientcredentials

**Comment by aeneasr** [comment]
```
docker-compose -f quickstart.yml exec hydra \
    hydra clients create \
    --endpoint http://127.0.0.1:4445/ \
    --id my-client-new2 \
    --secret secret \
    --audience "ad1,ad2" \
    -g client_credentials
```

:)

**Comment by aeneasr** [comment]
And curl:

```
audience=ad1,ad2
```

**Comment by SmotrovaLilit** [comment]
> ```
> docker-compose -f quickstart.yml exec hydra \
>     hydra clients create \
>     --endpoint http://127.0.0.1:4445/ \
>     --id my-client-new2 \
>     --secret secret \
>     --audience "ad1,ad2" \
>     -g client_credentials
> ```
> 
> :)

It is same that i did.  This command creates client with audiences ad1 ,ad2 such as
```
...
 --audience "ad1" \
 --audience "ad2" \
....
```

**Comment by SmotrovaLilit** [comment]
> And curl:
> 
> ```
> audience=ad1,ad2
> ```

Do you mean this:
```
curl -u "my-client-new2:secret" -X POST http://127.0.0.1:4444/oauth2/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'audience=ad1 ad2&grant_type=client_credentials'
```
?

This example works  but i can't use it. 

Because i use https://godoc.org/golang.org/x/oauth2/clientcredentials and this library makes request:
```
curl -u "my-client-new2:secret" -X POST http://127.0.0.1:4444/oauth2/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'audience=ad1&audience=ad2&grant_type=client_credentials'
```

**Comment by aeneasr** [comment]
Oh my bad, I should have read the issue description with more care. I think this is a problem with the way you're using `url.Values`. It should be:

```
		EndpointParams: url.Values{"audience": []string{
			"ad1 ad2",
		}},
```

Golang's http libarary tends to ignore any additional keys in `url.Values`, e.g. when using `r.URL.Query().Get("foo")`:

https://play.golang.org/p/0sgSPEwh7rO

**Comment by SmotrovaLilit** [comment]
Ok, thanks!
