### ISSUE TITLE
Error after upgrading caused by new handled_at column

### ISSUE THREAD

**Issue by mattfawcett** [ory/hydra#1725]
I believe https://github.com/ory/hydra/pull/1689 introduces a bug when upgrading an existing installation. When upgrading, any existing data in the table `hydra_oauth2_consent_request_handled` from before the upgrade will have the default value of `handled_at` as null.

This causes the following error for me after upgrading to the latest version when trying to go authenticate: `error msg="An error occurred" error="sql: Scan error on column index 11, name \"handled_at\": unsupported Scan, storing driver.Value type <nil> into type *time.Time` - even in a completely clean incognito window.

If I manually update all rows in that table to add a fake `handled_at` date then the error goes away.

I have tried running the tracer and I think the error is triggered in [FindGrantedAndRememberedConsentRequests](https://github.com/ory/hydra/blob/46cf8ebf3e324220a51d3667bc971c714d52a8f6/consent/manager_sql.go#L447) which attempts to load handled consent sessions for a given subject and client to see if the user has consented with that client before.

**Reproducing the bug**

1. Run an older version of hydra - I was on `v1.1.0`
2. Authenticate/consent as a user to a particular oauth client
3. Upgrade to latest hydra `v1.3.1` running the database migrations
4. In a completely clean browser with no existing cookies - attempt to login by the same user as above using the same oauth client. Error will occur

**Comment by aeneasr** [comment]
Fix incoming

**Comment by aeneasr** [comment]
Would you be possible to confirm if https://github.com/ory/hydra/pull/1726 fixes your issue? I was not able to write a test quickly because the test cases are a bit exotic for that method...

**Comment by aeneasr** [comment]
Released a fix as 1.3.2

**Comment by aeneasr** [comment]
Added a failing test case so this won't happen in the future :)

**Comment by mattfawcett** [comment]
Thanks, can confirm the fix works :)

**Comment by aeneasr** [comment]
awesome! thank you for reporting back :)
