### ISSUE TITLE
Add endpoint to Admin API to revoke access tokens

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1728]
**Is your feature request related to a problem? Please describe.**

It's currently not possible to revoke access tokens from `client_credentials` grants. This has been requested and I think it is a good idea to allow deletion of tokens based on the client_id. This makes sense if you lose trust in a client, for example, or if the secret changes.

**Describe the solution you'd like**

Similar to [this API endpoint](https://www.ory.sh/docs/hydra/sdk/api#revokes-consent-sessions-of-a-subject-for-a-specific-oauth-20-client) it should be possible to revoke tokens without a consent session attached as well. A good endpoint would be:

```
DELETE <hydra-admin>/oauth2/tokens?client_id=...
```

**Additional context**

https://community.ory.sh/t/disable-client-in-hydra-for-a-while-and-re-enable-it/1510/8

**Comment by lpedrosa** [comment]
This would be a pretty nice addition.

Would being able to revoke individual `client_credential` grants make sense as well? Or would that go against the use-case of this type of grant i.e. service-to-service authz?

I'm thinking about multiple instance of the same service holding different tokens.

**Comment by aeneasr** [comment]
> Would being able to revoke individual client_credential grants make sense as well? Or would that go against the use-case of this type of grant i.e. service-to-service authz?

I think it's quite difficult to track that from an admin perspective because there is no session identifier. Also, client_credential doesn't have refresh tokens so they expire after an hour.

**Comment by sagarshah1983** [comment]
Would this also result in deletion of access tokens created through authorization code workflow for the same client?
