### ISSUE TITLE
Validate configuration using JSON Schema and support config hot reloading

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1729]
**Is your feature request related to a problem? Please describe.**

Currently, ORY Hydra validates the configuration in a very crude way. We should fix that and support JSON Schema as we already do in Oathkeeper and Kratos.

To see how kratos does that (validation and reloading), check here: https://github.com/ory/kratos/blob/master/cmd/serve.go#L53

**Describe the solution you'd like**

Hydra already implements the architecture of kratos/oathkeeper that supports hot reloading of config values. Some config values (such as the server bind address) can not be reloaded and should thus cause an error (see how kratos/oathkeeper is handling that). We need to create a list of variables that can not be reloaded. I believe that the fosite's config doesn't support reloading at this time because many config values are read only once: https://github.com/ory/hydra/blob/74d8e3174c0adb33a263cb8d935d9c6c653fa81e/driver/registry_base.go#L247

**Comment by zepatrik** [comment]
`security.session.cookie.same_site`
