### ISSUE TITLE
Loopback interface redirection with arbitrary port

### ISSUE THREAD

**Issue by RazerM** [ory/hydra#1732]
**Describe the bug**

Hydra implements [OAuth 2.0 for Native Apps](https://tools.ietf.org/html/rfc8252) which states in section 7.3:

> The authorization server MUST allow any port to be specified at the time of the request for loopback IP redirect URIs, to accommodate clients that obtain an available ephemeral port from the operating system at the time of the request.

Unless I have missed some documentation, it doesn't seem possible with Hydra.

**Reproducing the bug**

Try to use an arbitrary port e.g. http://127.0.0.1:61023 without specifying it as a redirect URI when creating the client.

Hydra always gives the following error:

> The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.

I have tried it with and without PKCE.

**Expected behavior**

As is stated in the RFC.

**Environment**

* Version: v1.1.1

**Comment by aeneasr** [comment]
Nice find, let's fix this! Would you be up for a PR? This needs to be fixed in fosite I believe :)

**Comment by aeneasr** [comment]
Resolved on master
