### ISSUE TITLE
Token retrieval failed with error code 500

### ISSUE THREAD

**Issue by inigohu** [ory/hydra#1735]
**Describe the bug**

Sometimes, I get error code 500 when clients makes a request to the token endpoint

**Reproducing the bug**

1. Make API Request to with `https://mydomain/oauth2/token`
2. Request fails with response: `level=error msg="An error occurred" debug=": not_found" description="The authorization server encountered an unexpected condition that prevented it from fulfilling the request" error=server_error`

*Server logs*

```
Stack trace: 
github.com/ory/fosite/handler/oauth2.(*RefreshTokenGrantHandler).PopulateTokenEndpointResponse
    /go/pkg/mod/github.com/ory/fosite@v0.30.0/handler/oauth2/flow_refresh.go:145
github.com/ory/fosite.(*Fosite).NewAccessResponse
    /go/pkg/mod/github.com/ory/fosite@v0.30.0/access_response_writer.go:36
github.com/ory/hydra/oauth2.(*Handler).TokenHandler
    /go/src/github.com/ory/hydra/oauth2/handler.go:585
net/http.HandlerFunc.ServeHTTP
    /usr/local/go/src/net/http/server.go:2007
github.com/julienschmidt/httprouter.(*Router).Handler.func1
    /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/params_go17.go:26
github.com/julienschmidt/httprouter.(*Router).ServeHTTP
    /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334
github.com/urfave/negroni.Wrap.func1
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46
github.com/urfave/negroni.HandlerFunc.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
net/http.HandlerFunc.ServeHTTP
    /usr/local/go/src/net/http/server.go:2007
github.com/ory/hydra/x.RejectInsecureRequests.func1
    /go/src/github.com/ory/hydra/x/tls_termination.go:55
github.com/urfave/negroni.HandlerFunc.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29
github.com/urfave/negroni.middleware.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/x/metricsx.(*Service).ServeHTTP
    /go/pkg/mod/github.com/ory/x@v0.0.73/metricsx/middleware.go:261
github.com/urfave/negroni.middleware.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/ory/hydra/metrics/prometheus.(*MetricsManager).ServeHTTP
    /go/src/github.com/ory/hydra/metrics/prometheus/middleware.go:26
github.com/urfave/negroni.middleware.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP
    /go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136
github.com/urfave/negroni.middleware.ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38
github.com/urfave/negroni.(*Negroni).ServeHTTP
    /go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96
net/http.serverHandler.ServeHTTP
    /usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
    /usr/local/go/src/net/http/server.go:1890
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1357
```

*Server configuration*

```
    LOG_LEVEL: "debug",
    SERVE_PUBLIC_PORT: "8080",
    SERVE_ADMIN_PORT: "9000",
    URLS_SELF_ISSUER: accountUrl,
    URLS_LOGIN: signInUrl + "/login",
    URLS_LOGOUT: signInUrl + "/logout",
    URLS_CONSENT: signInUrl + "/consent",
    URLS_ERROR: signInUrl + "/error",
    URLS_POST_LOGOUT_REDIRECT: appUrl,
    OIDC_SUBJECT_IDENTIFIERS_ENABLED: "public,pairwise",
    TTL_LOGIN_CONSENT_REQUEST: "1h",
    TTL_ACCESS_TOKEN: "1h",
    TTL_REFRESH_TOKEN: "2160h",  // 90 days in hours
    TTL_ID_TOKEN: "1h",
    TTL_AUTH_TOKEN: "10m",
```

**Expected behavior**

I prefer to get a much more specific HTTP error code like 404 not found?

**Environment**

* Version: v1.0.9
* Environment: Docker in kubernetes

**Additional context**

We found this in the wild with an iOS integration by using [AppAuth](https://github.com/openid/AppAuth-iOS) library. Concretely it fails with this error: `Non-200 HTTP response (500) making token request to mydomain.com` [line](https://github.com/openid/AppAuth-iOS/blob/7e0b5c100d69caac34372efdad34b22b3464ddea/Source/OIDAuthorizationService.m#L492). 
We're also investigating with the integrator in order to clarify the root cause. Perhaps two concurrent token requests?

**Comment by aeneasr** [comment]
Thank you for the detailed report! 404 is not a valid OAuth2 response for that endpoint. I believe that later versions of Hydra correctly return 400 in this case. Most likely root cause is two requests using the same code/refresh token.

**Comment by aeneasr** [comment]
I checked, fosite pulls the refresh token twice from during refresh and only on the second call it returns ErrServerError on a not found issue. This heavily implies a double submit of refresh tokens on your end.

We should still return 400 instead of 500 when the error is not found (I think we return sqlcon.ErrNoRows or something like that)

Please keep the issue open so we don’t lose track of this :)

**Comment by aaslamin** [comment]
@aeneasr this issue is reproduced here https://github.com/ory/hydra/pull/1734/files#diff-8a4c55f53fc1d3a445cf9930b67cfafaR104

What's happening is two refresh requests come at the same time, but one finishes the transaction before the other one has had a chance to do the first read ([_to fetch the session_](https://github.com/ory/fosite/blob/387cade4c6e96e0b83df274da5835691e54d07af/handler/oauth2/flow_refresh.go#L140)). By the time the first request finishes, it removes the session from the DB (_as part of the transaction_) resulting in the `not_found` by the other request which then gets encapsulated as a server error.

**Comment by aaslamin** [comment]
@inigohu what DBMS are you using?

**Comment by inigohu** [comment]
> @inigohu what DBMS are you using?

CockroachDB

**Comment by chukyz** [comment]
Could be possible that this fix of error 500 (conccurrent trasnsactional) is not applied in version: v1.11.10? I have the same problem. Thanks!
