### ISSUE TITLE
Add support for a NoSql as persistence layer

### ISSUE THREAD

**Issue by alpha-verse** [ory/hydra#1740]
**Is your feature request related to a problem? Please describe.**
Hydra as of now uses Relational Stores as the persistance layer. This could be a bottleneck as the number of clients, with more number of users,  increase. Especially for authorization_code,  grant type
**Describe the solution you'd like**
I would want to be able to use NoSql as the persistence layer. For this if an interface is available for implementing different NoSql DBs as the persistence layer, it would be great. 
So that I can implement DynamoDB/MongoDB/Redis as the persistence store 
**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by aeneasr** [comment]
Hi, this has been discussed many times before and I always give the same answer: Security needs strong consistency.

We do not need a document store, but a relational model. That’s just how it is. We have people deploying Hydra that run literally millions of requests every day without one complaint about speed. You can always scale stores that speak SQL and, in fact, modern newSQL stores like Cassandra or CockroachDB allow you to take a step further.

I’m sorry but I will be closing this. A vague „noSQL scales better“ (which isn’t even true but depends on the use case) is not a good enough reason to throw out all the other concerns and requirements.

**Comment by kushagraThapar** [comment]
@aeneasr I am wondering if this is still true as of today. Do you still not provide a storage persistence layer to integrate with any database of our choice?
Given Ory/Hydra's popularity and use cases, we would like to support our customers using Cosmos DB to be able to integrate with Ory/Hydra organically.
If you want me to open a new issue, please let me know and we can discuss it in detail.

**Comment by kushagraThapar** [comment]
@aeneasr - FYI, created a new issue for discussing Azure Cosmos DB integration: https://github.com/ory/hydra/issues/3806
Feel free to let me know if you want me to provide Azure Cosmos DB details.
