### ISSUE TITLE
keys: Different uuid for imported keys

### ISSUE THREAD

**Issue by DennisPattmann5012** [ory/hydra#1741]
**Not sure if it's a bug!**

All keys generated by Hydra have the same UUID for private and public key. I imported a key-pair and the private and public key now have different UUIDs.

It this is the expected behavior feel free to close this issue. Otherwise I would like to open a PR.

**Reproducing the bug**

```bash
hydra keys import hydra.jwt.access-token ./priv.key ./pub.pub --endpoint XXXXXXXXX
hydra keys get hydra.jwt.access-token
```

**Comment by aeneasr** [comment]
I have to check, it's definitely a weird behavior. Did this cause any downstream bugs for you?

**Comment by DennisPattmann5012** [comment]
At the moment I can't see any misbehavior, however, Hydra doesn't use the imported key to sign tokens.

I think the ```JWKHandler ImportKeys``` method should generate the uuid only once. (Line 143/145)

**Comment by aeneasr** [comment]
I see - let's change that then - would you be up for that? :)

Regarding key rotation: https://www.ory.sh/docs/hydra/advanced#key-rotation

**Comment by DennisPattmann5012** [comment]
I will take care as soon as possible. :-)
