### ISSUE TITLE
The JWK api should be able to export .pem

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#175]
This could work like: `/keys/<set>/<key>?format=<pem|jwk>`

**Comment by waynerobinson** [comment]
Yeah, the Ruby world lacks tools to work with JWK. I had never even heard of the format until Hydra.

Literally the only library we were able to find is https://github.com/potatosalad/ruby-jose and it lacks users (it's only been downloaded about 5,200 times… nothing given how often gems end up being downloaded in the lifecycle of even a single product).

This has been fine for our purposes, which are basically to convert the JWKs into PEMs for use in OpenSSL and other libraries. It would be good if we could just get an efficient (hopefully cached) version of the PEM from Hydra itself as required. Especially if we assume we should always get the keys from Hydra for a future where key rotating or revocation may happen.

**Comment by arekkas** [comment]
Thanks for the insight, weird that there is no jwk in the ruby world.

Gesendet mit meinem HTC

----- Reply message -----
Von: "Wayne Robinson" <notifications@github.com>
An: "ory-am/hydra" <hydra@noreply.github.com>
Cc: "Aeneas" <aeneas@serlo.org>, "Assign" <assign@noreply.github.com>
Betreff: [ory-am/hydra] The JWK api should be able to export .pem (#175)
Datum: Mo., Sep. 12, 2016 08:27

Yeah, the Ruby world lacks tools to work with JWK. I had never even heard of the format until Hydra.

Literally the only library we were able to find is https://github.com/potatosalad/ruby-jose and it lacks users (it's only been downloaded about 5,200 times… nothing given how often gems end up being downloaded in the lifecycle of even a single product).

This has been fine for our purposes, which are basically to convert the JWKs into PEMs for use in OpenSSL and other libraries. It would be good if we could just get an efficient (hopefully cached) version of the PEM from Hydra itself as required. Especially if we assume we should always get the keys from Hydra for a future where key rotating or revocation may happen.

**Comment by arekkas** [comment]
There hasn't been any other request for this since Sep 2016. Also we're now able to import pem formatted keys. For validation of access tokens, all OpenID certified libraries support the `./well-known/jwks.json` pattern (part of the certification requirement). Closing.
