### ISSUE TITLE
Support Authentication Methods References in ID Token

### ISSUE THREAD

**Issue by bernard-wagner** [ory/hydra#1756]
**Is your feature request related to a problem? Please describe.**

Integrating with a client that is expecting amr values in the ID token.

**Describe the solution you'd like**

Similar to ACR in the OpenID, support AMR. 

**Additional context**

https://tools.ietf.org/html/rfc8176#section-6.1
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by aeneasr** [comment]
Sounds good, contributions welcomed!

**Comment by vinckr** [comment]
@tacurran  @bernard-wagner 
Is this resolved with the commit? Or is there still work needed?

**Comment by bernard-wagner** [comment]
Wow, this totally fell off my radar. I apologise for that. 

The fosite change is prerequisite, but the bulk of the work is still outstanding.

**Comment by synclpz** [comment]
Any news on this issue?
