### ISSUE TITLE
Introspection Response: `access_token` and `refresh_token` are not valid `token_type`

### ISSUE THREAD

**Issue by UkonnRa** [ory/hydra#1762]
As for [Introspection Spec](https://tools.ietf.org/html/rfc7662#section-2.2) and [Access Token Spec](https://tools.ietf.org/html/rfc6749#section-7.1), `bearer` and `mac` are the only valid Access Tokens. Some framework (like Vertx OAuth2) may consider all other `token_type` as invalid

https://github.com/vert-x3/vertx-auth/issues/376 is the related issue

**Comment by aeneasr** [comment]
Triaged as a bug, we should find a better key name for `token_type` to indicate whether the token is an access or a refresh token.

**Comment by UkonnRa** [comment]
I think `metadata.token_type` or `hydra_token_type` is good. BTW, why should I want to know whether the token is an access or a refresh token? There is nothing related in the spec.

**Comment by aeneasr** [comment]
> BTW, why should I want to know whether the token is an access or a refresh token? 

Because you might want to prevent people from using a refresh token as the access token, given that they usually don't expire.

**Comment by aeneasr** [comment]
I think `token_use` is an appropriate name:

- `token_use: access_token`
- `token_use: refresh_token`

**Comment by UkonnRa** [comment]
I think so, a good name!

**Comment by aeneasr** [comment]
I just realized that the request parameters have a token_type_hint parameter which can be access_token or refresh_token (see also RFC7009) but then return token_type in a completely different context (related to the HTTP auth mechanism). Classic OAuth2 ...

**Comment by ghenry** [comment]
Would token_type be Bearer or bearer?
