### ISSUE TITLE
Use transaction in VerifyAndInvalidateLoginRequest

### ISSUE THREAD

**Issue by arethusa** [ory/hydra#1773]
At consent/manager_sql.go@VerifyAndInvalidateLoginRequest

1. Get Challenge with Verify
2. Get Handled Request with Challenge
3. If Handled Request was used, reject
4. Update Handled Request was used

However, step 2 ~ 4 is not atomic and without lock

There maybe race condition for A & B get handled request is not used simultaneously.

If there cause a unexpected behavior or security issue?

**Comment by aeneasr** [comment]
Thank you for raising this. I don't believe that there are any security implications, but it would probably make sense to run this in a transaction instead of separate queries!

Would you be up for a PR? :)

**Comment by aeneasr** [comment]
This is now the case.
