### ISSUE TITLE
"target_audience" is not available for "oauth2_introspection" authenticator

### ISSUE THREAD

**Issue by ngrigoriev** [ory/hydra#1788]
**Is your feature request related to a problem? Please describe.**

"target_audience" that is available for JWT authenticator is not available for "oauth2_introspection" authenticator

**Describe the solution you'd like**

I think it would be nice for "oauth2_introspection" authenticator to be able to enforce the audience value, if available.

**Describe alternatives you've considered**

I do not see any except having to validate this separately in case of an opaque token...

**Comment by aeneasr** [comment]
Yeah, absolutely! Which version are you running?

**Comment by ngrigoriev** [comment]
Oh, my bad! I intended to open it in Oathkeeper project, not in Hydra. Please close this one. Also after more careful review it appears that it is just something missing from the docs. The code seems to be there. I'll reverify and make a small PR for the docs. Sorry for the mess!

**Comment by aeneasr** [comment]
No problem, thank you!
