### ISSUE TITLE
Respect XDG user directories

### ISSUE THREAD

**Issue by meMuszr** [ory/hydra#1793]
Read default config from `$XDG_CONFIG_HOME/hydra` instead of `$HOME`

**Comment by aeneasr** [comment]
You can override the config path using the `-c` flag.

**Comment by meMuszr** [comment]
Sure, this feature isn't about overriding config, just updating where default config sits. No breaking changes. Willing to submit PR if this is a matter of priority.

**Comment by aeneasr** [comment]
Ah yeah - sounds good :) I believe this should be handled in the ory/x package!

**Comment by aeneasr** [comment]
We no longer use the home approach, closing.
