### ISSUE TITLE
stat /.schema/config.schema.json: no such file or directory

### ISSUE THREAD

**Issue by ms42Q** [ory/hydra#1801]
**Describe the bug**
Since today my pipelines are failing because the pipeline runner which uses docker fails at starting hydra. I am using the `latest` tag. 

I assume this is caused by:
https://github.com/ory/hydra/commit/631cefd9023ee4702e082e0b1e4dac6187f42177

I am not modifying the container. I am only setting these env variables:

```
    # ENV vars hydra                                                                              
    URLS_LOGIN: "http://login:5000/login"                                                         
    URLS_LOGOUT: "http://login:5000/logout"                                                       
    URLS_CONSENT: "http://consent:5001/consent"                                                   
    URLS_SELF_ISSUER: "http://hydra:4444/"                                                        
    DSN: "memory"                                                                                 
    SECRETS_SYSTEM: "youReallyNeedToChangeThis"                                                       
```

**Reproducing the bug**

Set these variables and then execute:
```
docker run hydra:latest serve all --dangerous-force-http --dangerous-allow-insecure-redirect-urls http://localhost:3000/callback
```

_Server logs_

```
Starting service oryd/hydra:latest ...
Pulling docker image oryd/hydra:latest ...
Using docker image sha256:72101f950c4acffdbab1c6c19d176f814092be41fd86db81dc200a4e147856d2 for oryd/hydra:latest ...
*** WARNING: Service runner-XPrfB5Xo-project-9-concurrent-0-oryd__hydra-3 probably didn't start properly.
Health check error:
service "runner-XPrfB5Xo-project-9-concurrent-0-oryd__hydra-3" has no exposed ports
Service container logs:
2020-04-16T16:32:14.371078188Z Config file not found because "Config File ".hydra" Not Found in "[/]""
2020-04-16T16:32:14.371476111Z time="2020-04-16T16:32:14Z" level=fatal msg="Unable to open configuration JSON Schema." error="stat /.schema/config.schema.json: no such file or directory"

```

_Server configuration_

default configuration

**Expected behavior**

I expect the server not to crash

**Environment**

- Version: docker image sha256:72101f950c4acffdbab1c6c19d176f814092be41fd86db81dc200a4e147856d2  oryd/hydra:latest 

- Environment: Docker

**Comment by ms42Q** [comment]
I switched back to hydra:v1.4.2 which doesn't produce the error.

**Comment by benoror** [comment]
Seeing the very same error today as I am trying Hydra for first time 😅 

@ms42Q glad you reported it!

**Comment by aeneasr** [comment]
Yup looks like a packer binary task is missing in the build process. Fixing

**Comment by benoror** [comment]
That was fast, thank you guys!

**Comment by aeneasr** [comment]
Released as 1.4.5

**Comment by benoror** [comment]
looks like docker-compose yaml is pointing to non-existing `1.4.4`: https://github.com/ory/hydra/blob/master/quickstart.yml#L18

**Comment by aeneasr** [comment]
Yeah, looks like the CI task failed there :) Fixing manually...

**Comment by benoror** [comment]
@aeneasr thanks x2 :)
