### ISSUE TITLE
Hydra login/consent flow - not redirecting to http://consent-service/consent?consent_challenge=4567...

### ISSUE THREAD

**Issue by dhanyak-btc** [ory/hydra#1812]
I'm developing a nodejs application for login/consent flow using Hydra v1.4.2. 
I'm able to complete step #3 in https://www.ory.sh/hydra/docs/oauth2/#authenticating-users-and-requesting-consent. Hydra is not redirecting to a URL mentioned in step #4

Sequence of API calls:

1. GET https://35.194.72.53:9000/oauth2/auth?scope=offline_access&response_type=code&client_id=test&state=o1kh6qg4024&redirect_uri=http://localhost:3000/login
2. GET http://localhost:3000/login?login_challenge=00f4ac944f0b44f49e08aed581e71b7d
3. PUT https://35.194.72.53:9001/oauth2/auth/requests/login/accept?login_challenge=f19aa722927f4ded8f9c6743b5e7d1f6

PUT method returns below redirect_to URL 
https://35.194.72.53:9000/oauth2/auth?client_id=test&login_verifier=83eb38b0ab0c4c418f8d5ed583ca954c&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin&response_type=code&scope=offline_access&state=o1kh6qg4024

Redirecting to above URL using node-fetch causes
'http://localhost:3000/login?error=request_forbidden&error_debug=CSRF+session+cookie+could+not+be+decoded&error_description=The+request+is+not+allowed&error_hint=You+are+not+allowed+to+perform+this+action.&state=o1kh6qg4024',

Redirecting to above URL from browser causes
GET /login?error=invalid_request&error_debug=Authentication+verifier+has+been+used+already&error_description=The+request+is+missing+a+required+parameter%2C+includes+an+invalid+parameter+value%2C+includes+a+parameter+more+than+once%2C+or+is+otherwise+malformed&error_hint=Make+sure+that+the+various+parameters+are+correct%2C+be+aware+of+case+sensitivity+and+trim+your+parameters.+Make+sure+that+the+client+you+are+using+has+exactly+whitelisted+the+redirect_uri+you+specified.&state=o1kh6qg4024

node-fetch Code Snippet to redirect:

    fetch(redirectToUrl, {
      method: 'GET',
      //redirect: 'manual',
      headers: { 'cookie': 'oauth2_authentication_csrf=' + csrf1 + ';oauth2_authentication_session=' + csrf2 + ';SID=' + session_id + ';csrf=' + csrf1  }
    }).then(response => {
        console.log("new redirectTo: " + response.url);
        console.log(response.headers.raw()['set-cookie']);
        console.log(response);
        const parsedUrl = url.parse(response.url);
        const qsParams = querystring.parse(parsedUrl.query);
        let login_verifier = qsParams.login_verifier;
        console.log("login_verifier=" + login_verifier);
        res.cookie('oauth2_authentication_csrf', csrf1, { signed: false });
        res.cookie('oauth2_authentication_session', csrf2, { signed: false });
        res.cookie('SID', session_id, { signed: false });
        res.cookie('csrf', csrf1, { signed: false });
        res.redirect(response.url);
        // res.render('login', { 'loginChallenge': loggin_challenge });
      })
      .catch(err => {
        console.log(err);
      });

**Comment by aeneasr** [comment]
I will be answering this over here: https://community.ory.sh/t/hydra-login-consent-flow-not-redirecting-to-http-consent-service-consent-consent-challenge-4567/1659
