### ISSUE TITLE
Hydra OIDC server does not support PS256 algorithm for client_assertion

### ISSUE THREAD

**Issue by mkkarthik** [ory/hydra#1817]
I have used Hydra Server v1.4.5. I am running the Hydra server with default configuration. .hydra.yml is blank. When I invoke the token end point, i am using client_assertion_type and client_assertion. I have passed the client_assertion JWT with algorithm PS256. But the token end point giving the error stating the algorithm has to be RS256. Then I changed the JWT with RS256 algorithm and it is working fine.

After discussing in ory hydra community forum it appears that while the code supports PS256 and others, the client definition currently hardcodes the RS256 requirement. 

Please fix this issue.

thanks,
Karthik

**Comment by aeneasr** [comment]
So ory/fosite supports PS256 for client authentication but we are currently not allowing clients to define the algorithm themselves and just return RS256 always:

https://github.com/ory/hydra/blob/master/client/client.go#L262

I don't quite remember why that was the case but it could have been to save some time during implementation.

**Comment by mkkarthik** [comment]
Thanks for your response. Can you please make it as a configuration so that I can configure to use PS256 when adding the client?

**Comment by aeneasr** [comment]
Sure, you can also create a PR!

**Comment by mkkarthik** [comment]
Sorry I did not understand. What's PR stands for? is that 'purchase request' like commercial version of hydra? Please provide details.

**Comment by aeneasr** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests

**Comment by mkkarthik** [comment]
Thanks that clarifies. As of now I don't have the skill set to fix this issue.

**Comment by ka3de** [comment]
Hi, I was thinking on working on this if I'm allowed.

I have a couple of doubts thought.

Regarding docs: Modifications will include a new parameter `token_endpoint_auth_signing_alg` for the **Create an OAuth2 client** request body, but, what should be the approach here? Do I modify the docs `api.md` file directly? Or should I create a new version?

Also, regarding DB migration files for client. Is there any required action other than creating the corresponding `.sql` file for the postgres, mysql and cockroach folders?

Thanks.

**Comment by aeneasr** [comment]
Hi there, we just released https://github.com/ory/fosite/releases/tag/v0.32.0 which supports ECDSA. Contributions welcomed!

> Regarding docs: Modifications will include a new parameter token_endpoint_auth_signing_alg for the Create an OAuth2 client request body, but, what should be the approach here? Do I modify the docs api.md file directly? Or should I create a new version?

Swagger is all auto-generated. If you add the field to the client model, it will magically appear there :)
