### ISSUE TITLE
Hydra v1.4.2 Unable to load HTTPS TLS Certificate: error="tls configuration is invalid"

### ISSUE THREAD

**Issue by dhanyak-btc** [ory/hydra#1821]
I used below commands to create a private key and cert file:
openssl genrsa -out key.pem 2048
openssl req -new -x509 -sha256 -key key.pem -out hydra.crt -days 365

I copied the key.pem file contents and encoded the text using https://www.base64encode.org/ for SERVE_TLS_CERT_BASE64 value.

Docker run command throws this error:
level=fatal msg="Unable to load HTTPS TLS Certificate" error="tls configuration is invalid"

Docker run command:

docker run -d \
    --name ory-hydra-example--hydra \
    --network hydraguide \
    --hostname "hydra-dev-instance" \
    -h --skip-tls-verify \
    -p 9000:4444 \
    -p 9001:4445 \
    -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
    -e DSN=$DSN \
    -e OAUTH2_EXPOSE_INTERNAL_ERRORS=true \
    -e URLS_SELF_ISSUER=https://34.195.73.55:9000/ \
    -e URLS_CONSENT=http://localhost:3000/consent \
    -e URLS_LOGIN=http://localhost:3000/login \
    -e SERVE_PUBLIC_CORS_ENABLED=true \
    -e SERVE_PUBLIC_CORS_ALLOWED_ORIGINS="*" \
    -e SERVE_PUBLIC_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE" \
    -e SERVE_ADMIN_CORS_ENABLED=true \
    -e SERVE_ADMIN_CORS_ALLOWED_ORIGINS="*" \
    -e SERVE_ADMIN_CORS_ALLOWED_HEADERS="Accept, Content-Type" \
    -e SERVE_ADMIN_CORS_EXPOSED_HEADERS="Accept, Content-Type" \
    -e SERVE_PUBLIC_CORS_ALLOWED_HEADERS="Accept, Content-Type" \
    -e SERVE_PUBLIC_CORS_EXPOSED_HEADERS="Accept, Content-Type" \
    -e SERVE_ADMIN_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE" \
	-e LOG_LEVEL=debug \
    -e SERVE_TLS_KEY_PATH="/home/username/ssl_hydra/hydra.crt" \
    -e SERVE_TLS_CERT_BASE64="encoded key file contents" \
    oryd/hydra:v1.4.2 serve all

Please let me know why this error is coming.

**Comment by aeneasr** [comment]
Please use 1.4.6
