### ISSUE TITLE
Hydra v1.4.6 Unable to load HTTPS TLS Certificate: error="tls configuration is invalid"

### ISSUE THREAD

**Issue by dhanyak-btc** [ory/hydra#1822]
I used below commands to create a private key and cert file:
openssl genrsa -out key.pem 2048
openssl req -new -x509 -sha256 -key key.pem -out hydra.crt -days 365

I copied the key.pem file contents and encoded the text using https://www.base64encode.org/ for SERVE_TLS_CERT_BASE64 value.

Docker run command throws this error:
level=fatal msg="Unable to load HTTPS TLS Certificate" error="tls configuration is invalid"

Docker run command:

$docker run -d
--name ory-hydra-example--hydra
--network hydraguide
--hostname "hydra-dev-instance"
-h --skip-tls-verify
-p 9000:4444
-p 9001:4445
-e SECRETS_SYSTEM=$SECRETS_SYSTEM
-e DSN=$DSN
-e OAUTH2_EXPOSE_INTERNAL_ERRORS=true
-e URLS_SELF_ISSUER=https://34.195.73.55:9000/
-e URLS_CONSENT=http://localhost:3000/consent
-e URLS_LOGIN=http://localhost:3000/login
-e SERVE_PUBLIC_CORS_ENABLED=true
-e SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=""
-e SERVE_PUBLIC_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE"
-e SERVE_ADMIN_CORS_ENABLED=true
-e SERVE_ADMIN_CORS_ALLOWED_ORIGINS=""
-e SERVE_ADMIN_CORS_ALLOWED_HEADERS="Accept, Content-Type"
-e SERVE_ADMIN_CORS_EXPOSED_HEADERS="Accept, Content-Type"
-e SERVE_PUBLIC_CORS_ALLOWED_HEADERS="Accept, Content-Type"
-e SERVE_PUBLIC_CORS_EXPOSED_HEADERS="Accept, Content-Type"
-e SERVE_ADMIN_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE"
-e LOG_LEVEL=debug
-e SERVE_TLS_KEY_PATH="/home/username/ssl_hydra/hydra.crt"
-e SERVE_TLS_CERT_BASE64="encoded key file contents"
oryd/hydra:v1.4.6 serve all

$ docker logs ory-hydra-example--hydra
time="2020-04-24T09:43:58Z" level=fatal msg="Unable to load HTTPS TLS Certificate" error="tls configuration is invalid"

Please let me know why this error is coming.

**Comment by aeneasr** [comment]
```
-e SERVE_TLS_KEY_PATH="/home/username/ssl_hydra/hydra.crt"
```

Unless you mounted the file under that directory, the path is invalid because it does not exist in the docker container.

**Comment by dhanyak-btc** [comment]
Please share the command to mount the file/directory and also update the document. It'll help developers who are new to docker and hydra. I added below line to docker run command, I still get same error.

	-v /home/dhanyak/ssl_hydra:/home/dhanyak/ssl_hydra \

**Comment by aeneasr** [comment]
Which document should be updated?

If it still does not work, please provide the full context. The full command, the full log, the contents of the directories that you mount, and so on. Otherwise we will spend so much time going back and forth. For example, your previous command uses `-e SERVE_TLS_KEY_PATH="/home/username/ssl_hydra/hydra.crt"` and you mount under `-v /home/dhanyak/ssl_hydra:/home/dhanyak/ssl_hydra`. So that can't work.

**Comment by dhanyak-btc** [comment]
I tried below options, I still get the error. username is just a placeholder. Please add a step to configure SSL in https://www.ory.sh/hydra/docs/configure-deploy


        -v /home/username/ssl_hydra:/home/username/ssl_hydra \
	--mount src="/home/username/ssl_hydra",target=/home/username/ssl_hydra,type=bind \

**Comment by aeneasr** [comment]
As I said before, please provide all the commands you are running, step by step. Otherwise I will not be able to help.

**Comment by dhanyak-btc** [comment]
Below docker run command causing the error.
time="2020-04-24T10:06:25Z" level=fatal msg="Unable to load HTTPS TLS Certificate" error="tls configuration is invalid"

// run the server
docker run -d \
    --name ory-hydra-example--hydra \
    --network hydraguide \
    --hostname "hydra-dev-instance" \
	--mount src="/home/dhanyak/ssl_hydra",target=/home/dhanyak/ssl_hydra,type=bind \
    -h --skip-tls-verify \
    -p 9000:4444 \
    -p 9001:4445 \
    -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
    -e DSN=$DSN \
	-e OAUTH2_EXPOSE_INTERNAL_ERRORS=true \
    -e URLS_SELF_ISSUER=https://34.195.73.55:9000/ \
    -e URLS_CONSENT=http://localhost:3000/consent \
    -e URLS_LOGIN=http://localhost:3000/login \
    -e SERVE_PUBLIC_CORS_ENABLED=true \
    -e SERVE_PUBLIC_CORS_ALLOWED_ORIGINS="*" \
    -e SERVE_PUBLIC_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE" \
    -e SERVE_ADMIN_CORS_ENABLED=true \
    -e SERVE_ADMIN_CORS_ALLOWED_ORIGINS="*" \
    -e SERVE_ADMIN_CORS_ALLOWED_HEADERS="Accept, Content-Type" \
    -e SERVE_ADMIN_CORS_EXPOSED_HEADERS="Accept, Content-Type" \
    -e SERVE_PUBLIC_CORS_ALLOWED_HEADERS="Accept, Content-Type" \
    -e SERVE_PUBLIC_CORS_EXPOSED_HEADERS="Accept, Content-Type" \
    -e SERVE_ADMIN_CORS_ALLOWED_METHODS="POST,GET,PUT,DELETE" \
	-e LOG_LEVEL=debug \
    -e SERVE_TLS_KEY_PATH="/home/dhanyak/ssl_hydra/hydra.crt" \
    -e SERVE_TLS_CERT_BASE64="LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdUErVXJRNlJpbFpJcUgxM2tZUnJQYXVSTFFEaXg1TFpETFBMaW1JV1FDZVA5ZEpUCnRydWI5N05zcWtXbE4xVFVJbVhWK2VXM1A3akFSSk9qZFhOWnMxN2J1Rm1zVjBEQXRqbjZzbWpCcHQ2TDVTZUwKVXB3UUFDMndEd2RObmdWQlkzMTZhMGZhVkIzeFpqVWh4N3oyV3ltdU5nUlk3ZXR1NStQZG02ZUdhdWkxMkhNYQpRZU1yci9WMG9mL0ZRakdaUmljOU1PUEdtWU4xaUhlR2RuWVNJbHFwN0lIZ0NhK0VTb2RpUHJpNFZ4K0tXU2g5CkR4K1Z1R1F3TjBTWlJWalRaZ2s3OVVqNER0N1ZVak02NTVyb3JzeitCWWcyV2xPTnRzdzVsKyt3STJ1Q01CVTMKTzRxOExLaXRoZkF1dVAwMEUvZU5BSTBYYkFhdjI2b0Y2RG4xY1FJREFRQUJBb0lCQUNVZFJ5NktOSUMvbTFFVwpVNmp0R2E3S3pMQlZjR1VyMEVhR2JyR055OHpON1hKMUlkcEVCRlF6UXVNbXZnVGxQdzFjbVlRVmRSa05TUC9MCkFYZnFkWmo4dExOOHFZckNqTmx4NFlKZUswWlpzNzNXZG5xRzY1Y05uMlc0WkVkTDZmNkV5ODJjSklNM3NuaVkKbUNJdGtVT2FxUDFOYlIwMGp4MkZUaWRYNVh2aTd3ajRpV2RSbld4aHBoZzlBeURIeEt1ODZMSVFtZUlqZlpacQp3Q2tSZjcwSWc4N2NyeWtIcmNyTnorVUhQOGd1RlZ1d3B0Z2Y1SU81SVgzN2wyaEFnTTFqbW5Tei9ZUk9LVHpJCi9ZZDdGRlFWMVNYM2tsYjZQZ1I4dGpTazhXY041dEMxTEdONWFXZElwTGFJRVE3S1doSUFESTBhUHpNNGtQOVgKdHRPU2lOMENnWUVBNjcycmhVemVvalI4MDM0UGZaMSt6NE5uQ21FNCsybUtyRkpjNTZiZFRGMjdENFlGV0g3TQpZZTZwcmxNMXNYZ0xFUUcyOThWY3ZoQS9aS1hiMmQ1M0lVWWRQVFBuOFJBWWpOYS9QK1NaLyt2dHFHa1hFWGQ3CkpXT1psYStTcENzUXhvS2hlQWxNRGRkd0RKUmNtZ0dzaHZwbmRqN2xHMDhJTDhjTlRXTnhOdmNDZ1lFQXgrRHgKZnRaUUY3RVNhZmlvM2lyUDd5T0ZqUitsNmJqN2NmczU1Uk9QWVlJT2ZiajdZRnZSQzFYdEw5TnVBeER5SitnSgpDWnBMbUlmNVRSRXZUV2F3akZVSUpVTEdXNHhGK093N1k1ZDFUS2kzbVJ0VllNL3RWRXkycFlJMllTWUhESVl2CmVuTyt4VUY2OVU0VTZuV0FNcjF0ZXQ0ZUVmbWdJcXU4K01VU2xOY0NnWUVBNlY3VW81dWJjbHdmam9ibTh1V3QKR2VUdFpwc2tlODdabHduYUt3Rkhaa2dMM0t4Q01uOGorWGI0eHpoY21SbExhMFNWU3VjNGpuY3JLb24vQU1sNAppWm9OYS84c2g3bjFjOGRMZ1FiZlpUaThCdEl5SWZwMEVHbHZLMzJwMzVjNmZpbm5peHM1RFNMUEs4VGJmeUpWCkZ6SmdwZkJSZ2gxVTcyZFFSZUpCdTdVQ2dZRUFrbzdYeEg3MFgwclJDNjd1YzJqRTZyNExFUDFodEV5VTRuQ3AKZE5Td3ozaURrNS90Z2l3UXpkVUZnNG51SW9Wc2FlSnpyZnphN1U3V2Q3SGdFMHIyclE4MFY4M3NqL2Y4M3Bhbwp2VSt6RExDeFhxeHlIL2lXTnJmQlBQNkxUUlNMR3AzUmRtSWtRWkxQeThxaS8zK0VycS9DOU5LbERkMFJsQnFGCkI0dkpJaVVDZ1lFQXc2MmhsNDIwSlgwcGtISnB4VVFPUUhwc2VPVWlZR0grUm1KRzRtVTJ0cDM3QjdYY1FQVXkKdnZpZGNtaTk2S240YXBOeVFyRUg2bXV3MjdyQVhDc0hKaENuei9aSUoyZ21FeXVTMzJ3UndpeEovNnhmZUZqcgpHYXZ2NEU1aEVNMHpnUmk3NE9lQ2ZjRFQxTURoZVdyZ2lGZTB3RHc3TFJmZldlVWZTd3F0S2RRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==" \
    oryd/hydra:v1.4.6 serve all

**Comment by aeneasr** [comment]
```
-e SERVE_TLS_KEY_PATH="/home/dhanyak/ssl_hydra/hydra.crt" 
```

crt is the certificate, you need the `key.pem` file here. I believe this would be correct:

```
-e SERVE_TLS_KEY_PATH="/home/dhanyak/ssl_hydra/key.pem" 
-e SERVE_TLS_CERT_PATH="/home/dhanyak/ssl_hydra/hydra.crt"
```

**Comment by dhanyak-btc** [comment]
Thanks @aeneasr for quick solution. Kindly add SERVE_TLS_KEY_PATH and SERVE_TLS_CERT_PATH to https://www.ory.sh/hydra/docs/reference/configuration/

**Comment by aeneasr** [comment]
I've added this to the docs!
