### ISSUE TITLE
Move to go-jose key generation

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#1825]
**Is your feature request related to a problem? Please describe.**

See https://github.com/square/go-jose/pull/300

**Comment by harsimranmaan** [comment]
This needs to wait for go-jose v3 release or the util patch backport to v2 branch.

**Comment by anderslauri** [comment]
🤔 

Is `go-jose` worth relying on? The activitiy seems relatively limited. There is a community fork available [here](https://github.com/golang-jwt/jwt) - might be worth considering?

**Comment by aeneasr** [comment]
You're probably viewing the master branch, which is not the correct one. This one is: https://github.com/square/go-jose/tree/v2

**Comment by anderslauri** [comment]
> 
> 
> You're probably viewing the master branch, which is not the correct one. This one is: https://github.com/square/go-jose/tree/v2

No, I meant `v2` - looks like it's only being updated whenever a security issue arise. Never the less this might be perfectly sufficent.

**Comment by aeneasr** [comment]
That's pretty good - go-jwt has had several CVEs over the past two years and it has already gone through multiple community forks:

* https://github.com/dgrijalva/jwt-go
* https://github.com/form3tech-oss/jwt-go

**Comment by aeneasr** [comment]
done
