### ISSUE TITLE
Set `strategies.access_token` in config.yaml gives an error during startup

### ISSUE THREAD

**Issue by kevinjqiu** [ory/hydra#1837]
**Describe the bug**

According to the [sample config](https://github.com/ory/hydra/blob/master/internal/config/config.yaml#L342-L349), `strategies.access_token` is a valid config.

However, with this set in the config file and start hydra, it reports an error:

```
FATA[0000] The configuration is invalid and could not be loaded.  [config_key=strategies]="additionalProperties \"access_token\" not allowed" config_file=config.yaml

```

**Reproducing the bug**

```
$ cat config.yaml
strategies:
  access_token: jwt

$ cat start.sh
export URLS_SELF_ISSUER=http://127.0.0.1:4444
export URLS_CONSENT=http://127.0.0.1:3000/consent
export URLS_LOGIN=http://127.0.0.1:3000/login
export URLS_LOGOUT=http://127.0.0.1:3000/logout
export DSN=memory
export SECRETS_SYSTEM=youReallyNeedToChangeThis
export OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
export OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
hydra serve all --dangerous-force-http --config config.yaml

$ sh start.sh
FATA[0000] The configuration is invalid and could not be loaded.  [config_key=strategies]="additionalProperties \"access_token\" not allowed" config_file=config.yaml
```

_Server logs_

_Server configuration_

**Expected behavior**

No error is reported. Hydra server runs and produces JWT oauth tokens.

**Environment**
- eca9b2d83702cd541e838b54f53b09f6c5a985ef
- Also happens on v1.4.x

**Additional context**

It's worth noting that setting this in the environment variable works as expected:

```
export STRATEGIES_ACCESS_TOKEN=jwt
```

**Comment by aeneasr** [comment]
This should be fixed on 1.4.10 :)

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/pull/1830

**Comment by uday1331** [comment]
Hi, is this already fixed?

I'm getting the same error on the `oryd/hydra:latest` image pulled from docker hub

My config.yaml file looks like this:

```
strategies:
    scope: exact
    access_token: opaque
```

and it returns the same error as ^^

```
time="2020-06-11T09:24:43Z" level=fatal msg="The configuration is invalid and could not be loaded." [config_key=strategies]="additionalProperties \"access_token\" not allowed" config_file=/config.yaml
```

I'm trying to get JWTs working, I've tried with Ory Oathmaker and this and seems not working

**Comment by aeneasr** [comment]
Don't use :latest, use a dedicated version tag!

**Comment by uday1331** [comment]
> Don't use :latest, use a dedicated version tag!

I originally tried it with oryd/hydra:1.4.8.
If possible, could you give some guidance on getting jwts from hydra using oathkeeper? I already have read [this](https://www.ory.sh/hydra/docs/advanced/#json-web-tokens) but it doesn't help much. 

I modified the 5 minute tutorial and added oathkeeper as the reverse proxy for my request. My rules.json is below:
```
[   
  {
    "id": "hydra-port1",
    "upstream": {
      "url": "http://hydra:4445/",
      "preserve_host":true
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/<(?!oauth2).*>",
      "methods": [
        "GET"
      ]
    },
    "authenticators": [{ "handler": "noop" }],
    "authorizer": { "handler": "allow" },
    "mutators": [{ "handler": "noop" }],
    "errors": [
        {
          "handler": "json"
        }
      ]
  }, 
  {
    "id": "hydra-port2",
    "upstream": {
      "url": "http://hydra:4444/",
      "preserve_host":true
    },
    "match": {
      "url": "http://<127.0.0.1|localhost>:4455/<(oauth2)>/<.*>",
      "methods": [
        "GET","POST"
      ]
    },
    "authenticators": [{ "handler": "noop" }],
    "authorizer": { "handler": "allow" },
    "mutators": [
      { 
        "handler": "id_token",
        "config":{
          "issuer_url":"http://localhost:4455/",
          "jwks_url": "file:///jwks.json"
        }
      }
    ],
    "errors": [
        {
          "handler": "json"
        }
      ]
    }
]


```

**Comment by aeneasr** [comment]
Would it be possible for you to make the repository public? That way others benefit from this as well. Then I'm also happy to check it out and help you figure out what's going on :)

**Comment by aeneasr** [comment]
You are correct however, it looks like there's something phishy going on!

**Comment by uday1331** [comment]
> You are correct however, it looks like there's something phishy going on!



> Would it be possible for you to make the repository public? That way others benefit from this as well. Then I'm also happy to check it out and help you figure out what's going on :)

Yeah definitely I can!! As I'm figuring this out I wanna make anyone else can get help too :))

**Comment by uday1331** [comment]
> You are correct however, it looks like there's something phishy going on!

I kind of figured what's wrong. I was using oathkeeper as a proxy to hydra instead of the service. I'll set up a basic service and see if I can get the jwts there.

**Comment by aeneasr** [comment]
The best location for discussions is probably at https://community.ory.sh ! So you figure out what's wrong and got it working?

**Comment by uday1331** [comment]
> The best location for discussions is probably at https://community.ory.sh ! So you figure out what's wrong and got it working?

I'm still working on it. As soon as I get a minimum thing going, I'll make my documentation better so that others can benefit too.

**Comment by uday1331** [comment]
> The best location for discussions is probably at https://community.ory.sh ! So you figure out what's wrong and got it working?

I have the whole setup working but for some reason when I try to decode the jwt on jwt.io, I can't see the user information. I checked and the user information is being sent in the header as a Oauth2 token but when converted to jwt it looks like it gets lost. Do you have any idea as to why that might be happening?
