### ISSUE TITLE
Disable healthcheck logs for /health/ready and /health/alive

### ISSUE THREAD

**Issue by christian-roggia** [ory/hydra#1839]
**Is your feature request related to a problem? Please describe.**

Currently when Hydra is deployed on kubernetes a large number of logs is generated due to healthchecks hitting the liveness and readiness endpoints:

```
time="2020-05-01T20:32:19Z" level=info msg="started handling request" method=GET remote="XXX.XXX.XXX.XXX:XXXXX" request=/health/ready
time="2020-05-01T20:32:19Z" level=info msg="completed handling request" measure#hydra/admin: https://example.com/o/.latency=198613 method=GET remote="XXX.XXX.XXX.XXX:XXXXX" request=/health/ready status=200 text_status=OK took="198.613µs"

time="2020-05-01T20:32:20Z" level=info msg="started handling request" method=GET remote="XXX.XXX.XXX.XXX:XXXXX" request=/health/alive
time="2020-05-01T20:32:20Z" level=info msg="completed handling request" measure#hydra/admin: https://example.com/o/.latency=148176 method=GET remote="XXX.XXX.XXX.XXX:XXXXX" request=/health/alive status=200 text_status=OK took="148.176µs"
```

**Describe the solution you'd like**

No logs happening for liveness and readiness endpoints.

**Comment by aeneasr** [comment]
This is possible with `serve.admin.access_log.disable_for_health` and `serve.public.access_log.disable_for_health`.

For future issues please include the version of the software. Thank you!
