### ISSUE TITLE
Make cookies with SameSite=None secure by default or using the configuration flag

### ISSUE THREAD

**Issue by kraikill** [ory/hydra#1844]
**Is your feature request related to a problem? Please describe.**

I am use  `--dangerous-force-http` flag for local development.  The secure option for cookies depends on this flag. Chrome Dev and Firefox Nightly drops scrf cookies because they are not marked as Secure.
Example prompt:
```
A cookie associated with a resource at (servername) was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
```

**Describe the solution you'd like**

So I see 2 option how to solve this:
1. Make cookies secure by default if SameSite==None
2. Add  a configuration option (in addition to same_site_mode) or a flag (such as --dangerous-force-http) to control Secure option manually

Hydra v. 1.4.9

**Comment by aeneasr** [comment]
Did you see https://github.com/ory/hydra/pull/1843 ?

But we should definitely use another SameSite mode when `--dangerous-force-http` is set

**Comment by samkelleher** [comment]
I am not using Hydra in dev, but have the same issue on server where Hydra is not setting the `secure` flag on the cookie, so it's being dropped. Not sure how to enable it (the request is over https 🤷 )

**Comment by pablodanielrey** [comment]
same problem here. oauth2_authentication_csrf not beign setted in chrome because SameSite=None and not Secure. request is being done by https. but i'm using http in hydra and https termination in a load balancer.

**Comment by samkelleher** [comment]
I realised that Chrome 85 fails, Chrome 84 will work. Because in 85 they drop the SameSite=None when not secure (regardless of the site being on https). This the oauth request fails because the CSRF cookies are missing.

https://www.chromestatus.com/feature/5633521622188032

**Comment by nseba** [comment]
This is a major problem at the moment. We have numerous customers reporting that they are not able to access our product anymore with the latest of chrome and after debugging everything the problem seems to be related to the fact Chrome rejects the oauth cookies. Is there a workaround or quick solution for this? This is a major blocker right now.

**Comment by aeneasr** [comment]
Thank you for the reports, investigating!

**Comment by aeneasr** [comment]
Could you quickly say which cookie it is that is missing the secure flag?

**Comment by nseba** [comment]
`oauth2_authentication_csrf` and `oauth2_consent_csrf`

**Comment by aeneasr** [comment]
Thanks!

**Comment by nseba** [comment]
You're welcome. By the way we're using the helm chart so if you fix this it would be great to also update the docker image and/or chart so that we can deploy a fix as quick as possible. 

From more testing it seems that currently Chrome and Chromium browsers in Germany are affected by the last update (84.0.4147.105), while browsers installed in other areas (Romania) seem not to be affected yet. Edge (Chromium) and Firefox still work, but they show warnings regarding this so it could be just a matter of time until they also stop working. Safari also seems to be still working.

**Comment by aeneasr** [comment]
To me it appears that `oauth2_authentication_csrf` have `secure` set to `true` unless you run the hydra daemon with `dangerous-force-http`. Are you running the daemon using that flag?

**Comment by samkelleher** [comment]
I am using docker image `oryd/hydra:v1.4.6`, via helm with `dangerousForceHttp: false`

It writes two cookies as SameSite=None, but with secure=false. They are ignored in Chrome 85. I am looking to see if temporary changing the SameSite policy to Lax would help until how to set the secure flag.

**Comment by aeneasr** [comment]
To set the same site, see: https://www.ory.sh/hydra/docs/guides/cookies

Basically setting `serve.cookies.same_site_mode=Lax` in your config should help for now.

**Comment by aeneasr** [comment]
Ok so I checked with ORY Hydra v1.4.6, without `--dangerous-force-http` set and the cookie is configured correctly for me:

```
Set-Cookie: oauth2_authentication_csrf=MTU5NjEwNDMwMHxEdi1CQkFFQ180SUFBUkFCRUFBQVB2LUNBQUVHYzNSeWFXNW5EQVlBQkdOemNtWUdjM1J5YVc1bkRDSUFJRFF4WmpJeE0ySTJZVGt5TnpRMll6RTRaREl6TkdObU56VmpOREE0WldZenyZdZF6_XU8Vy7R7uXZoOssvvAJeInepP9_FPvvq7zuRQ==; Path=/; Expires=Sat, 29 Aug 2020 10:18:20 GMT; Max-Age=2592000; HttpOnly; Secure; SameSite=None
```

The consent csrf cookie is also set with the secure flag:

```
Set-Cookie: oauth2_consent_csrf=MTU5NjEwNDQxMXxEdi1CQkFFQ180SUFBUkFCRUFBQVB2LUNBQUVHYzNSeWFXNW5EQVlBQkdOemNtWUdjM1J5YVc1bkRDSUFJREUwT0dZNFpUUmtNRGcyT0RRNFpqTmlabVF6TUdRMVpEZG1aRGhrWXpJd3w9zrvhEwg4Vpyqe6hea9PcoZ2i71Gj9tCqaoN241lr6g==; Path=/; Expires=Sat, 29 Aug 2020 10:20:11 GMT; Max-Age=2592000; HttpOnly; Secure; SameSite=None
```

The authentication session is also set with the secure flag:

```
Set-Cookie: oauth2_authentication_session=MTU5NjEwNDQ4OHxEdi1CQkFFQ180SUFBUkFCRUFBQVFmLUNBQUVHYzNSeWFXNW5EQVVBQTNOcFpBWnpkSEpwYm1jTUpnQWtaams1T0Rkalpqa3RORGRsWlMwME9UUTVMV0V3Wm1JdFl6QXlNV05qWVdFeFlqY3d80vNivfv3YCmes5bVBQ_v59tqb8FJrLlk9VfSPCiex60=; Path=/; Expires=Thu, 30 Jul 2020 11:21:28 GMT; Max-Age=3600; HttpOnly; Secure; SameSite=None
```

So basically this means that the issue can not be reproduced if ORY Hydra is configured correctly (without `--dangerous-force-http` set which I hope is true for all production systems...).

@samkelleher what helm chart version are you using?

**Comment by cburmeister** [comment]
@nseba were you able to resolve this? I think we're experiencing the same issue.

We're using `--dangerous-force-http` (our k8s ingress handles TLS) and `serve.cookies.same_site_mode=Lax` but having problems with the following browsers:

- Chrome Mobile 84.0.41471.8k
- Chrome Mobile 83.0.41031.5k
- Mobile Safari 13.1.1742
- Chrome Mobile 85.0.4183713
- Samsung Internet 12.0695
- Mobile Safari 13.1.2596
- Samsung Internet 12.1522
- Firefox Mobile 68.0153
- Mobile Safari 12.1.2146
- Chrome 85.0.418394

**Comment by aeneasr** [comment]
@cburmeister please fill out the issue template and provide as much detail as possible, otherwise I can not help debug this!

**Comment by aeneasr** [comment]
I can confirm that this is solved properly.
