### ISSUE TITLE
Support for Multiple Login and Consent URLs

### ISSUE THREAD

**Issue by dhanyak-btc** [ory/hydra#1851]
Does hydra support multiple values for below variables? I tried comma separated values but hydra considered it as single value. How to pass multiple login & consent URLs? 

 -e URLS_CONSENT="http://localhost:3000/consent" \
 -e URLS_LOGIN="http://localhost:3000/login" 

Expected feature result: Apps send redirect_uri param, hydra should check if this param value exists/contains in pre-registered URLS_CONSENT or URLS_LOGIN and then redirect to redirect_uri instead of URLS_LOGIN or URLS_CONSENT value. This simplifies integrating single hydra server with multiple web/mobile applications.

**Comment by aeneasr** [comment]
No it does not, but you can redirect in your login/consent app based on e.g. the client ID or some other parameter.
