### ISSUE TITLE
Incorrect error thrown for handled_at if missing TZ on consent_challenge accept

### ISSUE THREAD

**Issue by ghenry** [ory/hydra#1863]
**Describe the bug**
https://www.ory.sh/hydra/docs/reference/api/#accept-a-consent-request

If I supply a timestamp without a TZ zone, I get:

```
[debug] $VAR1 = {
          'error_debug' => 'parsing time ""2020-05-18T12:08:12"" as ""2006-01-02T15:04:05Z07:00"": cannot parse """ as "Z07:00"',
          'request_id' => '',
          'error_description' => 'The error is unrecognizable.',
          'error' => 'error',
          'status_code' => 500
        };
```

I think this could be explained better or docs tightened.

**Comment by aeneasr** [comment]
We're using the standard JSON time as generated/parsed by Go, JavaScript, and I believe all other popular programming languages: https://stackoverflow.com/questions/10286204/the-right-json-date-format

**Comment by ghenry** [comment]
Thanks. My point was the docs or the error should say something like
"RFC3339 support only" rather than a raw internal parsing error.

Or ISO8601

**Comment by aeneasr** [comment]
I see! We should definitely document that somewhere.
