### ISSUE TITLE
SDK doesn't support HTTP?

### ISSUE THREAD

**Issue by gdbinit** [ory/hydra#1864]
**Describe the bug**

Hydra Go SDK doesn't seem able to talk to Hydra in HTTP mode?
I am using TLS termination so both hydra daemons are running on localhost. I need the backend application to register the clients but the SDK doesn't seem to have any option to set that.

**Reproducing the bug**

```go
    adminURL, err := url.Parse("http://localhost:4445")
    c := client.NewHTTPClientWithConfig(nil, &client.TransportConfig{Schemes: []string{adminURL.Scheme}, Host: adminURL.Host, BasePath: adminURL.Path})
    // It is important to create the parameters using `New...`, otherwise requests will fail!
    result, err := c.Admin.CreateOAuth2Client(
        admin.NewCreateOAuth2ClientParams().WithBody(&models.OAuth2Client{
        ClientID: "register",
    }))
```
**Expected behavior**

Ability to use the Go SDK to talk to Hydra admin backend so backend applications can register their clients without using Hydra command line?
Alternative seems to be using the "dangerous" cmdline argument?

**Comment by aeneasr** [comment]
I think you can create an HTTP Client that always includes a HTTP header (`X-Forwarded-Proto: https`) and use that client with the SDK. I don't quite remember the syntax though...

**Comment by aeneasr** [comment]
Here you go: https://stackoverflow.com/questions/51325704/adding-a-default-http-header-in-go
