### ISSUE TITLE
config: scopes_supported doesn't have offline_access

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#1866]
**Describe the bug**

Document says `supported_scope` at discovery always has `offline_access` but actually discovery doesn't have it.
https://www.ory.sh/hydra/docs/reference/configuration

**Reproducing the bug**

1. Run `DSN=memory go run main.go serve all`
2. Make API Request to with `curl -k https://127.0.0.1:4444/.well-known/openid-configuration`
3. Response doesn't have `offline_access` at `scopes_supported` property

**Expected behavior**

I'm not sure which way hydra should go.

* Response should have `offline_access` at `scopes_supported` property
* Document should be fixed

**Environment**

- Version: git sha hash 5661ec3ba57fe3a3d86dc4bddc963c1da07101d3
- Environment: Mac

**Additional context**

`DefaultClientScope` has `offline_access`
https://github.com/ory/hydra/blob/5661ec3ba57fe3a3d86dc4bddc963c1da07101d3/driver/configuration/provider_viper.go#L157

but `OIDCDiscoverySupportedScope` doesn't have
https://github.com/ory/hydra/blob/5661ec3ba57fe3a3d86dc4bddc963c1da07101d3/driver/configuration/provider_viper.go#L427

**Comment by aeneasr** [comment]
Oh, thanks, would you be up for a PR to fix this? :)
