### ISSUE TITLE
Unable to migrate to v1.4

### ISSUE THREAD

**Issue by swapnil1988** [ory/hydra#1890]
**Describe the bug**

Unable to migrate to v1.4 from existing version v1.3. 
Migration from v1.0.0 to v1.3 just works fine, while migration from v1.3 to v1.4 fails. 

**Reproducing the bug**

1. Install hydra with version v1.0.0 or v1.3 (fresh install using MySQL)
2. Hydra will generate jwk sets in hydra_jwk table
3. Run migrate sql command to migrate sql schema to v1.4
4. Try to run hydra v1.4 (running hydra v1.4 fails at startup with **error="cipher: message authentication 
failed"**)

_Server logs_
```
time="2020-06-01T00:53:59Z" level=fatal msg="Could not ensure that signing keys for \"hydra.openid.id-token\" exists. If you are running against a persistent SQL database this is most likely because your \"secrets.system\" (\"SECRETS_SYSTEM\" environment variable) is not set or changed. When running with an SQL database backend you need to make sure that the secret is set and stays the same, unless when doing key rotation. This may also happen when you forget to run \"hydra migrate sql\".." error="cipher: message authentication failed"
```

**Expected behavior**

It is expected that hydra 1.4 should be able to use existing JWK generated by version 1.3 or below.

**Environment**

- Version: v1.4
- Environment: Docker
- DB: MYSQL 5.7

**Additional context**

Ideally, the migration (v1.3 to v1.4) should work but for some reason, the jwk (in hydra_jwk table) validation fails at startup. No config change was done during migration, specifically no change in **SYSTEMS_SECRET**

**Comment by aeneasr** [comment]
Sorry to hear that you have problems with migrations. There have been no changes to the jwk or cipher submodule between 1.3.0 and 1.4.0 and this is also the first report of a broken migration for that version range, whose release was over 2 months ago.

Would it be possible for you to create a reproducible github repository (docker compose is fine) with the same (or nearly the same - feel free to replace things such as the secret) so we can figure out what's going on?

**Comment by swapnil1988** [comment]
Thanks @aeneasr for your quick response. 

I have created a [github repo](https://github.com/swapnil1988/hydra-upgrade-test) with steps to reproduce the issue. I think it is somehow related to k8s deployments with helm charts since the systems_secret is picked up from values.yaml array field that is added to k8s secret and injected as env variable in the k8s deployment manifest. The string representation of the SYSTEMS_SECRET looks something like **[secret]** (maybe something related to it, I am not sure though)

**Comment by aeneasr** [comment]
Wow, incredibly helpful, thank you! So I think I know what's going on - using a secret of type `[secret]` as an env var could have been interpreted as a plain string or as an array. I believe that viper changed here and it is now interpreted differently than it was before (so before it was a literal string and now it is interpreted as an array for example, or vice versa). If you remove the brackets and redo the whole thing (removing the db beforehand) you won't see any issues.

What you could try is to create a config file and point Hydra to it and include one the secret as a literal string or as an array

```
secrets:
  system:
    - secret1234567890
```

```
secrets:
  system:
    - "[secret1234567890]"
```

when running 1.4+. Maybe @zepatrik has some further info on this as he worked on the config pipeline.

**Comment by zepatrik** [comment]
My guess is it should work with env vars if you add extra square brackets around the secret (`[[secret]]`). The reason is that previously they where interpreted as part of the string but now they are not any more.

**Comment by aeneasr** [comment]
https://github.com/swapnil1988/hydra-upgrade-test/pull/1
