### ISSUE TITLE
SDK C# client

### ISSUE THREAD

**Issue by skitt2000** [ory/hydra#1894]
Hi,
we need a C# client to use oauth 2.0 with Hydra in our environment. Could you help us?

**Comment by aeneasr** [comment]
Sure! This should be possible quite easily because we use openapi-generator (https://github.com/ory/sdk) so basically we just need to add the generator to the automation pipeline.

I don't write C#, do you know if there's a package manager like npm? Or is a GitHub repository enough?

**Comment by skitt2000** [comment]
https://github.com/NuGet, is this enough?

**Comment by aeneasr** [comment]
Not sure if I understand your question, is NuGet like NPM for C#?

**Comment by skitt2000** [comment]
Yes, NuGet is package manager for dot NET including C#.

**Comment by tacurran** [comment]
@skitt2000 we would like to get this started with a PR.  @vinckr is going to work with you to get it going

**Comment by skitt2000** [comment]
@tacurran Thanks a lot.

**Comment by vinckr** [comment]
@skitt2000 
https://github.com/ory/hydra/issues/2017

>Here's the script we use to generate the csharp SDK:

```
npx @openapitools/openapi-generator-cli generate \
  -i api.swagger.json \
  -g csharp \
  --additional-properties=packageName=Sh.Ory.Hydra \
  -o ./lib
```

Now we just need to add it to the automatically generated SDK's so you dont need to regenerate manually. 
[Here](https://www.ory.sh/hydra/docs/sdk/)

**Comment by vinckr** [comment]
So https://github.com/ory/hydra/issues/2017 and this can be merged? @tacurran

**Comment by aeneasr** [comment]
This is resolved by https://github.com/ory/sdk/pull/26!
