### ISSUE TITLE
Support accessing admin API via unix sockets

### ISSUE THREAD

**Issue by dalcde** [ory/hydra#1898]
#1230 lets us bind the admin API to a unix socket. However, it appears that we cannot set the endpoint of, say, `hydra clients` to a unix socket, so we must still go through some sort of web server.

**Comment by aeneasr** [comment]
https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74 appears to be how one calls unix sockets. PRs welcomed :)

**Comment by dalcde** [comment]
Closed by #1899
