### ISSUE TITLE
post-logout-callbacks

### ISSUE THREAD

**Issue by materia2021** [ory/hydra#1902]
I can't find any documentation regarding this parameter --post-logout-callbacks when creating a client but it does fix the error when I logout via http://hydra/oauth2/sessions/logout? saying the post_logout_redirect_uri is not whitelisted. I only found this : 

 post_logout_redirect 
  
   When a user agent requests to logout, it will be redirected to this url afterwards per default.
  
   Examples:
  - https://my-example.app/logout-successful
  
  Set this value using environment variables on
  Linux/macOS:
 $ export URLS_POST_LOGOUT_REDIRECT=<value>
  Windows Command Line (CMD):
> set URLS_POST_LOGOUT_REDIRECT=<value>

 post_logout_redirect: https://my-example.app/logout-successful

I tried using it but it does not fix the problem.

  hydra:
    image: oryd/hydra:v1.4.10
    command: serve all --dangerous-force-http
    environment:
      SECRETS_SYSTEM: changeme
      DSN: postgres://hydra:changeme@db:5432/hydra?sslmode=disable
      URLS_SELF_ISSUER: http://localhost:4444
      URLS_CONSENT: http://localhost:8090/consent
      URLS_LOGIN: http://localhost:8090/login
      URLS_LOGOUT: http://localhost:8090/logout
      URLS_POST_LOGOUT_REDIRECT: http://localhost:4200/dashboard
      OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES: "public,pairwise"
      OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT: changeme
      OAUTH2_ACCESS_TOKEN_STRATEGY: jwt
      SERVE_PUBLIC_CORS_ENABLED: "true"
      SERVE_PUBLIC_CORS_ALLOWED_ORIGINS: "*"

**Comment by aeneasr** [comment]
Does this not help? https://www.ory.sh/hydra/docs/implementing-consent#user-logout

**Comment by materia2021** [comment]
I’ve read that but no mention of client specific post logout redirect uri (—post-logout-callbacks)

**Comment by aeneasr** [comment]
Right! It appears that isn't properly documented. The global env var is the **default redirect URL** while the client-specific URL is whitelisting the `post_logout_redirect_uri` parameter you send when initiating the logout!

**Comment by materia2021** [comment]
Found it in the CLI. clients -help so I guess it’s okay?

**Comment by webB1an** [comment]
Hi!@mrguamos, I'm also confused by how to configure `post_logout_redirect_uri `

Can you give me any ideas?

Thanks!
