### ISSUE TITLE
Support Zipkin Tracing

### ISSUE THREAD

**Issue by timsazon** [ory/hydra#1903]
**Is your feature request related to a problem? Please describe.**

In my project, we use a Zipkin tracing system and we can't trace Hydra which only supports the Jaeger system.
It would be great to have support Zipkin since it's still one of the most popular tracing systems.

**Describe the solution you'd like**

It can be easily done via https://github.com/openzipkin/zipkin-go and https://github.com/openzipkin-contrib/zipkin-go-opentracing libraries

Zipkin implements opentracing API so the collected information will be the same and no changes to the middleware are required.
Sending data will be in the following format:
```
  {
    "id": "352bff9a74ca9ad2",
    "traceId": "5af7183fb1d4cf5f",
    "parentId": "6b221d5bc9e6496c",
    "name": "/oauth2/token",
    "timestamp": 1556604172355737,
    "duration": 1431,
    "kind": "",
    "localEndpoint": {
      "serviceName": "ORY Hydra"
    },
    "tags": {
      "http.method": "POST",
      "http.status_code": "401",
      "error": true,
    }
  }
```

**Comment by aeneasr** [comment]
Merged on master, thank you! :)
