### ISSUE TITLE
Logout multiple tabs

### ISSUE THREAD

**Issue by materia2021** [ory/hydra#1906]
I'm building an SPA. Also using this [oidc-client](https://github.com/IdentityModel/oidc-client-js/).
Since session management is not yet supported, is it possible to logout all tabs when using multiple tabs? 

For ex, I logout from the first tab, then I switched to the 2nd tab. the 2nd tab should be logged out also.

**Comment by aeneasr** [comment]
Thank you for opening this issue. Please ask generic use case questions over at: community.ory.sh . To make long things short:

a. This depends on how **you** implement session management and detection **in your app**
b. Hydra deletes a cookie when you log out which affects all browser tabs
