### ISSUE TITLE
how can hydra skip the steps to get the user's authorization and get the auth code directly

### ISSUE THREAD

**Issue by feikiss** [ory/hydra#1921]
**Is your feature request related to a problem? Please describe.**

hydra follow the security best practice but it cannot fit the scenario that request to skip user's authorizaton.

**Describe the solution you'd like**

I'd like to suggest hydra to support a direct way to support developer use a more effective way to fit their own requirement.  In many cases, the product manager hate the dialog to ask user's authorization in the Private cloud platform。  

**Describe alternatives you've considered**
support a way to skip the user's authorization of getting the auth code steps , so that developer can get the auth code directly and get the access token more simple.
In some scenario, the product manager request to skip/hide the  UI to get the end user's authorization.

A clear and concise description of any alternative solutions or features you've
considered.

**Comment by aeneasr** [comment]
This is already possible. You control the consent app, so you don't need to show the UI. I don't recommend it and it's bad practice, but this is possible today. No changes to Hydra are required to get this working.
