### ISSUE TITLE
Disable traces for health endpoints

### ISSUE THREAD

**Issue by inigohu** [ory/hydra#1924]
Disable span creation for health endpoints or give the option to disable them like `disable_for_health` flag for logs.

**Comment by inigohu** [comment]
I bumped Hydra to v1.6.0 and I still get traces from health endpoints.

I realized that hydra, instead of using the [internal tracing package](https://github.com/ory/hydra/tree/v1.6.0/tracing) where I did the changes, is using the external [x/tracing](https://github.com/ory/hydra/blob/v1.6.0/driver/registry.go#L11) package. That is why my change is not working.

Should we remove [hydra/tracing](https://github.com/ory/hydra/tree/v1.6.0/tracing) and apply my changes in the external [x/tracing](https://github.com/ory/x)

**Comment by aeneasr** [comment]
Ah, absolutely! Thank you for debugging this :)

**Comment by inigohu** [comment]
> Ah, absolutely! Thank you for debugging this :)

I will send you a PR with the fix then :+1:
