### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by Faares** [ory/hydra#1925]
**Describe the bug**

Request to: `https://[HYDRA_URLS_SELF_ISSUER]/oauth2/auth/requests/login/?login_challenge=[string]`  return status:  `404 Not Found`, the body of the response:
`{"error": "Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port."}` 

**Expected behavior**

return `200 Ok`

**Environment**

- Version: v1.51
- Environment: Docker

**Comment by aeneasr** [comment]
This is exposed at the admin endpoint

**Comment by Faares** [comment]
I got it! thank you! :)
