### ISSUE TITLE
Add client_id filtering on consent sessions listing endpoint

### ISSUE THREAD

**Issue by SlevinWasAlreadyTaken** [ory/hydra#1926]
**Is your feature request related to a problem? Please describe.**

Talking about the [consent sessions listing endpoint](https://www.ory.sh/hydra/docs/reference/api/#lists-all-consent-sessions-of-a-subject), the request makes mandatory a query paramater called `subject` to retrieve all consent sessions linked to it.

In my current usage, it would be also useful to be able to filter by `client_id`, otherwise I have to parse all sessions for all `client_id` and find the current one that I am interested in.

**Describe the solution you'd like**

I think the need is mostly about query optimization. The Hydra storage layer is the most appropriate place to filter this information to me.

Considering the ticket about [filter/sort the list of clients](https://github.com/ory/hydra/issues/1485) is still open, I am not sure about how to inform Hydra about the `client_id` filtering.

At this point considering no convention seems to have been expressed, I would add it using **an optional query parameter** name `client_id`. I do not think to have many client IDs to filter on is necessary.

**Describe alternatives you've considered**

I consider that maybe the quoted ticket should be solved before.

**Additional context**

I can try to contribute myself to add this feature if you agree with the need and express an expected design.

**Comment by aeneasr** [comment]
Sorry for the late reply - thank you for the issue and offer to PR this - I think it makes a ton of sense! I have come to terms that we probably need some simple filtering that's based on REST, unfortunately ;)

**Comment by vinckr** [comment]
Hey @SlevinWasAlreadyTaken , you probably have a lot on your plate, but we would love to move this forward. Do you still want to work on this?
Feel free to bounce this back if you don't have time to look at it, though. (And let me know if you'd prefer not to receive such requests in the future.)

**Comment by SlevinWasAlreadyTaken** [comment]
@vinckr since this feature seems to be a good choice for a first contribution I will try to work on it this week if the timing is ok to you :) If I don't find the time I will let you know ! Thanks for asking me

**Comment by SlevinWasAlreadyTaken** [comment]
Unfortunately, quite a busy time last full week... I didn't have the time to work on this and considering my current load I am not sure I will be able to work on it this one too... so feel free to do it on your side. Sorry!
