### ISSUE TITLE
Logout post_logout_redirect_uri doesn't work when URI encoded

### ISSUE THREAD

**Issue by chriskolenko** [ory/hydra#1927]
**Describe the bug**

When the post_logout_redirect_uri query is uri encoded it does not match what's configured in the client config.

https://...../oauth2/sessions/logout?post_logout_redirect_uri=https%3A%2F%2Fwww.test.com&id_token_hint=....

Code is here:
https://github.com/ory/hydra/blob/master/consent/strategy_default.go#L842-L846

**Reproducing the bug**

Login and logout using RP flow but encode the post redirect url

**Comment by aeneasr** [comment]
I don't think that's true, Go's URL parser properly decodes this [here](https://github.com/ory/hydra/blob/master/consent/strategy_default.go#L733).

**Comment by chriskolenko** [comment]
Found the issue with the library I was using which was double encoding.
