### ISSUE TITLE
Initiate user registration using prompt=create

### ISSUE THREAD

**Issue by SzilardS** [ory/hydra#1929]
**Is your feature request related to a problem? Please describe.**

Allow a client to initiate to initiate a login session with a registration page initially.

**Describe the solution you'd like**

Implement the prompt option 'create' described in:
[Initiating User Registration via OpenID Connect - draft 03](https://openid.net/specs/openid-connect-prompt-create-1_0.html#authz-req)

**Describe alternatives you've considered**

Haven't come up with other choices yet.

**Comment by aeneasr** [comment]
Given that this is a very early draft (security considerations have not yet been defined) and that ORY Hydra doesn't really have a registration flow (sure, we could delegate that to the login app) I don't think this will land here anytime soon :/

**Comment by bala-striva** [comment]
If not handling the value of the prompt, would you allow adding the prompt field to `OpenIDConnectContext` so the login provider could handle the prompt as it's want to?

**Comment by aeneasr** [comment]
Does Hydra currently fail to process the request when `prompt=create`?

**Comment by bala-striva** [comment]
It's not failing, it's simple ignoring it which is fine, but as we want to use this value in the login provider making the prompt's value available would solve our use case.

**Comment by aeneasr** [comment]
You can get that value by checking `request_url` when fetching the login/consent challenge!

**Comment by bala-striva** [comment]
Thanks that looks like what we need!

**Comment by aeneasr** [comment]
Perfect then, closing as a workaround for this exists, and because the spec is still very undefined this won't be implemented.
