### ISSUE TITLE
Let the identity provider handle requests with prompt=none

### ISSUE THREAD

**Issue by jonkjenn** [ory/hydra#1933]
**Is your feature request related to a problem? Please describe.**
Currently Hydra makes the decision to reject the login with `prompt=none` based on the existence of Hydra cookies/session. The identity provider might have separate cookies/session that identifies the user but is unable to act on this since the login attempt is already rejected by Hydra.

**Describe the solution you'd like**
Add an option to let the identity provider handle requests even when `prompt=none` is present.

**Additional context**
If there's interest in having this functionality in Hydra we would likely be interested in creating the PR for it.

**Comment by aeneasr** [comment]
Sessions between Hydra and the Identity Provider must not diverge, otherwise you won't be able to become OpenID Connect certified. Hence I do not recommend implementing this.
