### ISSUE TITLE
Connection to Postgres, connects but throws error "Could not ensure that signing keys for "hydra.openid.id-token"

### ISSUE THREAD

**Issue by DarkBlaez** [ory/hydra#1944]
I am consistently getting an error when I attempt to launch Hydra with Helm. It looks like everything is starting ok and evening connecting to Postgres.

The Helm install:
helm install --namespace ory hydra-idp \
  --set 'hydra.config.secrets.system=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | base64 | head -c 32)' \
  --set 'hydra.config.dsn=postgres://X:X@postgresql.dataops.svc.cluster.local:5432/hydra' \
  --set 'hydra.config.urls.self.issuer=https://pubclic.hydra.localhost/' \
  --set 'hydra.config.urls.login=https://idp.hydra.localhost/login' \
  --set 'hydra.config.urls.consent=https://idp.hydra.localhost/consent' \
  --set 'hydra.config.urls.logout=http://idp.hydra.localhost/logout' \
  ory/hydra

The Error:
2020-07-08T20:40:44.656099412Z time="2020-07-08T20:40:44Z" level=info msg="No tracer configured - skipping tracing setup"
2020-07-08T20:40:44.656171683Z time="2020-07-08T20:40:44Z" level=info msg="Establishing connection with SQL database backend" dsn="postgres://*:*@postgresql.dataops.svc.cluster.local:5432/hydra?"
2020-07-08T20:40:44.686833412Z time="2020-07-08T20:40:44Z" level=info msg="Successfully connected to SQL database backend" dsn="postgres://*:*@postgresql.dataops.svc.cluster.local:5432/hydra?"
2020-07-08T20:40:44.68844989Z time="2020-07-08T20:40:44Z" level=fatal msg="Could not ensure that signing keys for \"hydra.openid.id-token\" exists. This can happen if you forget to run \"hydra migrate sql\", set the wrong \"secrets.system\" or forget to set \"secrets.system\" entirely." error="ERROR: relation \"hydra_jwk\" does not exist (SQLSTATE 42P01)"

The result is the same even when I have created an existing secret. If I run with dsn=memory all is good

Postgres is running in a pod and exposed internally with a ClusterIP, reachable with the service name per above. Other apps access Postgres so it is reachable.

Postgres version: PostgreSQL 11.8 on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

Is this indeed the error/issue->error="ERROR: relation \"hydra_jwk\" does not exist (SQLSTATE 42P01)", if so how to resolve. The database was created, user id, password, all have the correct access to the database to create tables, etc. 

Thanks
DB

**Comment by aeneasr** [comment]
Did you run the migrations like the log suggests?

```
This can happen if you forget to run "hydra migrate sql",
```

**Comment by DarkBlaez** [comment]
I will try that and see. I did not as I was anticipating a clean install without having to jiggle it from a client command. I will give that a try.

**Comment by DarkBlaez** [comment]
Would autoMigrate=true handle this?

**Comment by DarkBlaez** [comment]
What does "hydra migrate sql" perform. I noticed upon first run no tables are created. Why would this "migrate sql" be needed as an external step and above all with a client side executable reach inside the pod to do so. Would not detecting this condition and then performing this migration from within the container be more prudent?

**Comment by DarkBlaez** [comment]
Actually I just found the migrate_sql.go code so will inspect this further

**Comment by DarkBlaez** [comment]
Closing the issue, it still exist and the mechanism for having to use "hydra migrate sql" as the initial means to setup the DB is something that will cause me to retool the instance of the DB. However, I will see about injecting this in another way.
