### ISSUE TITLE
Error on raspberry pi 4: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by tox777** [ory/hydra#1950]
Hi. please help me.
Im trying to install on raspberri pi 4, 4gb ram. But when i tried to execute this command the terminal show me "standard_init_linux.go:211: exec user process caused "exec format error""

command: docker run -it --rm --entrypoint hydra oryd/hydra:v1.5.2 help serve

**Comment by harsimranmaan** [comment]
The first thing that came to mind after looking at the error is CPU type mismatch. Raspberry is ARM based and the hydra docker image is built for amd64 as per https://hub.docker.com/r/oryd/hydra/dockerfile. You might have to build your own image for ARM. I can help you with that if you are interested as I am also exploring some edge deployment use cases with ory.sh/*.

**Comment by aeneasr** [comment]
Correct, you can download ARM binaries on the [releases tab](https://github.com/ory/hydra/releases) or using the install script: https://www.ory.sh/hydra/docs/install#linux
