### ISSUE TITLE
Docker image of consent isn't available on docker hub

### ISSUE THREAD

**Issue by RemiKalbe** [ory/hydra#1955]
In the quickstart.yml file, the consent image is set like that
`image: oryd/hydra-login-consent-node:v1.6.0`, but v1.6.0 is not a tag available on docker hub.
See https://hub.docker.com/r/oryd/hydra-login-consent-node/tags?page=1

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/blob/master/quickstart-cockroach.yml#L18 ?
