### ISSUE TITLE
docs: Hydra supports two concepts of authorization

### ISSUE THREAD

**Issue by mitar** [ory/hydra#1992]
**Describe the bug**

Hydra docs say:

> Hydra supports two concepts of authorization. One is called Token Introspection which is a standard by the IETF ( https://tools.ietf.org/html/rfc7662 ). It is primarily targeted at third-party services and is usually used by a programmatic API. It can be used by first-party services too. The sole purpose of this endpoint is to check whether an access token is valid or not.

I see only one concept of authorization described? But it starts that it supports two. Which one is the second one?

**Reproducing the bug**

See: https://www.ory.sh/hydra/docs/security-architecture/#how-does-access-control-work-with-hydra

**Comment by aeneasr** [comment]
Thank you, I fixed the section in question. if you find issues in the docs, feel free to just throw up PRs with your suggested changes and/or ideas :)
