### ISSUE TITLE
issueLogoutVerifier should allow POST requests as well

### ISSUE THREAD

**Issue by mitar** [ory/hydra#1993]
**Describe the bug**

[The spec says](https://openid.net/specs/openid-connect-rpinitiated-1_0.html):

> OpenID Providers MUST support the use of the HTTP GET and POST methods defined in RFC 7231 [RFC7231] at the Logout Endpoint. RPs MAY use the HTTP GET or POST methods to send the logout request to the OP. If using the HTTP GET method, the request parameters are serialized using URI Query String Serialization. If using the HTTP POST method, the request parameters are serialized using Form Serialization. 

But Hydra currently checks only the query parameters.

**Reproducing the bug**

Currently the code in `issueLogoutVerifier` is as follows:

```
	hint := r.URL.Query().Get("id_token_hint")
	state := r.URL.Query().Get("state")
	requestedRedir := r.URL.Query().Get("post_logout_redirect_uri")
```

**Comment by aeneasr** [comment]
PRs welcomed!

**Comment by mitar** [comment]
This has been done.
