### ISSUE TITLE
DRAFT WIP Ory Hydra Roadmap: July - December 2020

### ISSUE THREAD

**Issue by tacurran** [ory/hydra#1996]
Roadmap Overview
This roadmap explains our priorities until December. The approach we use here helps us set expectations and communicate with the Ory community.  We estimate based on prior experience with the project's implementation as well as input from individual developers.

In this Roadmap we will focus on the following goals:

**Comment by aeneasr** [comment]
Check out the milestones (https://github.com/ory/hydra/milestones) and project board (https://github.com/orgs/ory/projects/8)

**Comment by tacurran** [comment]
@aeneasr we are taking an initial attempt to gather all issues.  Of course in accordance with the milestones and other information available.

**Comment by aeneasr** [comment]
I'll be closing this - we're managing roadmap a bit differently now :)

**Comment by tacurran** [comment]
@aeneasr we like the approach that typescript uses, and we have enough materials available. I suggest that we publish the approach in this issue #1996 or create a new one to that we can use in all projects.

**Comment by aeneasr** [comment]
We have a milestone document which documents the roadmap: https://github.com/ory/hydra/blob/master/docs/docs/milestones.md

This is also published in the documentation: https://www.ory.sh/hydra/docs/next/milestones

The idea is to use the GitHub toolchain to fill this document with life (e.g. milestone descriptions, better issue content, ...). We could of course pin the link to it in an issue here!

**Comment by aeneasr** [comment]
I will be closing and unpinning because it pollutes the issues page but does not add any new information for readers.

Let's create a new thread once we've finalized the roadmap and pin it to the repository or publish it in the documentation! :)
