### ISSUE TITLE
gitlab openid connect try to access '.well-known/webfinger' fail

### ISSUE THREAD

**Issue by Csirme** [ory/hydra#2005]
HYDRA LOGS:

GET path:/.well-known/webfinger query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.20.0.1:48324 scheme:http]】

GILTLAB LOGS:

10:54
OpenIDConnect::Discovery::DiscoveryFailed (Not Found):

**Comment by aeneasr** [comment]
Please look to GitLab: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/62208

**Comment by Csirme** [comment]
gitlab_rails['omniauth_providers'] = [
  { 'name' => 'openid_connect',
    'label' => 'RRT SSO',
    'args' => {
      'name' => 'openid_connect',
      'scope' => ['openid','profile'],
      'response_type' => 'code',
      'issuer' => 'https://auth.xxxxx.com/',
      'discovery' => true,
      'client_auth_method' => 'query',
      'uid_field' => 'sub',
      'client_options' => {
        'identifier' => 'gitlab',
        'secret' => 'gitlab-secret',
        'redirect_uri' => 'http://192.168.22.200/users/auth/openid_connect/callback'
      }
    }
  }
]


OpenIDConnect::Discovery::DiscoveryFailed (Issuer mismatch):
  
lib/gitlab/metrics/elasticsearch_rack_middleware.rb:24:in `call'
lib/gitlab/metrics/redis_rack_middleware.rb:22:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:29:in `call'
lib/gitlab/metrics/rack_middleware.rb:17:in `block in call'
lib/gitlab/metrics/transaction.rb:54:in `run'
lib/gitlab/metrics/rack_middleware.rb:17:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:13:in `call'
lib/gitlab/middleware/multipart.rb:140:in `call'
lib/gitlab/middleware/read_only/controller.rb:51:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:23:in `call'
config/initializers/fix_local_cache_middleware.rb:9:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:60:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'

Oauth Server log:
host:auth.xxxxx.com method:GET path:/.well-known/openid-configuration query:<nil> remote:172.20.0.1:48404 scheme:http] http_response=map[status:200 text_status:OK took:270.8µs]
