### ISSUE TITLE
Publish a generated csharp SDK

### ISSUE THREAD

**Issue by alampros** [ory/hydra#2017]
**Is your feature request related to a problem? Please describe.**
We need an easier way to communicate with the Admin API from our dotnet project than raw HTTP. We used the open-api-generator to generate an SDK for csharp and it worked wonderfully.

**Describe the solution you'd like**
Include a csharp generated SDK in the [automatically-generated SDKs](https://www.ory.sh/hydra/docs/sdk/) and publish it to nuget when a new hydra version is released.

**Describe alternatives you've considered**
We're currently using our own generated lib and manually regenerating it for new versions. 

**Additional context**
Here's the script we use to generate the csharp SDK:

```sh
npx @openapitools/openapi-generator-cli generate \
  -i api.swagger.json \
  -g csharp \
  --additional-properties=packageName=Sh.Ory.Hydra \
  -o ./lib
```

**Comment by aeneasr** [comment]
This is resolved by https://github.com/ory/sdk/pull/26!
