### ISSUE TITLE
Expired token is considered an error

### ISSUE THREAD

**Issue by catper** [ory/hydra#2031]
**Is your feature request related to a problem? Please describe.**

When Hydra receives a request with a token that is no longer valid, it logs an error with what appears to be debug output:
```
{"debug":"Token is expired","description":"Token expired","error":"token_expired","hint":"The token expired.","level":"error","msg":"An error occurred","time":"2020-08-28T20:14:40Z"}
```

At high loads, logs can get completely bogged down with these messages, which isn't only annoying but also affects the performance of the application as I/O is expensive.

**Describe the solution you'd like**

An invalid token does not indicate an error with the application and therefore I don't think it should be logged as such. Since it is not an event that requires action, I'd argue that it should be on a level no higher than `info`.

**Comment by aeneasr** [comment]
Yeah this should definitely move to the `AuditLogger()`. Contributions welcomed! :)
