### ISSUE TITLE
Unable to create client credentials client

### ISSUE THREAD

**Issue by akhanqi** [ory/hydra#2036]
**Describe the bug**

I'm using documentation from https://www.ory.sh/hydra/docs/guides/oauth2-clients/#client-credentials-flow to create client-credentials client, but when I use command I'm getting the following error:

> The request failed with the following error message:
invalid character 'C' looking for beginning of value

**Reproducing the bug**

1. Save docker-compose from https://gist.github.com/akhanqi/53487b1c558d1604e8f07e73f57fc1f1
2. run docker-compose, ensure that all migrations are applied
3. install hydra CLI client
4. run command `hydra clients create --endpoint http://localhost:9001 -g client_credentials --id test --secret testsecret`

_Server logs_

can be found https://gist.github.com/akhanqi/af255d0bd415b74cb3149e9e616ada16

```
hydra_1            | Config file not found because "Config File ".hydra" Not Found in "[/]""
hydra_1            | 2020/09/02 13:55:56 error: Config File ".hydra" Not Found in "[/]"
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=ORY Hydra service_version=
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=Establishing connection with SQL database backend audience=application dsn=postgres://*:*@pg:5432/hydradb?sslmode=disable service_name=ORY Hydra service_version=
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=Successfully connected to SQL database backend audience=application dsn=postgres://*:*@pg:5432/hydradb?sslmode=disable service_name=ORY Hydra service_version=
hydra_1            | Thank you for using ORY Hydra v1.7.4!
hydra_1            | 
hydra_1            | Take security seriously and subscribe to the ORY Security Newsletter. Stay on top of new patches and security insights.                                                                                                
hydra_1            | 
hydra_1            | >> Subscribe now: http://eepurl.com/di390P <<
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name= service_version=
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=Setting up http server on :4445 audience=application service_name= service_version=
hydra_1            | time=2020-09-02T13:55:56Z level=info msg=Setting up http server on :4444 audience=application service_name= service_version=
```

_Server configuration_

I didn't set any configuration, assuming docker will take default one

**Expected behavior**

Client for client_credentials to be created

**Environment**

Hydra CLI for MacOS:
- Version:    v1.7.4
- Git Hash:   ff980e6d6c5a5f17b7a0c55e7593a9ec75ea76ef
- Build Time: 2020-08-31T15:38:54Z

Hydra Server:
- Environment: Docker
- OS: MacOS

**Additional context**

I tried to use both to create client:

- native macos CLI
- docker hydra CLI

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by akhanqi** [comment]
@aeneasr  thanks for quick feedback. I updated original message whenever I could. Let me know if something is still missing

**Comment by aeneasr** [comment]
The logs say hydra runs on 4444 and 4445 but you used localhost:9001. Make sure the URLs are correct and you're accessing the right endpoint (admin vs public)

**Comment by akhanqi** [comment]
Ports are exposed to host, so they are accessible. I used docker hydra CLI as well connecting to network, it returns same error @aeneasr

**Comment by aeneasr** [comment]
The logs do not show that any request ends up at the server, so it's highly likely that the port set up is not correct. Double-check your docker compose config etc

**Comment by akhanqi** [comment]
All right, I ran hydra CLI from source code, found that error 

>  invalid character 'C' looking for beginning of value

comes from this line https://github.com/ory/hydra/blob/master/internal/httpclient/client/admin/create_o_auth2_client_responses.go#L32

Logs with DEBUG env variable set:

`DEBUG=1 go run main.go clients create --endpoint http://localhost:9001 -g client_credentials --id test --secret testsecret`

> You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
POST /clients HTTP/1.1
Host: localhost:9001
User-Agent: Go-http-client/1.1
Content-Length: 268
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip
{"client_id":"test","client_secret":"testsecret","created_at":"0001-01-01T00:00:00.000Z","grant_types":["client_credentials"],"response_types":["code"],"subject_type":"public","token_endpoint_auth_method":"client_secret_basic","updated_at":"0001-01-01T00:00:00.000Z"}
HTTP/1.0 400 Bad Request
Connection: close
Client sent an HTTP request to an HTTPS server.
The request failed with the following error message:
invalid character 'C' looking for beginning

**Comment by akhanqi** [comment]
OK, after debugging

` Client sent an HTTP request to an HTTPS server.`

that was the reason, I changed --endpoint to https and add flag --skip-tls-verify

`DEBUG=1 go run main.go clients create --endpoint https://localhost:9001 -g client_credentials --id test --secret testsecret --skip-tls-verify`

and was able to create OAuth2 client.
