### ISSUE TITLE
[I18N] Add i18n support for Messages

### ISSUE THREAD

**Issue by UkonnRa** [ory/hydra#2040]
**Is your feature request related to a problem? Please describe.**

Now Messages are something like:

```json
[
  {
    "id": 4000006,
    "text": "The provided credentials are invalid, check for spelling mistakes in your password or username, email address, or phone number.",
    "type": "error",
    "context": {}
  }
]
```

So if `text` contains some variables, it will be impossable to do the i18n work

**Describe the solution you'd like**

Use [ICU format](http://site.icu-project.org/) to solve the problem

```json5
[
  {
    "id": 4000006, // This is a 1/1 mapping to `i18nText`, in another word, one ID can map to one and only one `i18nText`
    "text": "Hello world, Foo Bar", // A meanful description for developer, it should NOT be used as i18n directly
    "i18nText": "Hello, {firstName} {lastName}",
    "i18nData": {
        "firstName": "Foo",
        "lastName": "Bar"
    },
    "type": "error",
    "context": {}
  }
]
```

**Describe alternatives you've considered**

No

**Additional context**

React i18n-next: https://react.i18next.com/misc/using-with-icu-format

**Comment by aeneasr** [comment]
Is it possible that you confused this with ORY Kratos?

**Comment by UkonnRa** [comment]
Ah, post to the wrong project, sorry :-(
