### ISSUE TITLE
JSON Web Key Sets API & Documentation

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#2045]
**Describe the bug**
Where is the REST API documentation indicating jwks endpoint (required for Open ID Connect) https://tools.ietf.org/html/rfc7517

I came across this documentation link https://www.ory.sh/hydra/docs/jwks
but noticed that link to JSON Web Keys API and  REST API Documentation are broken and returns 404 error.
Documentation needs to be corrected with valid links.
Also, please advise how do we access jwks endpoint so that oauth2 clients can verify the authenticity of ID tokens issued by the server?

**Reproducing the bug**
1. Access this page -  https://www.ory.sh/hydra/docs/jwks
2. Access documentation link to REST API Documentation and JSON Web Keys API

N/A

_Server logs_
N/A

_Server configuration_
N/A

**Expected behavior**

Link should provide documentation related to jwks endpoint required by OpenID Connect specification.

**Environment**
- Version: v1.7.4

**Additional context**
Also, please advise how do we access jwks endpoint?

**Comment by aeneasr** [comment]
The correct docs URL is: https://www.ory.sh/hydra/docs/reference/api/

Can you fix the link with a PR? :)

**Comment by sagarshah1983** [comment]
Sure, if you could please point me to correct location of file. I am newbie to "Go" and still trying to find where is the source of documentation page https://www.ory.sh/hydra/docs/jwks. :-)

**Comment by aeneasr** [comment]
There is an edit button at the bottom of the page :)

**Comment by sagarshah1983** [comment]
@aeneasr - I have created a PR for this documentation link fix https://github.com/ory/hydra/pull/2047
Let me know, if anything else is required to address this issue.
Thanks.
