### ISSUE TITLE
Reusing access tokens & caching

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#2046]
**Is your feature request related to a problem? Please describe.**
From optimization of disk & the performance point of view, do we see a need to reuse existing active access tokens instead of generating a new one every time a request comes to get access token.
Maybe it can be cached with external caching providers and once it expires from cache, we generate a new one and store in database?

A clear and concise description of what the problem is. 
I just tried getting access token with client_credentials, which is by default valid for 1 hour. In this 1 hour, every time I hit this endpoint, I get a new token even when old tokens are valid. Could it support reusing existing active/valid tokens from cache (for faster performance)? Is there a configuration already available in hydra that supports that with or without cache?

**Describe the solution you'd like**
I would prefer to check, if any existing active/valid token is available for the request that came through. If one is available then return that instead of creating a new one.

**Describe alternatives you've considered**
Alternative:  In case, this cannot be done for any reason, we should have a way to purge/delete the expired tokens from database tables like hydra_oauth2_access, as as db space is freed up.

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by aeneasr** [comment]
No, this would be against the spec. The client needs to make sure to use and store the tokens and refresh them when they become invalid.

**Comment by sagarshah1983** [comment]
Ok. Then does the table get cleaned up any time after token is expired. I am thinking from perspective of disk usage and database size when there are millions of users with access token for limited time and renewing those after the old one is expired.
Is there any approach to clean up expired tokens from database?

**Comment by aeneasr** [comment]
https://www.ory.sh/hydra/docs/cli/hydra-token-flush/

**Comment by sagarshah1983** [comment]
Thank you. That helps!
