### ISSUE TITLE
hydra serve reports 404 URL for config.yaml example (v1.7.4)

### ISSUE THREAD

**Issue by nessita** [ory/hydra#2065]
I've downloaded the hydra binary following the installation doc:

```
ory/hydra info checking GitHub for latest tag
ory/hydra info found version: 1.7.4 for v1.7.4/linux/64-bit
ory/hydra info installed ./bin/hydra
```

When executing `hydra serve` the returned help includes the following bits:

```
## Configuration

ORY Hydra can be configured using environment variables as well as a configuration file. For more information
on configuration options, open the configuration documentation:

>> https://github.com/ory/hydra/blob/ff980e6d6c5a5f17b7a0c55e7593a9ec75ea76ef/docs/config.yaml <<
```

but the URL above is a 404.

**Comment by tacurran** [comment]
@nessita please check https://www.ory.sh/hydra/docs/reference/configuration/

If you want to solve this issue and open a PR, start here https://github.com/ory/hydra/blob/master/cmd/clidoc/main.go
and here
https://github.com/ory/hydra/blob/master/cmd/serve.go
