### ISSUE TITLE
Report expired JWT assertion token to client

### ISSUE THREAD

**Issue by Marlinc** [ory/hydra#2066]
**Is your feature request related to a problem? Please describe.**

When using JWKS based client authentication you provide a JWT token as assertion that gets verified by Hydra after which it issues an access token for the client. Hydra doesn't provide a nice error message to the client when the JWT token assertion has expired, instead it returns in internal server error.

**Describe the solution you'd like**

Hydra already has quite a few validations for JWT token assertions that return nice useful error messages to the client, like for example a missing `kid` claim. I'd like to see the same for an expired JWT token.

**Additional context**

This is the error that gets logged by Hydra when an expired JWT token assertion gets sent:
```
time=2020-09-18T22:06:37Z level=error msg=An error occurred func=github.com/ory/hydra/x.LogError file=/home/ory/x/errors.go:49 audience=application error=map[message:Token is expired trace:stack trace could not be recovered from error type *errors.errorString] http_request=map[headers:map[accept-encoding:gzip user-agent:Go-http-client/2.0 x-forwarded-for:<source ip>, ::1 x-forwarded-proto:https] host:<some-host> method:POST path:/oauth2/token query:<nil> remote:[<some-ip>]:54662 scheme:http] service_name= service_version=
```

**Comment by divbhasin** [comment]
I can have a go at this!

**Comment by aeneasr** [comment]
Yes, please do! :)

**Comment by divbhasin** [comment]
I'm a bit confused on how to test this. @Marlinc are you using `token_endpoint_auth_method=private_key_jwt`? Can you also link your hydra config?

**Comment by dibyajyotibehera** [comment]
@Marlinc @aeneasr  - i could replicate the error . Looks like debug error messages  are  possible only with enabling following env variables -

OAUTH2_EXPOSE_INTERNAL_ERRORS=true;
OAUTH2_INCLUDE_LEGACY_ERROR_FIELDS=true

once you set the above env variables , you can get error_debug field as below .

```
{
    "error": "error",
    "error_description": "The error is unrecognizable",
    "status_code": 500,
    "error_debug": "Token is expired"
}
```

Should we close this issue ?

**Comment by aeneasr** [comment]
Maybe you could add a section in the docs about this? That would be awesome! Preferably here https://www.ory.sh/hydra/docs/debug or here: https://www.ory.sh/hydra/docs/debug/config

**Comment by dibyajyotibehera** [comment]
@aeneasr - Please review - https://github.com/ory/hydra/pull/2680

**Comment by aeneasr** [comment]
Thank you!
