### ISSUE TITLE
Prometheus endpoint should not require x-forwarded-proto header

### ISSUE THREAD

**Issue by amihalj** [ory/hydra#2072]
Similar to heathcheck, metrics endpoint should not require x-forwarded-proto.

We are running hydra service in K8 cluster as TLS terminated but we are unable to scrape metrics due to issue with header. Is there a way to exclude it like in health routes?

thank you,
Ante

**Comment by aeneasr** [comment]
Makes sense!

**Comment by amihalj** [comment]
I will provide PR, please take a loot at it and include in next release if possible.

thanks.

**Comment by amihalj** [comment]
Hi @aeneasr , will this PR be included in 1.8.x version or it will wait for 1.9.0 version?  we would rather have it sooner if it is possible. thank you

**Comment by aeneasr** [comment]
Hopefully we get 1.8 properly released today, had some upstream issues - so this will be 1.8.x
