### ISSUE TITLE
OpenID Connect Discovery returns incorrect URLs

### ISSUE THREAD

**Issue by nessita** [ory/hydra#2078]
I'm running the Ory Hydra server using the linux binary and I have the `serve.public.port` set to `6909` in the config. The server logs confirm that setting as follows:

```
{
  "audience": "application",
  "file": "/home/ory/cmd/server/handler.go:306",
  "func": "github.com/ory/hydra/cmd/server.serve.func1",
  "level": "info",
  "msg": "Setting up http server on 0.0.0.0:6909",
  "service_name": "",
  "service_version": "",
  "time": "2020-09-30T20:11:12Z"
}
```
When requesting the http://localhost:6909/.well-known/openid-configuration, the returned URLs have an incorrect `4444` port as follows:

```
$ curl http://localhost:6909/.well-known/openid-configuration | jq .
{
  "issuer": "https://localhost:4444/",
  "authorization_endpoint": "https://localhost:4444/oauth2/auth",
  "registration_endpoint": "http://localhost:5000/create_client",
  "token_endpoint": "https://localhost:4444/oauth2/token",
  "jwks_uri": "https://localhost:4444/.well-known/jwks.json",
  "subject_types_supported": [
    "public"
  ],
  "response_types_supported": [
    "code",
    "code id_token",
    "id_token",
    "token id_token",
    "token",
    "token id_token code"
  ],
  "claims_supported": [
    "sub",
    "email",
    "name",
    "username"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "client_credentials",
    "refresh_token"
  ],
  "response_modes_supported": [
    "query",
    "fragment"
  ],
  "userinfo_endpoint": "https://example.org/my-custom-userinfo-endpoint",
  "scopes_supported": [
    "offline_access",
    "offline",
    "openid",
    "email",
    "profile"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_post",
    "client_secret_basic",
    "private_key_jwt",
    "none"
  ],
  "userinfo_signing_alg_values_supported": [
    "none",
    "RS256"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "require_request_uri_registration": true,
  "claims_parameter_supported": false,
  "revocation_endpoint": "https://localhost:4444/oauth2/revoke",
  "backchannel_logout_supported": true,
  "backchannel_logout_session_supported": true,
  "frontchannel_logout_supported": true,
  "frontchannel_logout_session_supported": true,
  "end_session_endpoint": "https://localhost:4444/oauth2/sessions/logout"
}
```

**Reproducing the bug**

1. Download the hydra binary, and run it with a config so the `serve.public.port` value is not the `4444` default, for example `6909`
2. Make API Request to with `curl http://localhost:6909/.well-known/openid-configuration`
3. Request returns a successful response but URLs point to `localhost:4444` instead of `localhost:6909`

_Server configuration_

```yaml
server:
    public:
        port: 6909
```

**Expected behavior**

The URLs from the OpenID Connect Discovery results point to the correct URL, which in this case should be under the `localhost:6909` domain.

**Environment**

- Version: v1.7.4
- Environment: Ubuntu running the hydra binary

**Comment by nessita** [comment]
This issue seems to be broader than just the OpenID Connect Discovery response, when implementing the login endpoint and fetching the login challenge information, the returned `request_url` also points to an incorrect `https:localhost:4444` domain.

**Comment by aeneasr** [comment]
Looks like that is the value of `urls.self.issuer` but hard to say because the full config is missing in the issue description!

**Comment by nessita** [comment]
Oh @aeneasr you are right, I'm so silly!

I'm then closing this bug report since it's invalid. One question though, if I may ask: under which circumstances does it make sense to have the public service running in one domain/port and the issuer set to other value?
