### ISSUE TITLE
Docs: rendering issue (?) on reference REST API

### ISSUE THREAD

**Issue by nessita** [ory/hydra#2092]
When browsing the reference documentation for the REST API, there are some texts that are either incomplete or rendered/generated incorrectly. Examples:

```html
<table>
   <thead>
      <tr>
         <th>Parameter</th>
         <th>In</th>
         <th>Type</th>
         <th>Required</th>
         <th>Description</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>body</td>
         <td>body</td>
         <td>object</td>
         <td>false</td>
         <td>none</td>
      </tr>
      <tr>
         <td>» token</td>
         <td>body</td>
         <td>string</td>
         <td>true</td>
         <td>The string value of the token. For access tokens, this</td>
      </tr>
      <tr>
         <td>» scope</td>
         <td>body</td>
         <td>string</td>
         <td>false</td>
         <td>An optional, space separated list of required scopes. If the access token was not granted one of the</td>
      </tr>
   </tbody>
</table>
```
Or:

```html


<table>
   <thead>
      <tr>
         <th>Status</th>
         <th>Meaning</th>
         <th>Description</th>
         <th>Schema</th>
      </tr>
   </thead>
   <tbody>
      <tr>
         <td>204</td>
         <td><a href="https://tools.ietf.org/html/rfc7231#section-6.3.5" target="_blank" rel="noopener noreferrer">No Content</a></td>
         <td>Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is</td>
         <td></td>
      </tr>
      <tr>
         <td>typically 201.</td>
         <td>None</td>
         <td></td>
         <td></td>
      </tr>
      <tr>
         <td>401</td>
         <td><a href="https://tools.ietf.org/html/rfc7235#section-3.1" target="_blank" rel="noopener noreferrer">Unauthorized</a></td>
         <td>genericError</td>
         <td><a href="#schemagenericerror">genericError</a></td>
      </tr>
      <tr>
         <td>500</td>
         <td><a href="https://tools.ietf.org/html/rfc7231#section-6.6.1" target="_blank" rel="noopener noreferrer">Internal Server Error</a></td>
         <td>genericError</td>
         <td><a href="#schemagenericerror">genericError</a></td>
      </tr>
   </tbody>
</table>
```

**Reproducing the bug**

Visit https://www.ory.sh/hydra/docs/reference/api#introspect-oauth2-tokens (version 1.7 at the time of this writing) and look for incomplete phrases like:

`The HTTP status code for empty responses is`
`The string value of the token. For access tokens, this`
`An optional, space separated list of required scopes. If the access token was not granted one of the`

**Expected behavior**

I'm not sure about what to expect here. Considering that the detailed description can be read a few lines after the parameters table (for the first example), it may be the case where internally the "docstrings" for the methods need to follow a strict spec about formatting, so a first summary line can be showed in the table, and the detailed and longer explanation in the paragraphs below it.

For example, in Python, the PEP-257 defines how the multi-line docstrings should be formatted so documentation can be properly generated from it: there should be a one-liner summary no longer than 79cols, then a blank line, and then one or more paragraphs providing details about the method/class/params/etc. This way a doc generation process could choose to use the one-liner summary to render it in the parameters table, and the more detailed remaining to be put n the "Detailed description" section.

**Comment by aeneasr** [comment]
Just to understand the issue - do you mean that some of the content is hidden in the scrollbar, like here?

<img width="1129" alt="Bildschirmfoto 2020-10-06 um 13 09 03" src="https://user-images.githubusercontent.com/3372410/95194082-2085cc00-07d5-11eb-9a0a-ceab3d5a138e.png">

If so I guess that we need to make the table itself scrollable because right now, the scroll bar is at the very bottom!

**Comment by nessita** [comment]
> Just to understand the issue - do you mean that some of the content is hidden in the scrollbar, like here?

No, I mean that there is documentation content/phrases that is incomplete, and those match with the source code as follows:

 * for every truncated doc line, there is a multiline Go comment-documentation in the source code, and only the first Go comment-documentation line is rendered in the doc pages.

Example:

![Screenshot_2020-10-02 REST API ORY Hydra](https://user-images.githubusercontent.com/124304/95196350-4b105e80-07ae-11eb-8193-95e930d61f14.png)

The matching source code for that is: https://github.com/ory/hydra/blob/deb15740f32edb602a2e4592d79ebb9c42433f25/doc_swagger.go#L51

Another example:

![Screenshot_2020-10-02 REST API ORY Hydra(1)](https://user-images.githubusercontent.com/124304/95196470-7eeb8400-07ae-11eb-90a4-34fd8a11d809.png)

with the matching code being: https://github.com/ory/hydra/blob/077c54ab5143041d4189d5e79ca52920b91bc9b0/oauth2/doc.go#L293

**Comment by nessita** [comment]
For the sake of clarity, the tables in the examples from the previous comment, do not have a scrollbar (neither horizontal nor vertical), the issue I believe is how the Go comment-docs are fetched/parsed and used to render the HTML.

**Comment by aeneasr** [comment]
Oh I see - looks like those are cut off after the newline. That definitely needs some investigation! Did you check the api.swagger.json if the problem is there as well?

**Comment by aeneasr** [comment]
@vinckr can you take a look at this please? I can help if you need it

**Comment by nessita** [comment]
> Did you check the api.swagger.json if the problem is there as well?

I did not, and this week is very busy for me so it's likely I would not be able to investigate. Is the api.swagger.json a generated file? (seems like it from some simple GH searches).

**Comment by vinckr** [comment]
> Did you check the api.swagger.json if the problem is there as well?
It looks fine there `"The HTTP status code for empty responses is\ntypically 201."`
But apparently after the \n it gets cut off. 
It doesn't happen in the bigger scrollable tables.
Its the same for [kratos](https://www.ory.sh/kratos/docs/reference/api#responses-6), 
it seems to be at "responses"
`"description": "The string value of the token. For access tokens, this\nis the \"access_token\" value returned from the token endpoint\ndefined in OAuth 2.0. For refresh tokens, this is the \"refresh_token\"\nvalue returned."`
shrinks to
`The string value of the token. For access tokens, this` 
[here](https://www.ory.sh/hydra/docs/reference/api/#parameters-27)
but then there is a detailed description underneath so maybe this is intended in that case and somehow went over to the others?

**Comment by aeneasr** [comment]
Ok no this looks like a bug to me - could you point me to the exact lines of code for these errors?

**Comment by vinckr** [comment]
https://github.com/ory/hydra/blob/1e1c1c138fe971b167b2c89594c89510a07281d1/docs/api.swagger.json#L1071
https://github.com/ory/hydra/blob/dd9c892f67ec96883d1a99bb1beb2a148912cad2/.schema/api.swagger.json#L1564
https://github.com/ory/hydra/blob/dd9c892f67ec96883d1a99bb1beb2a148912cad2/.schema/api.swagger.json#L1571
These are lines that get cut.
It doesnt happen in the big properties table, where there is much more text so idk.

>The HTTP status code for empty responses is

The cut responses line I only found here:
https://github.com/ory/hydra/blob/dd9c892f67ec96883d1a99bb1beb2a148912cad2/.schema/api.swagger.json#L1768

Is this helpful or should I look somewhere else?

**Comment by aeneasr** [comment]
Yes this is helpful. It looks like the newline somehow causes the render output to fail. Will probably have to investigate manually...
