### ISSUE TITLE
5 min tutorial doc is confusing

### ISSUE THREAD

**Issue by dharmendrakariya** [ory/hydra#2100]
in 5 min tutorial doc is saying something and the actual thing is something else, please make it correct.
![actual](https://user-images.githubusercontent.com/22043860/95167534-79516680-07cd-11eb-9270-3d220ccc5b87.png)
![doc](https://user-images.githubusercontent.com/22043860/95167536-79e9fd00-07cd-11eb-8a1a-86ef3c6cea55.png)

**Comment by dharmendrakariya** [comment]
here its stating that, "setting up home route on http://127.0.0.1:445/ and callback on http://127.0.0.1:445/callback"
but in actual its different

**Comment by vinckr** [comment]
Thanks for pointing that out to us!

https://github.com/ory/hydra/pull/2102
https://github.com/ory/hydra/pull/2101

If you ever come across something like that again, feel free to open a pull request to change it :). 
The docs are built from the files in hydra/docs/docs/, so they have to be changed there (and in hydra/docs/versioned_docs/ too, to correct the current build).
