### ISSUE TITLE
Support AWS X-Ray as distributed trace

### ISSUE THREAD

**Issue by simpleway** [ory/hydra#2130]
**Is your feature request related to a problem? Please describe.**

AWS Fargate and ECS is a popular container cluster. Jaeger and datadog are not native to AWS, require additional setup, cost and operations. AWS X-Ray support distributed tracing for ECS and AWS lambda. A custom lambda can be developed for oauth2 token validation against Hydra. Currently tracing between lambda authorizer and hydra go to separate places, X-Ray and Jaeger.

**Describe the solution you'd like**
OpenCensus support export to AWS X-Ray: https://opencensus.io/exporters/supported-exporters/go/xray/. Now OpenTracing and OpenCensus are merged to OpenTelemetry. It will be nice to hydra support tracing to AWS X-Ray, so tracing lambda authorizer and hydra can be displayed in single place: X-Ray.

**Comment by aeneasr** [comment]
Sorry for the late reply, sounds like a good idea! Would you be open to contribute that?

**Comment by simpleway** [comment]
Sorry for late response. I'm new to golang, might take a while to get comfortable with. But I'd like to contribute, any guidelines of this project to follow?

**Comment by aeneasr** [comment]
Contributing guidelines can be found here: https://github.com/ory/hydra/blob/master/CONTRIBUTING.md

But other than that just give it a go :)

**Comment by aeneasr** [comment]
It's possible that you need to change something in github.com/ory/x

**Comment by driverpt** [comment]
This can be done in the scope of #2597 , since AWS has AWS OTEL Collector which natively integrates with XRay
