### ISSUE TITLE
ERROR: yaml.parser.ParserError: while parsing a block mapping

### ISSUE THREAD

**Issue by cawfree** [ory/hydra#2139]
Hey everyone, thanks so much for this awesome repo.

It appears that `quickstart.yml` is failing to parse correctly in [`0f0c5095fa1bc9d77a784d8f16d5ca675c92c913`](https://github.com/ory/hydra/commit/0f0c5095fa1bc9d77a784d8f16d5ca675c92c913).

```sh
$ docker-compose -f quickstart.yml     -f quickstart-postgres.yml     up --build
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./quickstart.yml", line 13, column 1
expected <block end>, but found ':'
  in "./quickstart.yml", line 81, column 1
```

**Comment by aeneasr** [comment]
Thank you! Looks like the automation is going haywire 😅
