### ISSUE TITLE
oauth2: resource owner password credentials proposal

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#214]
The resource owner password credentials flow, although discouraged, is something that has been requested by the community for several times. The reasoning for discouraging this flow are:

> The resource owner password credentials grant type is often used for
>    legacy or migration reasons.  It reduces the overall risk of storing
>    usernames and passwords by the client but does not eliminate the need
>    to expose highly privileged credentials to the client.
> 
> This grant type carries a higher risk than other grant types because
>    it maintains the password anti-pattern this protocol seeks to avoid.
>    The client could abuse the password, or the password could
>    unintentionally be disclosed to an attacker (e.g., via log files or
>    other records kept by the client).
> 
>   Additionally, because the resource owner does not have control over
>    the authorization process (the resource owner's involvement ends when
>    it hands over its credentials to the client), the client can obtain
>    access tokens with a broader scope than desired by the resource
>    owner.  The authorization server should consider the scope and
>    lifetime of access tokens issued via this grant type.
> 
>   The authorization server and client SHOULD minimize use of this grant
>    type and utilize other grant types whenever possible.

As Hydra does not talk directly to the identity provider nor being an identity provider itself, there is some trickery to be involved for usage of this flow.
## Consent Flow

Hydra could use a consent token, to verify user credentials.
1. Hydra creates an encrypted JWT with something like `username: "foo", password: "bar", flow: "resource owner password credentials"` using a PSK or the IDP's public key
2. Hydra redirects to the IDP
3. The IDP programmatically validates the JWT and the password credentials
4. The IDP issues a consent token and redirects back to hydra
5. Hydra issues the access token
## Proprietary IDP API

Hydra could require IDPs to implement an HTTP API, which it uses to validate tokens.

**Comment by arekkas** [comment]
Here is an exemplary request flow for this grant type:

* OAuth2 client requests `/oauth2/token?grant_type=resource_owner_password_credentials` (ropc)
* Hydra redirects client to `http://consent.app/consent?challenge=....` containing a key indicating that this is a a ropc grant and username/password
* Consent app validates username/password and generates consent response, redirect back to  `/oauth2/token?grant_type=resource_owner_password_credentials&consent=...`
* Hydra creates access token / refresh token

**Comment by jainh** [comment]
when this will be added to release ?
Thank you.

**Comment by arekkas** [comment]
I'm mostly struggling with a decision on the way this flow works as it will probably be how it's going to look like in the final release. This is simply not straight forward (from a security perspective too) so it needs some very good thinking and reasoning. This is why this issue is not resolved yet.

**Comment by pasikarkkainen** [comment]
Hmm.. I thought the Resource Owner Password Grant flow can't use redirects, because it's not (necessarily) web-based or interactive? 

https://tools.ietf.org/html/rfc6749#section-4.3

did I miss something?

**Comment by arekkas** [comment]
The reasoning behind it was that usually any http client also supports following redirects. The trade off is if we either want people to implement another (REST) API for authentication, or if we want them to adapt their consent flows, or if we actually don't want this flow at all as it's intended for legacy code bases only anyways.

**Comment by pasikarkkainen** [comment]
Ok, that explains. And it makes sense. I think it's better to support Resource Owner Password Credentials Grant flow with the added requirement of client needing to follow redirects, than not supporting it at all.

So +1 from me :)

**Comment by arekkas** [comment]
Closing, see #417
