### ISSUE TITLE
Newest install script fails to install v1.8.5 (latest stable)

### ISSUE THREAD

**Issue by Shne** [ory/hydra#2145]
**Describe the bug**

Using the newest install script from https://github.com/ory/hydra/blob/master/install.sh fails to install version v1.8.5 of Hydra.

**Reproducing the bug**

1. run `bash <(curl https://raw.githubusercontent.com/ory/hydra/master/install.sh) -b . -d v1.8.5` as described at https://www.ory.sh/hydra/docs/install/ but with version v1.8.5 and debug output enabled
2. output is
```
ory/hydra info checking GitHub for tag 'v1.8.5'
ory/hydra debug http_download https://github.com/ory/hydra/releases/v1.8.5
ory/hydra info found version: 1.8.5 for v1.8.5/linux/64bit
ory/hydra debug downloading files into /tmp/tmp.rD4Ba6Jc0X
ory/hydra debug http_download https://github.com/ory/hydra/releases/download/v1.8.5/hydra_1.8.5-sqlite_linux_64bit.tar.gz
ory/hydra debug http_download_curl received HTTP status 404
```

**Expected behavior**
I would have expected it to work, not get a 404 error.

**Environment**
- Linux

**Additional context**

I'm guessing that the issue is the addition of '-sqlite' to the download path, introduced here https://github.com/ory/hydra/commit/c614c0b98f2bca897828848fa5088f8eed125704#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44f
Because I can see in the assets for the releases, that release 1.8.5 does not contain any assets with '-sqlite' but 1.9.0-alpha.1 does: https://github.com/ory/hydra/releases
Since earlier releases also do not seem to include the '-sqlite' in any of their assets, I expect this to break for versions below 1.8.5 as well.

I've realized, while writing this issue, that a 1.8.5 version of the install script exists at https://raw.githubusercontent.com/ory/hydra/v1.8.5/install.sh but that is not at all clear from the documentation, and I would have expected the install script to be backwards-compatible. I mean, why would it take the version as a parameter if not for compatibility with multiple versions?

**Comment by aeneasr** [comment]
Thank you for the report! We should probably update the install script instructions to contain the tag. The breaking change in the binary naming format is indeed caused by the 1.9.0 pre-release.
