### ISSUE TITLE
Client update changes it's PK to 0

### ISSUE THREAD

**Issue by clement-buchart** [ory/hydra#2148]
**Describe the bug**

In v1.9.0-aplha.1, it seems when updating a client, it's PK is set to 0.

I'm not familiar with the pop persistence layer, but maybe here `cl` does not have the PK, and it should be copied from `o` which is retrieved from the database, so the PK does not change on update : 
https://github.com/ory/hydra/blob/97bc47d63940fabd0bec65b3e8051fc171d38011/persistence/sql/persister_client.go#L23-L42

**Reproducing the bug**

On a fresh hydra instance 
- Create 2 clients : they are given PK 1 and 2
- Update one of the clients, it's PK changes to 0
- Try to update the other -> duplicate key value violates unique constraint "hydra_client_pkey"

_Server logs_

```
duplicate key value violates unique constraint "hydra_client_pkey"
```

**Expected behavior**

PK is not set to 0 on update

**Environment**

- Version: v1.9.0-alpha.1

**Additional context**

I was using the alpha version by 'mistake' in a non-production environment, hope it's ok to report issue on an alpha.

Cheers.

**Comment by aeneasr** [comment]
Thank you for the report, this is indeed a pretty serious bug and we'll try to address it ASAP! And it's absolutely ok to report this.

@zepatrik can you please take a look and fix this? Please also add tests covering this and also add tests for all other implementations which use the new primary key set up introduced by gobuffalo/pop.
