### ISSUE TITLE
Doc improvement : how kratos can be used as the user manager of hydra

### ISSUE THREAD

**Issue by pc-tradelab** [ory/hydra#2159]
Hi,

I can't find how to integrate hydra with kratos to create and manage new users. There is a guide "Implementing the user interface", however I don't want to implement a user interface but use the kratos project !
Conversely, the kratos project does not show explicitly how to integrate the hydra project. It's a bit frustrating since we would like to use the whole ecosystem !

**Comment by aeneasr** [comment]
Closing as a duplicate of: https://github.com/ory/kratos/issues/273
