### ISSUE TITLE
Add list of possible errors to REST API documentation

### ISSUE THREAD

**Issue by cgrimal** [ory/hydra#2166]
**Is your feature request related to a problem? Please describe.**

In our application, we want to properly handle the response error when calling the REST API.
For instance, in some scenarios, the call to the [authorize endpoint](https://www.ory.sh/hydra/docs/reference/api/#the-oauth-20-authorize-endpoint) `/oauth2/auth` redirects to our callback URL, with `error` and `error_description` parameters. 
Our problem is that we don't know the list of possible values for these parameters.

**Describe the solution you'd like**

An exhaustive list of possible error responses for all REST API endpoints.

**Describe alternatives you've considered**

I've tried reading [RFC-6749](https://tools.ietf.org/html/rfc6749) (linked in the description of the authorized endpoint) but wasn't able to find such a list.

**Comment by aeneasr** [comment]
Yes, good idea. It's a bit tricky to document this in Swagger but should nontheless be documented. You can however find a list of all error codes [here](https://github.com/ory/fosite/blob/master/errors.go).

**Comment by cgrimal** [comment]
Thank you @aeneasr for the link, it is very useful and is quite literally what I as looking for (I tried to dig in the code myself but wasn't able to find it).

**Comment by aeneasr** [comment]
Nice! If you're down to add this stuff to swagger let me know and I can point you in the right direction!

**Comment by idivyanshbansal** [comment]
If I am going correct then can I continue on this issue?

![screencapture-github-idivyanshbansal-html-404-blob-main-README-md-2021-10-07-17_01_16](https://user-images.githubusercontent.com/86911142/136376004-7821ba5d-4710-45db-993d-467997ea365d.png)

**Comment by aeneasr** [comment]
I think this is done now!
