### ISSUE TITLE
Hydra Docs wrong info at /concepts/consent

### ISSUE THREAD

**Issue by Jalr4ever** [ory/hydra#2167]
Hi, developer guys:

I just found one confusing description in the hydra docs, (see https://www.ory.sh/hydra/docs/concepts/consent)

Is those description supposed to be about `consent challenge`, but not `login challenge` 

snapshot:
![image](https://user-images.githubusercontent.com/23929139/98321779-e51f2d00-2020-11eb-9da0-1e6f49fac510.png)

**Comment by sinambela** [comment]
i think ory hydra documentation is very confusing and also difficult to understand. Because I get the same problem like you have. more better to find out another oauth server to replace ory hydra. Documentation is  too verbose but less detail.

**Comment by zepatrik** [comment]
Right, looks like this paragraph was a copy/paste error and should just be deleted. If you find any mistakes in the documentation you know how to fix, we appreciate contributions a lot :wink:

**Comment by Jalr4ever** [comment]
> i think ory hydra documentation is very confusing and also difficult to understand. Because I get the same problem like you have. more better to find out another oauth server to replace ory hydra. Documentation is too verbose but less detail.
From now on, there are 
At this moment, we cant't find anything else for our proj,  as slight and large-scale using as ORY Hydra, new spring authorization server is in experimental version.
