### ISSUE TITLE
SDK documentation for javascript client returns a 404 page not found

### ISSUE THREAD

**Issue by CSRaghunandan** [ory/hydra#2171]
API documentation for nodejs client for hydra returns a 404 

The link mentioned in the documentation: https://github.com/ory/hydra/blob/master/sdk/js/swagger/README.md

**Comment by zepatrik** [comment]
Right, the whole page needs an overhaul https://github.com/ory/hydra/blob/master/docs/docs/sdk/js.md
The SDKs are now at https://github.com/ory/sdk/tree/master/clients/hydra/typescript

**Comment by vinckr** [comment]
What exactly needs to be done here? 

Change all links in the documentation from {{Project}}/sdk  to ory/sdk/{{Project}} ?

Should the existing documentation also be moved to ory/sdk/{{Project}}; 
or just point the sdk packages to ory/sdk and have the rest of documentation from {{Project}}/docs?

**Comment by zepatrik** [comment]
1. change all the links to point to the right repo
2. update the javascript page to make clear that it is a typescript and javascript sdk, just get inspired by the text from the sdk readme :wink:

**Comment by aeneasr** [comment]
Resolved on master :)
