### ISSUE TITLE
Missing  documentation for config key oidc.subject_identifiers.supported_types

### ISSUE THREAD

**Issue by gpor0** [ory/hydra#2182]
**Describe the bug**

After Hydra startup log warns about configuration key deprecation. There is no records in documentation reference (https://www.ory.sh/hydra/docs/reference/configuration/) about oidc.subject_identifiers.supported_types.

**Reproducing the bug**

Start Hydra Hydra v1.9.0-alpha.2 with oidc.subject_identifiers.enabled set to public

_Server logs_

```
Configuration key oidc.subject_identifiers.enabled is deprecated and will be removed in a future release. Use key oidc.subject_identifiers.supported_types instead! audience=application service_name= service_version=
Thank you for using ORY Hydra v1.9.0-alpha.2!
```
_Configuration_

```yaml
oidc:
  subject_identifiers:
    enabled:
       - public
```

**Expected behavior**

oidc.subject_identifiers.supported_types should be documented.

**Comment by zepatrik** [comment]
Right, this has to be changed here: https://github.com/ory/hydra/blob/master/.schema/config.schema.json#L503-L571

This change was introduced with #1706 but forgot to update the config schema.

**Comment by aeneasr** [comment]
Closed via https://github.com/ory/hydra/pull/2211
