### ISSUE TITLE
Update client fail

### ISSUE THREAD

**Issue by oldbig** [ory/hydra#2191]
**Describe the bug**

Update client with endpoint(DB is postgresql), fail, after debug, I found always set pk column of client to 0, this pk exists cause fail.

**Reproducing the bug**

 
1. update any existing client in any field value

**Comment by zepatrik** [comment]
This was fixed in #2150 right?

**Comment by oldbig** [comment]
Hi @zepatrik 
Yes, I found it is fixed, thank you.
