### ISSUE TITLE
Internal Server Error when deleting OAuth client

### ISSUE THREAD

**Issue by mpanne** [ory/hydra#2192]
**Describe the bug**

There was one OAuth client on our production system which failed to be deleted several times. When trying to delete the client via the REST API, an internal server error occurred after 1 minute. We have retried the delete action 30 to 40 times without success. Today the client could be deleted successfully without any changes made. 

**Reproducing the bug**

The bug could only be reproduced for this specific client.  

_Request_

```
curl -k -X DELETE 'https://<hydra-domain>/admin/clients/<client-id>
```

_Server log_

```
time=2020-11-23T11:49:31Z level=info msg=started handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br user-agent:PostmanRuntime/7.26.8 x-forwarded-for:172.20.6.142 x-forwarded-proto:https x-request-id:b3656695cd1a42b65296f8155cbe8787] host:hydra.bosch-iot-suite.com method:DELETE path:/clients/8c362907-33d8-44c1-a149-17e17c51d63e query:<nil> remote:172.20.79.109:60222 scheme:https]

time=2020-11-23T11:50:31Z level=error msg=An error occurred while handling a request audience=application error=map[message:read tcp 172.20.99.233:52634->172.20.103.212:5432: i/o timeout] http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br user-agent:PostmanRuntime/7.26.8 x-forwarded-for:172.20.6.142 x-forwarded-proto:https x-request-id:b3656695cd1a42b65296f8155cbe8787] host:hydra.bosch-iot-suite.com method:DELETE path:/clients/8c362907-33d8-44c1-a149-17e17c51d63e query:<nil> remote:172.20.79.109:60222 scheme:https] http_response=map[status_code:500] service_name= service_version=

time=2020-11-23T11:50:31Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br user-agent:PostmanRuntime/7.26.8 x-forwarded-for:172.20.6.142 x-forwarded-proto:https x-request-id:b3656695cd1a42b65296f8155cbe8787] host:hydra.bosch-iot-suite.com method:DELETE path:/clients/8c362907-33d8-44c1-a149-17e17c51d63e query:<nil> remote:172.20.79.109:60222 scheme:https] http_response=map[status:500 text_status:Internal Server Error took:59.988664255s]
```

_Client info_

```
{
   "client_id" : "8c362907-33d8-44c1-a149-17e17c51d63e",
   "client_name" : "some client name",
   "metadata" : null,
   "audience" : [],
   "subject_type" : "public",
   "policy_uri" : "",
   "contacts" : [],
   "tos_uri" : "",
   "owner" : "",
   "logo_uri" : "",
   "userinfo_signed_response_alg" : "none",
   "client_uri" : "",
   "client_secret_expires_at" : 0,
   "allowed_cors_origins" : [],
   "updated_at" : "2020-04-14T14:00:33Z",
   "scope" : "",
   "jwks" : {},
   "grant_types" : [
      "client_credentials"
   ],
   "response_types" : [],
   "token_endpoint_auth_method" : "client_secret_post",
   "created_at" : "2020-04-14T14:00:33Z",
   "redirect_uris" : []
}
```

**Expected behavior**

Client deletion succeeds with status 204.

**Environment**

- Version: v1.7.4
- Environment: Docker, k8s

**Additional context**

- No descriptive error or stack trace is provided by hydra even if `oauth2.expose_internal_errors` is set to true and log level is debug. Is there any way to get more information about the internal server error? 
- Could you maybe give us some insights what happens on client deletion and what could lead to the internal server error? 
- Maybe the deletion runs in some timeout, since it always failed after ~1 min?

**Comment by aeneasr** [comment]
Hm that is very strange - what happens if you set `LOG_LEVEL=trace`? Also, upgrading to ORY Hydra 1.8x might help with some debug messages.

**Comment by mpanne** [comment]
We didn't try setting log level to trace tbh. Now that the client is deleted, we cannot reproduce the bug any longer. 
Could you maybe give us some insights anyway? What other resources are deleted on client deletion and might that cause a timeout issue?

**Comment by aeneasr** [comment]
The most likely source is that a FK relation failed. How long have you been running ORY Hydra and what was your initial version?

**Comment by mpanne** [comment]
We started with version v1.0 (v1.0.9+oryOS.12) which was the running version at the time this client was created.

**Comment by aeneasr** [comment]
Yeah it is possible that there are some old records or migrations which didn't properly fix foreign key relations. Everything should be running smoothly now! I think we can close this and if you encounter any other hick ups feel free to reopen or create another issue!

**Comment by mpanne** [comment]
Alright, thank you!
