### ISSUE TITLE
ROPC proposal calling Http api

### ISSUE THREAD

**Issue by juananinca** [ory/hydra#2193]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**
**Is your feature request related to a problem? Please describe.**

No, my feature request is not releated to any problem. 
It is releated to the alternative proposed in this #214 in which Hydra calls an HTTP API in order to authenticate users. I see users voted for the HTTP API call but all info I have found is related to the consent flow (Second option).

**Describe the solution you'd like**

It would be nice to have a similar flow mentioined in #214  in which, for an identity provider url set in a given hydra's client, every token requested for that client Hydra calls to the identity provider with the user credentials. If the credentials are valid then hydra generates the token.

I think this flow is interesting since there there are no redircts with the client agent and just tells if the given credentials are valid for a particular hydra client.

**Additional context**

In case the description would seem messy, I'll describe the steps in this flow:

- Identity Provider (Http Api running on http://app:8080): This app can provide user's info and can validate user's credentials on path (http://app:8080/auth) with de following body:
`{"username": "qwer", "password": "psswd"}`

1. We create a client `client-test` in Hydra and set the url `http://app:8080/auth` as its Identity Provider.
2. Make a request to Hydra `http://hydra:4444/oauth/token?grant_type=password` with the authorization header (for `client-test`) added and a body `{"username": "qwer", "password": "psswd"}`
3. Hydra receive the request and since it has the grant_type password set and `client-test` in the Authorization basic, Hydra must call the Identity Provider set for that client which is `http://app:8080/auth`, thus Hydra will make a request to `http://app:8080/auth` with the body sent in the /oauth/token request.
4. The Identity Provider receives the request with the credentials, validate them and return ok, if they are valid.
5. Hydra gets the Identity Provider's response telling the credentials are valid (or invalid), depending on the response Hydra will provide a token or return an authentication error with the Identity Provider.

Note: I tried to follow the issues related to #214 but I did not find anything. Excuse me if this topic has been already discussed.

**Comment by aeneasr** [comment]
No, ROPC will not be supported in ORY Hydra. There have been several feature requests like this and we all rejected them. We have a dedicated page for this also: https://www.ory.sh/hydra/docs/limitations#resource-owner-password-credentials-grant-type-rocp

ROPC will also not be included in OAuth 2.1. If you want something that works like ROPC, you should take a look at ORY Kratos: https://github.com/ory/kratos

**Comment by brat002** [comment]
You can continue reject these requests but you can't reject presence of bots and backend flows which require ROPC flow. It is not a variant to create clients in hydra database and use client_credentials grant for them.
We all need an ability to exchange user credentials to JWT token within scripts and workers. At least RFC describes this flow.
