### ISSUE TITLE
Quickstart.yml broken.

### ISSUE THREAD

**Issue by debrutal** [ory/hydra#2213]
**Describe the bug**

doing the 5 min Quickstart is broken. 

**Reproducing the bug**

```
docker-compose -f quickstart.yml up
```
Error logs

```
ERROR: The Compose file './quickstart.yml' is invalid because:
Invalid top-level property "lite". Valid top-level sections for this Compose file are: version, services, networks, volumes, secrets, configs, and extensions starting with "x-".

You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.

```

**Expected behavior**

Start and migration of hydra environment

**Environment**

- Version: docker-compose version 1.25.0, build unknown

- Environment: Ubuntu 20 

**Additional context**

https://github.com/debrutal/hydra/commit/d849bd50c94b52c31cb6d4d274a197ed93277fb3#diff-08cb0596165bd96fa537dfee73f1cfe6e3f906d1f2f2bba276b4b50d9facbae1
inserted a 
```
lite: 
```
as top level element below volumes

**Comment by vinckr** [comment]
I just tried it, and got the same error.

**Comment by debrutal** [comment]
PR is available:
https://github.com/ory/hydra/pull/2214

**Comment by debrutal** [comment]
Please consider comment... i did not change the version of:
`oryd/hydra-login-consent-node` version is not correct. 
i could fix it using: `oryd/hydra-login-consent-node-v1.9.0-alpha.3.pre.0`
