### ISSUE TITLE
When starting hydra in docker it cannot find the configuration file

### ISSUE THREAD

**Issue by gustabart** [ory/hydra#2231]
Start hydra with a configuration file:

```bash
$ docker run -d \
  --name ory-hydra-example--hydra \
  --network hydraguide \
  -p 9000:4444 \
  -p 9001:4445 \
  -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
  -e DSN=$DSN \
  -e URLS_SELF_ISSUER=http://127.0.0.1:9000 \
  -e URLS_CONSENT=http://127.0.0.1:9020/consent \
  -e URLS_LOGIN=http://127.0.0.1:9020/login oryd/hydra:v1.8.5 \
  serve all --dangerous-force-http --config config.yaml
```

Logs:  

Config file not found because **"open config.yaml: no such file or directory"**
...

Of course I have the file.
Thanks in advance!

**Comment by aeneasr** [comment]
Hello, looks like you have some trouble with Docker. Please make sure that `config.yaml` actually exists in the directory which you are running this from (I can already tell you it does not). Make sure you have mounted the config file (if you have the intention of mounting it).

Did you modify this command or did you get it from a documentation page?

**Comment by gustabart** [comment]
Thanks @aeneasr.  It's weird because the problem seems pretty basic, I know. But of course the file exists.  
I also try without the --config flag, with a .hydra.yaml file in my $HOME. And hydra didn't find the settings either.  

Logs:

**Config file not found because "Config File ".hydra" Not Found in "[/]""
2020/12/09 12:30:56 error: Config File ".hydra" Not Found in "[/]"**

I get the example from de documentation page, yes!
I am new to Hydra. I did the 5 minute tutorial and it works fine. But now, I want to do something else with the config file and I can't. Maybe I have a problem in my environment, I don't think so, but I'll keep trying.

**Comment by zepatrik** [comment]
When hydra is running in docker, isn't it looking for the file in the container instead of the host? Wouldn't you have to mount it in the container therefore?

**Comment by aeneasr** [comment]
The error `"Config file not found because "Config File ".hydra" Not Found in "[/]""` no longer appears in ORY Hydra 1.9, which will be released as stable soon.

**Comment by gustabart** [comment]
> When hydra is running in docker, isn't it looking for the file in the container instead of the host? Wouldn't you have to mount it in the container therefore?

Yes, you are right! This works for me!

```
docker run \
  --name ory-hydra-example--hydra \
  --network hydraguide \
  -p 9000:4444 \
  -p 9001:4445 \
  -e SECRETS_SYSTEM=$SECRETS_SYSTEM \
  -e DSN=$DSN \
  -e URLS_SELF_ISSUER=http://127.0.0.1:9000 \
  -e URLS_CONSENT=http://127.0.0.1:9020/consent \
  -e URLS_LOGIN=http://127.0.0.1:9020/login \
  -v $(pwd)/config.yaml:/config.yaml \
  oryd/hydra:v1.8.5 serve all --config config.yaml --dangerous-force-http
```
Perhaps this point could be more explicit in the documentation. I'm not sure, I leave it to your consideration.
Thanks for the support!

**Comment by zepatrik** [comment]
From what page did you copy the command? I guess adding a small hint to some resource would help. Do you have any you like? I could not find a good one with a quick search.

**Comment by gustabart** [comment]
Maybe https://www.ory.sh/hydra/docs/configure-deploy/#deploy-ory-hydra can be a good place. There, there is a note: _In this example we did..._  Below that another note could be added. A suggestion:  

**Note 2: If you use the --config flag to set a configuration file (see https://www.ory.sh/hydra/docs/reference/configuration), remember to mount it in the container. For example:**

```bash
$ docker run -d \
  ...
  -v $(pwd)/config.yaml:/config.yaml \
  oryd/hydra:v1.9.0-alpha.3 serve all --config config.yaml
```
Bye.
