### ISSUE TITLE
URLS_ERROR and OAUTH2_ERROR_URL might be redundant and OAUTH2_ERROR_URL not properly documented

### ISSUE THREAD

**Issue by k9ert** [ory/hydra#2254]
**Describe the bug**

At the [hydra on docker](https://www.ory.sh/hydra/docs/configure-deploy/) page, the OAUTH2_ERROR_URL env-var is mentioned but it seem to collide from a semantic point of view with URLS_ERROR.
* URLS_ERROR is mentioned in the [Reference-Configuration](https://www.ory.sh/hydra/docs/reference/configuration)
* OAUTH2_ERROR_URL is not mentioned in the Reference-Configuration
* OAUTH2_ERROR_URL is used in the code [here](https://github.com/ory/hydra/blob/master/oauth2/handler_fallback_endpoints.go)

So in order to make consistent:
* Differences and similarities should be clarified
* If both of them are reasonable, they should both be documented properly

**Comment by aeneasr** [comment]
`OAUTH2_ERROR_URL` is deprecated starting ORY Hydra v1.9.0, so `URLS_ERROR` is the only valid format going forward!
