### ISSUE TITLE
/clients?limit=1000 endpoint caps number of returned clients to 500 instances

### ISSUE THREAD

**Issue by thormarius** [ory/hydra#2267]
**Describe the bug**

According to  documentation here [https://www.ory.sh/hydra/docs/v1.8/reference/api/#list-oauth-20-clients](https://www.ory.sh/hydra/docs/v1.8/reference/api/#list-oauth-20-clients) the admin `GET: /clients` endpoint "lists all clients in the database." 

It looks to me like it is limiting the response to the first 500 clients even though I set the query param `limit=1000`. 

**Reproducing the bug**

* Setup a instance with more than 500 clients
* Request  `GET: /clients?limit=1000`
* Observe that only the first 500 clients are returned

**Expected behavior**
I would expect the limit=1000 to be respected, or the documentation to state that only the first 500 clients are returned regardless of the value of the `limit` parameter.  

**Environment**
I've only tested this in v.1.8.5 with PostgresSQL database

**Comment by aeneasr** [comment]
Limit is 500, you need to use the page/offset prameter to fetch the next page. It is included in the header.

This is also explained here: https://www.ory.sh/docs/ecosystem/api-design

**Comment by thormarius** [comment]
Thank you - I appreciate that behaviour. In that case the documentation here https://www.ory.sh/hydra/docs/v1.8/reference/api/#list-oauth-20-clients should also reflect that the response is capped at 500 objects. It currently states that "_This endpoint lists all clients in the database_".

**Comment by aeneasr** [comment]
Thank you, would you be up for changing the docs for this to help prevent future confusion? The places to edit are:

- https://github.com/ory/hydra/blob/master/client/handler.go#L174
- https://github.com/ory/hydra/blob/master/client/doc.go#L52 (adding a note that the maximum value is 500)
- https://github.com/ory/docs/blob/master/docs/docs/ecosystem/api-design.md#pagination (adding a note that the limit always has an upper bound which usually depends on the API to prevent DoS)
