### ISSUE TITLE
Hydra does now allow to consent individual/partial scopes

### ISSUE THREAD

**Issue by mrendi29** [ory/hydra#2297]
We use Hydra as our OAuth server and we are trying to allow the user to select which scopes they want to allow an application to use. 
From the docs I can see that this behavior is supported as the docs show the use of checkboxes "https://www.ory.sh/hydra/docs/login-consent-flow/#the-flow-from-a-network-perspective".
When we try to accept the consent request with the list of scopes that the user wants to grant access to we get this error: 

```
error: request_forbidden
error_description: The request is not allowed

You are not allowed to perform this action.
error_hint: You are not allowed to perform this action.
```

The following is also an example the response that Hydra gives after we try to accept this specific use case of consent_request:

`{'redirect_to': 'http://127.0.0.1:4444/oauth2/auth?client_id=43239a1a-eddd-4e70-21a8-12f9f90ec793&code_challenge=A5Rw4vdCSCcbv1rLUS6Cb2BQBDm-WIsAjZV5nJ1A3Tk&code_challenge_method=S256&consent_verifier=355b3d8daeaa848fdba568216ee391a2d&redirect_uri=http%3A%2F%2F127.0.0.1%3A3001%2Fauthorization&response_type=code&scope=great+great.ex3+great.ex2&state=kG8I25kWlUaE3HSLh3C6y6xGPiJ33m'}`

Does Hydra allow granting access only to partial scopes instead of all the requested scopes? If so, can that be documented more clearly, and if not, can we add that functionality as intended?

**Comment by aeneasr** [comment]
Hello, this is certainly possible - however given that this is more of a question and missing vital debug information (e.g. which version, full payloads such as your client config, ...) this rather belongs in a discussion. For some reason, the "Convert to discussion" button is no longer available in my GitHub UI, so I must kindly ask you to create a discussion manually instead. You can use the same content with the additional requested details. Thank you!
