### ISSUE TITLE
wellknown is missing code_challenge_methods_supported

### ISSUE THREAD

**Issue by gbolo** [ory/hydra#2311]
**Describe the bug**

when pkce is enabled, i would expect the wellknown to advertise it's supported methods as defined in [RFC 8414](https://tools.ietf.org/html/rfc8414#section-2)

```
   code_challenge_methods_supported
      OPTIONAL.  JSON array containing a list of Proof Key for Code
      Exchange (PKCE) [RFC7636] code challenge methods supported by this
      authorization server.  Code challenge method values are used in
      the "code_challenge_method" parameter defined in Section 4.3 of
      [RFC7636].  The valid code challenge method values are those
      registered in the IANA "PKCE Code Challenge Methods" registry
      [IANA.OAuth.Parameters].  If omitted, the authorization server
      does not support PKCE.
```

The final sentence states: **If omitted, the authorization server does not support PKCE.**

**Expected behavior**

I expect to see the following snippet in the wellknown response:
```
...
"code_challenge_methods_supported": [
  "plain",
  "S256"
],
...
```

**Comment by aeneasr** [comment]
Hey there, yes, https://tools.ietf.org/html/rfc8414#section-2 is actually not supported ATM, we only support OpenID Connect Discovery. Would you be up for some PRs to address this?

**Comment by gbolo** [comment]
Hi @aeneasr, if this is something you would like to support I certainly don't mind addressing it in a PR. Whats the scope here? I'm assuming its to simply add the supported methods when to the wellknown response when pkce is enabled on hydra. Is that correct? I will familiarize myself with the code base

**Comment by aeneasr** [comment]
@gbolo sorry for the late reply. Yes, that is correct, and also add a little test (probably 3-5 lines). If you need guidance I can point you to the files!

**Comment by gbolo** [comment]
hi @aeneasr 

I looked through the code. It's fairly simple to modify the wellknown response to include the supported methods. However, I could not find any indication in the code that pkce is actually being validated. Adding support for pkce is a bit more than I bargained for ;) Can you verify this?

**Comment by aeneasr** [comment]
PKCE is supported and [somewhat documented](https://www.ory.sh/hydra/docs/guides/oauth2-public-spa-mobile/#creating-a-public-oauth-20-client).

**Comment by gbolo** [comment]
hi @aeneasr it looks like pkce is supported from the client perspective, but I cannot find any server side verification being done. Can you confirm this?

**Comment by aeneasr** [comment]
Confirm what exactly?

**Comment by gbolo** [comment]
> Confirm what exactly?

@aeneasr that the hydra server will validate the code_verifier with the already received code_challenge and the code_challenge_method during the client's access token request (PKCE)

**Comment by aeneasr** [comment]
That's what I tried to say https://github.com/ory/hydra/issues/2311#issuecomment-842052258

What was not clear about it / what could be improved?

**Comment by gbolo** [comment]
Hi @aeneasr sorry if I'm not being clear enough. I already made the required changes to the wellknown response, however i cannot find any evidence of the hydra server keeping track of the code challenge for validation later on when the token request comes in. Can you point me to the code that does this validation? It would be difficult for me to write that validation code, as I would have to get more intimate with the code base. I hope its clear now.

**Comment by aeneasr** [comment]
Ory Hydra supports PKCE as required by the specification and does the validation and everything. This happens in the library we are using: https://github.com/ory/fosite/

**Comment by gbolo** [comment]
thanks @aeneasr 

I have modified the response and adjusted the testcase for the response. Please review #2547 when you get a chance.
