### ISSUE TITLE
Support regular expression for dangerous-allow-insecure-redirect-urls flag

### ISSUE THREAD

**Issue by hgiasac** [ory/hydra#2319]
**Is your feature request related to a problem? Please describe.**

Currently the `dangerous-allow-insecure-redirect-urls` flag is compared equality between URLs. It isn't flexible for many use cases.
For example, we have a system that can create subdomains for users dynamically.
- user1.example.com
- user2.example.com
- ...
It seems annoyed to hard-coded every domain. Although the issue doesn't affect production, we need a easier way to develop in local and testing environments.

**Describe the solution you'd like**

Support regular expression validation. 

**Additional context**

I have a forked commit for this feature. Just wondering if it can be merged? If yes, I will create a PR for this
https://github.com/hgiasac/hydra/commit/feca6f1bd091f6e998cc34b38ebf2c21595443d6

**Comment by aeneasr** [comment]
I don't think we'll merge this, the feature is intended to be a bit tedious to set up, because we don't want people to end up using this in production. By adding more and more capabilities for this, the risk increases. Are you really having a lot of subdomains in your test environment? Could you not just create a static list?

**Comment by hgiasac** [comment]
That is just a simple case. We also create dynamic endpoints with random UUID, such as `http://user1.example.com/<uuid>/callback`. We don't think the static list is the good way to do

**Comment by aeneasr** [comment]
I am closing this issue as it has not received any engagement from the community or maintainers in a long time. That does not imply that the issue has no merit. If you feel strongly about this issue

- open a PR referencing and resolving the issue;
- leave a comment on it and discuss ideas how you could contribute towards resolving it;
- open a new issue with updated details and a plan on resolving the issue.

We are cleaning up issues every now and then, primarily to keep the 4000+ issues in our backlog in check and to [prevent](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer) [maintainer](https://www.jeffgeerling.com/blog/2016/why-i-close-prs-oss-project-maintainer-notes) [burnout](https://docs.brew.sh/Maintainers-Avoiding-Burnout). Burnout in open source maintainership is a [widespread](https://opensource.guide/best-practices/#its-okay-to-hit-pause) and serious issue. It can lead to severe personal and health issues as well as [enabling catastrophic](https://haacked.com/archive/2019/05/28/maintainer-burnout/) [attack vectors](https://www.gradiant.org/en/blog/open-source-maintainer-burnout-as-an-attack-surface/).

Thank you to anyone who participated in the issue! 🙏✌️
