### ISSUE TITLE
is there a way to migrate to another dsn ?

### ISSUE THREAD

**Issue by kamedodji** [ory/hydra#2322]
**Is your feature request related to a problem? Please describe.**

My current application use postgres sdn and i want to use instead mariadb sdn,
without starting from scratch.

**Describe the solution you'd like**

is there a way to migrate to migrate my original postgres db to mariadb one, with 
ory hydra internal tool, like https://www.ory.sh/hydra/docs/cli/hydra-migrate-sql/ ?

**Describe alternatives you've considered**

I known i can proceed with MySQL Workbench Migration Wizard, but i'm not exavtely
a database guy and seem's hydra migrate sql is performant tool !

Thanks a lot for your help.

**Comment by aeneasr** [comment]
No, there is not an option to do that - you have to do that manually, sorry!

**Comment by kamedodji** [comment]
Thanks for your feedback @aeneasr 
I was hoping that another user had the same paradigm... ;-)

**Comment by aeneasr** [comment]
No problem - is it ok if we close this issue as there are no plans to natively support this? You can still ask over at GitHub discussions if someone has some ideas how to achieve this!

**Comment by v03adk** [comment]
@aeneasr Hello. And do you have some kind of migration tool (or tutorial) to move existing tokens from another server to Hydra? so, we are using some library for oauth2 flow, but want to move to Hydra. at the same time, we want to keep our customers "logged in", so we would like move existing access_tokens to Hydra db. is there a way to do that? or tutorial?

**Comment by aeneasr** [comment]
In that case please migrate your SQL database. This is not in the scope of Ory Hydra :)

Closing as per https://github.com/ory/hydra/issues/2322#issuecomment-770381617

**Comment by v03adk** [comment]
@aeneasr I know that it's not the scope of Ory Hydra. I just asked if there some kind of tutorial maybe? or the only possible way is to dig into Hydra sources to find about the db schema?

**Comment by aeneasr** [comment]
I suggest using something like `mysqldump` or `pgdump` or whatever database tool you're using. There are tons of tutorials on moving databases (e.g. https://www.sysinfotools.com/blog/migrate-sql-server-database-from-one-server-to-another/) online. There is no documentation in Ory Hydra that would help with operational details of your database environment :/

**Comment by v03adk** [comment]
@aeneasr ok, I see that you confused my question with the first question. sorry for that. I am not moving from pgsql to mysql. 

I am movinf from completely another oauth2 server to Hydra. and want to move a completely different mysql scheme to Hydra. and asking about Hydra db structure, like if I have strict AccessToken in my db, how can I insert it into Hydra mysql structure?

**Comment by aeneasr** [comment]
I see. It's always better to open a new issue if your question does not relate to the original issue :)

That highly depends on what OAuth2 Server you are moving from. We currently do not have documentation for this and a migration won't be an easy 1:1 move as every server has different schemas and concepts. We would however greatly appreciate to understand how you are planning a migration (also from which OAuth2 server). Maybe you could track your progress and questions in the [discussions area of this repo](https://github.com/ory/hydra/discussions)?
