### ISSUE TITLE
Add support for context query parameter to store custom data when the init auth flow creates a login request.

### ISSUE THREAD

**Issue by DanPinzaru** [ory/hydra#2333]
**Describe the solution you'd like**

Add support for a query parameter, called "context" (similar to the "Accept Login Request" endpoint) so that the client can store some custom data that can be retrieved along with the login request (using the challenge code).

Endpoint to change:
/oauth2/auth

Every time a login request (via the /oauth2/auth/requests/login?login_challenge=${} endpoint) is retrieved by the challenge code, the "context" object is also present in the response data, containing whatever data the client passed in through the "context" query parameter.

**Additional context**

For my particular use case, I use Webviews for Android & iOS and I would like send in some metadata to the /oauth2/auth endpoint that can be retrievable by the "challenge code" that Hydra creates.

**Comment by aeneasr** [comment]
Hello, thank you for the idea! This is already possible. Both Login and Consent Requests have a [`request_url`](https://github.com/ory/hydra/blob/master/consent/types.go#L505) which contains the original OAuth2 Authorize URL (e.g. `/oauth2/auth?client_id=...&your_custom_param=...`.

**Comment by aeneasr** [comment]
@vinckr we could probably document this in the FAQ or as part of the ory documentation - the question is coming up once or twice a month!

**Comment by vinckr** [comment]
Yes definitely! I had no idea there is such an easy solution to this.

**Comment by DanPinzaru** [comment]
Brilliant! That does the job, thank you!

**Comment by aeneasr** [comment]
Glad it is what you need - I'll keep this issue open. Please reference this in the docs / FAQ PR @vinckr so we can close it.

**Comment by aeneasr** [comment]
#2334
