### ISSUE TITLE
Update ttl.access_token and ttl.refresh_token dynamically

### ISSUE THREAD

**Issue by Jalr4ever** [ory/hydra#2347]
**Is your feature request related to a problem? Please describe.**

Hydra is deploy by docker-compose in my Project, and I specified the configurations with `environment` flag, so did flag `ttl.access_token` and `ttl.refresh_token`.

I can't find any way to update `ttl.access_token` and `ttl.refresh_token` dynamically over looking through the ory hydra doc...

**Describe the solution you'd like**

Support `REST API` and `CLI Command` to update `ttl.access_token` and `ttl.refresh_token`  dynamically that without reboot hydra service.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by aeneasr** [comment]
Just update the config value in your config file!

**Comment by Jalr4ever** [comment]
> Just update the config value in your config file!

For some scenarios, I need to update these two flags by other services, without reboot the hydra service. It seems like updating in config file unable to reach the ideal result...?

**Comment by aeneasr** [comment]
Ory Hydra supports config hotreloading, you don't need to reboot. Just update the value, the process will see the changes and update the config. To the best of my knowledge, this also works with `ttl.access_token`.

How you do this in your deployment infrastructure - e.g. with Kubernetes Config Maps, shared volumes, ... is up to you!

There are no plans to add a REST endpoint to manage configuration it does not follow our architecture principles.

**Comment by Jalr4ever** [comment]
> Ory Hydra supports config hotreloading, you don't need to reboot. Just update the value, the process will see the changes and update the config. To the best of my knowledge, this also works with `ttl.access_token`.
> 
> How you do this in your deployment infrastructure - e.g. with Kubernetes Config Maps, shared volumes, ... is up to you!
> 
> There are no plans to add a REST endpoint to manage configuration it does not follow our architecture principles.

Thanks for your reply.
