### ISSUE TITLE
Configuration Web UI (generate hydra.yml | env variables)

### ISSUE THREAD

**Issue by Benehiko** [ory/hydra#2356]
**Is your feature request related to a problem? Please describe.**

When new to Ory Hydra - one of the beginner issues are to understand the configuration file (or environment variables) which are necessary to get started or even the formatting of the config file. It also takes a lot of time to customise and get started with all the different variables one can customise or use. 

**Describe the solution you'd like**

A small Web UI might be nice to select and change the variable you would like to include as well as some description of them. The UI would already have some things selected (such as necessary/basic variables that are required to run hydra) with the basic information - e.g. admin -> port -> 4444. The web-ui then allows you to save the configuration file to your machine as well as a little blurb of all the environmental variables generated based off of your selection (for easy copy-paste).

**Describe alternatives you've considered**

A cli command might be good to have, however, might not be as user-friendly.

**Additional context**

This would be a separate web-app running maybe on a different subdomain or path alongside the docs (?).

**Comment by aeneasr** [comment]
I think this is a good idea, some people do struggle with the config ("how do I set env vars?"). I think it would make sense to use the configuration schema for this.

As a starter I think a good place would be to improve the output of https://www.ory.sh/hydra/docs/reference/configuration

The script which generates this is this one: https://github.com/ory/docusaurus-template/blob/master/scripts/config.js

Once this is improved (visually structured, maybe tables, maybe more examples?), we will find all the fields that are populated incorrectly (e.g. example missing, default missing, ...). Once that is done, we could use the schema to generate the UI!

What do you think?

**Comment by Benehiko** [comment]
So I have sort of built a web app (in VueJs) based on the schema files found in each project (not sure if this is the right approach) found here:
https://github.com/ory/hydra/blob/master/.schema/config.schema.json

The web app uses the schema to then generate the form, so that any future properties being added or removed won't need major updates to the web app. You can look at it here: https://github.com/ory/ory-config

It is rather new still and will require a bit of love before being usable.

**Comment by aeneasr** [comment]
Given the availability of https://github.com/ory/ory-config I'll be closing this :)
