### ISSUE TITLE
SQA_OPT_OUT env var ignored

### ISSUE THREAD

**Issue by pjediny** [ory/hydra#2358]
**Describe the bug**
https://www.ory.sh/docs/ecosystem/sqa/ describes how to disable SQA, but the hydra is ignoring the setting via env var.

**Reproducing the bug**
Run with env var set `SQA_OPT_OUT=true`
There is no sqa configuration in config file
There is no sqa configuration as command line flag

Check logs for message:
```
level=info msg=Software quality assurance features are enabled. Learn more at: https://www.ory.sh/docs/ecosystem/sqa audience=application service_name=ORY Hydra service_version=v1.9.2
```

**Expected behavior**
Expecting `SQA_OPT_OUT=true` to disable telemetry

**Environment**

- Version: v1.9.2
- Environment: k8s

** Notes **

Command line flag `--sqa-opt-out` has effect
Probably caused by change from `viper` to `koanf`

**Comment by aeneasr** [comment]
Ah yes, thank you for finding this - that's most likely a regression from the recent move to koanf. If you can, could you provide a PR? Highly appreciate your help!

**Comment by pjediny** [comment]
Done.

But I could not `go test ./...` as it fails on downloading dependency:

```
go test ./...
go: github.com/ory/cli@v0.0.35 requires
        github.com/gobuffalo/fizz@v1.13.1-0.20200903094245-046abeb7de46: invalid version: unknown revision 046abeb7de46
```

Tested only by `make docker` and running the image with docker run.
