### ISSUE TITLE
Reference to config.md has a broken link

### ISSUE THREAD

**Issue by rafaeldasilva** [ory/hydra#2366]
**Describe the bug**

The link to file "https://github.com/ory/hydra/blob/undefined/docs/docs/reference/config.md" which is indicated on pages such as 
https://www.ory.sh/hydra/docs/cli/hydra-serve is broken

I see the file was renamed to https://github.com/ory/hydra/blob/master/docs/docs/reference/configuration.md

**Reproducing the bug**

Click on "https://github.com/ory/hydra/blob/undefined/docs/docs/reference/config.md"

**Expected behavior**
Open the file https://github.com/ory/hydra/blob/undefined/docs/docs/reference/config.md

**Comment by zepatrik** [comment]
Weird that there is `undefined` in the link. All of the occurrences are in the CLI docs, so the problem is somehow related to how we generate them.

**Comment by vinckr** [comment]
So for example in [serve.go](https://github.com/ory/hydra/blob/master/cmd/serve.go) it says:
>> https://github.com/ory/hydra/blob/` + config.Commit + `/docs/docs/reference/config.md <<

So changing config.md to configuration.md 
and making sure that config.Commit is not `undefined` but `master` should fix it. 
Not sure where or how the config.Commit is broken, investigating further.

**Comment by vinckr** [comment]
Looking through the history it seem it never really worked, was always `undefined` as far as i can see.
