### ISSUE TITLE
feat: Support partial client updates

### ISSUE THREAD

**Issue by mbonnell-wish** [ory/hydra#2385]
**Is your feature request related to a problem? Please describe.**

Currently, the only client updates supported by the REST API are updates with PUT semantics, meaning the entire client gets replaced. This is undesirable when one only wants to update a certain property, like a callback URI. 

This desire is referenced [here](https://github.com/ory/hydra/issues/2020#issuecomment-764668918) and [here](https://github.com/ory/hydra/pull/2049#discussion_r487434394).

**Describe the solution you'd like**

It would be good to also support partial client updates through a PATCH request. For the CLI, we could add some flag like `--partial` as suggested by @matheusfm. 

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

Would be happy to tackle this over the weekend.

**Comment by mattbonnell** [comment]
@aeneasr let me know if you'd be open to accepting a PR for this feature 😄 
Would be a little bit of work so just want to get the green-light from you before I start on it.

**Comment by aeneasr** [comment]
Yes, that would be great! There's an open issue for discussing ideas how to do this here: https://github.com/ory/meta/issues/2
