### ISSUE TITLE
Generated token begins with dash: can not introspect

### ISSUE THREAD

**Issue by vladfaust** [ory/hydra#2409]
**Describe the bug**

`hydra client create` may generate a token beginning with dash, e.g. `-ob80o50jO84ctxaAWaj73Vh9zvvv1n2_svhSVvum66w.-UUBNiuYFR66EDiuksdxqU4-A2ynnrmDRVy-tytEEtk`. Running `hydra token introspect -ob80o50jO84ctxaAWaj73Vh9zvvv1n2_svhSVvum66w.-UUBNiuYFR66EDiuksdxqU4-A2ynnrmDRVy-tytEEtk` then fails with: 

```
unknown shorthand flag: 'o' in -ob80o50jO84ctxaAWaj73Vh9zvvv1n2_svhSVvum66w.-UUBNiuYFR66EDiuksdxqU4-A2ynnrmDRVy-tytEEtk
```

**Reproducing the bug**

1. Run `hydra token introspect -ob80o50jO84ctxaAWaj73Vh9zvvv1n2_svhSVvum66w.-UUBNiuYFR66EDiuksdxqU4-A2ynnrmDRVy-tytEEtk`

**Expected behavior**

It allows to introspect any token it generated.

**Environment**

Version:
Git Hash:   f5b993a279bc8b4c96a3013607f574f0dc801153
Build Time: 2021-02-16T13:08:02Z

Environment: 
Ubuntu 18.04

**Additional context**

Wrapping the token in quotes (neither single nor double) doesn't help.

**Comment by aeneasr** [comment]
https://unix.stackexchange.com/questions/303929/handling-names-with-leading-dash-in-bash-shell

```
hydra token introspect -- -ob80o50jO84ctxaAWaj73Vh9zvvv1n2_svhSVvum66w.-UUBNiuYFR66EDiuksdxqU4-A2ynnrmDRVy-tytEEtk
```
