### ISSUE TITLE
Hydra CLI tool connection issue

### ISSUE THREAD

**Issue by nyvelius** [ory/hydra#2429]
**Describe the bug**

Unable to run migration, apparently due to a connection issue in the cli tool.

**Reproducing the bug**

For some reason, the hydra cli tool is not able to connect to the database.
```
docker run --rm -it oryd/hydra:v1.10.1 migrate sql postgres://pguser:<password>@localhost:5432/db

INFO[2021-03-26T12:23:58Z] No tracer configured - skipping tracing setup  audience=application service_name=ORY Hydra service_version=v1.10.1
The following migration is planned:

Could not get the migration status:
failed to connect to `host=localhost user=pguser database=db`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)
```

Connecting using psql works. 
```
psql -h localhost -d db -U pguser
```

Connecting to localhost from the IntelliJ database plugin using an SSH tunnel also works.

**Comment by aeneasr** [comment]
You are running docker and ask hydra to connect to localhost - so the docker - where there is no postgres running. This can not work. Please read about docker networking or try one of our quickstarts which have everything set up so you don't have to worry about it!
