### ISSUE TITLE
Support ES256

### ISSUE THREAD

**Issue by mitar** [ory/hydra#2453]
So fosite has ES256 support, I have seen some past PRs to support ES256 in Hydra (https://github.com/ory/hydra/pull/628, https://github.com/ory/hydra/issues/627), but looking at the code I do not see it really being supported in Hydra.

While RS256 is recommended by [the spec](https://tools.ietf.org/html/rfc7518#section-3.1), ES256 is close to that with its "Recommended+" recommendation. Supporting ES256 would thus allow one to migrate away from RS256 to ES256.

**Comment by aeneasr** [comment]
Contribs welcomed!

**Comment by dibyajyotibehera** [comment]
@aeneasr i can pick this up. However , looks like it was achieved  in PR [628](https://github.com/ory/hydra/pull/628) . Wondering how come its missing in master.

**Comment by aeneasr** [comment]
Yeah also not sure what this is referring to any more. Maybe we can close

**Comment by dibyajyotibehera** [comment]
actually i don't see the changes merged in PR [628](https://github.com/ory/hydra/pull/628) in master now. Was it intentionally dropped ?

**Comment by amaaniqbal** [comment]
@aeneasr Should I create a PR with the same changes to the `master` branch?

**Comment by aeneasr** [comment]
That PR is from 2017, thats 5 years ago - it probably won’t work ;)

**Comment by amaaniqbal** [comment]
Oh okay, I missed the date on the PR 😅.

**Comment by epicaqua** [comment]
Dear team,

Not sure if this is right thread,  I am looking out for documentation on how to change id-token/access-token signature algorithm from RS256 to ES256, 

Is ES256 for tokens signature already supported by ory-hydra? I saw some endpoint to create  ES-256 keys but GET request on endpoint  "/.well-known/jwks.json" was showing only RS256. how can I add there ES256 specific keys and allow it to sign tokens? any help would be great.
