### ISSUE TITLE
Public endpoints different than issuer

### ISSUE THREAD

**Issue by ppawliczek** [ory/hydra#2462]
**Describe the bug**

In the configuration there are parameters urls->self->public (URLS_SELF_PUBLIC) and urls->self->issuer (URLS_SELF_ISSUER). The former one is described as "This is the base location of the public endpoints of your ORY Hydra installation.". However, when I tried to set URLS_SELF_ISSUER to different value, the authorization and token endpoints reported in the metadata file (.../.well-known/openid-configuration) changes together with the "issuer" field (the parameter URLS_SELF_PUBLIC is ignored).

**Expected behavior**

I would expect that location of the endpoints is determined by URLS_SELF_PUBLIC, while the value of the issuer is determined by URLS_SELF_ISSUER.

**Comment by aeneasr** [comment]
Ah this looks like a regression from a recent patch we merged. You are correct, issuer should only be used for the issuer values. Would you be open to a PR?

**Comment by ppawliczek** [comment]
#2441 should fix it
