### ISSUE TITLE
Packaging - Debian and Fedora 

### ISSUE THREAD

**Issue by ghenry** [ory/hydra#2487]
Hi all,

Would you be interested in creating a deb repo and rpm repo?

Examples from another go project are below and I can retro fit and submit a PR. The repos would need to be hosted by the project. It would make deploying on VMs easier versus pulling the binary and doing all the systemd things ourselves:

https://github.com/cgrates/cgrates/tree/master/packages

Thanks,
Gavin.

**Comment by aeneasr** [comment]
Contributions welcomed!
