### ISSUE TITLE
Unable to go get

### ISSUE THREAD

**Issue by hash** [ory/hydra#2489]
**Unable to go get**

**Reproducing the bug**

```
PS C:\Users\hash> go get -d github.com/ory/hydra
go get: github.com/ory/hydra@v1.9.3-pre.1 updating to
        github.com/ory/hydra@v1.10.1 requires
        github.com/ory/cli@v0.0.48 requires
        github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
        github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Expected behavior**

Expected that `go get -d github.com/ory/hydra` would work

**Environment**

- Windows 10 10.0.19042
- go1.16.3.windows-amd64.msi

**Additional context**

N/A

**Comment by kuttas** [comment]
I'm seeing the same issue - I'm surprised no one else is running into this, since I am not specifying a specific older version of hydra.

```
[Mon Jul  5 16:42:37 2021]$go get -d github.com/ory/hydra
go get: github.com/ory/hydra@v1.0.0-beta.9 updating to
	github.com/ory/hydra@v1.10.2 requires
	github.com/ory/cli@v0.0.49 requires
	github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
	github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

MacOS 11.1, go version go1.16.5 darwin/amd64

I get a similar error trying to `go get -d github.com/ory/kratos`:
```
go get: github.com/ory/kratos@none updating to
	github.com/ory/kratos@v0.6.3-alpha.1 requires
	github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by akshaybharambe14** [comment]
I am not able to reproduce this with latest version v1.10.6.

**Comment by kuttas** [comment]
Just tried `go get -d github.com/ory/hydra` and I can confirm that it's trying to get v.1.10.6 and it works fine now. 

I noticed from the output logs it doesn't seem to depend on `ory/cli` or `ory/kratos` anymore. Coincidence, or related to the fix?

https://pastebin.com/uyd5KSpM
