### ISSUE TITLE
Optimize janitor's slow queries on requests tables

### ISSUE THREAD

**Issue by flavioleggio** [ory/hydra#2513]
**Problem description**

The new `hydra janitor` command introduced very important database cleanup routines in order to tackle production environments intense grow rate on tables for tokens and requests.
The queries simply delete obsolete records in `hydra_oauth2_access` and `hydra_oauth2_refresh` tables and rejected timed out requests records in `hydra_oauth2_authentication_request` and `hydra_oauth2_consent_request`. While the tokens tables `DELETE` queries look quite efficient if they run periodically on tables which are actually cleaned up and whose sizes are limited, requests tables grow indefinitely, thus making `DELETE` on that tables slower and slower every day.

**Main solution**

I think that the problem is related to the conditions in the queries, which are mainly based on the timestamp column `requested_at`, as one can see [here](https://github.com/ory/hydra/blob/master/persistence/sql/persister_consent.go#L482). If we could avoid making the `DELETE` queries directly depend on that field, we would at least lock the tables for a short amount of time. My first idea is of separating the writing part of the query from the reading part, which obviously is the main reason for the query to be slower and slower every day. We could just `SELECT` _deletable_ records with whatever condition we like and then `DELETE ... WHERE id IN (...)` using identifiers (primary keys) from the result set of the first query.

**Alternatives**

The proposed solution does not actually optimize the queries, but it prevents long time locks on that tables, which completely block hydra service for hours, as the tables grow. A real optimization would maybe require an explicit indexed column which marks obsolete records for delete, thus implementing a logical delete.

**Comment by Benehiko** [comment]
I think this makes sense! Have you been able to test this manually?

**Comment by flavioleggio** [comment]
About the main solution, i have not tried it yet, but I will on my development database. I will let you know as soon as i have news on this.
About the alternatives, I am pretty sure that implementing logical delete will have a massive performance gain in production environment, but I think it will have a deeper impact on coding size, as this means that we have to introduce a new column on each entity and change the database structure accordingly.
Do you think there is some other smart way to query `deletable` records using some already existing indexed column(s)? I could not come up with any solution other than adding an explicit column.

**Comment by flavioleggio** [comment]
Here are the results for the `EXPLAIN` of my version of the `SELECT` (I just substituted `DELETE` with `SELECT challenge`) in my development environment, in which `hydra_oauth2_authentication_request` table has 936 records.
|select_type|table|possible_keys|key|rows|filtered|Extra|
|-----------|-----|-------------|---|----|--------|-----|
|PRIMARY|hydra_oauth2_authentication_request|||936|33.33|Using where|
|DEPENDENT SUBQUERY|hydra_oauth2_consent_request|PRIMARY,hydra_oauth2_consent_request_login_challenge_idx|hydra_oauth2_consent_request_login_challenge_idx|1|100.0|Using index|
|DEPENDENT SUBQUERY|hydra_oauth2_consent_request_handled|PRIMARY|PRIMARY|1|19.0|Using where|
|DEPENDENT SUBQUERY|hydra_oauth2_authentication_request_handled|PRIMARY|PRIMARY|1|19.0|Using where|

As you can see, the `WHERE requested_at` condition is run against all 936 records in the table, which is obviously the same as for the equivalent `DELETE`, with the difference that this `SELECT` does not put any lock on the table, while the `DELETE` does, as far as I know, for the entire execution time.

The query gives back 15 records matching, in this case. Running `EXPLAIN DELETE FROM hydra_oauth2_authentication_request WHERE challenge IN (...)` with those 15 challenges gives back this analysis.
|select_type|table|possible_keys|key|rows|filtered|Extra|
|-----------|-----|-------------|---|----|--------|-----|
|DELETE|hydra_oauth2_authentication_request|PRIMARY|PRIMARY|15|100.0|Using where|

Here we use the table's primary key and we obviously just hit 15 records: I guess that's the minimum lock time we can get from our table structure without altering it.

If you want, I can try to analyse this in my production environment too, but I think that this results should be enough to prove my point. Do you agree?

**Comment by Benehiko** [comment]
> About the main solution, i have not tried it yet, but I will on my development database. I will let you know as soon as i have news on this.
> About the alternatives, I am pretty sure that implementing logical delete will have a massive performance gain in production environment, but I think it will have a deeper impact on coding size, as this means that we have to introduce a new column on each entity and change the database structure accordingly.
> Do you think there is some other smart way to query _deletable_ records using some already existing indexed column(s)? I could not come up with any solution other than adding an explicit column.

Yeah the database actually requires a rework, but it's too big a scope to tackle to fix just this one thing :) 
The best, from what I can see, is just to follow through with your method of select and then passing the primary keys to the delete method.
I will have to look into this more in-depth as well to see if there is any alternative I'm missing. 




> Here are the results for the `EXPLAIN` of my version of the `SELECT` (I just substituted `DELETE` with `SELECT challenge`) in my development environment, in which `hydra_oauth2_authentication_request` table has 936 records.
> 
> select_type	table	possible_keys	key	rows	filtered	Extra
> PRIMARY	hydra_oauth2_authentication_request			936	33.33	Using where
> DEPENDENT SUBQUERY	hydra_oauth2_consent_request	PRIMARY,hydra_oauth2_consent_request_login_challenge_idx	hydra_oauth2_consent_request_login_challenge_idx	1	100.0	Using index
> DEPENDENT SUBQUERY	hydra_oauth2_consent_request_handled	PRIMARY	PRIMARY	1	19.0	Using where
> DEPENDENT SUBQUERY	hydra_oauth2_authentication_request_handled	PRIMARY	PRIMARY	1	19.0	Using where
> As you can see, the `WHERE requested_at` condition is run against all 936 records in the table, which is obviously the same as for the equivalent `DELETE`, with the difference that this `SELECT` does not put any lock on the table, while the `DELETE` does, as far as I know, for the entire execution time.
> 
> The query gives back 15 records matching, in this case. Running `EXPLAIN DELETE FROM hydra_oauth2_authentication_request WHERE challenge IN (...)` with those 15 challenges gives back this analysis.
> 
> select_type	table	possible_keys	key	rows	filtered	Extra
> DELETE	hydra_oauth2_authentication_request	PRIMARY	PRIMARY	15	100.0	Using where
> Here we use the table's primary key and we obviously just hit 15 records: I guess that's the minimum lock time we can get from our table structure without altering it.
> 
> If you want, I can try to analyse this in my production environment too, but I think that this results should be enough to prove my point. Do you agree?

This makes sense :+1:

**Comment by flavioleggio** [comment]
I had a chance to try the cleanup procedure in a backup of my production database (identical tier instance too). I obviously just have records from today (00:00 AM) which are eligible for delete, because we run the janitor command each night. The `SELECT` query took **11 minutes** and extracted 39750 records, then i put all those challenges in a `DELETE FROM hydra_oauth2_authentication_request WHERE challenge IN (...)`  and this query took **6 minutes**.
Unfortunately, this is no good news, as we have to keep in mind that I only took a portion of the usual time window (from 00:00 to 08:00, at the time I extracted deletable records). I have to conclude that also the DELETE has its own performance issues dealing with a big table, maybe because of some internal reordering logic that InnoDB engine operates.
Maybe the table locking itself is only related to the behavior of this specific DBMS (gap locking?).

However, I don't know the DBMS only locks records in the IN condition or the whole table, I need some other tests for that. If it is the first case, execution time is not a big issue, otherwise we might have to change strategy or at least delete one by one or in batch.

**Comment by aeneasr** [comment]
Thank you for investigating this @flavioleggio ! Performance might indeed be dependent on the database family and storage engine. Generally I think that a `DELETE ... WHERE IN` makes sense. I guess we did not anticipate that the existing queries would also be slow.

One low hanging fruit would be to refactor the [joins](https://github.com/ory/hydra/blob/master/persistence/sql/persister_consent.go#L468-L481) to result in the opposite (get all of the IDs that need to be removed) in a `SELECT` query outside of a transaction (because once stale always stale) and with a configurable limit (e.g. 1000 items).

Then, we run `DELETE WHERE IN` (not sure if supported on all DBS?) on those items.

That job would then need to run more often which makes sense as we distribute the amount of time the job takes over the course of the day.

The only question is if the `SELECT` and `DELETE` query become more reliable through this.

I also believe that deleting many items in the same statement (read: transaction) means that we are indeed locking at least those values for the time it takes to delete them. Another alternative would be to run batches of e.g. 10 or 100 items in separate statements. This is probably DB specific!

**Comment by flavioleggio** [comment]
Hi @aeneasr and thank you for your feedback on this.
I've done a lot of research and testing on my production backups in these two days. Here's what I found out.
Looking at [innodb docs](https://dev.mysql.com/doc/refman/8.0/en/innodb-locks-set.html) it seems like in `DELETE`s with conditions that make it examine non-indexed columns every record is locked until completion.
> If you have no indexes suitable for your statement and MySQL must scan the entire table to process the statement, every row of the table becomes locked, which in turn blocks all inserts by other users to the table. It is important to create good indexes so that your queries do not unnecessarily scan many rows.

This explains why our `DELETE`s perform so bad and lock the entire table: we base it on the `requested_at` column. I think it is not a good idea to index such a column, mainly because of its high cardinality (usually not a good idea with any timestamp column, imo). This is the main reason for my other idea of adding some explicit indexed column to identify no more useful requests somewhere in the application logic (maybe related to #2514).

The same docs also say
> DELETE FROM ... WHERE ... sets an exclusive next-key lock on every record the search encounters. However, only an index record lock is required for statements that lock rows using a unique index to search for a unique row.

This tell us that if we delete records in batch with `DELETE FROM ... WHERE IN (...)` we just lock the row and the gap before the index record, as it talks about [next-key lock](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_next_key_lock). Here we may have issues related to not working with auto-increment numbers but with a varchar primary key (challenge) which is something like an uuid, i guess, but please correct me if I am wrong. In this case, inserting a new record may require taking a gap which is locked, thus resulting in an effective table lock.

This research brought me to a couple of tests.
I tried deleting a chunk of 1000 records with the `IN` condition and it took 3 seconds. This mean that for 40k records in loop it would have taken almost 2 minutes, which is better than 6 minutes. For this reason I tried with a stored procedure
```sql
USE HYDRA;
DROP PROCEDURE IF EXISTS cleanup_requests;
DELIMITER $$
CREATE PROCEDURE cleanup_requests ()
BEGIN
    REPEAT
    	DELETE FROM hydra_oauth2_authentication_request
		WHERE challenge IN (
		    ...
		  )
        LIMIT 1000;
    UNTIL ROW_COUNT() = 0 END REPEAT;
END$$
DELIMITER ;
CALL cleanup_requests();
```
The `IN` clause containing 40k challenges, this deletes every record 1000 at a time in a loop. I don't know if because of the limit or so, but this procedure took 4 minutes, which is still better than original 6 minutes. However (!) this still locks the table and prevents my from executing `INSERT`s in the meanwhile, which is too bad, because it breaks our service. Moreover, it seems that there is no way to create migrations for such procedures in `gobuffalo` and this solution may be DB and engine specific (other DBMS may not support stored procedures). Conclusion for this solution: a big NO NO.

I agree with @aeneasr in splitting operations in batch, however I don't think it is ok to distribute batch `DELETE`s during the day, as they lock the table and break hydra, even for a bunch of seconds, which is a lot of time in a mission critical service.
I think we should find a solution fast enough to be run during the service's maintenance window. The coordinating logic should be run inside janitor, which should run the `SELECT` part, keep result set somewhere in memory or in the file system and then run `DELETE`s in a loop, implementing splitting logic with a configurable batch size (1000 by default could be a good compromise) and a configurable sleep between queries, to let some other query get into play and not to lock everything.

The next step into my analysis is to try to externalize logic in a bash script or something similar, to try and benchmark with different batch sizes. We should also consider deleting one by one, which should put only a record level lock and should not lock anything else in the table.

**Comment by Benehiko** [comment]
yes, it makes sense. I also agree that the batch mode processing is the only way to go so far. However, we have some limitations we have to work around. So first one is that we cannot used stored procedures. Second is that gobuffalo/pop does not  seem to support batch mode processing.

That leaves us with two routes:
- We write the batch processing logic inside golang (this means our sql is simple, but we run more sql queries from go).
- We write one sql statement (somehow) that does batch deletes (without using stored procedures).

Also just a side note, these issues might not exist on a more *dangerous* janitor operation which does not care about the time at which the request was made for more intense cleanups, moreover we don't know if this issue exists on PostgreSQL.

**Comment by Benehiko** [comment]
My other concern with externalising the batch deletes (e.g. running the logic in golang instead of db) is that you're extremely dependant then on the host machine running janitor as well as the network speed/latency between janitor and the db. This might actually end up making the janitor cleanup routine execute way longer than intended instead of just leaving it to the db completely.

**Comment by flavioleggio** [comment]
Personally, this would not be a concern for us, as we already use a bastion host with sufficient resources and near to the database for this kind of operations (which should be the standard for cleanup / maintenance jobs, imo). I think it is however true that this becomes an host related issue, but this can also bring to some guide lines on where to put janitor to work, like minimum host requirements, don't you think?

**Comment by Benehiko** [comment]
I would rather prefer to keep everything database side, this prevents us from creating more possible future problems

**Comment by flavioleggio** [comment]
I am thinking that as the performance issues are related to a timestamp column and the majority of the big tables just handle events and not entities state, maybe **horizontal partitioning** based on `requested_at` would come to the rescue. The table should be designed in such a way that queries shoul run in a single partition and a partition could be dropped entirely at will.
I am sure this is way more complex than the batch delete solution, but this can also solve other problems, for example opening the way to more _dangerous_ cleanups in which we drop, let's say, tables older than a month.

**Comment by aeneasr** [comment]
Thank you for the research! Maybe I did not really make clear what I intended to say. So my idea was this:

```
rows, err := sql.Query("SELECT pk FROM ... JOIN ... WHERE requested_at ... LIMIT 1000")
pks := fromRows(rows)

sql.Exec("DELETE FROM ... WHERE id IN (%pks))")
```

So basically, we first select all the PKs using SELECT which might be slow but shouldn't cause a lock. Then we run the DELETE in a separate transaction. This means that we do not lock the table! This we could then run over the day as a background tasks (e.g. every 10 minutes) as it shouldn't impact locking of the tables? Or did miss the point completely 😅

**Comment by flavioleggio** [comment]
My only objection on this idea is that the `SELECT` would take a lot of time *each time*. Maybe we could select all records (or just a big part with a bigger limit, like 10k, configurable?) once and then run all the needed `DELETE`s with smaller chunks (let's say 100 or 1000) at a time from that big result set. Those would be in separate transactions and would not lock the table at all, I guess.

**Comment by aeneasr** [comment]
That makes sense to me! Large (configurable) SELECT, batched deletes (configurable). Sort of divide & conquer :)

**Comment by flavioleggio** [comment]
I've got some nice news on this!

Tonight we put our *dangerous* version of the database cleanup out in the wild (actual production environment). The procedure is a simple bash script that selects ids and challenges from some tables (column `login_session_id` from table `hydra_oauth2_authentication_request`, limited to 1 million and column `challenge_id` from table `hydra_oauth2_access`, limited to half a million) and deletes in batches (100 records each) with the `IN` conditions from other tables (`hydra_oauth2_authentication_session` and `hydra_oauth2_consent_request`), taking advantage of cascades to cleanup the whole database. So it's the same idea with just a different amount of data.
Total execution time was 48 minutes for authentication sessions and requests, while it took 2 hours for consent requests. I guess consent are slower because of the number of cascade relations they need to handle.

The good news about this is that this didn't affect the running service at all! Total operation is still slow, but I am quite confident it can also be run during service time (better during low traffic period, as it can affect database host cpu and memory) with no consequences on service availability. At least this solution is safer!

**Comment by flavioleggio** [comment]
It would be really nice, but I need some pointers for both code and pr, as it is my first experience with Go and in general with code contributions on GH :)
Would you be up for a chat in slack one of these days?

**Comment by Benehiko** [comment]
Hey @flavioleggio,

I could maybe help you with some pointers, just message me on slack :)

**Comment by pharman** [comment]
We have tried running janitor on a production copy of our database which has around 500gb in it. Deleting tokens works fine, but requests just times out after around 1 hour:
```
Error: Could not cleanup inactive login-consent requests: conn closed
```
Not sure if this is to do with the DSN settings (postgres) or just the data size and slow query. The _requests tables take up around 150gb. The DB is reasonable (db.r5.xlarge with 3000 IOPS), certainly more than is needed for day to day operations. I will try increasing the IOPS to see if that helps :)

**Comment by pharman** [comment]
@flavioleggio we can lend a hand with this even if just testing.

**Comment by flavioleggio** [comment]
Hi @pharman, I am already working on this in [my fork](https://github.com/flavioleggio/hydra/tree/janitor-slow-queries). I had some issues in replicating the safe delete logic in a separate query, but I am working on it. I am still experiencing some regressions, but as soon as I will have all tests passing, I will create a draft PR and you can comment / contribute there!

**Comment by aeneasr** [comment]
@pharman that'sprobably the same issue @flavioleggio is facing I believe. The proposed batch processing should definitely help here!
