### ISSUE TITLE
Invalid json response with get login request

### ISSUE THREAD

**Issue by dylandelaporte** [ory/hydra#2515]
**Describe the bug**

Thank you for this great project!

I think I ran into a bug while playing with the hydra endpoints. I developed a small NodeJS application similar to the hydra login consent application to perform login and consent acceptation. It is not using the hydra-client package.

After being able to correctly login and accept consent I get redirected to the callback url. From here everything works fine. Then I try to access back my login/consent application with the same login challenge. The application is calling the get login request api `GET http://hydra:4445/oauth2/auth/requests/login?login_challenge=9d26f29f511a44a39c6f6fd33d19ea56` and it has an invalid json response with two json objects.

```json
{
    "redirect_to": "https://oauth.domain.com/oauth2/auth?response_type=code&client_id=client-1&redirect_uri=https%3A%2F%2Fdomain.com%2Fcallback&scope=openid%20offline&state=qhbaiortnpmxapojffrocawg"
}{
    "challenge": "9d26f29f511a44a39c6f6fd33d19ea56",
    "requested_scope": [
        "openid",
        "offline"
    ],
    "requested_access_token_audience": [],
    "skip": false,
    "subject": "",
    "oidc_context": {},
    "client": {
        "client_id": "client-1",
        "client_name": "",
        "redirect_uris": [
            "https://domain.com/callback"
        ],
        "grant_types": [
            "authorization_code",
            "refresh_token",
            "client_credentials",
            "implicit"
        ],
        "response_types": [
            "token",
            "code",
            "id_token"
        ],
        "scope": "openid offline",
        "audience": [],
        "owner": "",
        "policy_uri": "",
        "allowed_cors_origins": [],
        "tos_uri": "",
        "client_uri": "",
        "logo_uri": "",
        "contacts": [],
        "client_secret_expires_at": 0,
        "subject_type": "public",
        "jwks": {},
        "token_endpoint_auth_method": "client_secret_basic",
        "userinfo_signed_response_alg": "none",
        "created_at": "2021-04-30T23:43:38Z",
        "updated_at": "2021-04-30T23:43:38.15676Z",
        "metadata": {}
    },
    "request_url": "https://oauth.domain.com/oauth2/auth?response_type=code&client_id=client-1&redirect_uri=https%3A%2F%2Fdomain.com%2Fcallback&scope=openid%20offline&state=qhbaiortnpmxapojffrocawg",
    "session_id": "5f0a364b-b6a3-4792-a9bd-2fab22701c1d"
}
```

I seems to occur only when I call a second time this endpoint after login and consent is completed.

**Reproducing the bug**

1. Run hydra
2. Get login request and accept login
```
GET /oauth2/auth/requests/login
PUT /oauth2/auth/requests/login/accept
```
3. Get consent request and accept consent
```
GET /oauth2/auth/requests/consent
PUT /oauth2/auth/requests/consent/accept
```
(from that point I was logged in and redirected to the callback page)
4. Call the get login request api with the same challenge

_Server logs_

```
time=2021-05-04T01:18:11Z level=info msg=started handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip,deflate user-agent:node-fetch/1.0 (+https://github.com/bitinn/node-fetch)] host:hydra:4445 method:GET path:/oauth2/auth/requests/login query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.19.0.10:51234 scheme:http]

2021/05/04 01:18:11 http: superfluous response.WriteHeader call from github.com/urfave/negroni.(*responseWriter).WriteHeader (response_writer.go:53)

time=2021-05-04T01:18:11Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* accept-encoding:gzip,deflate user-agent:node-fetch/1.0 (+https://github.com/bitinn/node-fetch)] host:hydra:4445 method:GET path:/oauth2/auth/requests/login query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.19.0.10:51234 scheme:http] http_response=map[status:200 text_status:OK took:16.625652ms]
```

_Server configuration_

Hydra was configured using environment variables: `SECRETS_SYSTEM`, `DSN`,  `URLS_SELF_PUBLIC`, `URLS_CONSENT`, `URLS_LOGIN`, `URLS_LOGOUT`

**Expected behavior**

The response from `http://hydra:4445/oauth2/auth/requests/login?login_challenge=9d26f29f511a44a39c6f6fd33d19ea56` should only contain:

```json
{
    "redirect_to": "https://oauth.domain.com/oauth2/auth?response_type=code&client_id=client-1&redirect_uri=https%3A%2F%2Fdomain.com%2Fcallback&scope=openid%20offline&state=qhbaiortnpmxapojffrocawg"
}
```

**Environment**

- Version: latest hydra [3e37546a878b248bf92b09697e0d1425fb1bc396](https://github.com/ory/hydra/commit/3e37546a878b248bf92b09697e0d1425fb1bc396)
- Environment: Docker, ARM64
- Hydra client: Custom, NodeJS 

**Additional context**

None.

**Comment by aeneasr** [comment]
@svrakitin the returns are missing: 

https://github.com/ory/hydra/pull/2473/files#diff-567166c33485b3996843a300681ef6f4cba3e7c340c63f91a96edef0582eb908L274-R275

https://github.com/ory/hydra/pull/2473/files#diff-567166c33485b3996843a300681ef6f4cba3e7c340c63f91a96edef0582eb908L497-R499

**Comment by svrakitin** [comment]
@aeneasr gonna fix it and add missing tests

**Comment by aeneasr** [comment]
Thank you!
