### ISSUE TITLE
Contributing guide is lacking information how to run tests

### ISSUE THREAD

**Issue by mitar** [ory/hydra#2532]
**Describe the bug**

I am trying to run tests to test my PR. I read [these instructions](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#pull-request-procedure) but they do not work. Just running `go test ./...` fails with many lines like:

```
Received unexpected error:
the DSN connection string looks like a SQLite connection, but SQLite support was not built into the binary. Please check if you have downloaded the correct binary or are using the correct Docker Image. Binary archives and Docker Images indicate SQLite support by appending the -sqlite suffix
```

I would expect that tests just work, or that contributing guide explains how to run tests locally fully. The `(or equivalent)` part in contributing guide does not tell me much. Please be precise. How can I run tests in this particular repository.

**Environment**

- Version: c8e65a685441a57f18e5389d527989555369fb20
- Environment: Ubuntu 18.04

**Comment by aeneasr** [comment]
You can find this in the README: https://github.com/ory/hydra#running-tests :)

**Comment by mitar** [comment]
Could that be linked to from the contributing file? Otherwise the contributing file is misleading.
