### ISSUE TITLE
Authorization requests with prompt=create cause errors in Hydra

### ISSUE THREAD

**Issue by felixjung** [ory/hydra#2538]
**Describe the bug**

When making a login request with the value `create` for the `prompt` parameter, Hydra returns an error to the client after the login endpoint application accepts the login request.

> The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Used unknown value '[create]' for prompt parameter

**Reproducing the bug**

1. Copy the login request URL from the hydra example client application and update it to have `prompt=create` instead of `prompt=`.
2. Open the login request URL.
3. Accept the login request from the login endpoint application, so that Hydra redirects you to the client.

```
hydra_1                | time=2021-05-19T15:54:04Z level=info msg=access denied audience=audit error=map[debug: message:invalid_request reason:Used unknown value '[create]' for prompt parameter status:Bad Request status_code:400] http_request=map[headers:map[accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 accept-encoding:gzip, deflate, br accept-language:de,en-US;q=0.9,en;q=0.8 cache-control:no-cache cookie:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". referer:http://localhost:8080/ user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36] host:localhost:4444 method:GET path:/oauth2/auth query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.24.0.1:57678 scheme:http] service_name=ORY Hydra service_version=

```

**Expected behavior**

Hydra should support existing and potentially new values for the `prompt` parameter and not return errors to clients. Potentially, the list of values should be configurable.

**Environment**

- Version: v1.10.2 (official docker image `oryd/hydra:v1.10.2`)
- Environment: Docker

**Comment by felixjung** [comment]
I would suggest to fix this by adding `create` to the [list of allowed values of the request validator](https://github.com/ory/hydra/blob/f588ec69d4fa03f602d3cbb20abd4188195a7375/driver/registry_base.go#L394). WDYT?

Maybe a better alternative would be to make the list of values in addition to the current ones configurable?

**Comment by aeneasr** [comment]
I believe the problem here is that `prompt=create` has no meaning to Ory Hydra: Does `prompt=create` (or `prompt=foo`) mean that we need to force the login flow? Or skip it? Or ignore the parameter?

If you are looking for adding context to your login app I would recommend to use the `request_url` of the Login Request to see the original OAuth2 URL which might include additional parameters such as `action=register` that have no meaning in OpenID Connect language and can therefore safely be ignored!

**Comment by felixjung** [comment]
Hm yeah, could do that. Using the existing draft for user registration seems nicer than creating our own parameter, though. So I was hoping to be able to start adopting drafts like this one or like `prompt=select_account` (which seems like it's already part of core and is being discussed in #1943). Is this something you wouldn't be willing to do until `prompt=create` makes it into the spec?

I could imagine a simple implementation where any existing session cookies from Hydra are thrown away. Once support for `prompt=select_account` is supported, doing `prompt=create` could create an additional session.

**Comment by felixjung** [comment]
OK, we can work around that. Thanks.

**Comment by aeneasr** [comment]
Thank you - closing then!
