### ISSUE TITLE
parsing of allow_termination_from from environment variable is broken

### ISSUE THREAD

**Issue by vesvalo** [ory/hydra#2541]
**Describe the bug**

Parsing of the `allow_termination_from` config parameter from the environment variable is broken, hydra throws the errors:

```
The configuration contains values or keys which are invalid:
serve.tls: map[allow_termination_from:127.0.0.1/32]
           ^-- doesn't validate with "#/definitions/tls_config"

The configuration contains values or keys which are invalid:
serve.tls.allow_termination_from: 127.0.0.1/32
                                  ^-- expected array, but got string
```

**Reproducing the bug**
run `hydra serve all` with SERVE_TLS_ALLOW_TERMINATION_FROM environment variable (other required parameters are omitted here) 
```
export SERVE_TLS_ALLOW_TERMINATION_FROM="127.0.0.1/32" 
hydra serve all
```

or 
```
export SERVE_TLS_ALLOW_TERMINATION_FROM="[127.0.0.1/32]" 
hydra serve all
```

**Environment**

- Version: v1.10.2
- Environment: Docker, Windows 10, Linux

**Additional context**
from the spec/config.json:
```
        "allow_termination_from": {
          "type": "array",
          "description": "Whitelist one or multiple CIDR address ranges and allow them to terminate TLS connections. Be aware that the X-Forwarded-Proto header must be set and must never be modifiable by anyone but your proxy / gateway / load balancer. Supports ipv4 and ipv6. Hydra serves http instead of https when this option is set.",
          "items": {
            "$ref": "#/definitions/cidr"
          }
        }
```
if this $ref is replaced with the actual content of the cidr definition, the parsing of this parameter works fine and hydra starts without those errors

**Comment by mityakoval** [comment]
+ 1

**Comment by inaniyants** [comment]
+1

**Comment by aeneasr** [comment]
Please don’t +1 your colleagues, it’s against our contribution guidelines and will certainly not help answer or fulfill your question.

**Comment by aeneasr** [comment]
You can now use JSON to specify this:

```
SERVE_TLS_ALLOW_TERMINATION_FROM='["127.0.0.1/32"]' 
```
