### ISSUE TITLE
Separate client management API from the API used for dynamic client registration and configuration.

### ISSUE THREAD

**Issue by dadrus** [ory/hydra#2549]
As of today the endpoints for the dynamic client registration and configuration are implemented as administrative end points and not as special purpose public ones. This has at least the following downsides:
* It is not possible to store additional information about the client, which shall not be available to the client itself. Best example is configuring per client valid ttls for the issued tokens as discussed in #1529.
* It is not possible to define which scopes a "dynamic" client is allowed to use and which not.
* Even the authentication of a "dynamic" client could happen in an infrastructure component, like a proxy, or an API-Gateway, it is very hard to do a proper authorization of requests to the configuration endpoint
* One is limited in products to be able to expose currently available `/clients` endpoints to support dynamic client registration and configuration.

**Describe the solution you'd like**

A pure admin API for client management purposes and public endpoints for dynamic client registration and configuration purposes. Configuration of requirements for the clients, which will register dynamically, shall be possible as well. The API for the public endpoints shall support proper authentication and authorization.

**Comment by fjvierap** [comment]
@dadrus @aeneasr a new PR has been created for this... Please review when you have sometime
