### ISSUE TITLE
oauth2: replace redirect uri exact match with protocol/host/path match

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#257]
>    The authorization server SHOULD require the client to provide the
>    complete redirection URI (the client MAY use the "state" request
>    parameter to achieve per-request customization).  If requiring the
>    registration of the complete redirection URI is not possible, the
>    authorization server SHOULD require the registration of the URI
>    scheme, authority, and path (allowing the client to dynamically vary
>    only the query component of the redirection URI when requesting
>    authorization).

**Comment by waynerobinson** [comment]
Specifically, allow clients to vary the query parameters of URLs.

**Comment by arekkas** [comment]
One example could be:

> http://foo/bar includes http://foo/bar?baz but http://foo/bar?baz=bar does not include http://foo/bar/baz=baz

**Comment by matteosuppo** [comment]
Would it be possible to specify a wildcard path? LIke http://foo/* Are there security shortcomings in doing so?

**Comment by arekkas** [comment]
@matteosuppo I don't think this would comply with:

> If requiring the
registration of the complete redirection URI is not possible, the
authorization server SHOULD require the registration of the URI
scheme, authority, and path (allowing the client to dynamically vary
only the query component of the redirection URI when requesting
authorization).

**Comment by arekkas** [comment]
What needs to be done for this is parsing urls and removing query components [here](https://github.com/ory/fosite/blob/master/authorize_helper.go#L79).

@zepatrik this is a good issue for you, ping me when you have time to address it.

**Comment by arekkas** [comment]
Interestingly enough, the spec also says:

> 3.1.2.3.  Dynamic Configuration
>
>   If multiple redirection URIs have been registered, if only part of
   the redirection URI has been registered, or if no redirection URI has
   been registered, the client MUST include a redirection URI with the
   authorization request using the "redirect_uri" request parameter.
>
>   When a redirection URI is included in an authorization request, the
   authorization server MUST compare and match the value received
   against at least one of the registered redirection URIs (or URI
   components) as defined in [RFC3986] Section 6, if any redirection
   URIs were registered.  If the client registration included the full
   redirection URI, **the authorization server MUST compare the two URIs
   using simple string comparison as defined in [RFC3986] Section 6.2.1.**

So, which one is it now 🤷‍♂️

**Comment by arekkas** [comment]
Right, so the complete section says:

> 
   The authorization server SHOULD require the client to provide the
   complete redirection URI (the client MAY use the "state" request
   parameter to achieve per-request customization).  If requiring the
   registration of the complete redirection URI is not possible, the
   authorization server SHOULD require the registration of the URI
   scheme, authority, and path (allowing the client to dynamically vary
   only the query component of the redirection URI when requesting
   authorization).

So if it's not possible to register the full URI, then we should fall back to the partial URI. Since we are capable of registering the full URI, this should not be the case for us.

Closing.

**Comment by arekkas** [comment]
> Protocol/host/path match can be useful for nested redirects:

That would not be compliant with the OpenID Dynamic Discovery so it's out of question unfortunately.

> does that mean we can use the state param to store it there ? I thought the state param was for security and should be random

No, it means that the state parameter will be appended to the redirect URL despite it not being whitelisted.

**Comment by arekkas** [comment]
Yes, you can also store it on the server-side. You have to store the state anyways in a cookie, so why not the redirect value? It will also make it harder to spoof this.

We inherit from Go. Usually also depends on your API gateway etc.

**Comment by mderazon** [comment]
> Yes, you can also store it on the server-side. You have to store the state anyways in a cookie, so why not the redirect value?

Good point. Thanks 👍

**Comment by kmandeville** [comment]
I have a question. My application uses the URL path to discern between different customers domains, like http://localhost/customer1/app, and http://localhost/customer2/app. Because of this, we've always been doing a partial match on the beginning of the url with just the scheme and domain. Now with these changes per the CVE, we'd have to do full match, which as you can see won't be possible with the way we've structured our URLs. It's pretty extensive throughout the app and APIs so changing out our uri structure would be difficult. Is there some way I could customize this to allow a single wildcard value in the URL where our customer name goes? Is there a way to override the matching with a custom matcher that would support a wildcard?
