### ISSUE TITLE
README links to archived example apps

### ISSUE THREAD

**Issue by mitar** [ory/hydra#2578]
Currently in the README:

> Implementing the login and consent app in a different language is easy, and exemplary consent apps (Go, Node) and SDKs are provided.

But links to `Go` and `Node` apps link to archived repositories. Should those links be updated?

* https://github.com/ory/hydra-consent-app-go
* https://github.com/ory/hydra-consent-app-express

**Comment by aeneasr** [comment]
Yes, it should link to: https://www.ory.sh/hydra/docs/sdk

Would you be up for a PR? :)

**Comment by vinckr** [comment]
I will take this one, thanks a ton for your watchful eyes @mitar
