### ISSUE TITLE
Always getting skip as false in the consent request for android custom scheme redirect urls

### ISSUE THREAD

**Issue by Sharad-Regoti-Unotech** [ory/hydra#2585]
**Describe the bug**
I am using the [android-auth-package ](https://github.com/openid/AppAuth-Android) with a public client to initial auth-flow with PKCE. 
I have successfully integrated the app & I am able to get refresh, id, access token.

But every time it I get skip = false even though I have set remember to true while accepting the initial consent,
After debugging the ory code, I believe this part is the issue
![image](https://user-images.githubusercontent.com/82866958/123097016-547d4c00-d44d-11eb-80a0-7a65d2bee26b.png)

I am using custom scheme redirect URLs (e.g -> `com.example.com`) because of that the above-mentioned code triggers & I don't get skip = true

If i use https based redirect URLs instead of custom scheme based URLs every thing works perfectly.

I think these are some related issues
https://github.com/ory/hydra/issues/866
https://github.com/ory/hydra/issues/2108

**Reproducing the bug**

1) Create a client on ory hydra & set the authentication method to none
2) Install the demo app provided [here](https://github.com/openid/AppAuth-Android/tree/master/app), (you have to change the configuration provided in this [file](https://github.com/openid/AppAuth-Android/blob/master/app/res/raw/auth_config.json))
3) Register a custom scheme URL in the app & ensure that the same URL is set a redirect URL while client registration

_Server logs_

_Server configuration_

**Expected behavior**
Ory should set skip = true for android custom scheme redirect urls

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
This is unfortunately expected behaviour as required by the OpenID Connect Certification process. Without it, OpenID Certification would not be achieved.

The specification explains that public clients using a non-https redirect scheme have to go through consent always.

Would you maybe be open to add this to the documentation to help others avoid going down this rabbit hole? :) https://github.com/ory/hydra/blob/master/docs/docs/guides/oauth2-public-spa-mobile.mdx

**Comment by Sharad-Regoti-Unotech** [comment]
What would be the consequences if just comment out that part of the code in ory hydra as shown in the image?

**Comment by sharadregoti** [comment]
Ok, I'll update the docs.
Can you give me some pointers about what info should I add?

**Comment by aeneasr** [comment]
I think a section explaining that public clients can’t skip consent (and the reason why) would be a perfect start :)
