### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by driverpt** [ory/hydra#2597]
**Is your feature request related to a problem? Please describe.**

At the moment Hydra does not support NewRelic Tracing, but since most of the providers already support OpenTelemetry Standard, it would be nice to support this Standard.

**Describe the solution you'd like**

As title says

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by aeneasr** [comment]
Yup, the place to add that would be around here: https://github.com/ory/x/blob/master/tracing/tracer.go#L154

Contribs welcomed!

**Comment by driverpt** [comment]
I did some digging and this might be a breaking change, which approach you suggest?

**Comment by aeneasr** [comment]
What would be the breaking change?

**Comment by driverpt** [comment]
Currently there is still no clear migration strategy to Opentelemetry from Opentracing

https://github.com/open-telemetry/opentelemetry-go/issues/453

It's still unclear the way to go with the new Go Lib

**Comment by aeneasr** [comment]
The original issue was about new relic right? So new relic does not support the way we currently do metrics? If so, a breaking change would only be acceptable if we keep support for all existing providers

**Comment by driverpt** [comment]
Newrelic supports Open Telemetry Spec. But regarding the code itself, the interface has changed and some older providers may not be supported.

**Comment by matoous** [comment]
👋 heya, I tried to address this issue in https://github.com/ory/x/pull/440. Ones it is merged (if it is merged) I will open PR also here.

**Comment by aeneasr** [comment]
ory/x is merged :)
