### ISSUE TITLE
Jaeger being unavailable is a fatal error that stops service from starting

### ISSUE THREAD

**Issue by pike1212** [ory/hydra#2642]
**Describe the bug**

A failure to initialize the tracer is fatal, even though it won't affect the functionality of the service.

https://github.com/ory/hydra/blob/f588ec69d4fa03f602d3cbb20abd4188195a7375/driver/registry_base.go#L436

**Comment by aeneasr** [comment]
Yeah, that's definitely a bug and we shouldn't fatal in that case but instead retry to connect to Jaeger!

**Comment by Gituser143** [comment]
Hi! I'd like to contribute to this. Can I take it up?

**Comment by aeneasr** [comment]
Yes! :)
