### ISSUE TITLE
Multi-architecture builds

### ISSUE THREAD

**Issue by sidharthramesh** [ory/hydra#2663]
**Is your feature request related to a problem? Please describe.**

I'm using an M1 Mac, with docker. Trying to run the ORY Hydra image is very slow because it's built for x86.

**Describe the solution you'd like**

Include arm64 in the pipeline while pushing to Dockerhub for all ORY projects.

**Describe alternatives you've considered**

Building the image on my machine using the Dockerfile doesn't take much time. But with `docker buildx` now mature, and more people using ARM processors, it'd be great to have a docker image for the ARM64 architecture by default.

**Comment by aeneasr** [comment]
Absolutely! Unfortunately we do not have access to an M1 yet so it is difficult for us to test. What you could do qould be to use our goreleaser config and goreleaser image (https://github.com/ory/xgoreleaser) to figure out whats needed for M1 buidls and contribute those changes :)

**Comment by sidharthramesh** [comment]
Okay. Perfect! I'll take a look at the GitHub actions workflow. Will try to include arm64 using buildx.

**Comment by sidharthramesh** [comment]
Hey @aeneasr, I want to know where the hydra image is being built before being published to dockerhub. 

In the repo that you mentioned, I see the workflow for the oryd/xgoreleaser image, but I don't see one for hydra anywhere. So, I'm assuming then that the build happens on Dockerhub or another CI/CD provider?

**Comment by aeneasr** [comment]
We use goreleaser to build the binaries and images: https://goreleaser.com

The release command is: https://github.com/ory/ci/blob/master/src/scripts/releaser/release.sh#L30

Goreleaser is responsible for pushing everything :)

**Comment by sidharthramesh** [comment]
Luckily for us, goreleaser added this feature very recently: https://github.com/goreleaser/goreleaser/issues/530.

Leaving this for other contributors (and future me):

Found a nice tutorial here: https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/

There are some changes that are needed in the goreleaser.yaml file. Qemu and buildx should also be setup in circleCI before the goreleaser command is run.

**Comment by sidharthramesh** [comment]
Hey @aeneasr, I think setting use: buildx in the .goreleaser.yml is what's needed. However, I am not able to test this because it includes dealing with CircleCI and the orbs. Maybe you can test this out and see if it works?

**Comment by aeneasr** [comment]
The best way to test it would be to follow: https://github.com/ory/xgoreleaser#testing-builds

So basically make the changes you need for multi-arch, then update the xgoreleaser image to whatever is needed to get it working, then follow the steps in "testing builds".

Since I do not have an M1 I can not test it unfortunately.

**Comment by sidharthramesh** [comment]
Also, docker based QEMU emulation is available, but seems like the container should run in privileged mode: https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408

**Comment by aeneasr** [comment]
phew... no idea to be honest.

```
0.368 standard_init_linux.go:228: exec user process caused: exec format error
```

This usually means that the binary format does not match the architecture it's running on, afaik

**Comment by sidharthramesh** [comment]
Thank you so much!

**Comment by aeneasr** [comment]
:)
