### ISSUE TITLE
Jwks public keys with use=sig parameter to be treated same as key_ops=["verify"]

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#2681]
### Discussed in https://github.com/ory/hydra/discussions/2675

**Describe the bug**
When using private_key_jwt using a client's public keys url, the approach for validating signature should be the same for following both options

1. use = sig
2. key_ops = ["verify"]

As per Specs, both are optional. And also that if both are used, then the value provided in both should be consistent.
Ref: https://datatracker.ietf.org/doc/html/rfc7517
```
The "use" and "key_ops" JWK members SHOULD NOT be used together;
   however, if both are used, the information they convey MUST be
   consistent.  Applications should specify which of these members they
   use, if either is to be used by the application.
```

**Reproducing the bug**
<div type='discussions-op-text'>

<sup>Originally posted by **sagarshah1983** August 12, 2021</sup>
1. Register an OAuth client as follows

```
{
    "client_id": "31386382-2423-4116-a7bd-1af1c94c144b",
    "client_name": "service client app",
    "redirect_uris": [],
    "grant_types": [
        "client_credentials"
    ],
    "response_types": [
        "token"
    ],
    "scope": "openid",
    "owner": "service client app",
    "policy_uri": "",
    "allowed_cors_origins": [],
    "tos_uri": "",
    "client_uri": "",
    "logo_uri": "",
    "contacts": [],
    "client_secret_expires_at": 0,
    "subject_type": "public",
    "jwks_uri": "https://inferno.healthit.gov/inferno/.well-known/jwks.json",
    "jwks": {},
    "token_endpoint_auth_method": "private_key_jwt",
    "token_endpoint_auth_signing_alg": "ES384",
    "userinfo_signed_response_alg": "none",
    "created_at": "2021-08-11T22:12:00Z",
    "updated_at": "2021-08-11T22:11:59.898059Z",
    "metadata": {
        "external": true
    }
}


```
As shown above, here's the public keys located. However, any public keys are ok as long as it used key_ops parameter instead of use
https://inferno.healthit.gov/inferno/.well-known/jwks.json

2. Using the private key generated a signed token
3. Call the token endpoint using the client_assertion.
Request:
```
client_assertion=<signed jwt token>&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&grant_type=client_credentials&scope=openid
```

**Expected behavior**
Expected behavior is to get the access token successfully from Hydra

**Actual behavior**
```
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Unable to find ECDSA public key with use='sig' for kid '4b49a739d1eb115b3225f4cf9beb6d1b' in JSON Web Key Set."
}
```

**Environment**
Hydra 1.9 (Docker)

**Suggested Approach**
key_ops=["verify"] should be treated the same way as "use"="sig" value in the public keys when it comes to verifying the signed JWT tokens.

Appreciate for looking into it.

</div>

**Comment by aeneasr** [comment]
Thank you, we indeed do not check `key_ops`. Is it possible in your use case to rely on `use` instead? As per spec:

> Applications should specify which of these members they
   use, if either is to be used by the application.

I am not sure where we would specify this.

But yeah, we could also just add support for key_ops. I assume the relevant line is around here:

https://github.com/ory/fosite/blob/c4ff105ec7c4c31811fbfa3674a50a47534a48e4/client_authentication.go#L290

However, I looked into the library (https://github.com/square/go-jose/tree/v2) we use and they apparently do not support `key_ops`: https://github.com/square/go-jose/issues/270

**Comment by sagarshah1983** [comment]
Thank you for your response and clarifications @aeneasr!
Challenge is we need to get public keys via 3rd party client's public key url. And inferno is one of the certification tool which uses key_ops instead of use. So we have no control over the same.
Could we put the additional condition to check for key_ops at the line you mentioned and create a PR? I am not sure what all other tests or documentation may be involved at this point, but looking forward to see what can be done to resolve this issue?

Appreciate your response!

**Comment by aeneasr** [comment]
@sagarshah1983 sorry for my late reply - the best course of action is to add this functionality to go-jose (see https://github.com/square/go-jose/issues/270) and then update the dependency here once it is merged :)

**Comment by sagarshah1983** [comment]
Thanks @aeneasr for providing your direction.
