### ISSUE TITLE
Invalid http response code when calling Token endpoint with incorrect client id and secret

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#2682]
**Describe the bug**
We are calling token endpoint with incorrect client id and secret for client_credentials flow in order to test compliance with OpenID Specs - https://openid.net/specs/openid-connect-core-1_0-final.html#ClientAuthentication

As per specs section 3.1.3.4:
```
If the Token Request is invalid or unauthorized, the Authorization Server constructs the error response. The parameters of the Token Error Response are defined as in Section 5.2 of OAuth 2.0 [RFC6749]. 
The HTTP response body uses the application/json media type with HTTP response code of 400.
```

Same error (401) is received when calling token endpoint with private_key_jwt as well. Expected error code is 400 in this case.

**Reproducing the bug**
1. Call the token endpoint as below
curl --location --request POST 'https://{AUTHZ DNS}/oauth2/token'
--header 'Authorization: Basic aW52YWxpZDppbnZhbGlk'
--header 'Content-Type: application/x-www-form-urlencoded'
--data-urlencode 'grant_type=client_credentials'

_Server logs_
Default
_Server configuration_
Default

**Expected behavior**
Hydra fails the call and returns 400 error (as indicated on Open Id Specs), but instead its currently returning with 401 unauthorized error.

**Environment**
- Version: v1.9
- Environment: Docker

**Additional context**
Relevant question thread: https://github.com/ory/hydra/discussions/2677

**Comment by aeneasr** [comment]
I believe the OpenID spec is not accurate enough here. The original OAuth2 spec formulates it like this:

> invalid_client
>
>  Client authentication failed (e.g., unknown client, no
               client authentication included, or unsupported
               authentication method).  The authorization server MAY
               return an HTTP 401 (Unauthorized) status code to indicate
               which HTTP authentication schemes are supported.  If the
               client attempted to authenticate via the "Authorization"
               request header field, the authorization server MUST
               respond with an HTTP 401 (Unauthorized) status code and
               include the "WWW-Authenticate" response header field
               matching the authentication scheme used by the client.

https://datatracker.ietf.org/doc/html/rfc6749#section-5.2

We currently implement this approach. Given that we are also passing OpenID Connect Certification I would conclude that this is implemented correctly!

**Comment by sagarshah1983** [comment]
Thanks for your response @aeneasr 
So expected behaviour passing correct client id but incorrect client secret is also 401 error code Or should that be 400 in that case?

**Comment by aeneasr** [comment]
That is 401

**Comment by sagarshah1983** [comment]
Ok, so my usecase is little different sorry for confusing earlier with invalid client id and with client secret flow.
Use case: An oauth client with auth method as private_key_jwt
JWT Token is signed by the app using its keys in which it uses correct client_id but invalid iss claim and passes that assertion to Hydra. 
In this case, hydra fails saying invalid_client. Having said that client_id passed in the JWT token is still correct, but iss is not same as client_id.
Should that be reported as invalid_client or some other error from hydra as per OpenID Spec?

Let me know, if you have further questions on this

**Comment by aeneasr** [comment]
As the JWT fails to pass the requirements for authenticating the client, 401 is the correct error code here as well - this is also a test of OIDC Conformance so in line with what is allowed by OpenID Connect.

**Comment by sagarshah1983** [comment]
Thanks for clarifying that @aeneasr. This could be closed in that case.

**Comment by aeneasr** [comment]
My pleasure!
