### ISSUE TITLE
Configurable token endpoint auth methods supported

### ISSUE THREAD

**Issue by Crevil** [ory/hydra#2708]
**Is your feature request related to a problem? Please describe.**

Our use of hydra implies creating clients that are only allowed to use the `client_secret_basic` token auth method.
But as the `.well-known/openid-configuration` endpoint uses a hard coded list ([handler](https://github.com/ory/hydra/blob/1248553ce481487e9722f361bb4f4ac1f3a40af6/oauth2/handler.go#L241)) we cannot indicate this limitation clearly to clients.

**Describe the solution you'd like**

It would be nice if we could configure the supported auth methods on the well-known endpoint to send a clear signal to clients on what they can expect.

**Describe alternatives you've considered**

I'm not sure of any alternatives TBH except documenting this for clients to read elsewhere.

**Additional context**

We'd be happy to provide the implementation if we can settle on this is worth implementing and if we can align on the configuration paramteres.

**Comment by aeneasr** [comment]
AFAIK that field is only used during OIDC Dynamic Client Registration, implying that unless you support that, it shouldn't be an issue!

**Comment by Crevil** [comment]
Yeah by systems that is true, but we also see clients use it for manually inspecting the configuration.
TBH I'm not sure whether that is a general pattern. If one cannot usually rely on this data to indicate what clients can use, then I think we are all fine and can leave it as is. :+1

**Comment by aeneasr** [comment]
Ok in that case I think we should close it as there is currently no toggle to influence actual behavior. If you feel strongly about this it is also possible to implement the discovery as your own endpoint / proxy :)

**Comment by Crevil** [comment]
Fine with me. Thank you for the quick responses 🙏

Do you know whether other OIDC servers can be configured like this? Just if you happened to know. Otherwise I'll do some research on my own 😀

**Comment by aeneasr** [comment]
No idea, sorry!

**Comment by Crevil** [comment]
All right, thanks.

I'll close this for now and look around.

Thank you again 🙏🙌
