### ISSUE TITLE
hydra-client.acceptLoginRequest() returns 400 because of double encoded body

### ISSUE THREAD

**Issue by RickvdP** [ory/hydra#2718]
**Describe the bug**

Using  `@ory/hydra-client@1.10.6` hooked up with a local `hydra@v1.10.6` instance ​it seems that `acceptLoginRequest()` is in a way wrongly encoding the request body to the admin API endpoint, resulting in a 400 response.

When manually submitting the same `PUT` request with the same body, the request also fails. When correcting the `body` encoding manually, I'm being welcomed by a warm `200 OK` response - as expected.
​
**Reproducing the bug**

Vanilla hydra install with aforementioned JS client and the following code:

```
const hydraAdmin = new AdminApi(
 ​new Configuration({
   ​basePath: HYDRA_ADMIN_URL,
 ​}),
);

const loginApproval = await hydraAdmin.acceptLoginRequest(String(loginChallengeCookie), {
       ​subject: 'foo@bar.com',
​});
```

Results in 

```
Error: Request failed with status code 400
   ​at createError (/Users/rick/htdocs/beep-prototype/node_modules/axios/lib/core/createError.js:16:15)
   ​at settle (/Users/rick/htdocs/beep-prototype/node_modules/axios/lib/core/settle.js:17:12)
   ​at IncomingMessage.handleStreamEnd (/Users/rick/htdocs/beep-prototype/node_modules/axios/lib/adapters/http.js:269:11)
   ​at IncomingMessage.emit (events.js:412:35)
   ​at IncomingMessage.emit (domain.js:470:12)
   ​at endReadableNT (internal/streams/readable.js:1317:12)
   ​at processTicksAndRejections (internal/process/task_queues.js:82:21) {
 ​config: {
   ​url: 'http://127.0.0.1:4445/oauth2/auth/requests/login/accept?login_challenge=794982024dd24f1a8c3c6d6effd4ae43',
   ​method: 'put',
   ​data: '"{\\"subject\\":\\"foo@bar.com\\"}"',
   ​headers: {
     ​Accept: 'application/json, text/plain, */*',
     ​'Content-Type': 'application/json',
     ​'User-Agent': 'axios/0.21.3',
     ​'Content-Length': 31
   ​},
...
```

Highlight for `data: '"{\\"subject\\":\\"foo@bar.com\\"}"'` looking like it's encoded twice.

Earlier in the same method `const loginChallenge = await hydraAdmin.getLoginRequest(loginChallenge);` is used, which actually executes & returns as expected - proving network connectivity, misconfiguration or other flukes not to be the issue.

_Server logs_

```
level=error 
msg=An error occurred while handling a request audience=application error=map[debug: message:invalid_request reason:Unable to decode body because: json: cannot unmarshal string into Go value of type consent.HandledLoginRequest status:Bad Request status_code:400] 
http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br connection:keep-alive content-length:35 content-type:text/plain *client*:*uuid* user-agent:PostmanRuntime/7.28.4] host:127.0.0.1:4445 method:PUT path:/oauth2/auth/requests/login/accept query:login_challenge=794982024dd24f1a8c3c6d6effd4ae43 remote:172.19.0.1:56232 scheme:http] 
http_response=map[status_code:400] 
service_name=ORY 
Hydra service_version=v1.10.6
```

Just to outline the key error: `Unable to decode body because: json: cannot unmarshal string into Go value of type consent.HandledLoginRequest `

_Server configuration_

Using defaults w/o meaningful changes, so omitting

**Expected behavior**

`200 OK` pretty much :)

**Environment**

- Version: oryd/hydra:v1.10.6 docker image
- Environment: Mac ARM, Docker v20.10.8, build 3967b7d28e

**Additional context**

I can't quite put my finger on it but it seems that `hydra-client/api.ts L1922` is applying some encoding, but it doesn't seem to be hit when debugging.

Additionally curious why L3026 `acceptLoginRequest` accepts an optional `body?: AcceptLoginRequest,` as parameter, when the API docs indicate that the `subject` is always required (which makes sense). 

_I saw being mentioned that the SDKs are being moved out, but couldn't find the respective TypeScript hydro-client repo. Hope it's OK to submit issue here instead of the new (empty) hydro-sdk-js repo_

**Comment by joelshepherd** [comment]
Seems it might be related to this upstream change (bug?) in axios: https://github.com/axios/axios/issues/4018

I am getting this in an older client version too, after updating my packages.

**Comment by aeneasr** [comment]
Thank you @joelshepher it looks like that could be indeed the cause!

**Comment by RickvdP** [comment]
Yep - that's it. Confirming that it works fine when exact pinning axios to `0.21.1`.

Workaround for others:

```
# turn package-lock.json into npm-shrinkwrap.json
$ npm shrinkwrap
```

Find the `@ory/hydra-client` section and add the `dependencies` key, pinning to the last working version of axios.
```
    "@ory/hydra-client": {
      "version": "1.10.6",
      "resolved": "https://registry.npmjs.org/@ory/hydra-client/-/hydra-client-1.10.6.tgz",
      "integrity": "sha512-Y072QUujPHj0pSWaKPjax+zT9zTZFEMhLEd2QCHXzY61e8eWHh/iBq2sOzOmXfyyVIGN36DXdbmI3fL6LgRdnw==",
      "requires": {
        "axios": "^0.21.1"
      },
      "dependencies": {
        "axios": {
          "version": "0.21.1",
          "from": "axios@^0.21.3"
        }
      }
    },
```

The linked axios PR shows that they're attacking the problem already as we speak, so unless you're actively blocked right _now_, easiest fix is probably waiting until they've pushed 0.21.4, likely in a couple of hours.

**Comment by Karlinator** [comment]
Can confirm that Axios v0.21.4 fixes this.

**Comment by RickvdP** [comment]
_"The best kind of problems are the ones that solve themselves"_ - me, just now, 2021
