### ISSUE TITLE
POST /oauth2/token with refresh_token encounter 500 error because the id_token claims.ExpiresAt doesn't update

### ISSUE THREAD

**Issue by kobayashilin** [ory/hydra#2722]
**Describe the bug**

POST /oauth2/token with refresh_token encounter 500 error because the id_token claims.ExpiresAt doesn't updated.

**Reproducing the bug**

1. Finished the sign-in flow and get the refresh token / id token
![image](https://user-images.githubusercontent.com/4756036/132323511-c7a9271e-836d-4df4-9d1b-255c8c1ef229.png)

2. Wait the 1.1 min ( let the id_token expired ) & POST /oauth2/token with refresh_token to update token
```
curl 'http://127.0.0.1:4444/authorization/oauth2/token' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Accept: */*' \
  -H 'Origin: http://127.0.0.1:4200' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://127.0.0.1:4200/' \
  -H 'Accept-Language: en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7' \
  --data-raw 'request_type=si%3As&refresh_token=9nnGM5L8K-gqxVcp_UBYuAJnjEWafX6l2gcfFCwROec.nudxIfn_u1Ou0891_JBYAiobmRDbDhNvPKUl6cXBKjg&grant_type=refresh_token&client_id=pkce-1-auth-code-client' \
  --compressed
```

3. It will get the 500 internal server errors.
(If success, repeat step 2 again will get the 500 internal server errors. )

_Server logs_

```
time=2021-09-07T17:40:25+08:00 level=error msg=An error occurred audience=application error=map[debug:Failed to generate id token because expiry claim can not be in the past. message:server_error reason: status:Internal Server Error status_code:500] http_request=map[headers:map[accept:*/* accept-encoding:gzip, deflate, br accept-language:en-US,en;q=0.9,zh-TW;q=0.8,zh;q=0.7 origin:http://127.0.0.1:4200 referer:http://127.0.0.1:4200/ user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 x-request-id:71ff13891e217a582eb95780] host:127.0.0.1:4444 method:POST path:/authorization/oauth2/token query:<nil> remote:127.0.0.1:55805 scheme:http] service_name=ORY Hydra service_version=master
```

```yaml
ttl:
   refresh_token: 70m
   access_token: 1m
   id_token: 1m
```

Remember for for the cookie is 1hr.

**Expected behavior**

Get the new tokens

**Environment**

- Version: v1.9.0

**Additional context**

I found the several code in fosite.
1. Error occurs in.
https://github.com/ory/fosite/blob/0a48821b156f4a5dffa0f7149d30d5cf02636f37/handler/openid/strategy_jwt.go#L224

2. Reset behavior does't not work. 
There's reset behavior was ignore because !request.GetGrantedScopes().Has("openid") is true. However, there's no document mention it on [official docs](https://www.ory.sh/hydra/docs/reference/api#operation/oauth2Token) 
https://github.com/ory/fosite/blob/0a48821b156f4a5dffa0f7149d30d5cf02636f37/handler/openid/flow_refresh_token.go#L41

If there is any information I misunderstand, please let me know.

Thanks!

**Comment by aeneasr** [comment]
That’s an interesting find! Can you confirm this is an issue in the newest release also?

**Comment by kobayashilin** [comment]
Sorry It's my mistake to change the order for custom handler. 

![image](https://user-images.githubusercontent.com/4756036/132459841-b74e9779-4de5-480a-83b0-0f855f5ec64e.png)
