### ISSUE TITLE
immutable configuration key "dsn" was changed

### ISSUE THREAD

**Issue by ludydoo** [ory/hydra#2728]
**Describe the bug**

By using hashicorp vault to rotate the oryd hydra DSN, oryd hydra will log an error:

hydra time=2021-09-08T16:09:25Z level=error msg=A configuration value marked as immutable has changed. Rolling back to the last working configuration revision. To reload the values please restart the process. func=github.com/ory/x/configx.LogrusWatcher.func1 file=/go/pkg/mod/github.com/ory/x@v0.0.276/configx/options.go:121 audience=application error=map[message:immutable configuration key "dsn" was changed from "postgres:/REDACTED@postgres:5432/hydra" to "postgres://REDACTED@postgres:5432/hydra" trace:stack trace could not be recovered from error type *configx.ImmutableError] key=dsn new_value=postgres://REDACTED@postgres:5432/hydra old_value=postgres://REDACTED@postgres:5432/hydra service_name=ORY Hydra service_version=v1.10.6

**Reproducing the bug**

Rotate the config DNS value

**Expected behavior**

Should not throw an error, and should respect the new DSN, should not have to restart the process

**Environment**

v1.10.6

**Comment by aeneasr** [comment]
You can not update the DSN on the fly and it will never be possible, sorry!
