### ISSUE TITLE
Replace the unmaintained JWT library to the community maintained one

### ISSUE THREAD

**Issue by Botary** [ory/hydra#2741]
The current JWT library that replaced the vulnerable one in 9a484fc [github.com/form3tech-oss/jwt-go](https://github.com/form3tech-oss/jwt-go) is now unmaintained and archived

It can be replaced with a new community maintained library [github.com/golang-jwt/jwt](https://github.com/golang-jwt/jwt)

**Comment by zepatrik** [comment]
Thanks, finally there is a solution for the `jwt-go` problem...
Would you be up for a PR?

**Comment by zepatrik** [comment]
This also applies to our other projects btw, so anyone looking into this would help a lot by making a PR in the others as well.

**Comment by Botary** [comment]
Ok, do you wanna use `go mod replace directive` again? Or you wanna replace it properly and delete all the references to github.com/dgrijalva/jwt-go?

**Comment by zepatrik** [comment]
I think both, as we have to use `replace` for deep dependencies.

**Comment by Botary** [comment]
Ok, I'm preparing a pull request with only the `replace directive` for hydra, but how to approach `I confirm that this pull request does not address a security
vulnerability.` question? Because technically it doesn't since it was already solved with the previous library replacement.

**Comment by zepatrik** [comment]
That's fine, we discussed it here already.
