### ISSUE TITLE
Missing schemas

### ISSUE THREAD

**Issue by miroljub1995** [ory/hydra#2748]
Version in [schemastore](https://github.com/SchemaStore/schemastore) is updated to v1.10.6, but now it looks like some of the reference schemas could not be found, like:
- https://raw.githubusercontent.com/ory/hydra/v1.9.0-alpha.0.pre.2/.schema/config.schema.json
- https://raw.githubusercontent.com/ory/hydra/v1.9.3-pre.5/.schema/config.schema.json
- https://raw.githubusercontent.com/ory/hydra/v1.10.3-pre.1/spec/config.json
- https://raw.githubusercontent.com/ory/hydra/v1.10.5-pre.1/spec/config.json

**Comment by aeneasr** [comment]
Hello there, pre versions are test releases to ensure that the pipeline works. These releases are not published and deleted after successful runs so they are also not published in the schema store!

Are they referenced somewhere and if so could you link those references please? Thank you!

**Comment by miroljub1995** [comment]
For example here: https://github.com/ory/hydra/blob/v1.10.6/.schema/version.schema.json#L241
Schemastore is referencing v1.10.6, but v1.10.6 is referencing some pre versions.

**Comment by aeneasr** [comment]
@zepatrik shouldn't those be skipped by now?

**Comment by zepatrik** [comment]
https://github.com/ory/cli/blob/d460a89e8adce046ebb55ac306d2fd8ebdaa2066/cmd/dev/schema/render_version.go#L37-L40

They should be skipped :thinking:

**Comment by zepatrik** [comment]
and btw, it is fixed in the schemastore now again: https://github.com/SchemaStore/schemastore/pull/1838
