### ISSUE TITLE
Login request not fully marked as used until browser navigates to /oauth2/auth

### ISSUE THREAD

**Issue by Conduitry** [ory/hydra#2824]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After accepting a login request with `PUT /oauth2/auth/requests/login/accept` but before the user's browser has navigated to the public `/oauth2/auth` URL, the login request has not yet been properly marked as "used". Calls to `GET /oauth2/auth/requests/login` succeed (seemingly indicating that this is still a valid login request), but further calls to `PUT /oauth2/auth/requests/login/accept` return a 409 error coming from the underlying database.

### Reproducing the bug

1. Follow the steps in [the quickstart tutorial](https://www.ory.sh/hydra/docs/5min-tutorial/)
2. When logging in, using some mechanism to make sure the browser doesn't then navigate to the `redirect_to` target (For example: Open browser dev tools, submit the form with incorrect credentials, grab the cURL command, edit it to fix the incorrect credentials, and then manually run it without automatically following redirects.)
3. Navigate to or refresh the login form. Observe that the `login_challenge` is accepted by `GET /oauth2/auth/requests/login`.
4. Fill out the form again and submit it. Observe the error response from `PUT /oauth2/auth/requests/login/accept`

### Relevant log output

```shell
level=error msg=An error occurred while handling a request audience=application error=map[debug: message:failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: duplicate key value violates unique constraint "hydra_oauth2_authentication_request_handled_pkey" (SQLSTATE 23505): Unable to insert or update resource because a resource with that value exists already reason: status:Conflict status_code:409] http_request=map[headers:map[accept:application/json, text/plain, */* connection:close content-length:72 content-type:application/json user-agent:axios/0.19.2] host:hydra:4445 method:PUT path:/oauth2/auth/requests/login/accept query:Value is sensitive and has been redacted. To see the value set config key "log.leak_sensitive_values = true" or environment variable "LOG_LEAK_SENSITIVE_VALUES=true". remote:172.21.0.4:58858 scheme:http] http_response=map[status_code:409] service_name=ORY Hydra service_version=v1.10.6
```

### Version

1.10.6

### In which environment are you deploying?

Docker Compose

### Additional Context

There are many network-related or other reasons outside of our control that a user's browser might not successfully navigate to the intended target to complete the login. When they return and attempt to use the same `login_challenge`, the identity provider should be able to tell that this login challenge isn't going to work and redirect the user somewhere else as appropriate to get a new one.

We're currently planning on addressing this by redirecting back when getting a 409 from `PUT /oauth2/auth/requests/login/accept`, but ideally we'd know earlier in the process (during the `GET /oauth2/auth/requests/login`) that there was going to be a problem.

**Comment by svrakitin** [comment]
The 409/410 response includes original request url which you can use to restart auth flow with a new login challenge instead of failing.

**Comment by Conduitry** [comment]
The 410 response that I get from `GET /oauth2/auth/requests/login` after the browser has visited `/oauth2/auth` includes a `redirect_to` value, yes.

But no, the 409 response I'm getting from `PUT /oauth2/auth/requests/login/accept` (when the browser hasn't visited `/oauth2/auth`) that I'm describing here is just `{"error":"Unable to insert or update resource because a resource with that value exists already","error_description":""}`.

**Comment by svrakitin** [comment]
I think we just need to make responses more consistent for already handled requests. Meaning that 409 on accept should return redirect location as well as 410 on get.

**Comment by aeneasr** [comment]
Agreed @svrakitin !

**Comment by aeneasr** [comment]
Contribs welcomed :)

**Comment by Conduitry** [comment]
Is there a way to make this situation fail at the GET? Is there a reason not to? It would be nice to not have to hit my database/other services/etc. while verifying the user's login if accepting the login request is going to fail anyway.

**Comment by aeneasr** [comment]
Yeah, we could return a 409 Conflict with a dedicated error message and a `return_to` which returns to the correct URL to re-initiate the flow!

**Comment by mig5** [comment]
> Yeah, we could return a 409 Conflict with a dedicated error message and a return_to which returns to the correct URL to re-initiate the flow!

Yes, please do! As per my comment here https://github.com/ory/hydra/issues/1569#issuecomment-1085236619 - it's nice as a developer to be gracefully recovering from the 410 on LoginRequest having already been handled, with the redirect_to URL.

But we can't do it with ConsentRequest having already been used.

If you do it, please make it `redirect_to` and not `return_to`, for consistency.

Thank you for your work on Hydra!

**Comment by aeneasr** [comment]
Absolutely, that makes sense!

**Comment by aeneasr** [comment]
https://github.com/ory/hydra/pull/3088 was merged!
