### ISSUE TITLE
Add list of authors from git commit to an author file including name and email address

### ISSUE THREAD

**Issue by tacurran** [ory/hydra#2829]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The author file in this repository would contain a list of contributors to the project including the names and email addresses.

### Describe your ideal solution

This has to be a part of the CI so it must be automated. There need to be numerous filters for the name/email address extraction

### Workarounds or alternatives

The alternative would be a curated list manager since some contributors, for instance Dependabot, are not real contributors. 

### Version

v1.10.7

### Additional Context

@grantzvolsky

**Comment by grantzvolsky** [comment]
Based on a brief survey of how other projects give credit to contributors, these are some common options:

1. Use the author metadata that is submitted included in git commits. It is possible to remove duplicates using [mailmap](https://git-scm.com/docs/gitmailmap), a feature built into git.

2. List people who signed the CLA in a CONTRIBUTORS file and the copyright holders in an AUTHORS file. See e.g. [Go](https://github.com/golang/go/).

3. Maintain a curated list of authors.

4. Just refer to the git commit history.

I submitted a PR that implements option 1, without deduplication.
