### ISSUE TITLE
add shellcheck to circleci

### ISSUE THREAD

**Issue by tacurran** [ory/hydra#2832]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

add shellcheck to the ci pipeline for testing and security improvements

### Describe your ideal solution

add this orb https://circleci.com/developer/orbs/orb/circleci/shellcheck to the configuration file

### Workarounds or alternatives

do nothing (current approach)

### Version

v1.10.7

### Additional Context

@gr

**Comment by aeneasr** [comment]
PRs welcomed :)

**Comment by hirasawayuki** [comment]
@aeneasr Can I take this?

**Comment by aeneasr** [comment]
yes:)
