### ISSUE TITLE
Release @ory/hydra-client@v1.10.7 on NPM

### ISSUE THREAD

**Issue by spg** [ory/hydra#2837]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently only @ory/hydra-client@v1.10.6 is available on NPM

### Describe your ideal solution

Release @ory/hydra-client@v1.10.7 on NPM 😁

### Workarounds or alternatives

N/A

### Version

v1.10.7

**Comment by aeneasr** [comment]
Tracking as https://github.com/ory/hydra/issues/2950
