### ISSUE TITLE
Add token_prefixes 

### ISSUE THREAD

**Issue by ludydoo** [ory/hydra#2845]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Hello there!

This is a feature request to enable adding prefixes to tokens that ory hydra generates, in order to distinguish the token type without having to call the introspection endpoint, and to keep access tokens opaque.

https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
https://api.slack.com/authentication/token-types
https://stripe.com/docs/api/authentication

### Describe your ideal solution

An option in the configuration to specify the prefixes for each token type

```
token_prefixes:
  access_token:  acme:oac:
  id_token:      acme:oid:
  refresh_token: acme:orf:
```

### Workarounds or alternatives

None that I could find, apart from modifying the source code

### Version

Latest

### Additional Context

The reason for this feature request is because we will need to generate other types of tokens than OAuth tokens. Our policy enforcement endpoint would need to verify the inbound request token. 

For example, given these token types
- `oa:` (oauth token issued by hydra)
- `or:` (oauth refresh token issued by hydra)
- `oi:` (oauth id token issued by hydra)
- `pat:` (personal access token issued by my-pac-service)
- `mt:` (machine token issued by my-admin-service)

The policy enforcement endpoint would need to distinguish which service to call for the token introspection. 

If the tokens were prefixed, it would be very easy to call the appropriate service to verify the token. That could even be done eg. Envoy ext_authz, with a route matcher. 

Sample logic
```
func VerifyAuthHeader(authorizationHeader string){
  if strings.HasPrefix(authorizationHeader, "Bearer oa:"){
    // call hydra admin token introspection 
  }
  if strings.HasPrefix(authorizationHeader, "Bearer pat:"){
    // call my-pac-service
  }
}
...
```

**Comment by aeneasr** [comment]
Thank you for the idea!  Please note that this will only work for opaque tokens, so when not using the JWT strategy. It will also not work for ID tokens!

But for refresh and access tokens this could work :) Do you have a concrete use case in mind?

**Comment by aeneasr** [comment]
done in v2

**Comment by rdfirtal** [comment]
Will token prefixes become configurable like OP suggests?

**Comment by aeneasr** [comment]
no!

**Comment by NickUfer** [comment]
What is the reason for not making these configurable except for everybody knowing ory hydra is used?

**Comment by aeneasr** [comment]
https://github.com/ory/fosite/pull/733#issuecomment-1371989154
