### ISSUE TITLE
fix coveralls 

### ISSUE THREAD

**Issue by tacurran** [ory/hydra#2871]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

https://coveralls.io/github/ory/hydra?branch=master is not up to date and needs a configuration change

### Reproducing the bug

check the badge in readme.md

### Version

1.10.7

**Comment by aeneasr** [comment]
https://app.codecov.io/gh/ory/hydra is the correct codecov. I've also pushed a commit to remove the internal mocks and auto-generated code used only for tests to provide a more accurate code coverage!
