### ISSUE TITLE
Access Revocation Management

### ISSUE THREAD

**Issue by tsoestini** [ory/hydra#2889]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I have access tokens set to 1 hour and refresh tokens set to 30 days.
I do not remember login or consent sessions (I require the user to re-login and re-authorize on each new request for access).
However, I use the remember_for field on consent sessions to remember what access has been granted, so it can be revoked later.

I want to provide my users a way to see and revoke their past authorizations.

I see that there is a route to revoke all consent sessions for a subject with a client, which also revokes all descendent tokens.
I see also that there is a route to list remembered consent sessions.
I can list the remembered consent sessions, extract a list of clients the subject has granted access to, and allow the subject to select which clients it wants to revoke.

I am having trouble setting a good value for remember_for for how long consent sessions should be remembered for.

If I set it to remember consent sessions for 60 days, refresh tokens for that client could still be out there being refreshed, granting the client access tokens to access the user's resources. Meanwhile, the route to list remembered consent sessions will only return clients from the past 60 days, with no indication of other clients that might still have access to their resources.

On the other hand, if I set it to remember a consent session forever, then my data slowly balloons as users log in to the same clients on new devices or re-login anytime a client forgets the user's refresh token.

### Describe your ideal solution (See update below)

~~In an ideal situation, I could tell ORY Hydra to remember_for consent sessions forever. And, when ORY Hydra detects that all refresh tokens for that consent session have expired, ORY Hydra would automatically forget that consent session, to keep my data from ballooning.~~ 

### Workarounds or alternatives (See update below)

~~Another alternative would be if I could set a maximum refresh token chain lifetime, such as 60 days, to correspond to a 60-day remember_for period on consent sessions. So,~~
~~- the first refresh token would be valid for 30 days.~~
~~- if it was refreshed on day 20, that would be valid for 30 days (20+30 < 60)~~
~~- if that was refreshed on day 40, that would be valid for only 20 days (40+30 > 60, so it has to be shortened)~~
~~- after 60 days, that refresh token chain could no longer be used.~~

### Version

1.10.7

### Update: currently preferred solution

After discussion in the comments and the other threads, I think my current ideal solution is either:

(A) A global Absolute Lifetime setting, like auth0. (ref: https://auth0.com/docs/security/tokens/refresh-tokens/configure-refresh-token-expiration )

or

(B) A `absolute_lifetime` parameter that can be passed to `acceptConsent` with the effect that no tokens issued as a result of that consent (regardless of how many refreshes) will be valid beyond that time.

**Comment by tsoestini** [comment]
Alternatively, maybe when you refresh a refresh token the new refresh token should have the same expiration as the first one?

**Comment by aeneasr** [comment]
Thank you for the report! I haven’t looked at the code in a while.

> Meanwhile, the route to list remembered consent sessions will only return clients from the past 60 days, with no indication of other clients that might still have access to their resources.

I thought we list all consent sessions? If not we should fix this :)

**Comment by tsoestini** [comment]
> I thought we list all consent sessions? If not we should fix this :)

We list ones that aren't tagged remember=true.

But if remember_for is set to 60 days, we stop listing them after 60 days.

I tried setting remember_for for only 1 hour, and it stopped appearing in the output after 1 hour. It does appear to still be in the database, though. Just doesn't get returned.

I wonder why it stays in the database, though? Since it's marked not to be remembered (for purposes of skipping consent) and since it's marked to only be remembered for 1 hour, what advantage does it have to remain around?

Does refreshing of refresh tokens even look at the consent at all?  If not, maybe it should?
If it already does, maybe that is the bug?
Maybe the consent session is not properly getting deleted after the remember_for time, which is allowing refresh tokens to be refreshed indefinitely?

**Comment by tsoestini** [comment]
In any event, what I'm trying to do is limit the amount of data that needs to be persisted by placing a sensible limit on how long unused consent sessions remain around.

Auth0 puts a 1-year maximum life on their refresh token chains: see Absolute Lifetime setting at https://auth0.com/docs/security/tokens/refresh-tokens/configure-refresh-token-expiration .

That certainly seems like one approach. For example, if we said that refresh tokens/access tokens are only valid as long as the consent remember_for period, then we could set that to 6 months, and after 6 months of the user giving their consent, the refresh/access tokens under that consent would automatically expire, and they'd have to give their consent again. Meanwhile, the expired consent and all the associated refresh/access tokens could be safely cleaned from the database.

If this is not the point of the "remember_for" period, maybe we should add an "valid_for" or "invalidate_after" period, which has the described effect?

Another approach (I was originally going for) would be to automatically invalidate it after the final refresh token in the chain expired. This would have the advantage of cleaning dead chains from the database earlier than 6 months, but I can see the argument you give for still keeping the consent session around in this case, to allow a new refresh token to be obtained via the consent flow with skip. However, allowing for a hard-limit after which consent MUST be re-given seems like a good way to limit downstream token use and provide a way to safely clean up the DB?

**Comment by tsoestini** [comment]
Additional discussion here: https://github.com/ory/hydra/discussions/2886#discussioncomment-2004792

I updated the op with my current preferred solution in light of all the discussion.

**Comment by aeneasr** [comment]
> (A) A global Absolute Lifetime setting, like auth0.

I think that is a very good idea! I believe this would be in line with https://github.com/ory/hydra/issues/2474 ?

**Comment by tsoestini** [comment]
I can't read all of the discussion in #2474 because the slack link has expired.

However, in section 8 of the IETF Draft that synclpz linked, I found:
>    Authorization servers MAY set different policies around refresh token
>    issuance, lifetime and expiration for browser-based apps compared to
>    other public clients.

Though (A) would make me happy, I think it would not allow setting different policies around refresh token issuance for browser-based apps compared to other public clients. I think (B) would allow for that, however.

I guess there is a further approach, (C) which would be to have an `absolute_lifetime` field that can be specified on clients, and would apply to all refresh tokens issued to that client.

However, above quote is just a MAY, not a MUST, so it's not strictly necessary to follow. I'm also not entirely sure if there's a way for the hydra server or the consent provider or the client registrar to differentiate between browser-based apps compared to other public clients, to properly set the `absolute_lifetime` field differently depending on that?

So, perhaps (A) is sufficient. Or, maybe, a global setting that varies per `token-endpoint-auth-method`. e.g., for `token-endpoint-auth-method` of `client-secret-basic` there could be one setting and a shorter one for `token-endpoint-auth-method` of `none`?

**Comment by aeneasr** [comment]
I think it would be useful to support global TTL on refresh chains as well as inactivity on refresh chains. Whether or not those can also be configured per client would be a different question IMO (see also: https://github.com/ory/hydra/issues/1529)
