### ISSUE TITLE
Performance issue in /oauth2/auth/sessions/consent Admin API

### ISSUE THREAD

**Issue by seremenko-wish** [ory/hydra#2898]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Performance of Admin API endpoint /oauth2/auth/sessions/consent gets worse with an increased number of objects you want it to return.

The root cause is running SQL queries in a loop (one SQL query to get one session object) in `Persister.resolveHandledConsentRequests` method here https://github.com/ory/hydra/blob/6ea0bf8f4dc990667c6911c92a1ad644733745be/persistence/sql/persister_consent.go#L337

This method can be written in a way that sends only one SQL query to get all sessions and process them much faster. Having this SQL query in a loop and the absence of read-only replica support, make it impossible to deploy Hydra in a distributed infrastructure.

### Reproducing the bug

With an increase in the number of open sessions, the latency on this endpoint will grow linearly.

### Version

all versions, master

**Comment by aeneasr** [comment]
Nice find! :) Did you check out wether https://github.com/ory/hydra/pull/2836 might resolve this already?

**Comment by grantzvolsky** [comment]
Indeed, #2836 should fix this; the function `resolveHandledConsentRequests` is simplified and renamed to `filterExpiredConsentRequests` because it doesn't resolve anything anymore.

**Comment by aeneasr** [comment]
Ok, closing this then. @seremenko-wish if you find that #2836 doesn't resolve this please feel free to comment here, reopen, or craete a new issue!
