### ISSUE TITLE
Consider recreating Hydra V2 database model instead of migrations

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#2902]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Right now, the database model evolved since 2015 and has gone through several iterations. We have already spent quite a lot of effort to migrate the DB model to the next version yet again. However, we now have several versions where some database were not supported and it makes the migration tests quite messy to use and test.

### Describe your ideal solution

@grantzvolsky has already proposed to make a clear cut in the database model and maybe not apply all the old migrations yet again for version 2.0.

I think this is a good idea. Maybe we should just redesign the database schema using fizz (or sql boiler?) from the ground up, meaning that we avoid all the primary key issues we had in the past.

One issue here of course is doing online migrations towards Hydra 2.0. However, we can also mark this as a non-requirement for the migration towards Hydra 2.0 and for large scale clients figure out a way to still have them online (maybe using some type of streaming pattern?).

### Workarounds or alternatives

Go on as we do right now and keep adding technical debt to the SQL schema.

### Version

master

**Comment by aeneasr** [comment]
Maybe for clarification. I don't mean that we should completely change the design. But what we could consider is to have a bunch of `CREATE TABLE` commands  instead of many, many `ALTER` and `SELECT * FROM ... INSERT` commands. Or, if we do have those, have them for old versions of Hydra and start the v2 branch off of new `CREATE TABLE` commands. The existing migrations which are very useful could still be used to get an old system onto the new system!

**Comment by grantzvolsky** [comment]
Specifically we could do the following:
1. Include v{any version before 2.0} -> v2.0 migrations in the 2.0 release
2. Replace all pre-2.0 migrations with v2.0 create statements (be it raw sql, fizz, or something else) in subsequent releases
