### ISSUE TITLE
Docker CVE scanner uses the wrong images

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#2903]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The trivy / docker scanner uses the incorrect Docker Images. It uses `make docker` which uses a local docker build image (usually used for testing) that is not actually distributed on Docker Hub.

### Reproducing the bug

We should use the image that is distributed on Docker Hub. This is typically `.docker/Docker` or `.docker/Docker-alpine`. You can find the Docker image which is distributed in the goreleaser configuration.

### Version

master

**Comment by kmherrmann** [comment]
is this still relevant?
