### ISSUE TITLE
Make Docker fails

### ISSUE THREAD

**Issue by aravindc26** [ory/hydra#2906]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Make Docker fails at go mod download step

### Reproducing the bug

when I run `make docker`,

I get the following error message:

```
docker build -f .docker/Dockerfile-build -t oryd/hydra:latest-sqlite .
Sending build context to Docker daemon  112.6MB
Step 1/21 : FROM golang:1.17-alpine3.15 AS builder
1.17-alpine3.15: Pulling from library/golang
Digest: sha256:4918412049183afe42f1ecaf8f5c2a88917c2eab153ce5ecf4bf2d55c1507b74
Status: Downloaded newer image for golang:1.17-alpine3.15
 ---> d8bf44a3f6b4
Step 2/21 : RUN apk -U --no-cache add build-base git gcc bash
 ---> Using cache
 ---> a5fc8be1d259
Step 3/21 : WORKDIR /go/src/github.com/ory/hydra
 ---> Using cache
 ---> 10a45fdd85ab
Step 4/21 : ADD go.mod go.mod
 ---> Using cache
 ---> 349993bd35ac
Step 5/21 : ADD go.sum go.sum
 ---> Using cache
 ---> 1d7a82bb53b6
Step 6/21 : ENV GO111MODULE on
 ---> Using cache
 ---> e4977ac4542a
Step 7/21 : ENV CGO_ENABLED 1
 ---> Using cache
 ---> 4f6d1d08594d
Step 8/21 : RUN go mod download
 ---> Running in 06b0ce0abd27
Error processing tar file(exit status 1): write /go/pkg/mod/github.com/aws/aws-sdk-go-v2@v1.9.2/codegen/sdk-codegen/aws-models/worklink.2018-09-25.json: read-only file system
make: *** [docker] Error 1
```

### Version

not applicable

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Docker

### Additional Context

docker version 4.2.0 (70708)

**Comment by aeneasr** [comment]
This appears to be an issue with your Docker environment and not related to Ory Hydra!

**Comment by aravindc26** [comment]
This is working with older version (3.6) of docker but not with 4.2
