### ISSUE TITLE
Empty login_session_id being returned by listSubjectConsentSessionsCall API call

### ISSUE THREAD

**Issue by geetparekh** [ory/hydra#2996]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

A user can have multiple sessions from different devices/browsers. When we get a logout request, we would like to fetch all the running sessions of the subject (using the listSubjectConsentSessionsCall API), then match the current session id(which we got from LogoutRequest.getSid) in the array returned by listSubjectConsentSessionsCall and then take some subsequent actions based on the oidc_context for that particular session. 

Currently when we invoke the listSubjectConsentSessionsCall API, we do get a response with an array of size 2, but from those two array objects, we are not able to identify the current session because login_session_id is empty in both the array objects.

### Reproducing the bug

Invoke listSubjectConsentSessionsCall  for a subject who has a running session. We see that the login_session_id value in the response is empty.

### Version

1.11

**Comment by aeneasr** [comment]
Thank you for the report, would it be possible to show the example payload that has this issue? Also helpful would be a reproducible example (or a screen cast if possible) to highlight the issue so we better understand the context.

Unfortunately, `login_session_id` is not always possible to be recovered so it might very well be that this is a limitation, but we have to see.
