### ISSUE TITLE
Unhandled `token_inactive` error

### ISSUE THREAD

**Issue by sawadashota** [ory/hydra#3004]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hydra returns 500 error with `token_inactive` debug log when RP requests refresh multiple requests using same refresh token at same same time.

Normally, `token_inactive` error is handled here and hydra returns 401.
https://github.com/ory/hydra/blob/5895d03a37ae8b1fd34db9dafdfbcfef449b4b3c/oauth2/handler.go#L582

But if multiple requests come and pass it, `token_inactive` occurs here and fosite does not handle it.
https://github.com/ory/hydra/blob/5895d03a37ae8b1fd34db9dafdfbcfef449b4b3c/oauth2/handler.go#L637
https://github.com/ory/fosite/blob/dcc6550b807980faca740b261790b3be339632c7/handler/oauth2/flow_refresh.go#L146-L148

### Reproducing the bug

I'm sorry but I don't know how to reproduce it.

### Relevant log output

```shell
{
  "audience": "application",
  "error": {
    "debug": "token_inactive",
    "message": "server_error",
    "reason": "",
    "status": "Internal Server Error",
    "status_code": 500
  },
  "http_request": {
    "method": "POST",
    "path": "/oauth2/token",
  },
  "level": "error",
  "msg": "An error occurred",
  "service_name": "Ory Hydra",
  "service_version": "v1.11.0",
  "time": "2022-02-22T06:18:18Z"
}
```

### Version

v1.11.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
This is merged on master!

**Comment by sawadashota** [comment]
This is merged on ory/fosite@master but this has not resolved at hydra yet.
Could you please release new ory/fosite version?

**Comment by aeneasr** [comment]
done

**Comment by sawadashota** [comment]
Thank you!
