### ISSUE TITLE
token_endpoint_auth_signing_alg is not support in the CLI

### ISSUE THREAD

**Issue by mitar** [ory/hydra#3025]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

REST API supports `token_endpoint_auth_signing_alg`, but it is not exposed through the CLI, it seems.

### Reproducing the bug

I ran `clients create --help` and it is not documented.

### Version

v1.10.6

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
This is a good first issue, if anyone wants to tackle it!

**Comment by aeneasr** [comment]
Resolved on master
