### ISSUE TITLE
License incompatibility

### ISSUE THREAD

**Issue by mitar** [ory/hydra#3028]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It looks like Hydra depends on https://github.com/timtadh/data-structures, which is GPL licensed. But Hydra claims that itself is Apache licensed.

### Reproducing the bug

See licenses of https://github.com/timtadh/data-structures and Hydra.

### Version

current master

### Additional Context

Maybe you should have some license compliance check in your CI?

**Comment by aeneasr** [comment]
Thank you for the report, can you identify which library we use is depending on it? I don’t think we use this library directly. If its only used in tests we might not be in violation as the code is not bundled :)

**Comment by mitar** [comment]
It is used by `github.com/mikefarah/yq/v4` which is used in `go_mod_indirect_pins.go`. But I do not know why it is there.

**Comment by aeneasr** [comment]
Thank you for finding that! We use yq as a dependency in the makefile to prepare config files in the e2e tests, so this code **is not** shipped as part of the binary. We can safely ignore this :)

**Comment by mitar** [comment]
Awesome!
