### ISSUE TITLE
"Lists All Consent Sessions of a Subject" is missing query parameters

### ISSUE THREAD

**Issue by tbalasavage** [ory/hydra#3033]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The documentation [here](https://www.ory.sh/docs/hydra/reference/api#operation/listSubjectConsentSessions) states that the response for listing consent sessions is paginated but the pagination query parameters `offset` and `limit` are not listed as valid parameters on the request. They are included in the operation for [listing OAuth 2.0 clients](https://www.ory.sh/docs/hydra/reference/api#operation/listOAuth2Clients), which is also paginated. Consequently, I think that when the SDKs are generated, these are not included in the admin operations so I'm unable to easily set these values using the SDK. For example, when listing OAuth 2.0 clients, I can do the following:
```go
		WithLimit(&limit).
		WithOffset(&offset),
```
These options aren't available when listing consent sessions.

### Reproducing the bug

1. Attempt to add `WithOffset` and `WithLimit` methods to a `ListSubjectConsentSessions` method as shown below using the Go SDK:
```go
ListSubjectConsentSessions(admin.NewListSubjectConsentSessionsParams().
		WithContext(ctx).
		WithSubject(subject)
```

### Version

github.com/ory/hydra-client-go v1.10.6

**Comment by aeneasr** [comment]
Thank you for the report! PR to fix this is linked
