### ISSUE TITLE
Wildcard for redirect_uris

### ISSUE THREAD

**Issue by maurolucc** [ory/hydra#3037]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

It's a pain if you have a client that usually creates a new site and it has to be added to redirect_uri whitelist.

### Describe your ideal solution

It could be nice to have the possibility of using wildcards within redirect_uri fields. In that sense, the client could decide that any page coming from its domain should be allowed to consume. 

For instance, with this whitelist:

```
...
   "redirect_uris": ["http://localhost:8080, "https://example.alternative.com", "*.mydomain.com"]
...
````

the following sites should be whitelisted to use OIDC:

- http://localhost:8080
- https://example.alternative.com
- https://pageA.mydomain.com
- https://pageB.mydomain.com
- https://pageZ.mydomain.com

but not

- https://badexample.alternative.com

### Workarounds or alternatives

Using Regex

### Version

1.10.7

**Comment by aeneasr** [comment]
Implementing this is against the OAuth2 specification and would fail security audits, thus it's unfortunately not possible to implement this even if the idea is useful IMO.
