### ISSUE TITLE
API generation bug regarding Accept Consent request session model

### ISSUE THREAD

**Issue by matejkramny** [ory/hydra#3058]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The API generates an incorrect definition for the Accept Consent request session data model in the Go api client (ref https://github.com/ory/hydra-client-go/issues/10)

Model in question:
https://github.com/ory/hydra-client-go/blob/master/model_consent_request_session.go#L23

It's type `"idToken": map[string]map[string]interface{}` when the API docs suggest it is `"idToken": map[string]interface{}`

The JS (node) api also sends an object of key: string, value: any. The dart api also has a similar mapping, but of String: JSONObject.

The model requires us to define the following body, which is not correct
```
idToken: {
  email: { email: "hello@email.com" },
  name: { name: "foo bar" },
}
```

### Reproducing the bug

1. Create a login session/ consent
2. OpenAPI consumer crashes (not expecting nested maps)

### Relevant log output

```shell
n/a
```

### Relevant configuration

```yml
n/a
```

### Version

1.11.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

### Additional Context

The openapi generator seems to incorrectly assume the value of the map and gives them a map instead

**Comment by zepatrik** [comment]
Hm looks like a problem with the generator, the spec looks fine. Also if other languages are working properly, this suggests it's a bug in the generator.

**Comment by matejkramny** [comment]
I've done some digging into how it's generated, it appears to have been a problem before

**Comment by aeneasr** [comment]
We had this problem in Kratos, a good solution is to remove the `type` attribute which de-bugs the spec. You can find such an example here: https://github.com/ory/kratos/blob/e50551330d976845c696bf68b6d9b61221da59d3/.schema/openapi/patches/schema.yaml#L2

To apply the patch, add it like so:

https://github.com/ory/kratos/blob/e50551330d976845c696bf68b6d9b61221da59d3/Makefile#L93

**Comment by matejkramny** [comment]
Thanks @aeneasr I'll create a patch and submit a PR

**Comment by matejkramny** [comment]
Apologies but I'd lik to reopen as the PR does not correct the definition:

https://github.com/ory/hydra-client-go/blob/master/model_consent_request_session.go#L23

**Comment by kotyara85** [comment]
This PR didn't seem to fixed the the client repo?
Looking for a fix too
Thanks

**Comment by aeneasr** [comment]
It's not yet released
