### ISSUE TITLE
Wrong content-type for 404 response

### ISSUE THREAD

**Issue by woylie** [ory/hydra#3064]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Requesting an unknown path returns a JSON error with the content-type `text/plain`.

The response body will be:

```
{\"error\": \"Error 404 - The requested route does not exist. Make sure you are using the right path, domain, and port.\"}
```

But the `content-type` header will be: `text/plain; charset=utf-8`. It should be `application/json`.

### Reproducing the bug

Make a GET request to `https://hydra:4445/does/not/exist`.

### Version

v1.11.7

**Comment by aeneasr** [comment]
Thank you for the report, nice find! It's awesome that you are looking into all of these things with such great care. Thank you!
