### ISSUE TITLE
Consider lestrrat-go/jwx as a jose alternative

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#3117]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Consider lestrrat-go/jwx as a jose alternative

https://github.com/lestrrat-go/jwx

### Describe your ideal solution

Evaluate https://github.com/lestrrat-go/jwx and potentially refactor

### Workarounds or alternatives

Keep the current go-jose dependency

### Version

master

**Comment by anderspitman** [comment]
@aeneasr curious if you ever did any more analysis of this? I'm using https://github.com/lestrrat-go/jwx for https://github.com/anderspitman/obligator but most projects seem to be using go-jose
