### ISSUE TITLE
Ory Hydra goes v2.x - FEATURE AND PR FREEZE FOR 1.X BRANCH

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#3126]
As we are working towards Ory Hydra v2.x we are introducing a feature freeze for the v1.x release branch. We will still accept security patches to v1.x but no changes to features or APIs. Please make ALL PRs against the https://github.com/ory/hydra/tree/v2.x branch!

**Comment by monwolf** [comment]
@aeneasr, Do you know when v2 will be available?
