### ISSUE TITLE
A 500 error on a back-channel endpoint can cause a fatal 502 for the proxy in front of Hydra after many retries

### ISSUE THREAD

**Issue by mig5** [ory/hydra#3135]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

If a back-channel logout endpoint on an RP throws a 500 internal server error, Hydra seems to retry the request 4 times (for a total of 5 attempts, at least).

After the 5th attempt, Hydra throws a 502 gateway error (at least, in my case - perhaps due to client timeout in the reverse proxy sitting in front of Hydra, after so many retries..).

This is poor UX from the user's perspective - a single RP with a problematic backchannel endpoint shouldn't completely disrupt the flow. And maybe it might risk other back-channels from failing to logout, though I understand that's asynchronous, so maybe not always a problem.

I have not attempted without a reverse proxy (Nginx) in front of Hydra, but what is meant to happen? Does Hydra just endlessly keep trying that endpoint? Or does it eventually throw its own kind of error page, or perhaps just give up and return to the post_logout_redirect_uri , and it's just not happening fast enough for my Nginx wait period? Is there a parameter/environment variable with which to control how many retries are allowed before giving up?

### Reproducing the bug

1. Make and register a back-channel endpoint in an RP that throws a 500 internal server error.

2. Attempt logout flow

3. Observe the retries and potentially a fatal disruption in the logout flow (at least if a reverse proxy in front of Hydra times out waiting for Hydra to respond)

### Version

v1.11.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by aeneasr** [comment]
I believe we changed this to async (background) processing in Ory Hydra 2.0

**Comment by mig5** [comment]
In fact, the async work made it in to the 1.11.8 release - even better! I was still on 1.11.7. Indeed it no longer 'blocks' if the back-channel is throwing fatal errors. My apologies.
