### ISSUE TITLE
Feature Request for v2: RS512 Generator

### ISSUE THREAD

**Issue by garywarner** [ory/hydra#3138]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The ORY Hydra API endpoint [POST /key/{set}](https://www.ory.sh/docs/hydra/reference/api#operation/createJsonWebKeySet)  provides a convenient and appropriate way of handling JWKS for use by third parties.

The current available Generators are "RS256", "ES256", "ES512", "HS512", and "HS256".

One of the third parties using our /.well-known/jwks.json endpoint is NHS Digital who have hardened their requirements to use RS512 keys in their latest API specifications. They state "It must be a 512-byte RSA version 2 key pair."

### Describe your ideal solution

Make available an RS512 Generator to the [POST /key/{set}](https://www.ory.sh/docs/hydra/reference/api#operation/createJsonWebKeySet) endpoint

### Workarounds or alternatives

We have tried RS256, but it has been rejected.
We have tried ES256 and ES512, but it has been rejected.
The specification states explicitly that RS512 is the only acceptable key (but we had to try!).

We have a workaround by using the [PUT /key/{set}](https://www.ory.sh/docs/hydra/reference/api#operation/updateJsonWebKeySet) with a hand-assembled JSON body but this is a much harder approach that does not lend itself to automated key rotation because:
- the current key and the new key both have to be in the body, rather than just adding a key with a post
- we need to have the private key on our machines, if only briefly, which we'd rather avoid
- assembling the JSON body requires skills that would not be needed if the POST endpoint provided the option of an RS512 generator

### Version

v1.11.8

### Additional Context

I realise that there is a feature freeze on v1, which I fully understand and probably means that this will not be implemented until v2 is released. We've always used the official releases for security and confidence, but with this we could fork the repo and add the Generator - if we do that and you would like use to raise as a PR for either v1 or v2, let us know.

Thanks for an awesome piece of kit - we love it.

**Comment by garywarner** [comment]
**Update:** It turned out the issue was not just the RS512, but the kid element as well. As hydra prepends either `public:` or `private:` to the kid, depending upon which key is being returned via either ./well-known/jwks.json for public external use or /keys/{set} for private internal use, this is being rejected when they attempt to get our public keys. By proxying through nginx and replacing `"kid":"public:` with `"kid":"` and `"alg":"RS256"` with `"alg:RS512"` in the response, we have been able to use the currently generated keys.

Although a bit of a kludge, this does mean that we can continue to use our official Hydra image and have the advantages of being able to automatically rotate keys and never have to see the private key.

As a perfect solution, a switch in the hydra.yaml webfinger that also allows for the "public:" to be omitted at /.well-known/jwks.json would be ideal... but realise that this is probably never going to be voted up. For the internal route, we just prepend "private:" and that works fine.

**Comment by aeneasr** [comment]
Thank you for the input - this is all resolved on v2.x :)
