### ISSUE TITLE
dsn for postgres not consistent

### ISSUE THREAD

**Issue by bweston92** [ory/hydra#3152]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Inconsistent `postgresql` scheme support in Ory applications for DSN.

### Reproducing the bug

Use `postgresql` for the scheme in the URI.

### Relevant log output

```shell
time=2022-06-14T09:44:15Z level=fatal msg=Unable to create service registry. audience=application error=map[message:dsn value requested an unknown driver] service_name=ORY Hydra service_version=v1.10.5
```
```


### Relevant configuration

_No response_

### Version

v1.10.5

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

Some providers like DigitalOcean when they give you a connection string they have it using the `postgresql` scheme.

This is fine, works even with Kratos as you can see here: https://github.com/ory/kratos/blob/037c0957cca2d6695b83b564efeaf17105d99b19/driver/registry_default.go#L509

But not in Hydra, this can lead to people wasting time investigating why it is working with Kratos but not Hydra.

**Comment by bweston92** [comment]
![Screenshot from 2022-06-14 11-01-03](https://user-images.githubusercontent.com/1764057/173552151-3c21e4ad-d35e-4e4f-879f-9cb4a9b773e6.png)

A screen shot example of DigitalOcean's connection string produced.

**Comment by aeneasr** [comment]
Please use `postgres://` as documented here: https://www.ory.sh/docs/ecosystem/deployment#postgresql

**Comment by bweston92** [comment]
I see that, I just think it is weird Kratos supports it which then means you have to go deep diving when it doesn't work with Hydra.

https://github.com/ory/kratos/blob/037c0957cca2d6695b83b564efeaf17105d99b19/driver/registry_default.go#L509

**Comment by aeneasr** [comment]
Oh, I see - that makes sense! I thought it was a deeper underlying issue in gobuffalo :) Thank you for the clarification. In that case, PRs accepted :)
