### ISSUE TITLE
CorrelationID/TransitID support in the logs

### ISSUE THREAD

**Issue by sgal** [ory/hydra#3179]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Our system is subject to annual audit and we have a requirement to have a correlation-id value in all system logs.
`CorrellationID` aka `TransitID` is essentially a value that is constant for any given request chain. Described in more detail [here](https://www.rapid7.com/blog/post/2016/12/23/the-value-of-correlation-ids/#:~:text=A%20Correlation%20ID%2C%20also%20known,well%20documented%20Enterprise%20Integration%20Pattern.)

Please let me know if this is already supported, cause I could not find anything in the docs.

### Describe your ideal solution

We would like to have a `correlation-id` or `transit-id` (prop name is not important) value in all logs produced by Hydra for each request.
The value should come from the inbound request in a header (which can be configurable).

So, one approach could be:
- Add new config entry `CorrelationIDRequestHeaderName: string` - defines in which request header Hydra should look for correlation-id value.
- Add correlation-id value in each log entry (could be done via middleware or similar approach)

### Workarounds or alternatives

No workarounds that we could think of.

### Version

1.x

**Comment by aeneasr** [comment]
We're happy to support standardized formats such as `X-Request-ID` (I think we do this already) but custom log entries for specific use cases are unfortunately out of scope!

**Comment by sgal** [comment]
@aeneasr Great, do you happen to have a documentation about it? As I mentioned, we are fine with a different name as long as it does the job.

**Comment by aeneasr** [comment]
Indeed
