### ISSUE TITLE
allow `default_grant_allowed_scope` for all grant types

### ISSUE THREAD

**Issue by oganexon** [ory/hydra#3194]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The `default_grant_allowed_scope` option has been added for the purpose of granting the default scope for the OAuth 2.0 Client without specifying a scope.

```yaml
oauth2:
  client_credentials:
    default_grant_allowed_scope: true
```

The doc clearly states :
```
"Defines how scopes are added if the request doesn't contains any scope"
```

However, it only works for `client_credentials` grant since it has been added to [migrate from MITREid](https://www.ory.sh/docs/hydra/guides/migrating-from-mitreid). The documentation does not specify this.

I'm using `authorization_code` and `refresh_token` grants, and it doesn't work, the scope is empty.

### Describe your ideal solution

The `default_grant_allowed_scope` option should be available for all grant types, not just `client_credentials`.

### Workarounds or alternatives

I tried to change my grant to `client_credentials` but this is far from ideal and this is not what I want to achieve.

### Version

v1.11.7

### Additional Context

I didn't know if it was a bug or a feature request, it's a bit of both.

**Comment by aeneasr** [comment]
Are you also in a MITREid environment?

**Comment by oganexon** [comment]
I don't use MITREid but I think the behavior could be extended to other use cases. I probably wouldn't be the only one to need it outside of MITREid users.

**Comment by aeneasr** [comment]
The problem is that it is not spec compliant, the scope should be requested explicitly by the application. This config option really is only for compatibility with MITREid. If you don't use MITREid, don't set this parameter :)

**Comment by oganexon** [comment]
Oh, I see, I thought upon seeing providers like github that it wasn't necessary to give the scope, but I didn't read the specification in enough detail. Thanks for your answer!
