### ISSUE TITLE
Ingore Specific Status Code when Using http-post

### ISSUE THREAD

**Issue by ThetaEdra** [ory/hydra#3202]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I want to recover the login to a site which uses a HTTP-Post form. On Invalid Login the Website returns a 401 Status Code. Because of this Hydra thinks falsely HTTP-Auth would be used. 

[ERROR] the target is using HTTP auth, not a web form, received HTTP error code 401. Use module "http-get" instead.

which is false. The Post Form just returns 401 on invalid credentials

### Describe your ideal solution

A flag like ignore-status 401 so that Hydra keeps trying with the given method

### Workarounds or alternatives

Using another tool

### Version

Hydra v9.3

**Comment by platoputhur** [comment]
Are you sure this is the right repo for this feature request?
