### ISSUE TITLE
RFC7523: Audience not checked against client audience

### ISSUE THREAD

**Issue by trondhauge85** [ory/hydra#3255]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

JWT audience claim is naively granted on the access token without checking the list of allowed audiences on the client.

### Reproducing the bug

1. Run Hydra with any configuration
2. Create a jwt trust grant:
`{
    "issuer": "XXXXXXX",
    "scope": [
        "openid",
        "offline_access",
    ],
  "jwk": {
    "kty": "RSA",
    "e": "AQAB",
    "kid": "XXXXX",
    "n":"XXXXXX"
    },
  "expires_at": "2023-09-01T18:25:43.511Z",
  "allow_any_subject": true
}`
3. Create a client:
`{
    "client_secret": "XXXXXX",
    "client_name": "Test client",
    "audience": [
        "https://example.com/test"
    ],
    "scope": "openid offline_access",
    "grant_types": ["urn:ietf:params:oauth:grant-type:jwt-bearer"],
    "token_endpoint_auth_method": "client_secret_post",
    "response_types": ["token"]
}`
4. Create a jwt with the following payload:
`
  "aud": [
    "http://127.0.0.1:4444/oauth2/token",
    "https://test.com"
  ],
  "exp": 1663189711,
  "iat": 1663186051,
  "iss": "XXXXXXX",
  "jti": "f12e66c1-9be7-47f1-9133-d0556959d285",
  "sub": "sdfds"
}`
5. Login with token
`
grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer;
scope: offline_access;
assertions: {JWT};
client-secrey: XXXXX;
client-id: XXXXXX
`
6. Introspect access token
`{
    "active": true,
    "scope": "offline_access",
    "client_id": "XXXXX",
    "sub": "XXXXX",
    "exp": 1663232003,
    "iat": 1663228403,
    "nbf": 1663228403,
    "aud": [
        "http://127.0.0.1:4444/oauth2/token",
        "https://test.com"
    ],
    "iss": "http://127.0.0.1:4444",
    "token_type": "Bearer",
    "token_use": "access_token"
}`
7. Expected: Aud should not contain https://test.com as it is not in the client aud list.

### Version

1.11.8

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by sidharthramesh** [comment]
@aeneasr I think this is a significant security vulnerability.

Clients can call `/oauth2/auth` using ANY `aud`, even ones not present in the `client.audience` list.

For example I have a client with `"audience": ["https://google.com"]`, making a authorization request with `oauth2/auth?aud=https://inferno.healthit.gov/invalid_aud` goes though to the consent page, and ends up on the redirect URL with a valid code!!


Exact client:
```
{
	"client_id": "8bae17c8-d722-4909-b327-625d3115ab74",
	"client_name": "Example",
	"redirect_uris": [
		"https://inferno.healthit.gov/suites/custom/smart/redirect"
	],
	"grant_types": [
		"authorization_code",
		"refresh_token"
	],
	"response_types": [
		"code",
		"id_token"
	],
	"scope": "openid",
	"audience": [
		"https://google.com"
	],
	"owner": "",
	"policy_uri": "",
	"allowed_cors_origins": [],
	"tos_uri": "",
	"client_uri": "",
	"logo_uri": "",
	"contacts": [],
	"client_secret_expires_at": 0,
	"subject_type": "public",
	"jwks": {},
	"token_endpoint_auth_method": "client_secret_basic",
	"userinfo_signed_response_alg": "none",
	"created_at": "2022-09-02T14:32:36Z",
	"updated_at": "2022-10-05T19:14:17.053341Z",
	"metadata": {}
}
```

Authorization request that works but should not:
```
/hydra/oauth2/auth?aud=https%3A%2F%2Finferno.healthit.gov%2Finvalid_aud&client_id=8bae17c8-d722-4909-b327-625d3115ab74&code_challenge=spoRnh1UOlgiZimReVI4doHB5EXrFIHz9XClhU6tMbk&code_challenge_method=S256&consent_verifier=68b116a79b3c4bfc99ffe97805073b6f&redirect_uri=https%3A%2F%2Finferno.healthit.gov%2Fsuites%2Fcustom%2Fsmart%2Fredirect&response_type=code&scope=openid&state=5eaeba4d-4f24-4ee5-9b3e-17c77349c834
```

**Comment by aeneasr** [comment]
If it was a security vulnerability, I would kindly ask you to please follow our [security policy](https://github.com/ory/hydra/security/policy) and do not disclose vulnerabilities publicly. Thankfully, what the OP wrote is not related to your finding.

And I don't think that you have found a security flaw, as this part of the system is well tested. Keep in mind that not having the audience just omits it from the tokens, it doesn't actually abort the flow. Please read more about this topic in our docs: https://www.ory.sh/docs/hydra/advanced#oauth-20-authorization-code-implicit-and-hybrid-flows

Regarding the finding @trondhauge85 made - you need to set the scope in your trust relationship. The client is just there so that we have an actor, and has in essence not a lot to do with the actualy trust relationship and token exchange. So this is working as intended!
