### ISSUE TITLE
In tokens granted through client_credentials, sub should be set to owner

### ISSUE THREAD

**Issue by fehrnah** [ory/hydra#3270]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I am exploring using the client_credentials grant as a way for my users to gain access to a ressource without going through a browser (ex: CLI app).
In order to do so, I am creating one OAuth2 client per user. And setting the client owner to the user's kratos user_id.

### Describe your ideal solution

When introspecting tokens issued through the client_credentials grant, I want to see the owner as subject.
If subject is not set, we can still use the client_id.

### Workarounds or alternatives

Things could remain the same and I would manually add the user_id in a claim of the token.

### Version

v1.11.8

### Additional Context

This change looks would be compatible with OAuth2 introspection [RFC7662](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2)

> sub
>       OPTIONAL.  Subject of the token, as defined in JWT [[RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)].
>       Usually a machine-readable identifier of the resource owner who
>       authorized this token.
>

**Comment by aeneasr** [comment]
Setting the subject to the owner for the client credentials grant has immense security implications. Unfortunately, we won’t introduce such a feature.

**Comment by fehrnah** [comment]
Would any design be possible to make this usecase possible ? I understand that for clients created via the public API this would be *bad*, but for client created by the admin API it wouldn't be a security risk, would it ?
