### ISSUE TITLE
Percona-XtraDB-Cluster failed, because of SERIALIZABLE transaction setting

### ISSUE THREAD

**Issue by architeacher** [ory/hydra#3278]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Failure to run migration on Percona Server.

### Reproducing the bug

Steps to reproduce:

* Prepare Percona cluster and make sure that `pxc_strict_mode` is set to `ENFORCING`
* Checkout v 1.8.5
* Run migration
* Checkout v1.11.10
* Run migration
* You should see this error
```
Error 1105: Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
```

### Version

1.11.10

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

**Comment by aeneasr** [comment]
We don't support Percona Server, only vanilla MySQL, and do not intend to support it in our code base, sorry! Please raise the error with them. It looks like some configuration problem in Precona.
