### ISSUE TITLE
Support POST /oauth2/auth

### ISSUE THREAD

**Issue by sidharthramesh** [ory/hydra#3280]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

According to https://www.rfc-editor.org/rfc/rfc6749#section-3.1
```
The authorization server MUST support the use of the HTTP "GET"
method [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] for the authorization endpoint and MAY support the
use of the "POST" method as well.
```

Some clients use POST for the authorization flow since there is no limit to the length of the scopes.
Having a POST endpoint for /oauth2/auth would be a great addition to Hydra.

### Describe your ideal solution

Support POST on /oauth2/auth if the content type is `application/www-form-encoded` and use the form data to continue the authorization flow.

### Workarounds or alternatives

Setting up a proxy infront of Hydra that redirects POST requests to the GET version of Hydra. However this still has the problem that the length of scopes is limited.

### Version

1.11.0

**Comment by kumanoko24** [comment]
@sidharthramesh I am also using hydra 1.11.0 recently, what is the behavior of hydra server when the OIDC client does a POST request to `/oauth2/auth` ?
