### ISSUE TITLE
Docker image (sha256-fdda93bdc) has error

### ISSUE THREAD

**Issue by kuwaharg** [ory/hydra#3299]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The following image in docker hub seems like it is bad and is causing issues with our image registry scanner. Could it be fixed or removed?

https://hub.docker.com/layers/oryd/hydra/sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig/images/sha256-7cadef3f4d1d8514fa6c935685b82d48b3fc41c3903dc4a5e6d1dc46111542d0?context=explore

```sh
% docker pull oryd/hydra:sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig
sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig: Pulling from oryd/hydra
b1bd4b1b1bd4: Extracting [==================================================>]     242B/242B
failed to register layer: Error processing tar file(exit status 1): unexpected EOF
```

### Reproducing the bug

1. Run the following command: docker pull oryd/hydra:sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig

### Relevant log output

```shell
% docker pull oryd/hydra:sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig
sha256-fdda93bdc9db445ab2f5b4d46025cbd17a42be2c06825d81269fe96d378d0ea9.sig: Pulling from oryd/hydra
b1bd4b1b1bd4: Extracting [==================================================>]     242B/242B
failed to register layer: Error processing tar file(exit status 1): unexpected EOF
```

### Version

N/A

**Comment by aeneasr** [comment]
This works fine now for me
