### ISSUE TITLE
warden: allow scopes in policies

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#330]
Could probably work really well with context

**Comment by kop** [comment]
+1 to this. Personally, I don't really understand how to use scopes together with Ladon/Warden and how they should work together.

@arekkas, maybe you could write a blog post showing how to build a simple API application using Hydra for both Authentication and Authorization?

**Comment by arekkas** [comment]
@kop absolutely, I wanted to do that for a long time but didn't manage yet. The idea would be:

1. Boot database + hydra with docker
2. Connect to it
3. Create a oauth2 client for the consent flow
4. Set up the right policies
5. Create another oauth2 client for token validation
6. Guard an API with it
7. Create another oauth2 client to perform the auth code flow

What do you think?

**Comment by kop** [comment]
@arekkas, sounds great! I would definitely love to see such post.

**Comment by arekkas** [comment]
We could probably start outlining it here, and it would be great to get some help with it :)

**Comment by arekkas** [comment]
https://github.com/ory/hydra/issues/385#issuecomment-284698726

**Comment by arekkas** [comment]
this doesn't make a lot of sense, the warden should be separate from oauth2 scopes
