### ISSUE TITLE
Some JWK types are missing the algorithm field

### ISSUE THREAD

**Issue by pschultz** [ory/hydra#3317]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

JSON Web Keys of type ECDSA and Ed25519 are missing the "alg" field:

```
{
  "keys": [
    {
      "use": "sig",
      "kty": "EC",
      "kid": "private:7bf98153-e1af-404d-89f0-c89f2a60091b",
      "crv": "P-256",
      "x": "MS7y-F6RJ3EqyHkl-JdoJaJ01351Vwi4g_I4vBzELbg",
      "y": "rEZyfAtNNsF-lCinbQNJ21QWJOa1b2pDRr0Qs5u3UwA",
      "d": "<redacted>"
    },
    {
      "use": "sig",
      "kty": "EC",
      "kid": "public:7bf98153-e1af-404d-89f0-c89f2a60091b",
      "crv": "P-256",
      "x": "MS7y-F6RJ3EqyHkl-JdoJaJ01351Vwi4g_I4vBzELbg",
      "y": "rEZyfAtNNsF-lCinbQNJ21QWJOa1b2pDRr0Qs5u3UwA"
    }
  ]
}
```

### Reproducing the bug

Simply generate a new key set using ES256 or ES512:

```sh
id=$(uuidgen)
curl -v http://localhost:1234/keys/$id -d '{"alg":"ES256","use":"sig","kid":"'$id'"}'
```

### Relevant configuration

```yml
server:
  admin:
    port: 1234
```

### Version

1.11.10

### On which operating system are you observing this issue?

Linux

### Additional Context

This is very easy to fix. The fields are simply not assigned in /ory/hydra/blob/v1.11.10/jwk/{generator_ecdsa256.go,generator_ecdsa512.go,generator_eddsa.go} (compare with generator_rs256.go).

I would have submitted a PR, but I couldn't work out which branch to base my work on for 1.x.

**Comment by aeneasr** [comment]
This should be resolved on master, the version will come out shortly.

**Comment by aeneasr** [comment]
It's out!
