### ISSUE TITLE
Issue while applying migrations

### ISSUE THREAD

**Issue by Amanb1145** [ory/hydra#3326]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am trying to setup Ory hydra on production on Azure VM using Ubuntu 20.04 but got some issues while following the documentation-
The url which is provided in documentation is not working anymore- 
`wget https://github.com/ory/hydra/releases/download/v2.0.1/hydra_v2.0.1-linux_64bit.tar.gz
`
so I used this one -

`wget https://github.com/ory/hydra/releases/download/v2.0.1/hydra_2.0.1-linux_64bit.tar.gz` 

after doing this I downloaded config file using this url- 

`wget https://raw.githubusercontent.com/ory/hydra/v2.0.1/contrib/quickstart/5-min/hydra.yml
`
and then added the following lines in hydra.yml file-

`dsn: postgres://hydra:b0qw68gr3Q@127.0.0.1:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
urls:
  self:
    issuer: https://oauth2.example.com`

then I tried to apply the migration.
`

### Reproducing the bug

command for migration is- 

`/opt/hydra/bin/hydra -c /opt/hydra/config/hydra.yml migrate sql -y postgres://hydra:b0qw68gr3Q@127.0.0.1:5432/hydra?sslmode=disable`

but getting the following error-

`INFO[2022-10-28T11:35:54Z] Retrying in 3.200000 seconds...               audience=application error=map[message:failed to connect to `host=127.0.0.1 user=hydra database=hydra`: failed SASL auth (FATAL: password authentication failed for user "hydra" (SQLSTATE 28P01))] service_name=Ory Hydra service_version=v2.0.1

### Version

2.0.1

### On which operating system are you observing this issue?

Linux

**Comment by aeneasr** [comment]
Hi, thank you for the issue. I see that you create a discussion as well. Please use only discussions to ask questions around configuration etc :)

The problem in your case is that the database password is apparently not correct.
