### ISSUE TITLE
redirect_uri cannot be relative

### ISSUE THREAD

**Issue by hesmar** [ory/hydra#3336]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I would like to use hydra on an embedded system which does not have a static IP or Hostname. Therefore I have to use a relative redirect-uri.

For example, I have a web app running on the same system under `/web`. For login, oauth2 should be used by calling the `https://<IP>/oauth2/auth` endpoint. Hydra should allow the relative URL `/web` and form a full redirection URL: `https://<IP>/web`.

### Reproducing the bug

1. Run Hydra Server
2. Register a new client with a relative redirect URI:
```
> hydra --endpoint http://localhost:4445 create client --redirect-uri "/web" --token-endpoint-auth-method none --name "web"
CLIENT ID       7c59b7a1-879f-41e7-8582-046dfec69699
CLIENT SECRET
GRANT TYPES     authorization_code
RESPONSE TYPES  code
SCOPE           offline_access offline openid
AUDIENCE
REDIRECT URIS   /web
```
3. Perform authorization code flow:
```
> hydra --endpoint http://localhost:4444 perform authorization-code --client-id 7c59b7a1-879f-41e7-8582-046dfec69699 --redirect "/web"
Setting up home route on http://127.0.0.1:4446/
Setting up callback listener on http://127.0.0.1:4446/callback
Press ctrl + c on Linux / Windows or cmd + c on OSX to end the process.
If your browser does not open automatically, navigate to:

        http://127.0.0.1:4446/
```
4. Open link and click on `Authorize application`.
5. In the following screen, it gives the following error message:
```The 'redirect_uri' parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.```

### Version

v2.0.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by DaveSmithh** [comment]
latest version have issues you can try with one or two older versions .

**Comment by aeneasr** [comment]
This is intentional and per spec as well as required for OpenID certification. Relative URLs are not allowed as redirect URLS. And no, v1 also does not support this!
