### ISSUE TITLE
Disabling TLS is broken in Hydra v2.0.1

### ISSUE THREAD

**Issue by yasha-spare** [ory/hydra#3339]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Disabling TLS for Hydra admin doesn't work on Ory Hydra v2.0.1.

### Reproducing the bug

Run Hydra with the config setting `serve.admin.tls.enabled: false` (but without the `--dev` flag), then make a call like:

```
curl -X POST 'http://localhost:4445/clients' \
  --verbose \
  --location \
  --header 'Content-Type: application/json' \
  --data '{ "client_name": "test", "grant_types": ["client_credentials"], "scope": "test-scope" }'
```

On Hydra v1, it just works.  On v2.0.1, it will:
- First return a 307 redirect to `https://localhost:4445/clients` (an HTTP -> HTTPS redirect for an admin endpoint, even though we disabled TLS for admin endpoints)
- Then, `curl` will receive an error like `curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`
  - Which I believe is basically a "why are you making an HTTPS request to an HTTP endpoint" error

It seems Hydra **_IS_** serving the admin endpoints on HTTP, but it's also redirecting HTTP to HTTPS (this is likely the bug), and then the HTTPS call fails because you're serving HTTP (that part is expected).  The end result is that the admin endpoints are un-callable.

Note that running Hydra with the `--dev` flag does still work (will allow http for Hydra admin), but that's not a great solution, as it degrades security.  A lot of Hydra users will expose admin only to an internal network where a lack of TLS is OK, so they want to disable TLS just for admin endpoints (which was supported up until this regression).

### Relevant log output

```
hydra-service-hydra-1  | time=2022-11-05T01:40:13Z level=info msg=started handling request http_request=map[headers:map[accept:*/* content-length:104 content-type:application/json user-agent:curl/7.64.1] host:localhost:4445 method:POST path:/clients query:<nil> remote:172.27.0.1:59702 scheme:http]
hydra-service-hydra-1  | time=2022-11-05T01:40:13Z level=info msg=completed handling request http_request=map[headers:map[accept:*/* content-length:104 content-type:application/json user-agent:curl/7.64.1] host:localhost:4445 method:POST path:/clients query:<nil> remote:172.27.0.1:59702 scheme:http] http_response=map[headers:map[cache-control:private, no-cache, no-store, must-revalidate location:https://localhost:4445/admin/clients] size:0 status:307 text_status:Temporary Redirect took:677.994µs]
```

### Relevant configuration

```yml
serve:
  admin:
    tls:
      enabled: false
```

### Version

v2.0.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

(but note - was also able to reproduce with with Docker running on my Mac)

**Comment by aeneasr** [comment]
Please read the changelog! `/clients` is now `/admin/clients`

**Comment by aeneasr** [comment]
Please see my reply here: https://github.com/ory/hydra/issues/3335#issuecomment-1304414945

**Comment by yasha-spare** [comment]
Ah you're right, my bad, thanks!

I guess there is a **_very_** minor bug, based on the release notes:

> Administrative endpoints now have an /admin prefix (e.g. POST /admin/keys instead of POST /keys). **_Existing administrative endpoints will redirect to this new prefixed path for backward compatibility._**

Backwards compatibility isn't preserved if you're using `serve.admin.tls.enabled: false` (it redirects you with HTTPS, which fails).  But that's super easily worked around by switching to the new endpoint :)

**Comment by aeneasr** [comment]
Ah yes true, the idea behind it is that without dev mode we expect hydra to run on HTTPS, even if hydra itself does not provide SSL certificates! We expect it to be behind some proxy that doe the SSL stuff :)
