### ISSUE TITLE
Avoid using public schema in Postgresql 15: (ERROR: permission denied for schema public)

### ISSUE THREAD

**Issue by wvh** [ory/hydra#3367]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello!

Postgresql 15 removed permissions to the `public` schema by default. See for instance [these release notes](https://www.postgresql.org/docs/15/ddl-schemas.html#DDL-SCHEMAS-PATTERNS).

Just creating a schema with the same name as the database user, e.g. `hydra`, will let the user automatically use their default schema because that appears in the `search_path` before the `public` schema. This requires no action from Hydra.

However, the problem is that some of the migrations have hardcoded references to the `public.*` schema, triggering permissions problems for the SQL of those migrations.

I think it would be fine to just remove the `public.` prefix from the few migrations that have it and it's probably a mistake that that schema prefix is included anyway. Assuming the default schema is `public` is going to become problematic as people are upgrading Postgresql to version 15 and beyond.

### Reproducing the bug

- install postgres 15
- run the Hydra quickstart
- some of the migrations will try to write to the `public` schema because they've hardcoded a fully qualified name in database references

### Relevant log output

```shell
idp-hydra-migrate-1  | ERROR: permission denied for schema public (SQLSTATE 42501)
```

### Version

v2.0.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by aeneasr** [comment]
Thank you for the report! Could you please point to the migrations which use the public schema? :)

**Comment by wvh** [comment]
Sure! I don't think I have the Postgres error logs themselves anymore, but here are the migration files that refer to a full schema identifier:

```
$ rg -l "\bpublic\." persistence/sql/
persistence/sql/migrations/20211019000001000004_merge_authentication_request_tables.cockroach.up.sql
persistence/sql/migrations/20221109000010000001_fix_foreign_key.cockroach.up.sql
persistence/sql/migrations/20221109000010000000_fix_foreign_key.postgres.up.sql
persistence/sql/migrations/20211019000001000002_merge_authentication_request_tables.cockroach.up.sql
persistence/sql/migrations/20211019000001000002_merge_authentication_request_tables.postgres.up.sql
persistence/sql/migrations/20211019000001000003_merge_authentication_request_tables.cockroach.up.sql
persistence/sql/src/20211019000001_merge_authentication_request_tables/20211019000001000000_merge_authentication_request_tables.postgres.up.sql
persistence/sql/src/20211019000001_merge_authentication_request_tables/20211019000001000000_merge_authentication_request_tables.cockroach.up.sql
```

These will return an error on Postgres 15 as the `public` schema is not writeable by default; and if the user creates another schema as suggested by Postgres – for instance with the same name as the user, because that gets picked up automatically – then those few migrations will be applied to `public` instead of the actual schema.

**Comment by aeneasr** [comment]
Thank you! Anyone looking at this, we welcome contributions :)
