### ISSUE TITLE
Unable to initialize Trace with datadog

### ISSUE THREAD

**Issue by morith** [ory/hydra#3372]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Can not use datadog as tracing provider.

### Reproducing the bug

Steps to reproduce the behavior

1. use datadog as tracing provider (`quickstart-tracing.yml`)
  ```yaml
  services:
    hydra:
      environment:
        - TRACING_PROVIDER=datadog
  ```
2. Run `docker compose -f quickstart.yml -f quickstart-tracing.yml`

### Relevant log output

```shell
time=2022-11-25T17:11:14Z level=error msg=Unable to initialize Tracer. audience=application error=map[message:expected one of [jaeger, zipkin, otel, ] but got datadog] service_name=Ory Hydra service_version=v2.0.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11bd0aa]

goroutine 1 [running]:
github.com/ory/x/otelx.(*Tracer).Tracer(...)
	/go/pkg/mod/github.com/ory/x@v0.0.514/otelx/otel.go:83
github.com/ory/hydra/driver.(*RegistryBase).Tracer(0xc000bcae00, {0xc000c3e9c0?, 0x2b?})
	/project/driver/registry_base.go:487 +0x16a
github.com/ory/hydra/driver.(*RegistrySQL).Init(0xc000c57080, {0x19f0d58, 0xc00004a020}, 0x0, 0x0, {0x19e94d0?, 0x24189e0?})
	/project/driver/registry_sql.go:102 +0xb1
github.com/ory/hydra/driver.NewRegistryFromDSN({0x19f0d58, 0xc00004a020}, 0xc000a76600?, 0xc000396258?, 0x1?, 0x0?, {0x19e94d0, 0x24189e0})
	/project/driver/registry.go:83 +0x86
github.com/ory/hydra/driver.New({0x19f0d58, 0xc00004a020}, 0xc000a764e0, {0xc000396250, 0x1, 0x0?})
	/project/driver/factory.go:101 +0x1d0
github.com/ory/hydra/cmd/server.RunServeAll.func1(0xc00001cf00, {0x160380d?, 0x3?, 0x4?})
	/project/cmd/server/handler.go:143 +0x28c
github.com/spf13/cobra.(*Command).execute(0xc00001cf00, {0xc000387040, 0x3, 0x4})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009d8300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/ory/hydra/cmd.Execute()
	/project/cmd/root.go:101 +0x3a
main.main()
	/project/main.go:14 +0x69
```

### Version

v2.0.2

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

* docker-compose
* Kubernetes

**Comment by aeneasr** [comment]
See https://github.com/ory/k8s/issues/538
