### ISSUE TITLE
Replace ory/instrumentedsql in favor of XSAM/otelsql

### ISSUE THREAD

**Issue by glerchundi** [ory/hydra#3396]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

As ORY Hydra 2.0 seems to be transitioning to use OpenTelemetry by default at least for tracing, I think it could sound like a good step forward to use something that is more aligned with the OpenTelemetry specs for database tracing (and even metrics).

Recently we were doing some performance testing on our systems and we felt like there was some lack of visibility and uniformity among our services. Specifically, we had a hard time identifying open DB connections in Hydra, which seemed to be the reason why we were seeing from time to time spikes in our latencies.

The proposal is to use [XSAM/otelsql](http://github.com/XSAM/otelsql) which is being actively maintained and although it's not officially part of the OpenTelemetry community, it's close to them: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5. After we evaluated some libraries out there we second the recommendation of one of the people on that thread: https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5#issuecomment-1200336095.

### Describe your ideal solution

Use [XSAM/otelsql](http://github.com/XSAM/otelsql) for DB tracing and metrics.

### Workarounds or alternatives

Continue to use [ory/instrumentedsql](https://github.com/ory/instrumentedsql).

### Version

2.0

**Comment by aeneasr** [comment]
I think it is a great initiative to improve the tracing around SQL connections. One problem though is that we use gobuffalo/pop as the underlying DBAL, and that project would need to transition to a different tracing set up :)

The file is here:

https://github.com/gobuffalo/pop/blob/42e5c2f2f9a1b97ee052676cead242dc1a6679aa/connection_instrumented.go

I did write the initial implementation for this, but it has been a while since then :)

**Comment by glerchundi** [comment]
Thanks for the prompt response @aeneasr! Great to see that you think it's a good idea 💪 

I initially supposed that it was a generic wrapping over `database/sql` driver instead of a specific implementation within the DB library. Let us take a closer look and we'll come back with more details about how would be the best (in our opinion) way to proceed.
