### ISSUE TITLE
Regression: unable to specify the ID for a new client in the CLI

### ISSUE THREAD

**Issue by MOZGIII** [ory/hydra#3398]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

After https://github.com/ory/hydra/commit/bb9c8ba4f7736b6e737528604445dbed05f1b997 the `--id` flag no longer exists.

We rely on it in our development flows (i.e. the CI creates a client with a predetermined ID) and it would be pretty difficult to switch to determining the ID dynamically. We'll create the client using curl for now.

### Reproducing the bug

```shell
$ hydra create client --id "myid"
...
unknown flag: --id
```

### Version

2.0.3

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Please read the changelog :) It is no longer possible to choose client IDs in Ory Hydra 2.0. There is also an issue/discussion around this: https://github.com/ory/hydra/issues/2911#issuecomment-1298440000

**Comment by MOZGIII** [comment]
Oof, I'll close this one then

**Comment by MOZGIII** [comment]
> Please read the changelog :) It is no longer possible to choose client IDs in Ory Hydra 2.0. There is also an issue/discussion around this: [#2911 (comment)](https://github.com/ory/hydra/issues/2911#issuecomment-1298440000)

But can we still set the ID if we use UUID?
