### ISSUE TITLE
Option to disable access log for /.well-known/openid-configuration and /.well-known/jwks.json endpoints

### ISSUE THREAD

**Issue by aarmam** [ory/hydra#3399]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

These endpoints are accessed frequently and generate considerable amount of logs.

### Describe your ideal solution

Add similar option to disable these endpoints from access log

https://github.com/ory/hydra/blob/master/cmd/server/handler.go#L214-L216

### Version

2.x

### Additional Context

Will implement it if accepted!

**Comment by project0** [comment]
It would be great if there would be a capability to disable all access logs.

**Comment by aeneasr** [comment]
I don't think that we'll add per-endpoint logging, just because at some point the amount of config options explodes. 

> It would be great if there would be a capability to disable all access logs.

Disabling the logging for access is already possible by setting `LOG_LEVEL=warn`

**Comment by project0** [comment]
@aeneasr unfortunately this also disables all other info log messages.

**Comment by aeneasr** [comment]
True, out of all the options then it would probably be the best option to simply disable access logging all together?
