### ISSUE TITLE
Using JWTs to exchange with access tokens

### ISSUE THREAD

**Issue by nryissuu** [ory/hydra#3404]
I've been following [https://www.ory.sh/docs/hydra/guides/jwt](https://www.ory.sh/docs/hydra/guides/jwt) and can't get this to work. 
Always gives me errors and I'm stuck at 400 Bad Request.

{`"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Client credentials missing or malformed in both HTTP Authorization header and HTTP POST body."}`

Are JWTs not supported yet?

Also _token_endpoint_auth_method_ seems to only allow _client_secret_basic_.
Am I missing something?

Thank you

_Originally posted by @nryissuu in https://github.com/ory/hydra/discussions/3359#discussioncomment-4498985_

**Comment by awill1988** [comment]
It does work. You need to honor the client config--at least that was my problem. In rfc7523, it states that if client credentials are found they must be presented. And it is indeed undocumented (in the example) but you need to add an argument for the `client_id` to the token endpoint. Not best docs, but I did get this working.
