### ISSUE TITLE
mTLS for admin/public interfaces

### ISSUE THREAD

**Issue by aarmam** [ory/hydra#3411]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to have mTLS option for both the admin and public interfaces.

### Describe your ideal solution

Introduce configurable ClientAuth and ClientCAs in [server handler tls configuration](https://github.com/ory/hydra/blob/master/cmd/server/handler.go#L320).

Configuration:

```yaml
serve.public.tls.client_ca: /path/to/file.pem
serve.admin.tls.client_ca: /path/to/file.pem
```

when specified, then ClientAuth would be set to ClientAuthType.RequireAndVerifyClientCert

### Version

2.x

### Additional Context

Willing to help implementing it if necessary!

**Comment by kmherrmann** [comment]
Thanks for filing this @aarmam!
@zepatrik I'd love your opinion here as we're working on improvements to API keys and PAKs. Would mTLS be possible to implement in this context?

**Comment by zepatrik** [comment]
There are many ways to do service authentication. While mTLS definitely is one of the most common, we would like to keep this complexity out of our services and rather recommend to offload this to a sidecar. Hydra would then only listen on localhost and therefore be only available through the sidecar.
The complexity comes when you require multiple CAs with different priviledges, need CA rotation, ....

A sidecar approach allows anyone to use any kind of auth, not just mTLS. Does that answer your question @aarmam?

**Comment by aeneasr** [comment]
I agree with Patrik here - mTLS (termination) should be done in envoy or another ingress proxy. Solving this in Hydra will have a lot of complexity - from different TLS modes to CAs, self signed certs, and so on :)

**Comment by alnr** [comment]
I think mTLS is a reasonable request. The only difficulty in the implementation would be auto-reloading the client CAs from disk.

**Comment by kmherrmann** [comment]
@aarmam after internal discussion, we won't be prioritizing mTLS support on our end. We'd be happy to review a PR if you'd like to contribute it though!

**Comment by aeneasr** [comment]
See also https://github.com/ory/fosite/issues/661 :)
