### ISSUE TITLE
Could not apply migrations: Error 3098: The table does not comply with the requirements by an external plugin.

### ISSUE THREAD

**Issue by xilu0** [ory/hydra#3415]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug
I use mysql innodb cluster

The following migration is planned:

Version                Name                                              Status
20190100000001000000   client                                            Applied
20190100000002000000   client                                            Applied
20190100000003000000   client                                            Applied
20190100000004000000   client                                            Applied
20190100000005000000   client                                            Applied
20190100000006000000   client                                            Applied
20190100000007000000   client                                            Applied
20190100000008000000   client                                            Applied
20190100000009000000   client                                            Applied
20190100000010000000   client                                            Applied
20190100000011000000   client                                            Applied
20190100000012000000   client                                            Applied
20190100000013000000   client                                            Applied
20190100000014000000   client                                            Applied
20190200000001000000   jwk                                               Applied
20190200000002000000   jwk                                               Applied
20190200000003000000   jwk                                               Applied
20190200000004000000   jwk                                               Applied
20190300000001000000   consent                                           Applied
20190300000002000000   consent                                           Applied
20190300000003000000   consent                                           Applied
20190300000004000000   consent                                           Applied
20190300000005000000   consent                                           Applied
20190300000006000000   consent                                           Applied
20190300000007000000   consent                                           Applied
20190300000008000000   consent                                           Applied
20190300000009000000   consent                                           Applied
20190300000010000000   consent                                           Applied
20190300000011000000   consent                                           Applied
20190300000012000000   consent                                           Applied
20190300000013000000   consent                                           Applied
20190300000014000000   consent                                           Applied
20190400000001000000   oauth2                                            Applied
20190400000002000000   oauth2                                            Applied
20190400000003000000   oauth2                                            Applied
20190400000004000000   oauth2                                            Applied
20190400000005000000   oauth2                                            Applied
20190400000006000000   oauth2                                            Applied
20190400000007000000   oauth2                                            Applied
20190400000008000000   oauth2                                            Applied
20190400000009000000   oauth2                                            Applied
20190400000010000000   oauth2                                            Applied
20190400000011000000   oauth2                                            Applied
20200521071434000000   consent                                           Applied
20200527215731000000   client                                            Applied
20200527215732000000   client                                            Applied
20200819163013000000   add_client_id_subject_idx_to_access_and_refresh   Pending
20200913192340000000   initial_sqlite                                    Pending
20201110104000000000   drop_uq_oauth2                                    Pending
20201116133000000000   set_null_time                                     Pending
20210928155900000000   support_amr_claim                                 Pending
20210928175900000000   client_custom_token_ttl                           Pending
20211226155900000000   grant_jwk_bearer                                  Pending
20211226156000000000   dynamic_registration                              Pending
20220328111500000000   support_any_subject_trusts                        Pending
Could not apply migrations:
Error 3098: The table does not comply with the requirements by an external plugin.
unable to execute statement: INSERT INTO schema_migration_transactional (version) SELECT version FROM schema_migration
github.com/ory/x/popx.(*Migrator).execMigrationTransaction.func1
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:333
github.com/ory/x/popx.(*Migrator).isolatedTransaction
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:314
github.com/ory/x/popx.(*Migrator).execMigrationTransaction
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:330
github.com/ory/x/popx.(*Migrator).migrateToTransactionalMigrationTable
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:285
github.com/ory/x/popx.(*Migrator).CreateSchemaMigrations
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:366
github.com/ory/x/popx.(*Migrator).exec
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:541
github.com/ory/x/popx.(*Migrator).UpTo
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:92
github.com/ory/x/popx.(*Migrator).Up
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:80
github.com/ory/hydra/persistence/sql.(*Persister).MigrateUp
        /project/persistence/sql/persister_migration.go:40
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL
        /project/cmd/cli/handler_migrate.go:107
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/ory/hydra/cmd.Execute
        /project/cmd/root.go:87
main.main
        /project/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
migrator: problem creating schema migrations
github.com/ory/x/popx.(*Migrator).exec
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:543
github.com/ory/x/popx.(*Migrator).UpTo
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:92
github.com/ory/x/popx.(*Migrator).Up
        /go/pkg/mod/github.com/ory/x@v0.0.368/popx/migrator.go:80
github.com/ory/hydra/persistence/sql.(*Persister).MigrateUp
        /project/persistence/sql/persister_migration.go:40
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL
        /project/cmd/cli/handler_migrate.go:107
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/ory/hydra/cmd.Execute
        /project/cmd/root.go:87
main.main
        /project/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
Successfully applied migrations!
time=2023-01-12T12:38:21+08:00 level=info msg=No tracer configured - skipping tracing setup audience=application service_name=Ory Hydra service_version=v1.11.10
Thank you for using Ory Hydra v1.11.10!

### Reproducing the bug

1. run hydra 1.7 first
2.  run hydra 1.11.10
3. migration failed as before

### Relevant log output

```shell
Could not apply migrations:
Error 3098: The table does not comply with the requirements by an external plugin.
unable to execute statement: INSERT INTO schema_migration_transactional (version) SELECT version FROM schema_migration
```

### Version

1.10.11

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
This looks like an issue in your MySQL configuration:

```
Error 3098: The table does not comply with the requirements by an external plugin.
```
