### ISSUE TITLE
redirect callback url is case sensitive for domain

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#3425]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Please refer to the comments dated Oct 31, 2022 and Nov 15, 2022 on this existing bug, which is already closed - https://github.com/ory/hydra/issues/380

My understanding is that domain part of redirect callback url is not case sensitive. 
Having said that on Hydra 1.10.5, we are facing this issue where domain name in redirect callback is matched in case-sensitive way. 

### Reproducing the bug

Steps
1. Run Ory Hydra 1.10.5
2. Configure a client with any valid callback url
3. Trigger OAuth2 flow with callback url as same valid url but domain name in a different case

Expected output: OAuth2 flow should work successfully
Expected output: OAuth2 flow fails with an error indicating invalid redirect callback url

### Version

1.10.5

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by Sacramentix** [comment]
Some DNS are case sensitive. Check out [https://en.wikipedia.org/wiki/Internationalized_domain_name](https://en.wikipedia.org/wiki/Internationalized_domain_name)

**Comment by Sacramentix** [comment]
traditionnal DNS use ascii which make them case  insensitive. But some are not so they can use some language specific character, it make them case sensitive.

**Comment by sagarshah1983** [comment]
I see. Thank you for your response and this information. That helps.

**Comment by aeneasr** [comment]
Yes, the OAuth2 spec is very explicit here. It needs to be an exact match, so we're fulfilling OpenID requirements here. Closing as I think this is answered
