### ISSUE TITLE
Logout flow does not redirect to client specific logout url when not passing id_token_hint

### ISSUE THREAD

**Issue by sagarshah1983** [ory/hydra#3426]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using v1.10.5 of Ory Hydra.
When I perform a logout flow with /oauth2/sessions/logout (without id token hint and post logout url parameters), it performs the logout but does not redirect me back to the post logout url configured at client level. It does redirect to the url that's configured globally.

Isn't there a way to perform this logout and redirect to client specific post logout url (configured at client level in hydra_client table) without looking for id token hint parameter?
Has anyone faced this issue?
Is it by design? or a bug?
Any suggestions are appreciated.

### Reproducing the bug

1. Run hydra with docker container
2. Configure a client with some post logout redirect url 
3. Perform OAuth2 flow that remembers the session information of the user and creates cookies
4. Perform logout flow by calling /oauth2/sessions/logout and avoid passing id_token_hint or post_logout_redirect_uri parameters

Expected output: Cookie is cleared and logout is performed and browser redirect happens to the post logout url configured the client 
Actual output: Cookie is cleared and logout is performed and browser redirect happens to the post logout url configured globally at hydra level and not at the client level.

### Version

1.10.5

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by sagarshah1983** [comment]
Also, I just found out another ticket which might be related - #2925

**Comment by aeneasr** [comment]
If you don't include the ID Token, then Hydra doesn't know which client initiated the logout. Hence, it can not redirect to the client URL. A login session can be used by any number of clients to establish an authorization grant. This is explained here: https://www.ory.sh/hydra/docs/concepts/logout#logout-flow

**Comment by sagarshah1983** [comment]
Thanks @aeneasr ! That helps. Only question further I have then is... if id token being passed as id_token_hint was expired, will it still remove session cookie and perform the logout with redirection to client specific logout page?

**Comment by aeneasr** [comment]
I think so!

**Comment by sagarshah1983** [comment]
Thanks again @aeneasr for your prompt reply. We will give a try to build a logout flow with id token parameter and post logout url

**Comment by aeneasr** [comment]
Closing but feel free to reopen if you discover an issue!
