### ISSUE TITLE
Passwordless Login integration to an web application

### ISSUE THREAD

**Issue by anil-intelops** [ory/hydra#3477]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

While integrating Passwordless Login to Next js web application, getting error message in dialog box like "This browser does not support WebAuthn!".
I'm using Chrome browser.

In the same browser it is not working with next js application but is is working with ory's default login ui.

### Reproducing the bug

clone and run the below projec.

https://github.com/ory/kratos-selfservice-ui-react-nextjs

### Relevant log output

```shell
This browser does not support WebAuthn!
```

### Version

 "@ory/client": "0.2.0-alpha.37",     "@ory/integrations": "0.2.8",     "@ory/themes": "~0.0.101",

### On which operating system are you observing this issue?

Windows

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Please use a browser that supports WebAuthn
