### ISSUE TITLE
Support statically defined OAuth2 clients

### ISSUE THREAD

**Issue by andremarianiello** [ory/hydra#3478]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Ory hydra provides a very nice CRUD api for dynamically managing oauth2 clients. However, my use case requires exactly 1 oauth2 client which does not need to be dynamically modified at all. However, we have no way to provide this client to hydra at start up. Instead we have to start hydra and the register the client using the API. If we could provide the client information at start up, we wouldn't have to dynamically register it.

### Describe your ideal solution

I think my ideal solution for this would be a section of the hydra config file dedicated to static clients. Providing client information here would allow us to stop running hydra-maester in k8s, and I think it would allow us to use the `memory` data storage, so we could run hydra statelessly. This would greatly simplify our current deployment methodology and infrastructure footprint.

### Workarounds or alternatives

The best workaround we have right now is to create an oauth2client custom resource and use hydra-maester to synchronize that resource with hydra. There are some issues with this approach stemming from lack of developer resources allocated to hydra-maester, but also this approach in general seems like overkill for what could be achieved with a 5-10 lines of configuration in a config file.

### Version

v2.0.3

**Comment by aeneasr** [comment]
Orchestration is out of context for Ory Hydra, please use a tool such as Terraform or the Ory Hydra CLI to create your client when you need it!

**Comment by andremarianiello** [comment]
I'm not sure what "Orchestration is out of context" means. Does it mean you don't have time to devote to this feature? Or does it mean that even if someone made a PR with this feature you wouldn't accept it? Or does it mean something else?

**Comment by aeneasr** [comment]
It's out of scope for Ory Hydra (meaning PRs likely not be merged), because there are many orchestration tools (such as terraform, the ory hydra cli, ...) that can do this for you, and the inconvenience of running a quick API call after start up does not justify the configuration complexity added by such a feature (and the potential future requests such as "oh but i want to create 3 clients and also add 2 json web keys and ...).

**Comment by andremarianiello** [comment]
Thanks for the clarification! We currently use terraform. It has some shortcomings that make it hard to integrate with hydra (terraform shortcomings, not hydra shortcomings). However, since I don't think we want this discussion to spiral into a detailed evaluation of why statically defined clients would be an improvement over the alternatives (for us), I will leave it at that. Thanks again for taking the time to look at this!

**Comment by aeneasr** [comment]
Alternatively you can also just run on a SQL back up that has the client available
