### ISSUE TITLE
cmd/cli: add flag for X-Forwarded-Proto for faking https termination

### ISSUE THREAD

**Issue by djeeg** [ory/hydra#349]
Hi,

I have a working setup of the latest Hydra on Docker with HTTPS, with a custom image that auto configures a test client

```
#!/bin/sh
/go/bin/hydra host 2> /var/log/hydraerror.log > /var/log/hydra.log &
sleep 30
hydra connect --url https://localhost:4444 --id USERNAME --secret PASSWORD --skip-tls-verify
hydra clients import /etc/hydra/client-test.json --skip-tls-verify
tail -f /var/log/hydra*
```

Now I want to enable SSL termination, so I added the env variable

```
  hydra:
    ports:
      - "4444:4444"
    environment:
      - LOG_LEVEL=debug
      - CONSENT_URL=https://PUBLICURL
      - HTTPS_ALLOW_TERMINATION_FROM=10.0.19.0/24
```
	  
Hydra seems to detect it okay

```
time="2017-01-03T16:38:25Z" level=info msg="Setting up http server on :4444"
time="2017-01-03T16:38:25Z" level=info msg="TLS termination enabled, disabling https."
```

The problem I have is trying to import the client.json file internally without TLS

This first attempt, I didnt expect to work, as Hydra is running HTTP

```
hydra connect --url https://localhost:4444 --id USERNAME --secret PASSWORD --skip-tls-verify
hydra clients import /etc/hydra/client-test.json
```

> Could not authenticate, because: Post https://localhost:4444/oauth2/token: http: server gave HTTP response to HTTPS client

I thought this would work, however it thinks Hydra is still in HTTPS mode

```
hydra connect --url http://localhost:4444 --id USERNAME --secret PASSWORD
hydra clients import /etc/hydra/client-test.json
```

> Response: {"request":"f5320b4e-30d1-4d5b-a3ae-e636ae490fb2","message":"Can not serve request over insecure http","code":500,"name":"internal-error"}

Am I trying to configure this wrong?

**Comment by arekkas** [comment]
Thanks for the detailed report, it is very well possible that there's a bug somewhere. I'll try to reproduce it tonight, latest by tomorrow!

**Comment by arekkas** [comment]
Ok I think I found the issue. The problem appears to be that you whitelisted `10.0.19.0/24` but are requesting from localhost. Because localhost is not whitelisted, it actually rejects all requests that do not come from `10.0.19.0/24`. Thus you get a `Can not serve request over insecure http`.

I think there are two possibilities here:

1. Open two ports, one for http and one for https
2. Allow to whitelist more than one range `10.0.19.0/24,127.0.0.0/24`

Both options are viable. What do you think?

**Comment by djeeg** [comment]
Hey, thanks for the near instant response!

I dig some tweaking in the last couple of minutes, pretty much as you said, went with something like this:

- HTTPS_ALLOW_TERMINATION_FROM=127.0.0.1/32,192.168.178.0/24,10.0.19.0/24,::1/32

Unfortuately I couldnt get the updated IPs to work.

I will try with your multiport suggestion

**Comment by djeeg** [comment]
Ahh I see what might be missing now, is there a way to fake the X-Forwarded-Proto header when calling [hydra clients import]

time="2017-01-03T17:22:19Z" level=warning msg="Could not serve http connection" error="X-Forwarded-Proto header is missing"
time="2017-01-03T17:22:19Z" level=error msg="An error occurred" error="Can not serve request over insecure http" request_id=62c2a8ed-98c2-4105-b57e-d9570eeb6072 status=502

**Comment by arekkas** [comment]
Ahh, yes, that makes sense! There is currently no way to fake that, you could however use the REST API with Postman for now - which of course isn't ideal - until I come up with a solution.

**Comment by arekkas** [comment]
Almost all CLI commands have a `--dry` option which prints the corresponding curl command. That way you could also make the requests using curl

**Comment by djeeg** [comment]
My current workaround is to just connect and import via the public URL, rather than localhost. As this is only a test environment, not too concerned.

**Comment by arekkas** [comment]
Sounds like a good workaround!

**Comment by arekkas** [comment]
https://github.com/ory/hydra/commit/79580e1ea9f28ed0298436dc7f8f0e611e8f5f34
