### ISSUE TITLE
Hydra versions 2.x showing memory leak behavior

### ISSUE THREAD

**Issue by gou-fi** [ory/hydra#3495]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello,

We've been running Hydra since last August or so, starting with version(s) 1.x. Purely supporting the client credentials flow, we were seeing no issues or concerns the entire time. 

Ever since updating to version 2.0.3, and recently 2.1.1, we have been seeing slow and steady memory leak behavior (increasing at a rate of about ~4% per day). The usage does not correlate with request count (during high usage times we'll see memory usage spike very briefly, then return to the previous rate of increase). We are seeing the same behavior with the memory even in test environments that are not receiving any requests but maintain similar memory usage patterns. 

Is this a known issue on your end? I was perusing the commit history and noticed that ory/x recently had a commit for addressing memory leaks but even with version 2.1.1 (which contains the relevant commit) the behavior remains. 

### Reproducing the bug

1. Run Hydra
2. Watch memory consumption go up

### Version

2.0.3, 2.1.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
Thank you for the report, we confirm that there is a memory leak in the v2 branch. We have not yet identified where it is exactly, but we think that the problem is in the open telemetry implementation. If you have any ideas where the leak is please do let us know, it would be very helpful!

**Comment by gou-fi** [comment]
Thanks for the response! Open telemetry would make sense, since we are scraping similarly in all environments. We have not been able to dedicate serious time or effort towards investigation unfortunately. But if we discover more we will update this ticket.

**Comment by ChrisLahaye** [comment]
Are default configurations without any explicit overrides for tracing also affected by this?

**Comment by aeneasr** [comment]
This is resolved on master branch afaik

**Comment by gou-fi** [comment]
Doesn't someone need to bump the version of ory/x? I see the old version on master atm.

**Comment by emtammaru** [comment]
Seeing similar memory leak in latest versions (v2.2 & v2.3):  Slow and steady memory leak behavior, increasing at a rate of about 256MB per day. The usage does not correlate with request volume -- seeing the same memory leak in test environments that are not receiving any requests.  The referenced fix https://github.com/ory/x/pull/689 looks like a different memory leak, and we are seeing this without tracing enabled.

**Comment by emtammaru** [comment]
Turned out the slow leak we were seeing was actually caused by container-level healthchecks in ECS using wget!

Somehow, this healthcheck causes a leak: 
```
HealthCheck = {
    command     = ["CMD-SHELL", "wget --no-check-certificate --no-verbose --tries=1 --spider https://localhost:4445/health/alive || exit 1"]
    interval    = 10
    retries     = 5
    timeout     = 5
    startPeriod = 30
  }
```
In our case, changing it to use `nc` instead fixed the issue:
```
command     = ["CMD-SHELL", "nc -z localhost 4445 || exit 1"]
```
