### ISSUE TITLE
Encrypt before saving `hydra_oauth2_flow.session_id_token`

### ISSUE THREAD

**Issue by KeiichiHirobe** [ory/hydra#3527]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The session_id_token is being saved to `hydra_oauth2_flow.session_id_token` without encryption. This is not ideal, especially if the id_token contains personal information such as address, email, and so on.

### Describe your ideal solution

Configuration `oauth2.session.encrypt_at_rest`  is explained as below.

```
If set to true (default) Ory Hydra encrypt OAuth2 and OpenID Connect session data using AES-GCM and the system secret before persisting it in the database.
```

I believe that if this option is enabled, `hydra_oauth2_flow.session_id_token` should be encrypted in the same manner.

### Workarounds or alternatives

We might consider creating a new configuration option for this purpose.

### Version

2.1.1

**Comment by naphattharawat** [comment]
I want the id_token to be encrypted as well.
