### ISSUE TITLE
policy: search policies by subject and resource

### ISSUE THREAD

**Issue by sebastian-garn** [ory/hydra#362]
Hi everyone,

as far as I could read from the api docs there only exists the possibility to search policies by subject (/policies?subject=john.doe). Is there a way/is it planned to narrow down the search results by also specifying a resource like for example "/policies?subject=john.doe&resource=resource:devices"?

Best regards,
Sebastian

**Comment by arekkas** [comment]
Unfortunately, this is currently not implemented and there is currently no plan to do so, but I welcome PRs and will put it on the backlog

**Comment by arekkas** [comment]
Removed from the backlog as this is now an issue in Keto. Feel free to reopen there and discuss possible PRs.
