### ISSUE TITLE
Hydra v2 is not certified

### ISSUE THREAD

**Issue by idc77** [ory/hydra#3635]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

You claim that Hydra is certified.
That is true for v1, but not for v2.
https://openid.net/certification/

```


ORY GmbH | ORY Hydra v1.0.0 | 14-Jul-2018
-- | -- | --


ORY GmbH 	ORY Hydra v1.0.0 	
[14-Jul-2018](https://openid.net/wordpress-content/uploads/2018/07/ORY_GmbH-ORY_Hydra-OP-Basic-7-June-2018.zip)
```

### Reproducing the bug

...

### Version

2

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
We run Hydra against the OIDC conformance test suite whose results are used to certify OIDC compatibility. These tests pass and have been the source of the original certification. Recertifying the software for every new release is very costly. As long as the oIDC conformance tests - which are part of the required CI pipeline to merge changes - pass you can consider Ory Hydra to be OIDC certified.
