### ISSUE TITLE
An error occurred during a concurrent test using memory mode

### ISSUE THREAD

**Issue by Zacama** [ory/hydra#3648]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Two goroutines execute oauth2 code flow at the same time. 

Then I got this:
{"audience":"application","error":{"debug":"Unable to serialize access due to a concurrent update in another session: The request could not be completed due to concurrent access","message":"server_error","reason":"","stack_trace":"\ngithub.com/ory/hydra/v2/persistence/sql.(*Persister).createSession\n\t/hydra/persistence/sql/persister_oauth2.go:240

### Reproducing the bug

Hydra In-Memory, two goroutines execute oauth2 code flow at the same time.

### Version

2.1.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment]
This is an SQLite limitation and is not going to be fixed, as SQLite is not intended for production operation.

**Comment by Zacama** [comment]
Okay, thank you.
