### ISSUE TITLE
`loginRequest.requested_access_token_audience` is setting to `null` instead of `[]`

### ISSUE THREAD

**Issue by JoMC98** [ory/hydra#3655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [x] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [x] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hi,

We are using Hydra v2.2.0rc3 that is on Pre-Release and in our login service, we are using Python client library `ory-hydra-client==2.2.0rc3`. 

When we try to obtain the login request with the library function:
`hydra_login_request = hydra.get_o_auth2_login_request(login_challenge=login_challenge)`, we receive the following error:

`ory_hydra_client.exceptions.ApiTypeError: Invalid type for variable 'requested_access_token_audience'. Required value type is StringSliceJSONFormat and passed type was NoneType at ['received_data']['requested_access_token_audience']`

The problem is that this api call: http://<HYDRA_HOST>:4445/admin/oauth2/auth/requests/login?challenge=<LOGIN_CHALLENGE> is returning `"requested_access_token_audience": null` as can be seen here:
![image](https://github.com/ory/hydra/assets/35965694/2f2dcf45-dfbf-4f98-8167-cabce197ace5)

The python client library expect an Array instead of null, throws an error and the login flow breaks.

I think this can be a bug on the pre-release hydra version and should be fixed before releasing the stable version.

I have read the following issue that is similar: https://github.com/ory/hydra/issues/2039, but we are not using in-memory database, we are using MySQL database.

Thanks in advance

### Reproducing the bug

1. Start hydra with v2.2.0rc3
2. GET `http://<HYDRA_HOST>:4445/admin/oauth2/auth/requests/login?challenge=<CHALLENGE>`
3. You can see that `requested_access_token_audience` is null instead of empty list

### Version

v2.2.0rc3

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by haslersn** [comment]
It seems v2.2 got released on docker hub (and v2 now points to v2.2) without this issue being fixed. So most clients are now broken. I guess this was not intentional, was it?

**Comment by haslersn** [comment]
@aeneasr this issue should have been a release blocker. Are there any plans on fixing this and creating a new release with the fix?
