### ISSUE TITLE
Peculiar EOF instead of response from the introspect endpoint.

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#368]
Hi!
I was browsing Hydra's logs on my test server and found that from time to time Hydra returns EOF from the https://hydra:4444/oauth2/introspect endpoint. 

There are no logs from Hydra about any of those requests.

**Comment by arekkas** [comment]
Could you share the log entry?

**Comment by arekkas** [comment]
Also, do you have, by any chance, set `LOG_LEVEL=debug`? It would include the stack trace in that case which would be really helpful

**Comment by janekolszak** [comment]
I only have logs from my resource owner and `LOG_LEVEL=debug` doesn't log anything.

**Comment by vorce** [comment]
I've seen similar behaviour. Running Hydra (0.5.2) in AWS behind an ELB. No logs in hydra for it.

**Comment by arekkas** [comment]
Please upgrade to Hydra 0.5.2 it should resolve some issues :)

**Comment by arekkas** [comment]
Closing because this didn't come up again
