### ISSUE TITLE
FATAL: no pg_hba.conf entry for host "xxx", user "hydra", database "hydra", no encryption (SQLSTATE 28000))

### ISSUE THREAD

**Issue by atliuhui** [ory/hydra#3762]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

migration error, using Azure Postgres service

### Reproducing the bug

WIndows Powershell
1. `.\hydra.exe migrate sql -y postgres://hydra:xxx@xxx.postgres.database.azure.com:5432/hydra?sslmode=disable`

### Relevant log output

```shell
time=2024-05-07T12:46:01+08:00 level=info msg=No tracer configured - skipping tracing setup audience=application service_name=Ory Hydra service_version=v2.2.0
time=2024-05-07T12:46:01+08:00 level=info msg=Retrying in 0.100000 seconds... audience=application error=map[message:failed to connect to `host=xxx.postgres.database.azure.com user=hydra database=hydra`: server error (FATAL: no pg_hba.conf entry for host "xxx", user "hydra", database "hydra", no encryption (SQLSTATE 28000))] service_name=Ory Hydra service_version=v2.2.0
```

### Version

2.2.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Hello, this looks like an SQL configuration error. Please read the docs for db strings: https://www.ory.sh/docs/self-hosted/deployment
