### ISSUE TITLE
Assign clients different consent urls 

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#378]
Hi,
As discussed on Slack I could implement multiple consent urls - one per client. This issue is the place I'd ask questions.

So should I make changes in fosite as well?

**Comment by arekkas** [comment]
There are no changes require in fosite. Instead, we need a consent url [here](https://github.com/ory/hydra/blob/master/client/client.go#L9) and use that value (if it exists) [here](https://github.com/ory/hydra/blob/master/oauth2/handler.go#L197)

**Comment by janekolszak** [comment]
I think I need to change something in fosite.

I can't find a way to get hydra Client, but I see fosite Client is available. 
https://github.com/ory/hydra/blob/master/oauth2/handler.go#L192

**Comment by arekkas** [comment]
This issue is no longer valid. The risky part of this is that third party clients could register malicious consent apps for phishing user passwords. Adding ACL to this piece complicates the hydra set up more and adds a potential security hole. Thus, this will not be supported in Hydra.
