### ISSUE TITLE
no /.well-known/openid-configuration endpoint implementation

### ISSUE THREAD

**Issue by waterdudu** [ory/hydra#379]
I'm using hydra as openid connect server, but hydra does not implement `/.well-known/openid-configuration` endpoint which is required by openid connect 1.0

**Comment by janekolszak** [comment]
You can implement it yourself in the idp.

**Comment by waterdudu** [comment]
> Hydra is a runnable server implementation of the OAuth 2.0 authorization framework and the OpenID Connect Core 1.0. 

As a server implemetation of oidc, I think hydra should implement the required endpoint in hydra side.

**Comment by janekolszak** [comment]
Hydra doesn't implement many endpoints that can be specified in this configuration, but can be implemented by your service, e.g. userinfo endpoint. 

The simplest way in my opinion is to have one, statically hosted file with this info.

**Comment by arekkas** [comment]
What do you think about implementing a minimalistic discovery file containing all the required fields but none of the optional?

**Comment by waterdudu** [comment]
I was integrating oidc client with hydra but came across the problem that the well-known endpoint was missing. I thought hydra is a full-implemented oauth2 and oidc server but I know now it's not. As @janekolszak said,  the missing endpoint is to easy to implement.

**Comment by arekkas** [comment]
I think you misunderstood. What I was suggesting is implementing this endpoint in hydra, but in a minimalistic version because Hydra does not support all of the things there.
