### ISSUE TITLE
redirect_uri domains are case-sensitive

### ISSUE THREAD

**Issue by waynerobinson** [ory/hydra#380]
Sometimes our users write weird URIs when redirecting.

The `redirect_uris` field in the client is case-sensitive for the domain when comparing. 

E.g. If `redirect_uris` is set to `"https://Yourfinancials.wealthdesk.com.au/my/auth/partner_hydra/callback"` then it won't match on `"https://yourfinancials.wealthdesk.com.au/my/auth/partner_hydra/callback"`

**Comment by arekkas** [comment]
How would this be handled in case of the path? Because `http://foo/authorizeSomething` is not the same resource as `http://foo/authorizesomething`.

**Comment by waynerobinson** [comment]
If you want to stay on-spec, hosts aren't case sensitive and paths are. 

Although you're only making it case-insensitive for the comparison part. The actual abuse window for a case-sensitive versus insensitive path is so tiny that I wouldn't think it was worth thinking about. And changing it will prevent future questions like these when people (Windows users in particular), fat-finger paths and wonder why there is an error. :-)

**Comment by arekkas** [comment]
Makes sense!

**Comment by arekkas** [comment]
The fix is [here](https://github.com/ory/fosite/pull/145). Unfortunately due to the moving of orgs the build isn't working currently. Might take a bit of time to fix this, sorry.

**Comment by waynerobinson** [comment]
It's fine for now. We have a hot fix in our own app that should prevent most of these issues at our end.

**Comment by sagarshah1983** [comment]
@aeneasr / @vinckr - With the fix referred above, are we expecting that if client is registered with redirect url as "https://bar.Com/cb" and if it uses the url in the oauth login flow as "https://bar.com/cb", then Hydra will allow that case insensitivity in domain name and won't return as an error?
As I am not seeing that happening on ory hydra version (1.10.5)

**Comment by sagarshah1983** [comment]
Has there been any updates here in past few days? I am not sure, if my understanding is right and if this needs to be reported as a bug. I dont see that domain part of redirect callback url is compared in case-insensitive way on v1.10.5
