### ISSUE TITLE
Support for Azure Cosmos DB as the database for Ory/Hydra

### ISSUE THREAD

**Issue by kushagraThapar** [ory/hydra#3806]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

We would like to integrate Ory/Hydra with Azure Cosmos DB as the storage layer.

### Describe your ideal solution

It would be ideal if this is supported by Ory/Hydra. If not, we are open to maintain this as an adapter. Is there any documentation available on wiring this up ourselves or is this planned by Ory/Hydra team in the near future?

### Workarounds or alternatives

We couldn't find any workarounds for this.

### Version

N/A

**Comment by aeneasr** [comment]
Hello, only Postres, MySQL and Cockroach are supported. Support for other databases is out of scope for Ory‘s projects in general. AWS and GCP have very good database products for both variants.
