### ISSUE TITLE
relation "hydra_client" does not exist (postgres)

### ISSUE THREAD

**Issue by ErnstA** [ory/hydra#381]
INFO[0000] Connecting with postgres://*:*@localhost:5432/hydra_test? 
INFO[0000] Connected to SQL!                            
WARN[0000] Expected system secret to be at least 32 characters long, got 0 characters. 
INFO[0000] Generating a random system secret...         
INFO[0000] Generated system secret: -6&F!...
WARN[0000] WARNING: DO NOT generate system secrets in production. The secret will be leaked to the logs. 
INFO[0000] Applied 1 migrations postgres!               
INFO[0000] Key pair for signing hydra.openid.id-token is missing. Creating new one. 
INFO[0004] Key pair for signing hydra.consent.response is missing. Creating new one. 
INFO[0011] Key pair for signing hydra.consent.challenge is missing. Creating new one. 
Could not fetch client list: pq: relation "hydra_client" does not exist

hydra_test=# \dt
                 List of relations
 Schema |           Name            | Type  | Owner 
--------+---------------------------+-------+-------
 public | hydra_groups_migration    | table | calm
 public | hydra_jwk                 | table | calm
 public | hydra_jwk_migration       | table | calm
 public | hydra_oauth2_access       | table | calm
 public | hydra_oauth2_code         | table | calm
 public | hydra_oauth2_migration    | table | calm
 public | hydra_oauth2_oidc         | table | calm
 public | hydra_oauth2_refresh      | table | calm
 public | hydra_policy_migration    | table | calm
 public | hydra_warden_group        | table | calm
 public | hydra_warden_group_member | table | calm
 public | ladon_policy              | table | calm
 public | ladon_policy_permission   | table | calm
 public | ladon_policy_resource     | table | calm
 public | ladon_policy_subject      | table | calm
(15 rows)

Versions:
hydra v0.7.7 ,  postgres 9.5 , Ubuntu 16.04.1 LTS

**Comment by arekkas** [comment]
Thank you, I think I know what the problem is

**Comment by arekkas** [comment]
Hm, are you sure that you're running version 0.7.7? I checked the code and it looks like this issue 4f931cd6097d9fb7c45f4569f624fb42a5e76f19 which that was resolved in > 0.7.2

**Comment by arekkas** [comment]
Sorry, nevermind the previous comment. The `hydra_groups_migration` table is there.

**Comment by ErnstA** [comment]
Hi Aeneas,

You are right:
$ hydra  version
Version:    v0.7.1
Git Hash:   5b425372b0e54a2e9ff00aa555083b8b6034ee6a
Build Time: 2017-02-21 21:21:08.677064699 +0100 CET

I am surprised as I downloaded:
https://github.com/ory/hydra/releases/download/v0.7.7/hydra-linux-amd64

Thanks
Ernst

**Comment by arekkas** [comment]
Hm, I can't reproduce this, at least on windows:

```
C:\Users\foobar\Downloads>hydra-windows-amd64.exe version
Version:    v0.7.7
Git Hash:   868a02b376ad699be9512b20d6fd40f515f0a00f
Build Time: 2017-02-21 21:30:32.4132341 +0100 CET
```

Are you sure the binary you're running is actually the one you downloaded?

**Comment by arekkas** [comment]
on linux neither:

```
$ wget https://github.com/ory/hydra/releases/download/v0.7.7/hydra-linux-amd64
$ ./hydra-linux-amd64 version
Version:    v0.7.7
Git Hash:   868a02b376ad699be9512b20d6fd40f515f0a00f
Build Time: 2017-02-21 21:31:50.9682054 +0100 STD
```

**Comment by ErnstA** [comment]
Somehow I must have mistakenly downloaded the wrong version.
So sorry.
