### ISSUE TITLE
Token introspection can respond `{"active": false}` for a valid token when losing DB connection

### ISSUE THREAD

**Issue by konstantin-baidin-y42** [ory/hydra#3811]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When Hydra has some problems with DB connection, it can respond with `{"active": false}` instead of responding with an error status or being unavailable.

### Reproducing the bug

I managed to reproduce it in k8s. I requested the hydra introspection endpoint multiple times with a valid token. At the same time, I scaled down the database deployment to 0. At some moment, hydra responded with `{"active": false}` several times, and after that, it stopped responding to requests.
When I scaled DB deployment back to 1, hydra responded with `active: true`.

So, from the client's perspective, Hydra can randomly respond with false negatives. I expect Hydra to return an error status or not respond at all if it can not access the database.

### Version

v2.2.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by aeneasr** [comment]
Dupe #3671
