### ISSUE TITLE
Hydra is consuming a lot of memory in prod

### ISSUE THREAD

**Issue by brenobaptista** [ory/hydra#3828]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Hydra is consuming a lot of memory in prod, which is only getting bigger, like a cache
Is there a way for us to free the resources?

![image](https://github.com/user-attachments/assets/c5dc493f-6d3c-4728-a2c6-2707b23d8ccf)
![image](https://github.com/user-attachments/assets/3b0026f2-3eda-4a0e-b3c6-1a01d4136c7c)

### Reproducing the bug

We're self-hosting it.
We don't see any config that could be causing this.

### Version

2.1.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes

**Comment by aeneasr** [comment]
Please upgrade to the latest version
