### ISSUE TITLE
cli handler_groups type error?

### ISSUE THREAD

**Issue by karantin2020** [ory/hydra#383]
in ` hydra/cmd/cli/handler_groups.go`
`func (h *GroupHandler) CreateGroup(cmd *cobra.Command, args []string)` and `func (h *GroupHandler) DeleteGroup(cmd *cobra.Command, args []string)` both have one code:

```go

	err = h.M.CreateGroup(cc)
	if h.M.Dry {
		fmt.Printf("%s\n", err)
		return
	}

        pkg.Must(err, "Could not create group: %s", err)
```

See https://github.com/ory/hydra/blob/fcdf6643845ff8b743a910295c5761dfd389a8a3/cmd/cli/handler_groups.go#L36
and
https://github.com/ory/hydra/blob/fcdf6643845ff8b743a910295c5761dfd389a8a3/cmd/cli/handler_groups.go#L58

Is that write?

**Comment by arekkas** [comment]
No, it's a bug. Thanks!
