### ISSUE TITLE
/.well-known/jwks.json is not registered with IANA, violating a MUST in RFC 5785

### ISSUE THREAD

**Issue by andersk** [ory/hydra#3832]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe the bug

Ory Hydra is using the `/.well-known/jwks.json` URI, but this URI is not registered in the [IANA well-known URIs registry](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml). This violates a [hard requirement of RFC 5785](https://datatracker.ietf.org/doc/html/rfc5785#section-3) that all `/.well-known/` URIs MUST be registered:

> A well-known URI is a URI [[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986)] whose path component begins with the characters "/.well-known/", and whose scheme is "HTTP", "HTTPS", or another scheme that has explicitly been specified to use well-known URIs.
>
> Applications that wish to mint new well-known URIs MUST register them, following the procedures in [Section 5.1](https://datatracker.ietf.org/doc/html/rfc5785#section-5.1).

This registration requirement is important to avoid colliding uses of `/.well-known/` URIs with different semantics.

Related:

- gravitational/teleport#46194

### Reproducing the bug

See https://www.ory.sh/docs/hydra/reference/api#tag/wellknown/operation/discoverJsonWebKeys and

https://github.com/ory/hydra/blob/57096be9befbde4a1436ef48338d253a248c91c4/jwk/handler.go#L32

### Version

2.2.0

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by aeneasr** [comment]
Sorry, but this is nonsense. This endpoint is literally part of the OIDC spec.

**Comment by andersk** [comment]
If the URL is not going to be changed, then it should be registered.

**Comment by aeneasr** [comment]
We are such a small project and don’t have the resources nor the connections to influence IANA. Please reach out to one of the many other players in the market, like Okta to formalize the endpoint: https://www.google.com/search?q=%22.well-known%2Fjwks.json

**Comment by andersk** [comment]
Okta uses `/oauth2/v1/keys`, not `/.well-known/jwks.json`. Example: https://example.okta.com/.well-known/openid-configuration → `"jwks_uri":"https://example.okta.com/oauth2/v1/keys"`.

**Comment by aeneasr** [comment]
https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-sets
