### ISSUE TITLE
Transition Dockerfile to Alpine Linux

### ISSUE THREAD

**Issue by nicholaswyoung** [ory/hydra#393]
Now that there's an official `golang:alpine` image, would you be open to using it instead? My trial build is over 50% smaller. (If this is a viable idea, I can assemble a PR with `musl` compilation, etc.)

**Comment by arekkas** [comment]
Hi, indeed I already have that in place. I'll submit a PR next week

**Comment by arekkas** [comment]
See https://github.com/ory/hydra/issues/374#issuecomment-284713870

**Comment by nicholaswyoung** [comment]
@arekkas Ah, I missed that. Sorry for the duplicate.

Thanks for your kind and quick response. Hydra is awesome so far. 👍

**Comment by arekkas** [comment]
No problem :)

Von meinem iPhone gesendet
