### ISSUE TITLE
oauth2: add possibility for denying consent requests

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#400]
Idea: `&consent=deny`

**Comment by Cikey** [comment]
Just a heads up: The [sdk](https://github.com/ory/hydra/blob/master/sdk/consent.go) currently uses `&consent=denied` in line 115:

    return fmt.Sprintf("%s&consent=denied", claims.RedirectURL), nil

**Comment by arekkas** [comment]
https://github.com/ory/hydra/commit/48c229b62af56ab16f26e827b221b9e04bb0c077
