### ISSUE TITLE
Add support to mongodb

### ISSUE THREAD

**Issue by ghazninattarshah** [ory/hydra#401]

**Comment by arekkas** [comment]
This will not be done as part of our official community work and will only be accepted as a PR by a maintainer who commits to maintaining the mongodb adapter over the next 2 years.

**Comment by atrauzzi** [comment]
Just jumping in to say it would be nice to see an officially supported mongodb driver made available.

**Comment by arekkas** [comment]
I honestly appreciate your input, but unfortunately it will not happen :(

**Comment by atrauzzi** [comment]
I don't know -- It seems like something you'll eventually have to change your mind on.  Forcing people into making deployment considerations for databases that aren't part of their tech stack eliminates this project from their consideration.

If I'm running on an MS tech stack (sometimes, not always thankfully), I don't have postgres and I definitely don't have rethink.  Driver support seems like something you really want to ace.

**Comment by ravihara** [comment]
> I don't know -- It seems like something you'll eventually have to change your mind on. Forcing people into making deployment considerations for databases that aren't part of their tech stack eliminates this project from their consideration.
> 
> If I'm running on an MS tech stack (sometimes, not always thankfully), I don't have postgres and I definitely don't have rethink. Driver support seems like something you really want to ace.

Totally agree. We need driver support for NoSQL databases as well. Adoption of Hydra should not be hindered by lack of storage backend support.

**Comment by aeneasr** [comment]
Now more than ever it is clear that MongoDB and NoSQL is *absolutely not* the right database engine for this project. Without strong consistency and `ON DELETE CASCADE` or similar we'll leave several gates open. Projects like CockroachDB (to be supported in the future) allow to run SQL across AZs in a HA way. We won't support MongoDB but you can always fork the project and write a MongoDB adapter yourself. It doesn't make sense to use a hammer for a screw.
