### ISSUE TITLE
Rest API documentation not working

### ISSUE THREAD

**Issue by ventayol** [ory/hydra#410]
Hi there,
We want to start using Hydra and for this we wanted to check the API.
When opening the REST API documentation link, Apiary says it's not found.

Try to open:
http://docs.hdyra.apiary.io/

And you will see the error.

**Comment by ventayol** [comment]
Found it has been changed but not yet update in the docs.
Just in case someone has the same problem:
http://docs.hydra13.apiary.io/

**Comment by arekkas** [comment]
What link was broken? Could you supply a PR for the broken link? I might have missed some docs.

**Comment by ventayol** [comment]
I've checked the problem and the link in the Readme is right but it's wrong in the Official documentation link.

I was reading the docs here:
https://ory.gitbooks.io/hydra/content/
And on this page the rest api link is wrong.

**Comment by arekkas** [comment]
Ah I see :) The file for that is [here](https://github.com/ory/hydra/blob/master/docs/README.md)

**Comment by arekkas** [comment]
Ah, actually, the link there is correct. Apparently there's an issue with the gitbook sync - reopening for tracking this

**Comment by arekkas** [comment]
Resolved
