### ISSUE TITLE
Small doc error

### ISSUE THREAD

**Issue by Grillz** [ory/hydra#411]
Hey in your 5 minute tutorial, the command `docker exec -i -t hydra_hydra_1 /bin/bash` doesn't work, it should be `docker exec -i -t hydra_hydra_1 /bin/sh`. Awesome project though, were excited to start using it

**Comment by arekkas** [comment]
Thank you! Could you supply a PR? The file is [here](https://github.com/ory/hydra/blob/master/docs/tutorial.md) :)

**Comment by Grillz** [comment]
np, https://github.com/ory/hydra/pull/412
