### ISSUE TITLE
Cockroachdb support

### ISSUE THREAD

**Issue by borag** [ory/hydra#413]
How hard is it to support Cockroachdb ?

**Comment by arekkas** [comment]
It will not be part of our community efforts. If you want to tackle it yourself, you will need to implement the various managers, for example [this one](https://github.com/ory/hydra/blob/master/client/manager.go). If you want us to implement it, drop us a line at hi@ory.am

**Comment by arekkas** [comment]
I'm closing this because it won't be part of our open source work and I think the question has ben answered

**Comment by drasko** [comment]
+1 for CocroachDB. It uses PQ driver, so effort should be minimal: https://www.cockroachlabs.com/docs/build-an-app-with-cockroachdb.html

**Comment by arekkas** [comment]
If it supports the golang pg driver, then you should be able to connect to it with `postgres://mycockroachdb:123/database`, but please be aware that we can't support that as part of our community effort.
