### ISSUE TITLE
ory vs ory-am

### ISSUE THREAD

**Issue by Grillz** [ory/hydra#414]
Hey so I was trying to implement the rest of the Discovery code that you had started with https://github.com/ory/hydra/issues/379. I noticed you all moved repositories from `ory-am` to `ory`, can I change the go imports to reflect that or were you waiting for some reason?

**Comment by arekkas** [comment]
The golang codebases will not be moved, to keep BC. Only new repos will use `ory`. So keep using `ory-am` where it says so in the readme :)

**Comment by Grillz** [comment]
hmm thats a bit odd, how are you syncing them? I made modifications to the oauth2 package and now I need to use those modifications in `cmd`, I don't see the repo under `ory-am` anymore, are you just renaming locally?

**Comment by arekkas** [comment]
no, there's a redirect: https://github.com/ory-am/hydra

**Comment by Grillz** [comment]
ok, I can make that work, this is just where Go's absolute imports are no fun, thanks for the help 👍
