### ISSUE TITLE
Resource owner password credentials grant

### ISSUE THREAD

**Issue by iNDicat0r** [ory/hydra#417]
Hi
I have gone through the documentation and it seems this grant type isn't implemented/supported and I can't find a good reason why not. For instance this grant type is used for the companies own mobile apps(android,ios...even js apps).

Any explanation ?

**Comment by arekkas** [comment]
* https://github.com/ory/hydra/pull/297
* https://github.com/ory/hydra/issues/214

It is currently not supported because hydra does not act as an IDP. Additionally, the ROPC grant is _only for legacy scenarios_, and we actually support the recommendations for mobile oauth2 from ietf: https://tools.ietf.org/html/draft-ietf-oauth-native-apps-09

**Comment by iNDicat0r** [comment]
Thank you for the prompt response.
Is there any link to the documentation with examples to use hydra for mobile apps ?

**Comment by iNDicat0r** [comment]
Also the documentation should be more clear, something which makes it easier for people to implement,

**Comment by arekkas** [comment]
Not right now, but it would be great if you could contribute to the [docs](https://github.com/ory/hydra/tree/master/docs) regarding this topic!

**Comment by iNDicat0r** [comment]
Alright then, i will dedicate some time for a proper implementation and contribute to the docs.

**Comment by arekkas** [comment]
Awesome!

**Comment by UkonnRa** [comment]
One of the scenarios using password grant in my app is for *testing the backend*. In testing, I want to login a user, get the access token, then do the test stuff. Without password grant, I cannot login at all. Any advice?

**Comment by aeneasr** [comment]
Use client credentials for that scenario

**Comment by UkonnRa** [comment]
> Use client credentials for that scenario
> […](#)
> On 14. Sep 2020, at 06:02, Ukonn Ra ***@***.***> wrote: ﻿ One of the scenarios using password grant in my app is for testing the backend. In testing, I want to login a user, get the access token, then do the test stuff. Without password grant, I cannot login at all. Any advice? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

But you cannot login **as a specified user** using client credentials

**Comment by aeneasr** [comment]
In that case you have to write a mock login provider that auto-accepts login as a specific user.

ROPC is being removed from OAuth 2.1 by the way.
