### ISSUE TITLE
Uname in session

### ISSUE THREAD

**Issue by matteosuppo** [ory/hydra#418]
Am I right in believing that the uname is not set in the session?
https://github.com/ory/hydra/blob/master/oauth2/consent_strategy.go#L93

I wanted to make use of it: 

> uname: You can set an arbitrary, non-unique username which will be echoed in the token introspection. (optional)

**Comment by arekkas** [comment]
The subject is the username :)

**Comment by arekkas** [comment]
Oh sorry, no, I misunderstood. I'll check into it tomorrow

**Comment by arekkas** [comment]
Yeah actualy it's not supported in the code. This might be an old reference. Is it enough for you to set at_ext/id_ext instead?

**Comment by matteosuppo** [comment]
Since I need it at introspection I should use at_ext, right?

Maybe I could make a pull request to fix the documentation?

Il ven 14 apr 2017, 09:23 Aeneas <notifications@github.com> ha scritto:

**Comment by arekkas** [comment]
Yes exactly, and yes, please do! :)
