### ISSUE TITLE
API error (500) during tests

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#419]
Hi!
I try to run hydra's tests but they fail with:

```
~/go/src/github.com/ory-am/hydra$ go test ./client/
2017/04/13 22:58:24 Could not start resource: : API error (500): {"message":"invalid environment variable: "}
```

I installed dependencies with `glide install`. I also installed dockertest: `glide get gopkg.in/ory-am/dockertest.v3`.

**Comment by arekkas** [comment]
Which docker version are you using?

**Comment by janekolszak** [comment]
```
docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by janekolszak** [comment]
Maybe it has something to do with hydra's path? I still have it under ory-am

**Comment by arekkas** [comment]
No, it's something with dockertest or the common library. I'll look into it tomorrow

**Comment by arekkas** [comment]
Yup, it's the common library, fixed there: https://github.com/ory/common/releases/tag/v0.4.0

Still need to update hydra and ladon deps
