### ISSUE TITLE
Outdated fosite

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#424]
Hi!
I think the fosite version should be bumped in glide.yaml.

**Comment by arekkas** [comment]
Why exactly? `^0.6.9` matches `0.6.18` (latest fosite release) according to semver

**Comment by janekolszak** [comment]
Maybe since I use ~0.7.10 in idp it will use ~0.6.9?

**Comment by arekkas** [comment]
There is no fosite 0.7.10: https://github.com/ory/fosite/releases

**Comment by arekkas** [comment]
Closing due to inacitivity, feel free to come back on this.
