### ISSUE TITLE
Mismatch between library versions

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#434]
Hi!
There seems to be a mismatch between gorethink and redis versions used in hydra and helper libraries.
Here is a clean, failing build of the idp library:
https://travis-ci.org/janekolszak/idp/jobs/226201533

Thanks

**Comment by arekkas** [comment]
Thanks, those libraries are really annoying because they introduce breaking changes every few months. This will be resolved with #425 which I hope to get done this week, latest next.
