### ISSUE TITLE
Freeze dependencies 

### ISSUE THREAD

**Issue by janekolszak** [ory/hydra#437]
Hi,
Can you freeze the dependencies of all libraries in `glide.yaml`?
Either remove `^` or replace it with `~` (if you believe people know what patches are).

`^` is too permissive. It prevents projects that depend on Hydra from building if any of those libraries has an issue.

Glossary: https://glide.readthedocs.io/en/latest/versions/

**Comment by arekkas** [comment]
There are two issues at hand:

1. Frozen dependencies (e.g. no prefix, or patch match) force you to use the exact same versions in your code in order to work
2. The hydra sdk should actually not pull the whole hydra stack

**Comment by janekolszak** [comment]
1 is not an issue if 2 is solved.

**Comment by arekkas** [comment]
why not lock hydra version to 0.7.9 for now?

**Comment by arekkas** [comment]
This is resolved now
