### ISSUE TITLE
herodot: resolve issue with infinite loop caused by certain error chain

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#441]
@matteosuppo this caused your rogue hydra instance, I think.

**Comment by matteosuppo** [comment]
Could be, it happened again. I will try as soon as there is a release with this commit.

**Comment by arekkas** [comment]
https://github.com/ory/hydra/releases/tag/v0.7.12 - should be on dockerhub in ~20 minutes

**Comment by matteosuppo** [comment]
<3

**Comment by arekkas** [comment]
At your service @matteosuppo 🖖
