### ISSUE TITLE
x-forwarded-for header

### ISSUE THREAD

**Issue by matteosuppo** [ory/hydra#451]
While debugging an issue with TLS termination I noticed that if there is a reverse proxy in the mix (nginx for example), the logs correctly use the X-Forwarded-For header:

```
time="2017-05-04T16:23:05Z" level=info msg="started handling request" method=GET remote="172.30.11.67:20489" request="/health" 
```

while in the [matchesRange function](https://github.com/ory/hydra/blob/master/config/config.go#L60) it uses `http.Request.RemoteAddr` which is different:

```
hydra_1   | 2017/05/04 16:37:08 172.17.0.4:48168
```

172.17.0.4 is the ip of the nginx docker container, while the headers contain the correct ip:

```
hydra_1   |  (string) (len=15) "X-Forwarded-For": ([]string) (len=1 cap=1) {
hydra_1   |   (string) (len=18) "172.30.11.67:20489"
hydra_1   |  },
hydra_1   |  (string) (len=17) "X-Forwarded-Proto": ([]string) (len=1 cap=1) {
hydra_1   |   (string) (len=5) "https"
hydra_1   |  },
hydra_1   |  (string) (len=9) "X-Real-Ip": ([]string) (len=1 cap=1) {
hydra_1   |   (string) (len=18) "172.30.11.67:20489"
hydra_1   |  }
```

**Comment by arekkas** [comment]
Shouldn't the remote address for the TLS Termination be the last IP in the chain? Or let me repharse: Why is this an issue?

**Comment by matteosuppo** [comment]
You're right. I was confused.
