### ISSUE TITLE
Challenge claims redirect http instead of https

### ISSUE THREAD

**Issue by ahillman3** [ory/hydra#455]
I'm trying to create an OAuth2 process flow using hydra as my OAuth2 server. I have it setup within Kubernetes running in Amazon, wth http.

I have added an SSL certificate to the load balancer, and added a DNS entry to Route53 to provide a public FQDN matching the certificate.

I don't see any issues with invalid certificate  errors, but when I ask for a challenge response the redirect value in the claim has http instead of https.

This makes completing the process flow difficult, as redirects don't work.

Any ideas, or more info needed?

**Comment by arekkas** [comment]
Definitely more info needed. What docker image are you running, what environment variables are set (don't include secrets)?

**Comment by ahillman3** [comment]
My docker image is built from the most recent code as of yesterday.
Environment variables:
SYSTEM_SECRET: ******
DATABASE_URL: mysql://**:**@tcp(34.209.182.159:3306)/hydra?parseTime=true
FORCE_ROOT_CLIENT_CREDENTIALS: **:**
AUTHORIZE_CODE_LIFESPAN: 10m
AUTH_CODE_LIFESPAN: 10m
ID_TOKEN_LIFESPAN:8760h
ACCESS_TOKEN_LIFESPAN: 8760h
CHALLENGE_TOKEN_LIFESPAN: 10m
CONSENT_URL: https://ad6c1aff82f3411e7899506d9bf1932f-844480084.us-west-2.elb.amazonaws.com:8081/consent
PROFILING: cpu

The consent url is not currently working, but I'm not having a problem with that.

**Comment by arekkas** [comment]
Which docker image are you using exactly? There are multiple flavors!

**Comment by arekkas** [comment]
Oh I misread, seems like you're building it yourself. Which docker image are you using?

**Comment by ahillman3** [comment]
Ahh.

 Docker-http

**Comment by arekkas** [comment]
Ok, that one has https disabled, use the normal one for https - does that answer your question?

**Comment by ahillman3** [comment]
Will that still work if I have it running without https in kubernetes? I like having the certificate outside kubernetes.

**Comment by arekkas** [comment]
Have you seen the TLS termination option? If not, check out `hydra help host` and look under the "HTTPS CONTROLS" section. That should be what you're looking for

**Comment by ahillman3** [comment]
I'll look. Thanks.

**Comment by arekkas** [comment]
otherwise you could probably also issue a certificate from the platform you're using for hydra, use that in hydra and serve regular https. that usually works too for e.g. AWS ELB - should also work on GCP

**Comment by ahillman3** [comment]
I'll look into that as well.

**Comment by arekkas** [comment]
also head over to our community channel on gitter (link in readme), the community is really helpful and has dealt with this as well :)

closing this issue, if you feel there's a bug or something please reopen or create a new issue

**Comment by ahillman3** [comment]
Thanks.
