### ISSUE TITLE
go install github.com/ory/hydra Fails to compile

### ISSUE THREAD

**Issue by linearregression** [ory/hydra#456]
go version
go version go1.7.4 darwin/amd64

Command and log:
go install github.com/ory/hydra

github.com/ory/hydra/vendor/github.com/ory/graceful
vendor/github.com/ory/graceful/http_defaults.go:13: undefined: tls.X25519
vendor/github.com/ory/graceful/http_defaults.go:20: undefined: tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
vendor/github.com/ory/graceful/http_defaults.go:21: undefined: tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
vendor/github.com/ory/graceful/http_defaults.go:66: srv.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/github.com/ory/graceful/http_defaults.go:67: srv.IdleTimeout undefined (type *http.Server has no field or method IdleTimeout)
vendor/github.com/ory/graceful/http_graceful.go:54: undefined: http.ErrServerClosed

**Comment by arekkas** [comment]
Please install go 1.8 as noted in [history.md](https://github.com/ory/hydra/blob/master/HISTORY.md#080) :)
