### ISSUE TITLE
Introspection endpoint responds with 401 on invalid payload token

### ISSUE THREAD

**Issue by eliasgs** [ory/hydra#457]
Assuming `ACCESS_TOKEN` is a valid client_credentials token for scope `hydra` and `VALID_TOKEN` is a valid authorization_code token, the issue can be replicated with:
```bash
curl -s -k -H "Authorization: Bearer $ACCESS_TOKEN" -d "token=$VALID_TOKEN" https://localhost:4444/oauth2/introspect|python -m json.tool
{
    "active": true,
    "scope": "...",
    "client_id": "...",
    "sub": "...",
    "exp": ...,
    "iat": ...,
    "aud": "..."
}
export INVALID_TOKEN=${VALID_TOKEN%?}
curl -s -k -H "Authorization: Bearer $ACCESS_TOKEN" -d "token=$INVALID_TOKEN" https://localhost:4444/oauth2/introspect|python -m json.tool
{
    "error": "request_unauthorized",
    "error_description": "The request could not be authorized",
    "statusCode": 401
}
```

Seeing that [rfc7662#section-2.3](https://tools.ietf.org/html/rfc7662#section-2.3) notes:
> Note that a properly formed and authorized query for an inactive or
>    otherwise invalid token (or a token the protected resource is not
>    allowed to know about) is not considered an error response by this
>    specification.  In these cases, the authorization server MUST instead
>    respond with an introspection response with the "active" field set to
>    "false" as described in Section 2.2.

We should instead return an `active=false` response.

**Comment by arekkas** [comment]
Thank you for reporting this, I'm quite busy this week, so if you want to take a look yourself please do so!

**Comment by arekkas** [comment]
https://github.com/ory/fosite/pull/176
