### ISSUE TITLE
"Subject claim can not be empty" error when trying to retrieve ID Token

### ISSUE THREAD

**Issue by mateomurphy** [ory/hydra#460]
I'm trying to retrieve an ID Token and I'm getting this error. I imagine I'm doing something wrong, but the error message is not helpful.

**Comment by arekkas** [comment]
You probably forgot to set the subject claim `sub` in the consent challenge. Read more on this here: https://ory.gitbooks.io/hydra/content/oauth2.html#consent-app-flow or consider using the js or go sdk.

**Comment by mateomurphy** [comment]
My consent claim looks like

```
{
  "jti": "64c4f79e-e016-45b8-8c0e-d96c671c1e8a",
  "aud": "c3b49cf0-88e4-4faa-9489-28d5b8957858",
  "exp": 1494558745,
  "scp": [
    "openid"
  ],
  "sub": 58318,
  "iat": 1494558145
}
```

and everything works fine when I don't use the `openid` scope.

**Comment by mateomurphy** [comment]
Ah, I dug through the fosite source and figured out that `sub` needs to be a string, otherwise it's silently discarded. I also just figured out that a `nonce` is required, otherwise you get a "The request used a security parameter (e.g., anti-replay, anti-csrf) with insufficient entropy (minimum of 8 characters)". Perhaps the error message and/or the documentation could be improved?

**Comment by arekkas** [comment]
sub needs to be a string, not a number :)

**Comment by arekkas** [comment]
yes definitely needs improvement! :)
