### ISSUE TITLE
Unable to set Public flag to false

### ISSUE THREAD

**Issue by faxal** [ory/hydra#463]
If a client is created with `Public` flag set to `true`, client managers are not able to update the flag to `false`. This is because of how `mergo` works. 

````go
package main

import (
	"fmt"

	"github.com/imdario/mergo"
)

type Client struct {
	Public bool
}

func main() {

	// Client with updated information,
	// wanting to set Public flag to false
	c := &Client{
		Public: false,
	}

	// Client in database with Public flag set to true
	o := &Client{
		Public: true,
	}

	// "Mergo is intended to assign only zero value fields on destination with source value."
	// mergo.Merge(dst, src)
	mergo.Merge(c, o)
	// Because c (the destination) contains false it is considered a zero value
	// and gets replaced by the value of o (the source)

	fmt.Printf("c %+v\n", c)
	fmt.Printf("o %+v\n", o)
}
````

**Comment by faxal** [comment]
I can't think of simple way to fix without resorting to `*bool`. Another way would be to inspect the JSON payload with any json query package and check if value was sent by the user. But then we would need pass around the fact that `Public` flag was set or not.

**Comment by arekkas** [comment]
Hm yeah, actually I think that the PUT command should have the full payload and not mergo at all. What do you think?

**Comment by faxal** [comment]
SGTM, that is more inline with the semantics of PUT. One downside would be backwards compatibility, I can't think of anything else.

**Comment by arekkas** [comment]
I think that's ok, we'll add it to the release notes

**Comment by arekkas** [comment]
@faxal would you mind creating a PR for that? Should be straight forward :)

**Comment by faxal** [comment]
Done #478
