### ISSUE TITLE
Allow configuration of `DB_HOST`, `DB_PASS`, `DB_USER`, `DB_NAME` separately.

### ISSUE THREAD

**Issue by kminehart** [ory/hydra#480]
We're having an issue with the helm chart right now, https://github.com/kubernetes/charts/pull/1022/files#r119681171

With Kubernetes, ideally passwords would be stored as `secret`s.  The problem with using the database URL as the only configurable option means the database password has to be stored in Kubernetes as a value in the deployment, rather than as a secret to be encrypted.*

* yes I know Kubernetes secrets are in plain text at the moment.  That won't be the case forever.

**Comment by 20zinnm** [comment]
@kminehart I don't see why this couldn't be done with the URL right now. If you set these as secrets, then you can interpolate them into the URL (i.e. `DATABASE_URL=postgres://${DB_USER}:${DB_PASS}...`). If the secrets are added as environmental variables, they could in turn be used to configure another environmental variable.

**Comment by arekkas** [comment]
I agree with @20zinnm

**Comment by 20zinnm** [comment]
@arekkas I would consider this closed.

**Comment by kminehart** [comment]
That's true, I had not considered that.  Thanks!
