### ISSUE TITLE
Headers should be case-insensitive

### ISSUE THREAD

**Issue by 20zinnm** [ory/hydra#496]
I'm trying to run Hydra on Kubernetes behind a Google Cloud Engine load balancer with SSL termination, but the load balancer converts headers to lowercase. The RFC ([RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2)) for HTTP/1.1 Message Syntax and Routing says that header fields have a case-insensitive field name.

https://github.com/ory/hydra/blob/79580e1ea9f28ed0298436dc7f8f0e611e8f5f34/config/config.go#L123

**Comment by arekkas** [comment]
I am confident that `r.Header.Get()` follows RFC 7230, otherwise most Go applications would not properly work with http. What issue are you observing exactly?

**Comment by 20zinnm** [comment]
Hydra fails requests through the load balancer because it's seemingly missing X-Forwarded-Proto. However, the docs say that that header is added.

**Comment by arekkas** [comment]
I can't reproduce this:

![image](https://user-images.githubusercontent.com/3372410/26865751-64e8fab6-4b5e-11e7-8f83-93c94a6c0fae.png)


![image](https://user-images.githubusercontent.com/3372410/26865729-4b785d56-4b5e-11e7-9937-fe355b58262d.png)

**Comment by toddams** [comment]
@20zinnm How did you resolve your issue? I'm having exactly the same situation
