### ISSUE TITLE
Question: Read Only DB (specifically warden)

### ISSUE THREAD

**Issue by joshuarubin** [ory/hydra#507]
It would be very helpful to have documented which actions require write access to the db. We would like to globally distribute read only copies of the db to reduce warden latency.

**Comment by arekkas** [comment]
Everything that isn't HTTP GET (/oauth2 endpoint excluded) requires write access. However, I'm not sure if you're not optimizing this prematurely. What issues do you have with warden latency?

**Comment by arekkas** [comment]
@joshuarubin do you have any further questions regarding warden performance? if not, I'll close this issue. By the way, we're working internally on a beefed version of Hydra which will include a caching layer for performance critical endpoints such as the warden. If this is interesting for you ping me on gitter

**Comment by joshuarubin** [comment]
So just to be 100% clear, hydra's `/warden/token/allowed` _does_ require write access because it is a POST request?

**Comment by arekkas** [comment]
You got me, requests to `/warden` (excluding `/warden/groups`) are all read-only, even when POST :)
