### ISSUE TITLE
Could not gracefully run server

### ISSUE THREAD

**Issue by nblum** [ory/hydra#513]
I tried to setup based on the docker image:

`docker run -e "DATABASE_URL=memory" -d --name my-hydra -p 4444:4444 oryd/hydra`

runnying `hydra host` output is

```
INFO[0000] DATABASE_URL set to memory, connecting to ephermal in-memory database. 
WARN[0000] Expected system secret to be at least 32 characters long, got 0 characters. 
INFO[0000] Generating a random system secret...         
INFO[0000] Generated system secret: kctDW&rh3kWMNQrad2(_R<3E-6mi<FC0 
WARN[0000] WARNING: DO NOT generate system secrets in production. The secret will be leaked to the logs. 
INFO[0000] Key pair for signing hydra.openid.id-token is missing. Creating new one. 
INFO[0002] Setting up telemetry - for more information please visit https://ory.gitbooks.io/hydra/content/telemetry.html 
INFO[0002] Key pair for signing hydra.consent.response is missing. Creating new one. 
INFO[0004] Key pair for signing hydra.consent.challenge is missing. Creating new one. 
WARN[0005] No clients were found. Creating a temporary root client... 
INFO[0005] Temporary root client created.               
INFO[0005] client_id: d277410c-2cab-4b9d-88c7-1cba12bbc70c 
INFO[0005] client_secret: /Cc1oj$)Kq5s(x7Y              
WARN[0005] WARNING: YOU MUST delete this client once in production, as credentials may have been leaked in your logfiles. 
WARN[0005] No TLS Key / Certificate for HTTPS found. Generating self-signed certificate. 
INFO[0005] Setting up http server on :4444              
Could not gracefully run server
```
Is there any log to figure out what went wrong?

**Comment by arekkas** [comment]
check if port 4444 blocked somehow

**Comment by nblum** [comment]
I tried to start container without port binding (to prevent used ports on the host system) `docker run -e "DATABASE_URL=memory" -d --name my-hydra oryd/hydra`. 

`netstat -tulpn` (inside the container) shows:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::4444                 :::*                    LISTEN      7/hydra
```
I think this is from the entrypoint which runs the hydra host command initially

**Comment by arekkas** [comment]
#514 will show a more verbose error message which will hopefully help resolve this.

**Comment by arekkas** [comment]
#514 is now merged and released under latest master and 0.9.2 - make soure you're actually pulling the latest version in docker with `oryd/hydra:0.9.2`. Building the docker image usually takes ~20 minutes.

**Comment by nblum** [comment]
perfect, i will try again

**Comment by nblum** [comment]
ok as you expected the error message is: `FATA[0014] Could not gracefully run server               error="listen tcp :4444: bind: address already in use"`

Should it be possible to run `hydra host` inside the docker container again?

**Comment by arekkas** [comment]
You can try to kill off all containers with `docker kill $(docker ps -q)` and then re-run this container, but since this isn't a hydra issue I'm closing this. You can also ask on our Gitter chat channel for help!
