### ISSUE TITLE
Fatal error when running docker container

### ISSUE THREAD

**Issue by drozzy** [ory/hydra#525]
Trying to follow the instructions [here](https://github.com/ory/hydra#5-minutes-tutorial-run-your-very-own-oauth2-environment), and running the command like this:

`docker run -e "DATABASE_URL=memory" -d --name my-hydra -p 4444:4444 oryd/hydra`

The container dies after I try to visit `localhost:4444` or `https://localhost:4444`. 

The `docker logs my-hydra` displays this as the last line:

```time="2017-06-16T00:47:07Z" level=fatal msg="Issuer must use HTTPS unless --dangerous-force-http is passed. To find out more, use `hydra help host`."```

Running docker version "17.03.1-ce" on windows.

**Comment by arekkas** [comment]
```
docker run -e "DATABASE_URL=memory" -e "ISSUER=https://localhost:4444/" -d --name my-hydra -p 4444:4444 oryd/hydra
```

**Comment by torrange** [comment]
Jiggly puff

**Comment by drozzy** [comment]
Ok, seems to not work and not crash.
Getting "404 page not found". Is this expected behavior?

**Comment by arekkas** [comment]
depends on what you're doing or expecting, if you are just calling the root url then yes. I recommend highly that you read the docs. Its all explained there, and has a tutorial

**Comment by drozzy** [comment]
Thanks, I read the docs.

**Comment by arekkas** [comment]
Ok, then I'm not sure what you're expecting at the root as the APIs are all [documented](http://docs.hydra13.apiary.io/) (root is not one of them) and there is no UI in Hydra.

If you haven't, check out the [5 minute tutorial](https://ory.gitbooks.io/hydra/tutorial.html) which might give you an idea of what Hydra actually does.

**Comment by drozzy** [comment]
Sorry, I may have overreacted. But you have to admit 404 is probably not the most straightforward message to display, especially to check that the system is working.

I suggest an index page with "You're up and running - go [here](http://docs.hydra13.apiary.io/#) to read the API docs and here for tutorial."

Also, I actually followed one of the installation instructions [here](https://github.com/ory/hydra/blob/master/docs/install.md), where it says:

> Now, you should be able to open https://localhost:4444. If asked, accept the self signed certificate in your browser.

**Comment by arekkas** [comment]
> Also, I actually followed one of the installation instructions here, where it says:

Perfect, thank you, I set this to `/health` now which gives some info on the running instance :)

> Sorry, I may have overreacted.

Don't worry, all good!

> I suggest an index page with "You're up and running - go here to read the API docs and here for tutorial."

I wanted to do this for some time but the problem is that most companies using Hydra don't want people to know they are using it - due to security reasons. Unless that's configurable it's going to not go well with some people, probably :|
