### ISSUE TITLE
docs: docker --link should be replaced by networks

### ISSUE THREAD

**Issue by drozzy** [ory/hydra#555]
Hey guys.
In the tutorial (https://ory.gitbooks.io/hydra/content/install.html) you use the deprecated `--link` from docker.

I think it should be replaced by the network feature instead: https://docs.docker.com/engine/userguide/networking/#user-defined-networks

This will make tutorial easier to follow for people who don't know about `link`.

**Comment by arekkas** [comment]
Thank you, I took a quick look at networks when writing the guide but it looked like more work to set that up (create network, create container, link container to network, ...). Do you know how to do this? And if yes, would you mind creating a PR?
