### ISSUE TITLE
Open a Patreon account

### ISSUE THREAD

**Issue by drozzy** [ory/hydra#558]
I think you should open a [patreon](https://www.patreon.com/) account, so that some of us can support your work.
Just an idea. Feel free to close.

**Comment by arekkas** [comment]
Thank you for the suggestion! There is one already! :) I should probably place it more visibly :)

https://www.patreon.com/_ory

**Comment by drozzy** [comment]
Yes, on the documentation page and the front page.

**Comment by arekkas** [comment]
this has been done, thank you for your input!
