### ISSUE TITLE
Error on go get the project

### ISSUE THREAD

**Issue by sredXNY** [ory/hydra#560]
Hi, I am currently trying to get the project and compile it by myself. But am facing a serie of errors related with the packages that are used by hydra. As the documentation says, I made: `go get -d -u github.com/ory/hydra` but then I get a lot of errors with many of the libraries, some of them I had them already installed in my environment because I used them in others projects. 

The repetitive error looks like this:

```
cd C:\MygoWorkspace\src\github.com\creator\library; git pull --ff-only
From https://github.com/creator/library
   5381866..d0303fe  master     -> origin/master
Updating 5381866..d0303fe
error: Your local changes to the following files would be overwritten by merge:
        afile.go
        anotherFile.go
        otherFile.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/creator/library: exit status 1
```

I didn't modified that libraries, and they're a lot. I tried  `go get -d github.com/ory/hydra` but then I get (for example):

```
 cd C:\MygoWorkspace\src\golang.org\x\text; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package golang.org/x/text/transform: exit status 1
```

What should I do? how can I make it work?

**Comment by arekkas** [comment]
You could try to remove your go workspace, unfortunately it doesn't look like an error specific to hydra, but some problem with your gopath. Maybe ask on stackoverflow, because I don't really know what the issue is and it doesn't seem to be linked to hydra directly.
