### ISSUE TITLE
Docker hub documentation showing up as HTML

### ISSUE THREAD

**Issue by atrauzzi** [ory/hydra#562]
Seems like the documentation isn't showing up quite right:

![image](https://user-images.githubusercontent.com/115199/28503936-7915f076-6fd4-11e7-9a22-888ed06417af.png)

Further, it might be nice to document all the ports, filesystem points and environment variables of the application in these docs.  Whether that's done as part of the `readme.md` in the repository or a specialized set of instructions for the docker hub registry... Probably up to you :)

**Comment by arekkas** [comment]
Thank you for the report!

**Comment by arekkas** [comment]
This is resolved now
