### ISSUE TITLE
Freemium Crap

### ISSUE THREAD

**Issue by dalu** [ory/hydra#567]
The one coder is very hostile. This is just a setup to grab your money.
Hydra is poorly documented but this is systematic.
The author, when asked by email, said that he would not provide help and that I should ask for commercial support, altough he messaged me privately first on a google groups post and I just responded.

I'd stay away from this unless you'd like to pay lots of money, and if you do then there are better solutions.
The "security" of hydra is also highly doubtful when you have telemetry that phones home.

You've been warned.

**Comment by janekolszak** [comment]
You must be joking... From my experience Hydra's dev is very helpful, Hydra's stable, well documented and as secure as I can review.

There's nothing bad in buying commercial support if you need it, but clearly the concept of paying for work must be foreign to you.

**Comment by arekkas** [comment]
Sorry that you had this experience, I have no idea who you are. This is definitely not a money set up. If you ask for personal support via email, I don't have unlimited time for free personal support. If you don't like he docs, help improve them. Telemetry is well documented and optional. Google Groups has been inactive for months.

Also, please adhere to our contribution guidelines (https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#conduct) or face the consequences mentioned there.

**Comment by arekkas** [comment]
Sorry that you had this experience, I have no idea who you are. This is definitely not a money set up. If you ask for personal support via email, I don't have unlimited time for free personal support. If you don't like he docs, help improve them. Telemetry is well documented and optional. Google Groups has been inactive for months.

Also, please adhere to our contribution guidelines (https://github.com/ory/hydra/blob/master/CONTRIBUTING.md#conduct) or face the consequences mentioned there.
