### ISSUE TITLE
installer: homebrew recipe for macOS users

### ISSUE THREAD

**Issue by Phrohdoh** [ory/hydra#572]
[homebrew](https://brew.sh/) is the defacto package manager for macOS.

The name `hydra` is already taken as a recipe name so perhaps `hydra-oauth2` could be used.

This would make installation and upgrading much simpler for end-users.

**Comment by arekkas** [comment]
I would prefer `ory-hydra` as a name. However, I have little experience with homebrew. If you want and know how to write homebrew recipes I'd love to see that! If so, ping me on [Gitter](https://gitter.im/ory-am/hydra) :)

**Comment by arekkas** [comment]
While this would be nice to have, we do not have the resources to support this. Maybe later we will be able to provide different installation options using homebrew, aptitude, chocolate, ...
