### ISSUE TITLE
`authorization` header in `/oauth2/token` endpoint is case sensitive

### ISSUE THREAD

**Issue by ducky427** [ory/hydra#575]
As noted in [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), HTTP headers are supposed to be case-insensitive.

I've noticed that when getting a token from the `/oauth2/token` endpoint, the `authorization` header needs to be capitalised and not lower case. This is not standard HTTP behaviour.

**Comment by arekkas** [comment]
Hm, that is quite unlikely because we're not using anything custom-made, only regular Go-libraries which are RFC conform. Could you show a reproducible test case?

**Comment by ducky427** [comment]
My bad. I can't seem to produce this.

Thanks!
