### ISSUE TITLE
Feature Request: ability to list all groups

### ISSUE THREAD

**Issue by joshuarubin** [ory/hydra#594]
We are building a management UI around hydra and would like to be able to list all groups in a single API call. Right now we build a list dynamically from the list of clients:
```
for client in range clientList {
    GET /warden/groups?member=client.ID
}
```
and policies:
```
for policy in range policyList {
    for subject in range policy.Subjects {
       GET /warden/groups?member=subject
    }
}
```

This is obviously very inefficient and even wasteful because policy subjects are not necessarily only groups.

This also has the possibility of missing groups because we can only find groups that have a known client id as a member or have a policy listing the group as a subject. We understand that the groups we might miss, orphan groups, necessarily can't have any affect on the system, but it would still be nice to find them. Additionally, it is challenging if we create a group with no members, and then intend to update/create a policy referencing it, the group doesn't show up as being available (e.g. for autocompletion) until after the policy is updated/created.

Thank you very much!

**Comment by arekkas** [comment]
Yeah that makes totally sense!

**Comment by arekkas** [comment]
If you want, you can take a shot at it yourself.

The handler is [here](https://github.com/ory/hydra/blob/master/warden/group/handler.go#L73-L92). You could probably build a check [after here](https://github.com/ory/hydra/blob/master/warden/group/handler.go#L75) to see if `members == ""`. If so, you could run a manager function that implements `ListGroups(limit, offset)`. Then you would have to implement that function in the managers:

* [sql](https://github.com/ory/hydra/blob/master/warden/group/manager_sql.go)
* [memory](https://github.com/ory/hydra/blob/master/warden/group/manager_memory.go)
* [http](https://github.com/ory/hydra/blob/master/warden/group/manager_http.go)

And of course add some test [somewhere around here](https://github.com/ory/hydra/blob/master/warden/group/manager_test_helper.go#L36) where you check if the groups in the manager match the expected amount of groups.

If you don't feel confident with Go you could either ask on Gitter or let me know and I'll try to address it soon (no time guarantees though, sorry).
