### ISSUE TITLE
sql/postgres: wherever limit/offset is used, include ORDER BY clause

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#619]
See https://github.com/ory/hydra/pull/612#discussion_r145348108

**Comment by blockloop** [comment]
I can look into this

**Comment by arekkas** [comment]
Nice! If you need help feel free to ask!

**Comment by zerodivisi0n** [comment]
I can't find any queries with `limit/offset` in **hydra** project in `master` and `v0.9.x` branches. However, I found one in dependent **ladon** project there: [manager_sql.go](https://github.com/ory/ladon/blob/4223d97b7a16808bc1213cc641d529e764e67eea/manager/sql/manager_sql.go#L425). Does it require the fix?

**Comment by arekkas** [comment]
Nice! Yes, that should definitely be updated there!
