### ISSUE TITLE
documentation vague regarding returned client_secret

### ISSUE THREAD

**Issue by abusaidm** [ory/hydra#620]
documentation state that when you update client details using `PUT` `/clients/id` and you provide client_secret, the secret will be returned just this once. but I noticed that the secret is not returned and that a hashed form of the secret is returned.

> If you pass client_secret the secret will be updated and returned via the API. This is the only time you will be able to retrieve the client secret, so write it down and keep it safe.

**Comment by arekkas** [comment]
Thank you, this should be fixed with 0.10.0 however, are you on 0.9.x?

**Comment by abusaidm** [comment]
I am seeing this on the docs `http://docs.hydra13.apiary.io/#reference/oauth2/clientsid/update-an-oauth-2.0-client`

I don't know what version this is!

**Comment by arekkas** [comment]
The docs always match latest master, so it's version 0.10.x. What I meant is that you are probably running a hydra version below 0.10.x which is why you see the issue you describe. This is the patch that fixed this:

https://github.com/ory/hydra/commit/96df49822b1dbce648f324ee699f2ec93bbaea46

**Comment by abusaidm** [comment]
ah I see, thank you. I thought you are referring to the docs version.

**Comment by xiaofei-du** [comment]
Hi, @aeneasr, I am using the Golang SDK `hydra-client-go v1.10.6`, when I patch a client by 

```golang
r, e := client.Admin.PatchOAuth2Client(admin.NewPatchOAuth2ClientParams().WithID(id).WithBody(...)
```
The returned `r.Payload.ClientSecret` is not empty but looks like a hashed form of the secret. Is it an expected behaviour or am I doing something wrong?

Thanks.
