### ISSUE TITLE
docs: adding policy to consent app doesn't work as resource using <.*>

### ISSUE THREAD

**Issue by abusaidm** [ory/hydra#621]
The following line will not work on OSX terminal.
`--resources rn:hydra:oauth2:consent:requests:<.*> \`
it will need to be quoted to work as bash will try interpret:
`--resources "rn:hydra:oauth2:consent:requests:<.*>" \`

**Comment by arekkas** [comment]
Thank you! Can you create a PR for it? The files are in `./docs`
