### ISSUE TITLE
docs: followed the installation guide and was unable to get a successful consent

### ISSUE THREAD

**Issue by abusaidm** [ory/hydra#623]
Hello,

I followed the installation guide `https://ory.gitbooks.io/hydra/content/install.html#perform-oauth-20-flow` and was unable to get a successful run.

The issue seems to come from consent app saying `Unhandled rejection Error: Bad Request`
and
From hydra `level=error msg="An error occurred" error="The client is not allowed to request scope hydra.consent: The requested scope is invalid, unknown, or malformed"`

i have also noticed different versions in the guide so on my last attempt I used the version `v0.10.0-alpha.8` for:
1. hydra migration
2. hydra cli
3. hydra server

I noticed that this gave me an extra migration that was not available in the v0.9.x so I thought this might have been a mistake in the guide.

I will try to diagnose the issue further to see where the complain is from and dig deeper.

Thank you.

**Comment by arekkas** [comment]
Hey, I found the error, it's a typo here:

```
$ hydra clients create --skip-tls-verify \
  --id consent-app \
  --secret consent-secret \
  --name "Consent App Client" \
  --grant-types client_credentials \
  --response-types token \
  --allowed-scopes hydra.consent*
```

specifically

```
  --allowed-scopes hydra.consent*
```

that line should read

```
  --allowed-scopes hydra.consent
```

**Comment by abusaidm** [comment]
Hey,
I got it working thank you.
This turned out to be one part of the problem, the other part is in the the consent app demo `https://github.com/ory/hydra-consent-app-express/blob/master/routes/index.js`.
I changed the following:
`const scope = 'hydra.consent hydra.consent.*'`
to
`const scope = 'hydra.consent'`

and this removed the follwing error:

`level=error msg="An error occurred" error="The client is not allowed to request scope hydra.consent.*: The requested scope is invalid, unknown, or malformed"`

**Comment by arekkas** [comment]
Oh yes absolutely! Would you mind updating that in the consent app as well? Thank you so much for this, you are helping a lot of people!

**Comment by abusaidm** [comment]
no problem.

I wanted to find out where hydra stores its core scopes as I didn't find them in the database, and if I could pick your brains a little to better understand the system when I have question, I would like to write a documentation detailing this and we could publish it if you wanted.

**Comment by arekkas** [comment]
The scopes are stored in this [SQL column](https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go#L32) - and I always welcome docs! :)

**Comment by abusaidm** [comment]
I mean, how does hydra know about hydra.consent ?

**Comment by arekkas** [comment]
They are defined in the http handlers, for example [here](https://github.com/ory/hydra/blob/master/oauth2/consent_handler.go#L21) or [here](https://github.com/ory/hydra/blob/master/client/handler.go#L27-L28).

**Comment by arekkas** [comment]
I hope all your questions are answered and thus closing this issue. If questions remain feel free to come back here.
