### ISSUE TITLE
Support ES256 JWK Algo

### ISSUE THREAD

**Issue by joshuarubin** [ory/hydra#627]
It looks like support for ES256 is available (jwk/generator_ecdsa256.go), but that the JWK handler doesn't support it (https://github.com/ory/hydra/blob/master/jwk/handler.go#L27-L38).

Go's P-256 is implementation is constant-time (which prevents certain types of attacks) while its P-384 and P-521 are not (https://github.com/gtank/cryptopasta).

**Comment by joshuarubin** [comment]
closed in favor of #628

**Comment by arekkas** [comment]
I think we should disable the P521 generator for now, as it's not safe to use them for repeated use in private keys.

**Comment by joshuarubin** [comment]
[RFC7518](https://tools.ietf.org/html/rfc7518#section-3.1) lists ES256 as "Recommended+" meaning:

> The use of "+" in the Implementation Requirements column indicates
   that the requirement strength is likely to be increased in a future
   version of the specification.

I think that the stronger algorithm should continue to be supported.

Also, the [webcrypto](https://w3c.github.io/webcrypto/Overview.html#ecdsa-operations) spec has renamed `ES521` to `ES512`: 

>  If the "alg" field is equal to the string "ES512":
Let algNamedCurve be the string "P-521".

**Comment by arekkas** [comment]
Ok, let's keep them then. As long as JWK/JWT spec talk of ES521 I think we should keep it that way. Definitely doesn't help though that there are naming inconsistencies now.

**Comment by joshuarubin** [comment]
Can you link to the spec which still references ES521?

**Comment by arekkas** [comment]
My bad, looks like I got mixed up, it's definitely ES512

**Comment by arekkas** [comment]
I closed this because ES512 is now tracked in #651
