### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by stijndehaes** [ory/hydra#669]
Hi,

We are using hydra in our production environment on kubernetes. We have some small issues with hydra at the moment and want to investigate further. Our stack uses prometheus for monitoring.

For prometheus monitoring we would like and endpoint that exposes the current metrics in valid prometheus format. I would propose an another endpoint /health/prometheus.

Does that seem allright with you? Will you implement this or are you expecting a PR.

Kind Regards,
Stijn De Haes

**Comment by arekkas** [comment]
How stable is the Prometheus protocol/payload you would like to include?

**Comment by arekkas** [comment]
Is it possible to pipe stdout/stderr to prometheus instead?

**Comment by elliots** [comment]
Apologies for the +1 but metrics for prometheus would be great for us too.

**Comment by sboulkour** [comment]
Hey @arekkas, regarding the stability of the Prometheus protocol, it is currently the de facto standard for kubernetes deployments. Prometheus and Kubernetes are part of the CNCF (https://www.cncf.io/) and are here to stay for some time from my point of view.

**Comment by arekkas** [comment]
If anyone wants to tackle this, I'm open to discuss it and review PRs :)

**Comment by arekkas** [comment]
Solved on master, see #827
