### ISSUE TITLE
Json logging

### ISSUE THREAD

**Issue by stijndehaes** [ory/hydra#670]
Hi,

We are using hydra in our production environment on kubernetes. We have some small issues with hydra at the moment and want to investigate further. Our stack uses fluentd + elasticsearch for log collection.

For this it would be easy if the logs could be exposed in a JSON format. Is this possible at the moment? Or does the code need to be updated.

If you can point me in the right direction and if it is not too hard I would be happy to make a PR.

Kind Regards,
Stijn De Haes

**Comment by arekkas** [comment]
```
hydra help host | grep log
- LOG_LEVEL: Set the log level, supports "panic", "fatal", "error", "warn", "info" and "debug". Defaults to "info".
- LOG_FORMAT: Leave empty for text based log format, or set to "json" for JSON formatting.
```

**Comment by Vikash-novo** [comment]
What is the location of the file that Hydra using to store the logs?
I want to export these logs into kibana, is there a way we can do that?
