### ISSUE TITLE
oauth2: Reintroduce audience claim

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#687]
It is not possible to set the audience claim in the consent acceptance payload, and it's not possible to retrieve it using the warden API, nor the introspection API. To add it, it must probably be introduced as part of the session.

**Comment by someone1** [comment]
The session seems [to persist](https://github.com/ory/hydra/blob/master/oauth2/fosite_store_sql.go#L167) the request.Form so maybe this can already be done with slight modification of the challenge session persistence?

If a request comes to the `/oauth2/auth` handler with an `audience` URL parameter (in addition to the client_id, state, redirect_uri, etc. like [Auth0 does](https://auth0.com/docs/api/authentication?javascript#implicit-grant)), then this can be persisted in the [ConsentRequest](https://github.com/ory/hydra/blob/master/oauth2/consent_manager.go#L20) and returned as part of the [Session](https://github.com/ory/hydra/blob/master/oauth2/consent_strategy.go#L103).

Side note, it looks like hydra is treating every auth request as an OpenID Connect request? Unless `scope=openid` is specified, you do not need to force the `aud=client_id` behavior. All Sessions seem to be represented internally as fosite [openid.DefaultSessions](https://godoc.org/github.com/ory/fosite/handler/openid#DefaultSession). I don't think this impacts anything but was confusing to me as I was trying to use hydra's handlers and wanted to use JWT tokens but got an OpenID token instead.

**Comment by someone1** [comment]
Depending on how issue #772 is implemented, this might be rolled up into those changes?
