### ISSUE TITLE
cmd: Add newsletter info and sign up

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#755]
We should add two reminders to sign up for the hydra newsletter.

* [ ] When running `hydra connect`, the third question should be "Enter email address to receive emails on important updates: [enter email here]" (or some similar wording). Once an email was entered, it should be added to mailchimp using mailchimp's API. The command should not ask again about this.
* [ ] When running `hydra host` we should show a warning in the logs right before the HTTP server starts (so it's visible) with something like: "Receive updates on critical patches and new releases by clicking here: <link to mailchimp>"

**Comment by zepatrik** [comment]
Is there some central storage, like a `.hydra` config file in `~` so I can check whether an email address is already submitted?

**Comment by arekkas** [comment]
Yes:

* Storing the configuration is, for example, done here: https://github.com/ory/hydra/blob/master/cmd/connect.go#L57
* Retrieving the configuration is automatic and accessible through, for example [`c.ClientID`](https://github.com/ory/hydra/blob/master/cmd/connect.go#L43). To add a field to this configuration, you must add a field [here](https://github.com/ory/hydra/blob/master/config/config.go#L51)

I'd say that the host process should always show that info, and connect only if it has not been entered yet.

**Comment by zepatrik** [comment]
Yes, then someone else looking into logs could also sign himself up, good point.
Is it better to store only whether it is submitted or which email address? I think a boolean would be sufficent

**Comment by arekkas** [comment]
I agree, it has less attack surface for leaking email addresses

**Comment by arekkas** [comment]
Resolved
