### ISSUE TITLE
docker: Add image capable of loading policies/clients/jwks from an init.d directory

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#760]
Currently, hydra is able to detect if an installation is new or not by [checking if a client exists in the database already](https://github.com/ory/hydra/blob/v0.11.4/cmd/server/handler.go#L195). If so, the following tasks are executed:

1. A new [root client](https://github.com/ory/hydra/blob/v0.11.4/cmd/server/helper_client.go#L73) is generated with random credentials (can be changed with an environment variable)
2. A [policy for said client is generated](https://github.com/ory/hydra/blob/v0.11.4/cmd/server/helper_client.go#L86). It allows the client to do anything in hydra (thus "root" client)

~We should update this part and add a couple of things:~

1. ~We should rename [the method](https://github.com/ory/hydra/blob/v0.11.4/cmd/server/helper_client.go#L29) doing this to "initializeNewInstallation" and move it to `installation_helper.go`~
2. ~If a new installation is detected, root client and policy are generated as before~
3. ~We look in `<project-root>/init.d/policies` for policies (json formatted) and in ``<project-root>/init.d/clients`~

**Comment by arekkas** [comment]
Actually, it would be much better to have a docker image which is capable of doing that using the hydra CLI!

**Comment by pnicolcev-tulipretail** [comment]
Throwing together a dockerized go app to use the SDK to bootstrap initial clients was really easy, but this would be super convenient.

**Comment by arekkas** [comment]
Examples how to do that are now at https://github.com/ory/examples
