### ISSUE TITLE
sdk: PHP sdk missing from releases

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [ory/hydra#781]
The php sdk folder is absent from the releases tags: 
https://github.com/ory/hydra/tree/v0.11.6/sdk

Current workaround is to target `dev-master` in composer.

**Comment by arekkas** [comment]
Whoops, I totally forgot about this issue - thanks for reminding me in the survey :)

**Comment by pnicolcev-tulipretail** [comment]
Using dev-master will work until the api has a breaking change. Another workaround is to compose in a specific git SHA, like `"ory/hydra": "dev-master#4125eabb96cae588eeb8336c21a48b93b6e9a0b3"`

**Comment by pnicolcev-tulipretail** [comment]
This has been fixed as of 0.11.9 :)

**Comment by arekkas** [comment]
Closing this because it's resolved (afaik)
