### ISSUE TITLE
Don't push to coveralls in CI when PR comes from fork

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#782]
See https://circleci.com/gh/ory/hydra/1225?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by arekkas** [comment]
So the issue is that forked repos also try to push to coveralls, which fails, as the forked repo is not registered at coveralls. There are two ways to fix this:

1. See if we can add a check based on [Circle CI's environment variables](https://circleci.com/docs/2.0/env-vars/#build-details) that prevents coveralls push when we're building a fork. **(preferred option)**
2. Don't fail the tests when coveralls push fails. This should be the fallback option that we use if 1 fails.

**Comment by zepatrik** [comment]
Does goveralls run the test or is it in it's own command? Is replacing [this line](https://github.com/ory/hydra/blob/master/.circleci/config.yml#L41) with something like
```bash
[ -z "$CIRCLE_PR_NUMBER" ] && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"
```
enough?

**Comment by arekkas** [comment]
It doesn't run the test suite in our case - so something like that should work. But I still want code coverage for PRs, just not for the ones from forked repos :)

**Comment by arekkas** [comment]
Ah nice! I missed that :)

**Comment by arekkas** [comment]
Actually, maybe removing the repotoken is already enough!

> For a public github repository, it is not necessary to define your repository key (COVERALLS_TOKEN).

Can you try that (without `[ -z "$CIRCLE_PR_NUMBER" ] && `)?
