### ISSUE TITLE
Feature Request: oauth2/token endpoint json payload option

### ISSUE THREAD

**Issue by sandrom** [ory/hydra#786]
Would it be possible to consider respecting the Content Type like application/json in the POST oauth2/token request? currently it seems only to support forms and I am aware that the IETF explicitly only specified them. Problem is, because everyone somehow does json, so do the customers and does the old implementation here, so I am either putting yet another service in front of hydra just to translate json to forms, or hydra can directly understand json. It would be awesome, if that could be considered.

**Comment by arekkas** [comment]
Thank you for your suggestions. We want to keep Hydra as close to the spec as possible and not introduce any custom features for those specs. Customers should not be using their own code anyways and use well-tested open source libraries for interacting with oauth2. In conclusion, this request will not make it into hydra, sorry!

**Comment by sandrom** [comment]
@arekkas While I understand your point, hope vs reality is different beasts at time. For us here its not possible to change from json easily as changing anything the customers are currently doing is a big issue and they do json right now. One battle at a time. Furthermore its not that uncommon to use json for doing exactly that, see https://auth0.com/docs/api-auth/tutorials/client-credentials

While I understand, that its possibly not favorite, for us using hydra means just adding a service in front to translate from json to forms if that feature can not be mapped by hydra and I see already people questioning the use of hydra then. The age old problem of kiss vs reality. :(

**Comment by arekkas** [comment]
ps: If you find a IETF/OpenID spec which either allows extension of body payloads for those endpoints, or specifically mentions json I'd be open to add it.

**Comment by sandrom** [comment]
funny, that API article was already posted by our team as one of the many desperate attempts to introduce some kind of any version management around, which currently is non-existent. tell me about it :)

anyway, no problem, we can solve it and I know where you're coming from standing for that (usually it's one of us waving IETF specs around that should be considered instead of another ruby-halfbaked-iknoweverythingbetter-solution). Just had to make sure as there are still many other battles to fight and our time is simply rather limited. I'd also rather get rid of simple client_credentials flows generally, but that's another story altogether.

nevermind and thank you a lot for taking the time!

**Comment by arekkas** [comment]
You're welcome, and good luck with fighting the battles ;)

You probably don't need to implement that on your own, I think API Gateways such as Kong support request transforms out of the box - maybe there's some json to form plugin available already

**Comment by sandrom** [comment]
api gateway? :D but yes, maybe it's about time to have an urgent reason for one! ;) could be worse. fortunately naming is exactly the same, so converting it will be simple, just one more dependency to test :)

**Comment by arekkas** [comment]
It is encouraged to run hydra behind an api gateway anyways, at least something capable of handling TLS termination

**Comment by sandrom** [comment]
I know! but...well I am fighting for it for a while :D still enough time, so I am quite confident there will be one, once it is live
