### ISSUE TITLE
oauth2: Remove exp and iat from ID token header

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#787]
```
{
  "alg": "HS256",
  "iat": 1519302684,
  "exp": 1519306284
}
```

**Comment by mdziemianko** [comment]
seems like that might break compatibility with some standard python librariees like flask oidc (it uses itsdangerous see https://github.com/pallets/itsdangerous/blob/master/itsdangerous.py)

**Comment by arekkas** [comment]
It doesn't belong there though, the [spec](https://tools.ietf.org/html/rfc7519#section-4.1.4) clearly puts it in the JWT claims.

**Comment by arekkas** [comment]
It wasn't a bug in hydra but the mentioned library instead.
