### ISSUE TITLE
Can you build an identity provider with hydra or not?

### ISSUE THREAD

**Issue by pholisma** [ory/hydra#789]
![image](https://user-images.githubusercontent.com/4893589/36553092-718e3528-17c9-11e8-97d1-f32708bdca07.png)
![image](https://user-images.githubusercontent.com/4893589/36553143-95c831c8-17c9-11e8-9c94-3ccb10071ae9.png)
These seem to contradict each other.

**Comment by arekkas** [comment]
The wording is indeed a bit confusing. Hydra does not manage identities (user login, logout, password reset), but with OpenID Connect you can become an identity provider for third parties (think Google SSO) - you still need your own identity management though.

**Comment by mderazon** [comment]
@arekkas Can I use Hydra to authenticate my own app's users via OIDC ? In such case, would I still have to show a consent screen to the user ? Doesn't make much sense if I have a sign up page for my own service and in the sign up / sign in flow I show the users a consent screen

**Comment by arekkas** [comment]
You can skip the consent screen for first party clients.

**Comment by arekkas** [comment]
Tracked as https://github.com/ory/hydra/issues/789
