### ISSUE TITLE
oauth2: Allow multiple audience claims on ID token

### ISSUE THREAD

**Issue by lsthornt** [ory/hydra#790]
In our setup, we have a backend and frontend service that are both issued different client ids.

Once logged into the frontend service, we have an ID token with `{aud: "frontend"}`, but it cannot be used to make requests to the backend service, because the `aud` claim must match the client_id of the backend service.

OpenID Connect claims docs:
> **aud**
> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

Looks like #314 took care of making the claim an array, so presumably this would involve an addition to `AcceptOAuth2ConsentRequest`, potentially just a special case for when `aud` is included in `Access/IdTokenExtra`?

**Comment by arekkas** [comment]
Sorry for my silence on this, but we tracked this issue internally and will address it with the 1.0.0 release!

**Comment by aeneasr** [comment]
This is tracked as #883

**Comment by aeneasr** [comment]
Regarding string/array - array MUST be supported according to spec. String MAY be supported, see JWT spec:

>  In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.  The
   interpretation of audience values is generally application specific.
   Use of this claim is OPTIONAL.

**Comment by OvermindDL1** [comment]
> Regarding string/array - array MUST be supported according to spec. String MAY be supported, see JWT spec:

Yep, I've already submitted a PR to them.  Just curious if there is a way to just send a single string regardless when there is only a single string in the array, at the very least it lowers processing and network time every so tiny slightly.  :-)

**Comment by OvermindDL1** [comment]
I think that was a similar issue the library itself had, they ended up writing their own (obviously incomplete) JWT handler, my fix for this issue for them is at:  https://github.com/markbates/goth/pull/240
