### ISSUE TITLE
A way to skip the consent screen for certain clients (first party)

### ISSUE THREAD

**Issue by nigeltiany** [ory/hydra#791]
Is there a way to skip the consent screen for first-party clients? What is the best way of handling first-party apps with hydra?

**Comment by pnicolcev-tulipretail** [comment]
This is more of a question than a feature request, I don't think issues is for questions.

But currently yes, because you write the consent app yourself you can determine on your own if an app is first-party and doesn't require consent.

**Comment by arekkas** [comment]
That is correct @pnicolcev-tulipretail :)

**Comment by nigeltiany** [comment]
Just came across this https://github.com/ory/hydra/issues/772. It sights a use case for first party apps that i think will be nicer.
