### ISSUE TITLE
docker: Build time always return time.Now()

### ISSUE THREAD

**Issue by ManassehZhou** [ory/hydra#792]
it seems in 

https://github.com/ory/hydra/blob/master/cmd/root.go#L37:14

it seems this should change into some random string...

![screenshot_20180225163452](https://user-images.githubusercontent.com/2705803/36639547-d8c295ea-1a49-11e8-9755-b73e5014dffd.png)

**Comment by arekkas** [comment]
I suppose this is docker, right?

**Comment by ManassehZhou** [comment]
Yes, and it can reappear in the latest release on docker hub and my own build
