### ISSUE TITLE
Moving the access control engine to Oathkeeper

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#807]
We have learned a lot over the last year in terms of how ORY Hydra is being used. Initially, we wanted to avoid the problems facing popular databases like MongoDB or others, which did not include authentication for their management APIs.

For this reason, the Warden API was born and primarily used internally and exposed via HTTP. We learned that access control policies are well received, but also add additional complexity to understanding the software. While we firmly believe that these policies implement best practices for access control in complex systems, we do understand that they add a barrier to getting started with ORY Hydra.

For this reason we are planning on moving the Warden API from this project to [ORY Oathkeeper](https://github.com/ory/oathkeeper) or potentially it's own server. We would add a migration path for existing policy definitions to the new service. The default docker image would combine the services in such a way, that ORY Hydra is protected. We would additionally have an (insecure) docker image without authentication which can be used for testing.

This also opens up the possibility of having more access control mechanisms than access control policies. For example, we can add ACL and RBAC and other mechanisms too.

Please let us know what you think of this idea!

**Comment by bogdanvarlamov** [comment]
I definitely like the Warden API. If it is being developed on it's own and enhanced with additional functionality, I like that too. I would just hope that few functionality doesn't make it more complicated to get started using it--sometimes that happens when there are 300 pages of docs for the 20 ways to do something, and it's just too many options.

**Comment by arekkas** [comment]
That's absolutely sensible. There should definitely be a standard way of solving it without digging through a ton of documentation. Maybe like a standard docker image with default policies and protection.

I'll have to think a bit more about deployment complexity and so on.

**Comment by arekkas** [comment]
Ok, so I thought about this a bit more.

First I think it makes good sense to move this functionality into a separate service and remove the warden calls internally completely. The reason being that not everyone wants to rely on Hydra's access control. Sometimes it's enough to use a gateway in front and require e.g. an API key for management or whatever. New adopters are always baffled by complexity involved with policies and scopes. Removing that from the core could really help. The user survey has also shown that this stuff is quite complex and opinionated.

The idea is to have a separate service which is basically ladon as a HTTP API. I think it makes sense to add some functionality to resolve access tokens so it would basically be very similar to the current warden API - probably even equal. There would definitely be some backup mode where hydra's database tables and migrations are used as to make migration as easy as possible.

Then, we would ship docker images and example set ups where different configurations are shown. One of the configurations would be the current one, so basically what we have now in hydra but with the three services combined in one image.

**Comment by arekkas** [comment]
done!
