### ISSUE TITLE
consent app: Restart consent flow

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [ory/hydra#809]
We have a situation (on a mobile client) in which users can idle for indefinite periods on the login page (when the device is locked or after logout, for example). This results in the consent expiring (and CSRF cookies, and that sort of thing expiring as well) and makes login impossible unless users start the consent flow from the beginning. 

I'm requesting that we have a way to get the initial hydra request URL via the consent id. Our consent app can then have a javascript timer that sends users back to restart the flow if they idle for too long.

**Comment by arekkas** [comment]
What you're looking for is the redirect URL - just remove the consent query parameter :)

**Comment by pnicolcev-tulipretail** [comment]
I don't follow. All I have at the consent stage is the consent_id. Introspecting that will give me these details (the golang sdk docs have a broken link to this struct so I'll post the php one)
https://github.com/ory/hydra/blob/master/sdk/php/swagger/docs/Model/OAuth2TokenIntrospection.md

But I can't rebuild the original request from that. If I query about redirect_uris belonging to the client I could have several.

**Comment by arekkas** [comment]
The consent id is used at the consent endpoint. The SDK docs are terrible :( The consent request response contains the redirect url which you can use!

**Comment by arekkas** [comment]
Apparently there were issues with the API docs - first the link was broken and second some of the swager models did not show up. I fixed that now, so the response docs look like that now:

![image](https://user-images.githubusercontent.com/3372410/37554416-63560ba4-29d8-11e8-9f4d-539734f450bc.png)

There you see the redirectUrl - it's the parameter you're looking for. Just make sure to remove the consent parameters.

**Comment by pnicolcev-tulipretail** [comment]
Hmm, okay! Thanks. I'll also need state, if that's not included there. Will check on monday.

**Comment by arekkas** [comment]
It's included!

**Comment by pnicolcev-tulipretail** [comment]
Updating here for some discussion.

As of hydra 0.11.12, Hydra's behaviour is such when a consent expires it does not report an error when the consent app confirms it. We're using consent code identical to what's in the golang demo app here: https://github.com/ory/hydra-consent-app-go/blob/master/main.go#L135-L141
Hydra returns a 204 though, regardless of whether the consent has expired or not.

Here's a timeline starting from the 204 response on the consent confirmation
```
time="2018-04-13T18:53:42Z" level=info msg="completed handling request" measure#https://example.com/auth.latency=17446989 method=PATCH remote=... request=/oauth2/consent/requests/85a7b5ff-e0ee-40ed-be0b-fc85b5215aae/accept status=204 text_status="No Content" took=17.446989ms
time="2018-04-13T18:53:42Z" level=info msg="started handling request" method=GET remote=… request="/oauth2/auth?scope=openid&state=d15c419f662335bfc70bb0f05d0c8b1a&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fexample.com%2Frp%2Fexchange&client_id=rp-id&consent=85a7b5ff-e0ee-40ed-be0b-fc85b5215aae&consent_csrf=1d8bd9c9-8247-4931-ab3e-f862f8b4b9d8"
time="2018-04-13T18:53:42Z" level=error msg="An error occurred" error="Consent session expired"
time="2018-04-13T18:53:42Z" level=info msg="completed handling request" measure#https://example.com/auth.latency=12050123 method=GET remote=… request="/oauth2/auth?scope=openid&state=d15c419f662335bfc70bb0f05d0c8b1a&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fexample.com%2Frp%2Fexchange&client_id=rp-id&consent=85a7b5ff-e0ee-40ed-be0b-fc85b5215aae&consent_csrf=1d8bd9c9-8247-4931-ab3e-f862f8b4b9d8" status=302 text_status=Found took=12.050123ms
```

I guess that 204 should be a 400-level response. 

Since our consent app maintains sessions, we can work around this problem by asking users to restart the login flow at which point they're remembered by the consent app and don't need to enter credentials, however I understand Hydra's going to be taking over that responsibility in the long run. If you're doing that, perhaps you can remove the need for consent id's to expire? At least not before a user's session cookie does.

**Comment by arekkas** [comment]
Yeah it should be a 400 response, it will be included in the next release with the refactored consent flow

**Comment by arekkas** [comment]
The new consent flow is capable of doing that, but it hasn't been properly implemented yet - still tracking.

**Comment by arekkas** [comment]
This is resolved on master
