### ISSUE TITLE
docs: Link to php sdk README is wrong

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [ory/hydra#811]
Page: https://www.ory.sh/docs/guides/1-hydra/7-sdk/3-php

grep for " the full API docs"

Link points to https://github.com/ory/hydra/blob/master/sdk/js/hydra/swagger/README.md

Should be https://github.com/ory/hydra/blob/master/sdk/php/swagger/README.md

**Comment by arekkas** [comment]
The source resides here: https://github.com/ory/docs/tree/master/guides/1-hydra/7-sdk :)
