### ISSUE TITLE
Does warden groups work with internal Hydra APIs?

### ISSUE THREAD

**Issue by bdudelsack** [ory/hydra#823]
I'm trying to create a group of superadmins which members can access the Hydra API but it does not work. 

Am i understanding right that the internal Access Controll of Hydra API does not support subjects like "groups:..." and only work with user IDs?

Sample policy:

```json
{
    "id": "group-superadmins",
    "description": "Allow everyhting for members of the superadmin group",
    "subjects": [
        "groups:superadmins"
    ],
    "effect": "allow",
    "resources": [
        "rn:hydra:<.*>"
    ],
    "actions": [
        "<.*>"
    ],
    "conditions": {}
}
```

**Comment by bdudelsack** [comment]
That works. Thank you!

**Comment by arekkas** [comment]
Reopening, because you're the third or fourth person having that misconception. Should be fixed in the docs.

**Comment by arekkas** [comment]
Ok, so this has changed significantly over the past few weeks as access control is now optional and configured via oathkeeper and keto. I'll update the docs before the release.
