### ISSUE TITLE
Error 1406: Data too long for column 'subject' at row 1

### ISSUE THREAD

**Issue by JesseFinch** [ory/hydra#829]
looks like new oauth2 have some troubles with subject field.
for example
```
An error occurred: Error 1406: Data too long for column 'subject' at row 1
```
for following oauth2 tables hydra_oauth2_access/hydra_oauth2_code/hydra_oauth2_oidc/hydra_oauth2_refresh/  of subject field.

At the same time, the hydra_consent_request table has a dimensionless field.

**Comment by arekkas** [comment]
How long is your subject id?

**Comment by JesseFinch** [comment]
427 characters

**Comment by arekkas** [comment]
Well, that's to long unfortunately, max is 255 characters. Keep in mind that this column will be indexed in the future, so

1. longer keys are not possible
2. the longer the key the lower the index performance and the larger the index

**Comment by JesseFinch** [comment]
so my question is why `hydra_consent_request` table has a dimensionless subject field?

**Comment by arekkas** [comment]
Yeah, that will be fixed with 1.0.0 as we need that field indexed in order to remove all access tokens of a user, for example.

**Comment by JesseFinch** [comment]
oh, it.s ok. but where should i store my JWT? 👑

**Comment by arekkas** [comment]
Don't store a JWT as the subject field. The subject field should be a user id in clear text (or hashed to anonymize). If you need extra data use the `extra` fields in the consent request.

Closing because question answered.

**Comment by JesseFinch** [comment]
thx
