### ISSUE TITLE
Duplicate client creation results in 500

### ISSUE THREAD

**Issue by njnygaard** [ory/hydra#835]
I would like to be able to ensure that each of the Hydra clients and policies exist every time we deploy production. When a client is created, I get a 201. When I try to create the same client again, I get a 500. What is the rationale for not returning 409, or 304?

```
hydra clients create \
> --config /home/web/.hydra.yml \
> --skip-tls-verify \
> --id "TESTING_CLIENT" \
> --secret "super-secret" \
> --name "TESTING CLIENT" \
> --grant-types "client_credentials,introspect" \
> --allowed-scopes "hydra hydra.warden hydra.* hydra.introspect";
You should not provide secrets using command line flags. The secret might leak to bash history and similar systems.
OAuth2 client id: TESTING_CLIENT
OAuth2 client secret: super-secret
```

Then again with the same call.

```
hydra clients create \
> --config /home/web/.hydra.yml \
> --skip-tls-verify \
> --id "TESTING_CLIENT" \
> --secret "super-secret" \
> --name "TESTING CLIENT" \
> --grant-types "client_credentials,introspect" \
> --allowed-scopes "hydra hydra.warden hydra.* hydra.introspect";
You should not provide secrets using command line flags. The secret might leak to bash history and similar systems.
Command failed because status code 201 was expeceted but code 500 was received.
```

I was asked to create this issue by @arekkas in the Discord chat.

```
hydra version
Version:    v0.10.10
Git Hash:   1d1b945494c14ac048d3d6040661c9bf7c761593
Build Time: 2018-05-01 14:56:48.457237963 +0000 UTC
```

Should this be tested on a newer version?

**Comment by arekkas** [comment]
Yeah it definitely should return 409. The problem right now is that each database driver has different error codes and also error types for a primary or unique key constraint violation. Matching that is simply not done at the moment but by solving that, we would essentially solve this issue as well. If you want, feel free to give it a shot.

Check, for example, the [`PG`](https://godoc.org/github.com/lib/pq#PGError) error type as well as the specific [error code](https://github.com/lib/pq/blob/d34b9ff171c21ad295489235aec8b6626023cd04/error.go#L178) which I think would be thrown when this happens. I guess MySQL will work similarly.

**Comment by arekkas** [comment]
This should be resolved on master
