### ISSUE TITLE
Allow configuring consent URL per client

### ISSUE THREAD

**Issue by MOZGIII** [ory/hydra#837]
We need to have very different consent flows based on what client initiated the authentication. It is not possible to configure it currently, so we have to run multiple hydra servers.
Can we add the ability to customize consent URL at client level?

**Comment by MOZGIII** [comment]
Found this: #416

That thread has a quite elegant solution: actually implement a single consent app and in it read the consent authorization request, verify it, map the client (we have the `clientId` at the response from `/oauth2/consent/requests/{id}`) to the correct consent URL, and redirect the user agent to a client specific consent request page. This is much better than just allowing custom consent URLs from the security standpoint.

**Comment by arekkas** [comment]
Just check for the client id in your consent app and act accordingly ;)

**Comment by arekkas** [comment]
Whoops, missed in my emails that you already found a solution and also closed it!
