### ISSUE TITLE
REST API /clients limit & offset bug

### ISSUE THREAD

**Issue by 4ichpich** [ory/hydra#838]
The limit and offset parameters have no effect in the rest api.
`{url}/clients?limit=1&offset=1` still returns all clients

**Comment by arekkas** [comment]
Which version are you on?

**Comment by 4ichpich** [comment]
Version:    dev-master
Git Hash:   undefined
Build Time: 2018-05-02 11:54:47.033295477 +0000 UTC m=+0.004540814

it's was from docker oryd/hydra:latest
I can't tell what version it was excactly

**Comment by arekkas** [comment]
Ok, it's definitely an older version - `oryd/hydra:latest` doesn't exist an dif the build doesn't show the right version it's definitely outdated. Use `v0.11.12`

**Comment by 4ichpich** [comment]
The bug is still existing in v0.11.12
I'm using `v0.11.12-alpine`

**Comment by arekkas** [comment]
Yeah, my bad, it has actually landed in master (which is not the 0.11 release branch but prepares the 1.0.0 release). There it will work (and has tests too).
