### ISSUE TITLE
security: add HttpOnly cookie flag

### ISSUE THREAD

**Issue by pnicolcev-tulipretail** [ory/hydra#847]
This is being recommended per OWASP https://www.owasp.org/index.php/HttpOnly

**Comment by arekkas** [comment]
This is solved in [1.0.0](https://github.com/ory/hydra/blob/1.0.x/consent/strategy_default.go#L222-L226) (and also [here](https://github.com/ory/hydra/blob/1.0.x/consent/helper.go#L59))

**Comment by arekkas** [comment]
If you want to address this in < 1.0.0 please let me know and I'll reopen
