### ISSUE TITLE
consent: Add ability to specify Access Token Audience

### ISSUE THREAD

**Issue by aeneasr** [ory/hydra#883]
Currently, the audience of the ID Token is set explicitly in the oauth2 handler:

```
	// done
	response, err := h.OAuth2.NewAuthorizeResponse(ctx, authorizeRequest, &Session{
		DefaultSession: &openid.DefaultSession{
			Claims: &jwt.IDTokenClaims{
				Audience:    authorizeRequest.GetClient().GetID(),
				Subject:     session.ConsentRequest.Subject,
				Issuer:      h.IssuerURL,
				IssuedAt:    time.Now().UTC(),
				ExpiresAt:   time.Now().Add(h.IDTokenLifespan).UTC(),
				AuthTime:    session.AuthenticatedAt,
				RequestedAt: session.RequestedAt,
				Extra:       session.Session.IDToken,
			},
			// required for lookup on jwk endpoint
			Headers: &jwt.Headers{Extra: map[string]interface{}{"kid": h.IDTokenPublicKeyID}},
			Subject: session.ConsentRequest.Subject,
		},
		Extra: session.Session.AccessToken,
	})
```

and the audience of the access token is set by the extra session. Instead, the audience should be a first-class citizen of the consent flow/responses for both ID and access token.

**Comment by arekkas** [comment]
Actually, the audience should probably be defined by the client making the request, not the consent endpoint.

**Comment by bbulczynski** [comment]
How would you suggest to do that? Maybe using claims and setting value?

**Comment by aeneasr** [comment]
Not sure yet, needs investigation

**Comment by Aggouri** [comment]
> While modifying the audience of an ID Token is not desirable, specifying the audience of an OAuth 2.0 Access Token is.
> ORY Hydra implements this feature, which is not defined as an IETF Standard but is
considered good practice in certain environments.
> 
> To use the audience feature, you must specify the intended audiences in the OAuth 2.0 Client's metadata on a per-client basis:

While I don't necessarily have the best writing skills, I think this would be slightly more clear:

> While modifying the audience of an ID Token is not desirable, specifying the audience of an OAuth 2.0 Access Token is. This is not defined as an IETF Standard but is considered good practice in certain environments. 
> 
> For this reason, Hydra allows you to control the `aud` claim of the access token. To do so, you must specify the intended audiences in the OAuth 2.0 Client's metadata on a per-client basis:

**Comment by bbulczynski** [comment]
1. How do you plan to alter pairwise subject functionality to cooperate with that?
2. Do you mind interchangeability of id_token between clients?
3. How about client deciding about which of his auds should be visible to other? I think aud content should be decided per client by user on consent page.

**Comment by aeneasr** [comment]
> How do you plan to alter pairwise subject functionality to cooperate with that?

Not related IMHO

> Do you mind interchangeability of id_token between clients?

Not sure what you mean by that?

> How about client deciding about which of his auds should be visible to other? I think aud content should be decided per client by user on consent page.

Depends on your understanding of audience. It can be user granted or defined per client. The audience is not officially specified nor is how you authorize audience.

**Comment by aeneasr** [comment]
> Do you think that id token could be shared between clients from aud list? Otherwise bother putting list of aud into token, ok client can check if that is intended for him, but why put there other aud values? I could imagine situation where third parties share id token, that is signed and can be verified, and pass information about user among themselves that way.

Personally, I think it could be shared. However, this will not be addressed as part of this PR. The access token audience is the real deal, requests/use cases for oidc audience have not come up yet.

**Comment by aeneasr** [comment]
Thank you @Aggouri for the correction, updated in the docs!

**Comment by bbulczynski** [comment]
OK, thanks for sharing.

**Comment by ErwinSteffens** [comment]
@aeneasr 

> We're defining one or more audience matching strategies (e.g. exact, wildcard, ...)

Was the wildcard part also implemented? Not finding anything in the documentation about this.
