### ISSUE TITLE
Incorrect CORS-related env vars parsing

### ISSUE THREAD

**Issue by MOZGIII** [ory/hydra#886]
Consider this code:
https://github.com/ory/hydra/blob/56aa5d267f541472958ab368143022671b65cbcc/cmd/server/handler.go#L57-L60

When a missing or empty `CORS_EXPOSED_HEADERS` is being parsed, the result contains an array with a single element - empty string, instead of it being an empty array.
Same applies to the rest. This breaks how CORS are handled.

**Comment by arekkas** [comment]
Thank you for reporting this, it's a bug indeed (caused by strings.split always returning at least one element, an empty string)
