### ISSUE TITLE
Extend status page to check dependencies.

### ISSUE THREAD

**Issue by husio** [ory/hydra#887]
I would like to propose an enhancement for hydra's status page functionality.

[Current `/health` endpoint implementation](https://github.com/ory/hydra/blob/master/health/handler.go#L68-L72) has hardcoded "OK" response. I does not report any issues, even if hard dependency is not available (for example, used storage engine is not available). 

It would like to extend status page with dependencies check. Return "OK" only if all core components are functional.

In current state, there is no way to properly monitor hydra's health. One could try to do this by observing all API calls, but this could produce false positives when API calls are failing due to client's mistakes. Updating health endpoint to report service health including health status of all hard dependencies will make returned information more reliable. 

Is this something that can fit into current development plans? Can it be accepted together with a pull request implementing such functionality?

**Comment by arekkas** [comment]
Absolutely valid request, PRs are welcome! Before supplying a PR, please lay out a plan (e.g. pseudocode, short list) how you'd like to achieve that. Doesn't have to be thorough, just a rough idea how it would work. As storage is a DBAL (which could be SQL or in-memory) there is an abstraction layer that has to be resolved properly here.

**Comment by husio** [comment]
I looked at the code and here's rough idea of how it could work https://github.com/ory/hydra/compare/master...husio:healthcheck_proposal

Each hard dependency implements `HealthChecker` interface and is registered as such. List of all dependencies is passed to health handler to be used when requested. As an optimization, background check task can be periodically performed for each health checker.

I'm not sure how to expose list of dependencies to the health check endpoint, nor how to properly format error response, but I think those are minor issues. 

What do you think about the approach?

**Comment by arekkas** [comment]
Yeah, that looks pretty solid so far. However, the `pkg/fosite_storer.go` interface should be left completely untouched, similar to the fosite store implementation.

Instead, you should define an healthy interface in the `health` package and implement it's method signature in files like [this](https://github.com/ory/hydra/blob/master/config/backend_memory.go) (that should return true always) as well as [the plugin backend](https://github.com/ory/hydra/blob/master/config/backend_plugin.go) (this one should explicitly define a function that is being loaded from the plugin for health checking).

For SQL Connections, you could probably write a wrapper for `sqlcon.SQLConnection` that implements the health check.

**Comment by pnicolcev-tulipretail** [comment]
Heyo, I think these two endpoints are different concepts. A health endpoint that responds with a hard-coded "ok" is useful in a different way than a full status check is. Some systems separate these two concepts. I guess Kubernetes calls them liveness and readiness. The idea being to distinguish between a need to restart a container (unresponsive, not alive) versus waiting for its deps (not ready) where perhaps you are diverting traffic away from it while it starts up but don't want to restart it.

Perhaps call one health and the other status?

**Comment by arekkas** [comment]
This makes tons of sense! How about:

* `/health/alive`
* `/health/ready`

**Comment by arekkas** [comment]
@husio sorry if you already put work into this, I'll adapt your changes and quickly supply a PR as I want this to be released in the preview of 1.0 (which will be released today or latest tomorrow). Thank you for raising the issue and your ideas on how to solve this!

**Comment by husio** [comment]
I should have communicated better. 

I was working on proper solution (what I have provided so far was more of a pseudo code), including @pnicolcev-tulipretail suggestion, but if you say you will finish this, than that's great as well. Thanks!
