### ISSUE TITLE
Missing commits between v0.11.10 and v0.11.12

### ISSUE THREAD

**Issue by joshlreese** [ory/hydra#894]
Per our conversation in Discord, I'm opening a bug report for this issue.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Commits are missing between v0.11.10 and v0.11.12. Specifically (the only ones I've tracked down) are missing commits in `cmd/server/helper_client.go` which create the `default-oidc-id-token-public-policy` policy.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Run Hydra 0.11.12
2. Run `hydra policies get default-oidc-id-token-public-policy`, a 404 is returned.

**What is the expected behavior?**
Expect to receive the policy details for `default-oidc-id-token-public-policy`

**Which version of the software is affected?**
v0.11.12

See https://github.com/ory/hydra/commits/v0.11.10/cmd/server/helper_client.go vs https://github.com/ory/hydra/commits/v0.11.12/cmd/server/helper_client.go

**Comment by arekkas** [comment]
Ok, so some commits were missing here. This should now be resolved on this branch: https://github.com/ory/hydra/tree/v0.11.x

Can you please double-check to make sure this is the case? If so, I'll release a 0.11.13 version.

**Comment by arekkas** [comment]
@joshlreese sorry for pinging, but could you check if the branch is ok?

**Comment by arekkas** [comment]
I pushed a new release based on that branch, let me know if something doesn't look right.
