### ISSUE TITLE
oidc_context empty

### ISSUE THREAD

**Issue by clausdenk** [ory/hydra#900]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In my authorization code flow I always get an empty member oidc_context in the structure consentReq as returned by 

    `consentReq, _, err := client.GetConsentRequest(challenge)`

which is called when handling the GET on /consent. Everything in consentReq seems fine, but oidc_context (in the json) which is empty.

oauth url:

https://localhost:9000/oauth2/auth?access_type=online&client_id=example-client&prompt=consent&response_type=code&scope=openid+email+profile+ex.quotes&state=somerandomstate&ui_locales=en+es

**What is the expected behavior?**
At least the ui_locales related data should be in there

**Which version of the software is affected?**
oryd/hydra:v1.0.0-beta.2-alpine

**Comment by arekkas** [comment]
Are you using the in-memory store or the SQL one?

**Comment by clausdenk** [comment]
in-memory

**Comment by arekkas** [comment]
Ah yeah, it appears that this info is missing from the consent endpoint but available in the login endpoint due to a missing copy. Thank you for identifying and raising the issue!

**Comment by arekkas** [comment]
Resolved with  #901 . Congrats on raising the 900th issue :D
