### ISSUE TITLE
is hydra can build on window ?

### ISSUE THREAD

**Issue by springe2004** [ory/hydra#910]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which version of the software is affected?**

**Comment by arekkas** [comment]
Yes, it's even auto-build and available in the [release tab](https://github.com/ory/hydra/releases) for windows.
