### ISSUE TITLE
Hydra version 0.11.13-alpine break cli

### ISSUE THREAD

**Issue by jbpin** [ory/hydra#917]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I try to run a cli on docker using v0.11.13-alpine but cli say `Error: unknown command "connect" for "hydra"`
I though this was due for 1.0.0 

**What is the expected behavior?**
I expect 0.11.13 to be a patch revision

**Which version of the software is affected?**
0.11.13-alpine

**Comment by arekkas** [comment]
Can you please show the bash history

**Comment by jbpin** [comment]
![image](https://user-images.githubusercontent.com/332405/42438753-4047e082-8361-11e8-8cd9-0aa64f59dd66.png)

**Comment by arekkas** [comment]
Oh boy, I hope the commit history didn't get messed up 😨 I'll check it out, `connect` should definitely be included.

**Comment by jbpin** [comment]
Ok It's working now on v0.11.14. Thanks. Fixed

**Comment by arekkas** [comment]
👍
