### ISSUE TITLE
Opentracing tracing integration

### ISSUE THREAD

**Issue by gsagula** [ory/hydra#931]
Would be great to have tracing integrated into Hydra so the operator and developers can easy debug errors and latency issues.

For more details about Zipkin:
https://zipkin.io

Zipkin Go library:
https://github.com/openzipkin/zipkin-go

Intro to tracing:
http://opentracing.io/documentation/

**Comment by gsagula** [comment]
Please, Let me know if you need help with this integration.

**Comment by arekkas** [comment]
I think we could add the http middleware, would that be enough?

**Comment by gsagula** [comment]
I think that's a great starting point. We can span all the rest later. Please feel free to assign it to me if you are happy with the integration.

**Comment by arekkas** [comment]
Yup, PR welcome, most likely to be added somewhere around here: https://github.com/ory/hydra/blob/master/cmd/server/handler.go#L83

**Comment by arekkas** [comment]
Wouldn't it be better to adopt opentracing instead of zipkin? Namely [go-opentracing](https://github.com/opentracing/opentracing-go)?

**Comment by gsagula** [comment]
I'm glad you mentioned it. I was about starting this work. Sorry for the delay on that btw. Yes, good point! Let me take a look into that.

**Comment by gsagula** [comment]
@aaslamin has kindly offered to take care of this issue. I'm handing the work to him.

cc @arekkas

**Comment by aaslamin** [comment]
I should have a PR up soon to get some early feedback @aeneasr. I will include instructions for how to run everything locally.

Example trace creating hitting `POST /clients`:

![image](https://user-images.githubusercontent.com/1800781/44883536-50645c00-ac6c-11e8-8c97-809560d81dfd.png)

**Comment by someone1** [comment]
Anybody have a look at https://opencensus.io/? I personally bootstrap Hydra on my own and overlay StackDriver for tracing - I only bring this up as the PR's current implementation seems specific to a single tracing service (jaeger).

Is the idea to only support CNCF projects within Hydra?

Either way, I'd really love to see tracing beyond just HTTP requests - luckily for me since I also use my own database plugin I get tracing for both HTTP requests and database queries but only where the requests' `context.Context` is passed down. Maybe some restructuring can be done to pass the context down throughout the entire application on a per-request basis, and wire up more traces throughout (especially for database interactions)?

Would also like to see StackDriver support though doesn't look like there's opentracing.io support for it, however opencensus.io does seem to support most of the same backends as opentracing.io + StackDriver!

**Comment by aeneasr** [comment]
I’m open to different integrations. I think one of the dangers (for us) of adding a ton of adapters is that they must be maintained over a long period of time. That’s why there’s currently a focus towards CNCF products. I’m not entirely sure how to handle the magnitude of cloud products for tracing, performance, metrics sensibly.Any ideas?

**Comment by someone1** [comment]
I think it makes sense to choose a framework and wire up Hydra (and other ORY products) for tracing/metrics with said framework. Then you can probably support 1 or 2 exporters and maybe introduce a plugin system similar to databases for others? OpenCensus also has [this repository](https://github.com/census-instrumentation/opencensus-service) which aims to let your code be instrumented with OpenCensus but lets the user setup which backend to report the data to - probably worth keeping an eye on as it probably eliminates the need for Hydra to do anything more than support a single exporter which can then be confiured to send metrics/traces to other systems without Hydra having to support them all itself.

Really it comes down to OpenTracing vs OpenCensus today, with the latter covering stats in addition to tracing. Both provide a vendor-agnostic way to instrument your code for tracing, but they differ in project scope. From what I can tell, outside of stats collection that OpenCensus provides, OpenTracing is more of a spec that vendors are urged to support, OpenCensus will do the data collection for you and officially support backend products to report to.

There is much [discussion](https://dzone.com/articles/opentracing-has-caught-the-attention-of-the-apm-wo) about the two - Google decided to bring OpenCensus out there despite OpenTracing being revealed almost 2 years prior.

**Comment by aeneasr** [comment]
Interesting. I have no answer at the moment for this. Maybe there is a way to abstract this away and offer different strategies for tracing, but the API contract will always be somewhat close to the features being offered. For now, OT has been merged but I'm open to give OC a go as well. IMO all of this should be in the runtime and not hardwired in the code, but we're not there yet unfortunately.

**Comment by aeneasr** [comment]
However, I think we can close this since open tracing is now supported via jaeger!
