### ISSUE TITLE
Id_token_hint doesn't work as expected

### ISSUE THREAD

**Issue by michalwojciechowski** [ory/hydra#951]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**Steps to reproduce**
1. Follow the tutorial available on https://www.ory.sh/docs/guides/v1.0.0-beta.7/hydra/1-tutorial/ using docker-compose to have hydra, hydra-login-consent-node and a database setup locally, with the default configuration
2. Add a client with grant_type=authorization_code,refresh_token and sope=openid,offline
3. Start the provided example application (e.g. docker exec -it hydra_hydra_1  hydra token user...)
4. Go to http://127.0.0.1:4445/ in the private mode to avoid caching all the web resources including cookies
5. Follow the whole flow till the very end
6. Access Token, Refresh Token and IdToken are shown to the user 
![id_token_hint_1](https://user-images.githubusercontent.com/28198530/43202810-c84cc278-901c-11e8-8bb1-d23107e2c7df.png)
7. Manually validate the IdToken
![id_token_hint_2](https://user-images.githubusercontent.com/28198530/43202811-c8748a60-901c-11e8-9603-4bfda32ee864.png)
8. Close the browser
9. Restart the client one more time (e.g. docker exec -it hydra_hydra_1  hydra token user...)
10. Go to http://127.0.0.1:4445/ again
11. Fetch the newly produced URI for authorization (with the newly generated state and so on...)
12. Alter the URL in a way that id_token_hint is following the last param in the URI:
```
http://localhost:4444/oauth2/auth?client_id=auth-code-client&redirect_uri=http%3A%2F%2F127.0.0.1%3A4445%2Fcallback&response_type=code&scope=openid+offline&state=xbbzauoiwtqzvuirkaibqujy&nonce=argvdvklixaqktcjxrhwidcz&id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6InB1YmxpYzpkOTJhNjFkMC04YjUyLTQ0NGYtYmUyNS0wNzY2NTAwZjdhMTkiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOlsiYXV0aC1jb2RlLWNsaWVudCJdLCJhdXRoX3RpbWUiOjE1MzI1MjA2NDMsImV4cCI6MTUzMjUyNDI0NywiaWF0IjoxNTMyNTIwNjQ3LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjQ0NDQvIiwianRpIjoiNjU3NGM4ZWQtYWNjYy00ODZhLWFhOWEtZmNlMjc0OWRmMzMzIiwibm9uY2UiOiJhcmd2ZHZrbGl4YXFrdGNqeHJod2lkY3oiLCJyYXQiOjE1MzI1MjA2NDEsInN1YiI6ImZvb0BiYXIuY29tIn0.nniPgsLU7ZNMnfRjyuK6I9RWohtalDnRlTteL7gw6iWlBGa_rVKvX37lSdjEsxDhLI0KVUSlE0rfY1KmTxor_Lym7NR5afXEWQwK6zBqzjExyUGdrG8shMiA7exUUDs2CVSYGj7CBza0M4SSzoX0a7goaaj70waHMEWQNGwT_a24xWXwrl4rG9R8bgqtgn-jb6Y2af75vlJv4W5rVxxjoxJBfa84HRTNup8hZ5J4MBEx4lB0dBxEpRWO1Q_XG70ZXSi4gfqaIE13rHdugJiUhcX-ZVlUlpT8uFU9FHBMfbMbaMFGTTuwdEGY4y0b9Q9rV9N51_1kOUnfB5jEbsDU5dMvVyPxKL7v-9_t48a_XTWDQyib-8iLSwsicp5lDvuSZ0f7dE1iFQaGx1wYIyib5fSXwpd0KaL_5tOC4yZuqOCaOO67Vi4L7c7cKcmJ9riT8zH8ab9X9zB_hce6sgI6EMgl5kXb5ym9blZz4X4pCsurm1UpIMAMNSFVyGkvM70oOGcmAV_K5f4ufJTAFeZhSX6hnxgAkoAP8h1oxnVLuNCjjJSPB-_nQMlBbuhrUhClRuP3gM1tOZ7z9XgPOlPJpRr_SVJKWpM3_vfkLyUPuMNDPZj-DCLLo2IUjyLrfQEmxtUPC9JkA_cU52wn3esmMGCzVMccSWc2hA_NF-EkoB0
```
13. Execute this URI

**What is the current behavior?**
Hydra redirects us to the login page with the new generated login_challenge.
![id_token_hint_3](https://user-images.githubusercontent.com/28198530/43202812-c89c72f0-901c-11e8-882e-6db88856f0b6.png)

**What is the expected behavior?**
Hydra should skip the login page.

**Which version of the software is affected?**
 v1.0.0-beta.7

**Comment by arekkas** [comment]
Thank you for raising this issue. This is actually according to the recommendations made in the OpenID Connect Core 1.0 specification:

> OPTIONAL. ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client. If the End-User identified by the ID Token is logged in or is logged in by the request, then the Authorization Server returns a positive response; otherwise, it SHOULD return an error, such as login_required. When possible, an id_token_hint SHOULD be present when prompt=none is used and an invalid_request error MAY be returned if it is not; however, the server SHOULD respond successfully when possible, even if it is not present. The Authorization Server need not be listed as an audience of the ID Token when it is used as an id_token_hint value.

The important part is here:

> If the End-User identified by the ID Token is logged in or is logged in by the request, then the Authorization Server returns a positive response; **otherwise, it SHOULD return an error, such as login_required.**

while SHOULD is not imperative, the language is clear (see RFC2119):

> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

The OpenID certification self-service has a test for this. It requires a fresh browser, logs the user in, requests an ID token, and then redoes the flow with setting the id_token as id_token_hint.

Please let me know if you see this differently or can cite sources that contradict my statement.

**Comment by arekkas** [comment]
To clarify a bit more:

1. *"If the End-User identified by the ID Token is logged in"*: You provide an `id_token_hint` with `subject=foouser`. The device (browser) accessing the `/oauth2/auth` endpoint has a session for `foouser` -> valid request.
2. *"If the End-User identified by the ID Token [...] or is logged in by the request"*: You provide an `id_token_hint` with `subject=foouser`. The device (browser) accessing the `/oauth2/auth` endpoint has no session. The user requires re-authentication. If the authenticated user is `foouser` -> valid request
3. *"otherwise, it SHOULD return an error, such as login_required."*: Any other case where either the session or the re-authenticated user does not match the `sub` value from the ID token.

**Comment by pokuniewicz-sii** [comment]
We have tested this against private mode and with cache in the browser. 
Everything according to the specification. 
IdToken contains the same subject and IdToken is still valid and not expired.

Did we missed something? I can see you have pointed us on specification, but did we done something wrong?

**Comment by arekkas** [comment]
Right, the important piece is `Close the browser` which removes the session cookies (so cookies that have no Max-Age set). It's possible that the cookie that was set has no Max-Age set (e.g. because `remember_for` or `remember` were not set). There was also a PR ( #930 ) about this recently which has been merged on master but not yet released. Could you check if the cookie is set properly during the first authentication process?

**Comment by pokuniewicz-sii** [comment]
Ok, so without "Remember me" checkbox enabled on login page, cookie has Max-Age set to 3600. With "Remember me" enabled, Max-Age value is 2592000. But we have tested that in incognito mode in the browser and close the browser after the first flow has ended. 

I am wondering about second point in your comment: 

> "If the End-User identified by the ID Token [...] or is logged in by the request": You provide an id_token_hint with subject=foouser. The device (browser) accessing the /oauth2/auth endpoint has no session. The user requires re-authentication. If the authenticated user is foouser -> valid request

How do you understand by "logged in by the request"?
In our case, authenticated user is foouser.

**Comment by arekkas** [comment]
> Ok, so without "Remember me" checkbox enabled on login page, cookie has Max-Age set to 3600. With "Remember me" enabled, Max-Age value is 2592000. But we have tested that in incognito mode in the browser and close the browser after the first flow has ended.


When you close an incognito browser window, all cookies will be removed regardless of Max-Age. So it is to be expected that the user has to re-authenticate.

> How do you understand by "logged in by the request"?
In our case, authenticated user is foouser.

In the scenario you described (closing an incognito browser window), the user is no longer authenticated.

**Comment by pokuniewicz-sii** [comment]
If I understand the specification correctly, the valid and not expired IdToken send as id_token_hint in authorization request is responsible to tell Authorization Server that Resource Owner of this IdToken is already authenticated. So if the valid and not expired IdToken has been sent by RO then RO should be authenticated and Hydra should skip the login page no matter what the cookies values are. 
In the OpenId specification, there is no correlation between IdToken and cookies.

> 3.1.2.3.  Authorization Server Authenticates End-User: If the request is valid, the Authorization Server attempts to Authenticate the End-User or determines whether the End-User is Authenticated, depending upon the request parameter values used. The methods used by the Authorization Server to Authenticate the End-User (e.g. username and password, session cookies, etc.) are beyond the scope of this specification. [...]

1. User passed the whole flow and get IdToken, which expires in 1h. After that, user has closed all of the browser windows and clear all of the cookies and cache. 
2. During this hour, user is sending authorization request with not expired IdToken in id_token_hint query param. 
3. Hydra should should recognize this user as logged in by the request. 
4. Hydra should return a positive response for authentication.
5. Hydra should skip login part and redirect directly to consent page. 
Am I right? 

I have also tried to send `id_token_hint` with `prompt=none` and got this error `/callback?error=login_required&error_debug=Prompt+%22none%22+was+requested%2C+but+no+existing+login+session+was+found&error_description=The+Authorization+Server+requires+End-User+authentication&state=nzecmixehtjoxqhlvvwqunlh`

**Comment by pokuniewicz-sii** [comment]
Thank you for the explanation. In that case, we can close this issue.
