### ISSUE TITLE
consent: expose  a list of all clients authorized by a user

### ISSUE THREAD

**Issue by kingjan1999** [ory/hydra#953]
**Do you want to request a *feature* or report a *bug*?**
Feature

There is currently no direct way to get a list of all clients for which a particular user has given consent. @joshuarubin has already mentioned in #304 that:

>We, however, would like to have a single interface for the user to see all the applications they have approved and have an opportunity to revoke access for any particular app.

As he also wrote, this is currently feasible by storing the authorized clients in the Consent application. This information is already available in Hydra (you can even delete all tokens since #304, but you can't list them).

Although I am a Go beginner, I don't think it should be too complicated, since `FindPreviouslyGrantedConsentRequests` already provides a similar functionality. If the idea meets with approval here, I would try a pull request.

**Comment by arekkas** [comment]
This also touches #902 - PRs appreciated!
