### ISSUE TITLE
Refresh token and access token share same lifetime

### ISSUE THREAD

**Issue by ayZagen** [ory/hydra#955]
**What is the current behavior?**
When ACCESS_TOKEN_LIFESPAN environment variable set it affects refresh tokens too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Set ACCESS_TOKEN_LIFESPAN to a value that you will wait for and start hydra.
- Get a refresh token
- Introspect it after ACCESS_TOKEN_LIFESPAN expires
- Result should be `{ active: false }`

**What is the expected behavior?**
Refresh token lifespan config should be seperate

**Which version of the software is affected?**
Master branch.

**Comment by arekkas** [comment]
Please share your configuration (all env vars, truncate sensitive ones) too.

**Comment by ayZagen** [comment]
![screenshot 1](https://user-images.githubusercontent.com/11196940/43390662-61be2004-93f7-11e8-80b5-a3c189b9731d.png)

I checked postgres and they seem active. But when I try to introspect it returns false.

**Comment by ayZagen** [comment]
Alright my bad. I was sending in `refresh_token` field. It should be `token` instead. Could you improve response output ? :)

**Comment by jigetage** [comment]
Configuration key ACCESS_TOKEN_LIFESPAN is deprecated and will be removed in a future release. Use key ttl.access_token instead!
