### ISSUE TITLE
client: client specific CORS settings

### ISSUE THREAD

**Issue by ayZagen** [ory/hydra#957]
It would be great to have the ability to set client specific allowed origins.

**Comment by arekkas** [comment]
Please provide more context:

- Which endpoints should be affected?
- What's the use case?
- Does this exist in the wild, and if so, where?

Thank you!

**Comment by ayZagen** [comment]
Taken from Auth0 

> Allowed Origins are URLs that will be allowed to make requests from JavaScript to Auth0 API (typically used with CORS). By default, all your callback URLs will be allowed. This field allows you to enter other origins if you need to. You can specify multiple valid URLs by comma-separating them or one by line, and also use wildcards at the subdomain level (e.g.: https://*.contoso.com). Notice that querystrings and hash information are not taking into account when validating these URLs.

**Comment by arekkas** [comment]
Right, but in this case this would be only the `/oauth2/token` and `/oauth2/revoke` endpoints, as all other endpoints do not have a concept of request ownership. Does that cover your use case?

**Comment by ayZagen** [comment]
Also `/oauth2/auth` ?

**Comment by aeneasr** [comment]
Closed by https://github.com/ory/hydra/pull/1009
