### ISSUE TITLE
cmd/server: Export useful bootstrap function

### ISSUE THREAD

**Issue by someone1** [ory/hydra#973]
I had discussed this in issue #949 and removed it from my PR #956 suggesting we add it to #948 instead. I see that `NewHandler` was exported but this doesn't boostrap the hydra features into the handler. 

I think exporting `registerRoutes` is necessary to make this useful. I'd also suggest we consider exporting `rejectInsecureRequests` and possibly even `enhanceRouter` as they also perform helpful bootstrap options but are not necessary.

I can submit a PR to export these functions if you find it agreeable!

**EDIT:**
Exporting `enhanceRouter` would remove the need to export `registerRoutes` as it has access and uses it.

**Comment by arekkas** [comment]
Exporting them sounds OK to me!

**Comment by arekkas** [comment]
Oh and could you, once those are all done, add an example to the [advanced section](https://github.com/ory/docs/blob/add-admin-port/guides/hydra/6-how-to/3-advanced.md) in the docs?

**Comment by someone1** [comment]
Sure I don't mind adding an example - do you just want a basic example of how to bootstrap hydra outside of hydra?

**Comment by arekkas** [comment]
Yeah, basic example would be perfect!

**Comment by someone1** [comment]
closed by https://github.com/ory/hydra/pull/1023
