### ISSUE TITLE
cmd: CLI should be able to import PEM keys to JWK store

### ISSUE THREAD

**Issue by arekkas** [ory/hydra#98]

**Comment by arekkas** [comment]
I am not confident with PEM encoding and in particular the differences between PKCS#1 and PKCS#8 and how to detect which format we are dealing with. Additionally, support for encrypted PEM files should be added as well. Here's my current work in progress take at this:

```go
`

func (h *JWKHandler) ImportPEMKey(cmd *cobra.Command, args []string) {
	if len(args) != 3 {
		fmt.Println(cmd.UsageString())
		return
	}

	var key interface{}
	block, _ := pem.Decode()
	switch block.Type {
	case "EC PRIVATE KEY":
		key = x509.ParseECPrivateKey()
		break;
	case "RSA PRIVATE KEY":
		key = x509.ParsePKCS1PrivateKey()
		break;
	default:
		x509.ParsePKCS8PrivateKey()
		fmt.Printf("Unknown PEM block type: %s", block.Type)
		os.Exit(1)
	}


	err := h.M.AddKey(args[0], &jose.JsonWebKey{
		Key: key,
		KeyID: args[1],
	})
	pkg.Must(err, "Could not store keys: %s", err)

	fmt.Println("Key import succeeded.")
}
```

**Comment by janekolszak** [comment]
I think it's OK if you support only one, the most popular key format. Users can always convert their key with openssl.

**Comment by arekkas** [comment]
No one has ever complained about this, I think it's ok to not implement it.

**Comment by arekkas** [comment]
Actually: https://github.com/ory/hydra/issues/175#issuecomment-246252942
