### ISSUE TITLE
Use ID_TOKEN_LIFESPAN when doing refresh

### ISSUE THREAD

**Issue by clausdenk** [ory/hydra#985]
**Do you want to request a *feature* or report a *bug*?**
possibly bug

**What is the current behavior?**
The IDToken, when first created has the correct lifespan as indicated by ID_TOKEN_LIFESPAN (I use 1m for testing). However, when I do a refresh_token, the new IDToken has a lifespan of 1h. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Run hydra with ID_TOKEN_LIFESPAN=1m (different from default)
2) Get a Token with auth code flow, scope openid. 
3) Verify IDToken, it has lifespan ID_TOKEN_LIFESPAN (1 minute)
4) Wait 1m and refresh token
5) Verify IDToken, it now has lifespan=1h

**What is the expected behavior?**
The refreshed IDToken should have a lifespan of ID_TOKEN_LIFESPAN

**Which version of the software is affected?**
oryd/hydra:unstable (v1.0.0-beta.8). As a sidenote, it would be nice if hydra could print the version number to the logs on startup.

**Comment by arekkas** [comment]
That looks like a bug, I'll try to confirm once I'm back in office by end of this week.

**Comment by arekkas** [comment]
Tracked #987
