### ISSUE TITLE
sdk: add oauthapi functions to golang interface

### ISSUE THREAD

**Issue by clausdenk** [ory/hydra#991]
**Do you want to request a *feature* or report a *bug*?**

Complete SDK for Go

**What is the current behavior?**

In https://github.com/ory/hydra/blob/master/sdk/go/hydra/sdk_api.go the following functions from https://github.com/ory/hydra/blob/master/sdk/go/hydra/swagger/o_auth2_api.go do not show up:

- OauthAuth
- OauthToken
- RevokeAllUserConsentSessions
- RevokeAuthenticationSession
- RevokeUserClientConsentSessions
- RevokeUserLoginCookie
- Userinfo
- WellKnown

In the case of the first two I suppose this is intended. But the rest should probably be included? Also, "WellKnown" and the existing "GetWellKnown" are very similar names.

**Which version of the software is affected?**
latest

**Comment by arekkas** [comment]
The `/oauth2/auth` and `/oauth2/token` endpoints should not be included. They have difficult parameters to handle which should be implemented via a proper library. The others could/should be added (except RevokeUserLoginCookie).
