### ISSUE TITLE
invalid if condition about SubjectTypesSupport

### ISSUE THREAD

**Issue by vvakame** [ory/hydra#992]
https://github.com/ory/hydra/blob/c67b7fe7475a50c2ea33817ecef4bb4533280867/cmd/server/handler_oauth2_factory.go#L178-L180
this line should compare `"public"` to `c.GetSubjectTypesSupported()`, not `"pairwise"`.

**Comment by arekkas** [comment]
Thanks, this is definitely a typo but does not cause any issues because that strategy is actually not used :) Cleaning this up anyways.
