### ISSUE TITLE
Can not remember consent because no user interaction was required with resp['skip'] false

### ISSUE THREAD

**Issue by ionutzp** [ory/hydra#999]
The response from fetching log in details using the `login_challenge` contains `resp['skip'] = false` yet still an error is thrown with code `400`

After retrying a log in `resp['skip']` comes back as true *without the user logging in!*

happens in hydra 1.0-beta8

**Comment by ionutzp** [comment]
@arekkas can help with more details, if you let me know what's needed

**Comment by arekkas** [comment]
You're talking about log in, but this shows the consent API. Which is it?

**Comment by ionutzp** [comment]
this is indeed the consent part of the flow

**Comment by ionutzp** [comment]
should i understand this is expected behaviour as I never show the consent screen to the user?

**Comment by arekkas** [comment]
If you remember the consent of, you should not to show the consent screen again for the same client_id + user + scopes. The remember flag sets that
